<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatchSeeder281To490 extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            [281, "Diare", "Mules", "Atis", "Kesehatan", "Adik terkena diare.", "Adhik mules.", "Adhi atis."],
            [282, "Didih", "Ngodhok", "Ngodhok", "Kata Kerja", "Air mulai mendidih.", "Banyu wiwit nggodhok.", "Toya wiwit nggodhok."],
            [283, "Didik", "Didik", "Didik", "Pendidikan", "Guru mendidik murid dengan sabar.", "Guru ndidik murid kanthi sabar.", "Guru ndidik siswa kanthi sabar."],
            [284, "Dinding", "Tembok", "Tembok", "Rumah", "Dinding rumah dicat putih.", "Tembok omah dicet putih.", "Tembok griya dipuncet putih."],
            [285, "Dingin", "Adhem", "Asrep", "Cuaca", "Udara pagi terasa dingin.", "Esuk hawane adhem.", "Enjing hawanipun asrep."],
            [286, "Dinosaurus", "Dinosaurus", "Dinosaurus", "Hewan", "Dinosaurus hidup jutaan tahun lalu.", "Dinosaurus urip biyen.", "Dinosaurus gesang rumiyin."],
            [287, "Direktur", "Direktur", "Direktur", "Profesi", "Direktur memimpin rapat.", "Direktur mimpin rapat.", "Direktur mimpin rapat."],
            [288, "Diskon", "Diskon", "Diskon", "Perdagangan", "Toko memberi diskon besar.", "Toko menehi diskon gedhe.", "Toko maringi diskon ageng."],
            [289, "Diskusi", "Rembugan", "Rembagan", "Pendidikan", "Siswa berdiskusi bersama.", "Murid rembugan bareng.", "Siswa rembagan sesarengan."],
            [290, "Doa", "Donga", "Dedonga", "Agama", "Ibu membaca doa.", "Ibu maca donga.", "Ibu maos dedonga."],
            [291, "Dokter", "Dhokter", "Dhokter", "Profesi", "Dokter memeriksa pasien.", "Dhokter mriksa pasien.", "Dhokter mriksa pasien."],
            [292, "Dokumen", "Dhokumen", "Dhokumen", "Teknologi", "Saya menyimpan dokumen.", "Aku nyimpen dhokumen.", "Kula nyimpen dhokumen."],
            [293, "Dompet", "Dompet", "Dompet", "Benda", "Dompet ayah berwarna hitam.", "Dompet bapak ireng.", "Dompet rama cemeng."],
            [294, "Donat", "Donat", "Donat", "Makanan", "Adik makan donat.", "Adhik mangan donat.", "Adhi dhahar donat."],
            [295, "Dorong", "Dorong", "Dorong", "Kata Kerja", "Tolong dorong meja itu.", "Tulung dorong meja kuwi.", "Sumangga dorong meja punika."],
            [296, "Dosa", "Dosa", "Dosa", "Agama", "Kita harus menjauhi dosa.", "Kita kudu adoh saka dosa.", "Kita kedah tebih saking dosa."],
            [297, "Drama", "Drama", "Drama", "Seni", "Sekolah mengadakan drama.", "Sekolah nganakake drama.", "Sekolah nganakaken drama."],
            [298, "Dua", "Loro", "Kalih", "Kata Bilangan", "Saya punya dua pensil.", "Aku duwe loro potlot.", "Kula gadhah kalih potlot."],
            [299, "Duduk", "Lungguh", "Lenggah", "Kata Kerja", "Silakan duduk di sini.", "Lungguh ing kene.", "Mangga lenggah wonten mriki."],
            [300, "Duga", "Ngira", "Nginten", "Kata Kerja", "Saya menduga jawabannya benar.", "Aku ngira wangsulane bener.", "Kula nginten wangsulanipun leres."],
            [301, "Duka", "Susah", "Sungkawa", "Perasaan", "Keluarga itu sedang berduka.", "Kulawarga kuwi lagi susah.", "Kulawarga punika saweg sungkawa."],
            [302, "Dulang", "Dulang", "Dulang", "Peralatan Rumah", "Ibu membawa dulang.", "Ibu nggawa dulang.", "Ibu nggawa dulang."],
            [303, "Dulu", "Mbiyen", "Rumiyin", "Waktu", "Dulu kami tinggal di desa.", "Mbiyen kita manggon ing desa.", "Rumiyin kula dedalem wonten desa."],
            [304, "Dunia", "Donya", "Buana", "Alam", "Dunia sangat luas.", "Donya amba banget.", "Buana amba sanget."],
            [305, "Duri", "Eri", "Eri", "Tumbuhan", "Bunga mawar memiliki duri.", "Kembang mawar nduweni eri.", "Sekar mawar gadhah eri."],
            [306, "Durian", "Duren", "Duren", "Buah", "Ayah membeli durian.", "Bapak tuku duren.", "Rama mundhut duren."],
            [307, "Dusta", "Ngapusi", "Dusta", "Kata Kerja", "Jangan berkata dusta.", "Aja ngapusi.", "Sampun ngucap dusta."],
            [308, "Duta", "Duta", "Duta", "Profesi", "Kakak menjadi duta sekolah.", "Mas dadi duta sekolah.", "Raka dados duta sekolah."],
            [309, "Duyung", "Duyung", "Duyung", "Hewan", "Duyung hidup di laut.", "Duyung urip ing segara.", "Duyung gesang wonten seganten."],
            [310, "Editing", "Nyunting", "Nyunting", "Teknologi", "Saya sedang editing video.", "Aku lagi nyunting video.", "Kula saweg nyunting video."],
            [311, "Efektif", "Migunani", "Migunani", "Kata Sifat", "Cara itu efektif.", "Cara kuwi migunani.", "Cara punika migunani."],
            [312, "Ekor", "Buntut", "Buntut", "Anggota Tubuh", "Hewan itu memiliki ekor panjang.", "Kewan kuwi buntute dawa.", "Kewan punika buntutipun dawa."],
            [313, "Ekonomi", "Ekonomi", "Ekonomi", "Pendidikan", "Ayah belajar ekonomi.", "Bapak sinau ekonomi.", "Rama sinau ekonomi."],
            [314, "Ekoran", "Buntutan", "Buntutan", "Kata Benda", "Anak bermain ekoran.", "Bocah dolanan buntutan.", "Putra dolanan buntutan."],
            [315, "Elektronik", "Elektronik", "Elektronik", "Teknologi", "Toko menjual barang elektronik.", "Toko adol barang elektronik.", "Toko sade barang elektronik."],
            [316, "Email", "Email", "Email", "Internet", "Saya mengirim email.", "Aku ngirim email.", "Kula ngirim email."],
            [317, "Emas", "Emas", "Emas", "Benda", "Cincin itu terbuat dari emas.", "Cincin kuwi digawe saka emas.", "Sesupek punika kadamel saking emas."],
            [318, "Ember", "Ember", "Ember", "Peralatan Rumah", "Ibu mengisi ember dengan air.", "Ibu ngisi ember nganggo banyu.", "Ibu ngisi ember kaliyan toya."],
            [319, "Emosi", "Emosi", "Emosi", "Perasaan", "Kita harus mengendalikan emosi.", "Kita kudu ngendhaleni emosi.", "Kita kedah ngendhaleni emosi."],
            [320, "Empat", "Papat", "Sekawan", "Kata Bilangan", "Ada empat buku di meja.", "Ana papat buku ing meja.", "Wonten sekawan buku wonten meja."],
            [321, "Empedu", "Empedu", "Empedu", "Anggota Tubuh", "Dokter memeriksa empedu.", "Dhokter mriksa empedu.", "Dhokter mriksa empedu."],
            [322, "Empuk", "Empuk", "Empuk", "Kata Sifat", "Bantal itu empuk.", "Bantal kuwi empuk.", "Bantal punika empuk."],
            [323, "Enak", "Penak", "Penak", "Makanan", "Makanan ini sangat enak.", "Panganan iki penak.", "Dhaharan punika penak sanget."],
            [324, "Enam", "Enem", "Enem", "Kata Bilangan", "Saya memiliki enam buku.", "Aku duwe enem buku.", "Kula gadhah enem buku."],
            [325, "Energi", "Energi", "Energi", "Sains", "Tumbuhan memerlukan energi matahari.", "Tanduran butuh energi srengenge.", "Tetuwuhan mbutuhake energi surya."],
            [326, "Engsel", "Engsel", "Engsel", "Peralatan Rumah", "Pintu itu memiliki engsel baru.", "Lawang kuwi duwe engsel anyar.", "Lawang punika gadhah engsel enggal."],
            [327, "Enzim", "Enzim", "Enzim", "Sains", "Enzim membantu pencernaan.", "Enzim mbantu pencernaan.", "Enzim mbiyantu pencernaan."],
            [328, "Erat", "Raket", "Raket", "Kata Sifat", "Persahabatan mereka erat.", "Pasedulurané raket.", "Pasaduluranipun raket."],
            [329, "Erosi", "Erosi", "Erosi", "Alam", "Erosi terjadi saat hujan deras.", "Erosi kedadeyan wektu udan deres.", "Erosi kadadosan nalika udan deres."],
            [330, "Es", "Es", "Es", "Minuman", "Adik membeli es batu.", "Adhik tuku es watu.", "Adhi mundhut es sela."],
            [331, "Es batu", "Es watu", "Es sela", "Minuman", "Masukkan es batu ke gelas.", "Lebokna es watu ing gelas.", "Lebetaken es sela wonten gelas."],
            [332, "Es krim", "Es krim", "Es krim", "Makanan", "Anak makan es krim.", "Bocah mangan es krim.", "Putra dhahar es krim."],
            [333, "Eyang", "Mbah", "Eyang", "Keluarga", "Eyang tinggal bersama kami.", "Mbah manggon bareng awake dhewe.", "Eyang dedalem sesarengan kula."],
            [334, "Eyel-eyelan", "Eyel-eyelan", "Eyel-eyelan", "Perilaku", "Jangan suka eyel-eyelan.", "Aja seneng eyel-eyelan.", "Sampun remen eyel-eyelan."],
            [335, "Eja", "Meja", "Ngeja", "Pendidikan", "Guru mengajari eja kata.", "Guru mulang ngeja tembung.", "Guru mucal ngeja tembung."],
            [336, "Fabel", "Fabel", "Fabel", "Sastra", "Guru membacakan fabel.", "Guru maca fabel.", "Guru maos fabel."],
            [337, "Fajar", "Fajar", "Fajar", "Alam", "Fajar mulai terlihat.", "Fajar wiwit katon.", "Fajar wiwit katingal."],
            [338, "Fakir", "Mlarat", "Fakir", "Agama", "Kita membantu fakir miskin.", "Kita nulungi wong mlarat.", "Kita mitulungi fakir miskin."],
            [339, "Fakta", "Kanyatan", "Kanyatan", "Pendidikan", "Guru menjelaskan fakta.", "Guru nerangake kanyatan.", "Guru nerangaken kanyatan."],
            [340, "Famili", "Kulawarga", "Kulawarga", "Keluarga", "Mereka masih famili.", "Dheweke isih kulawarga.", "Piyambakipun taksih kulawarga."],
            [341, "Fasilitas", "Sarana", "Sarana", "Tempat Umum", "Sekolah memiliki fasilitas lengkap.", "Sekolah nduweni sarana lengkap.", "Sekolah gadhah sarana jangkep."],
            [342, "Februari", "Februari", "Februari", "Waktu", "Bulan Februari memiliki dua puluh delapan hari.", "Wulan Februari nduweni rong puluh wolu dina.", "Wulan Februari gadhah wolulikur dinten."],
            [343, "Feodal", null, null, "Sejarah", "Siswa mempelajari sistem feodal.", "Murid sinau sistem feodal.", "Siswa sinau sistem feodal."],
            [344, "Feri", "Kapal feri", "Kapal feri", "Transportasi", "Kami naik kapal feri.", "Kita numpak kapal feri.", "Kula nitih kapal feri."],
            [345, "Film", "Film", "Film", "Hiburan", "Kami menonton film bersama.", "Kita nonton film bareng.", "Kula mirsani film sesarengan."],
            [346, "Filter", "Filter", "Filter", "Teknologi", "Aplikasi memiliki filter baru.", "Aplikasi duwe filter anyar.", "Aplikasi gadhah filter enggal."],
            [347, "Final", "Pungkasan", "Pungkasan", "Pendidikan", "Pertandingan memasuki final.", "Pertandhingan mlebu pungkasan.", "Pertandhingan mlebet babak pungkasan."],
            [348, "Finansial", "Keuangan", "Keuangan", "Ekonomi", "Ayah mengatur finansial keluarga.", "Bapak ngatur keuangan kulawarga.", "Rama ngatur keuangan kulawarga."],
            [349, "Fisika", "Fisika", "Fisika", "Mata Pelajaran", "Kakak belajar fisika.", "Mas sinau fisika.", "Raka sinau fisika."],
            [350, "Fitnah", "Fitnah", "Fitnah", "Agama", "Jangan menyebarkan fitnah.", "Aja nyebar fitnah.", "Sampun nyebar fitnah."],
            [351, "Flanel", "Kain flanel", "Kain flanel", "Kerajinan", "Ibu membeli kain flanel.", "Ibu tuku kain flanel.", "Ibu mundhut kain flanel."],
            [352, "Flashdisk", "Flashdisk", "Flashdisk", "Komputer", "Data disimpan di flashdisk.", "Data disimpen ing flashdisk.", "Data dipunsimpen wonten flashdisk."],
            [353, "Fleksibel", "Luwes", "Luwes", "Kata Sifat", "Bambu sangat fleksibel.", "Pring kuwi luwes.", "Pring punika luwes."],
            [354, "Flu", "Pilek", "Influenza", "Kesehatan", "Adik terkena flu.", "Adhik pilek.", "Adhi gerah influenza."],
            [355, "Fokus", "Fokus", "Fokus", "Pendidikan", "Siswa harus fokus belajar.", "Murid kudu fokus sinau.", "Siswa kedah fokus sinau."],
            [356, "Folder", "Folder", "Folder", "Komputer", "Saya membuat folder baru.", "Aku nggawe folder anyar.", "Kula damel folder enggal."],
            [357, "Foto", "Foto", "Foto", "Teknologi", "Saya melihat foto lama.", "Aku ndelok foto lawas.", "Kula mirsani foto kina."],
            [358, "Fotokopi", "Fotokopi", "Fotokopi", "Sekolah", "Guru meminta fotokopi tugas.", "Guru njaluk fotokopi tugas.", "Guru nyuwun fotokopi tugas."],
            [359, "Frasa", "Frasa", "Frasa", "Bahasa", "Guru menjelaskan frasa.", "Guru nerangake frasa.", "Guru nerangaken frasa."],
            [360, "Freezer", "Freezer", "Freezer", "Peralatan Rumah", "Daging disimpan di freezer.", "Daging disimpen ing freezer.", "Daging dipunsimpen wonten freezer."],
            [361, "Frekuensi", "Frekuensi", "Frekuensi", "Sains", "Radio memiliki frekuensi tertentu.", "Radio nduweni frekuensi tartamtu.", "Radio gadhah frekuensi tartamtu."],
            [362, "Fungsi", "Guna", "Gina", "Pendidikan", "Guru menjelaskan fungsi akar.", "Guru nerangake guna oyot.", "Guru nerangaken ginanipun oyot."],
            [363, "Futsal", "Futsal", "Futsal", "Olahraga", "Anak-anak bermain futsal.", "Bocah-bocah dolanan futsal.", "Para putra dolanan futsal."],
            [364, "Gabah", "Gabah", "Gabah", "Pertanian", "Petani menjemur gabah.", "Pak tani ngemur gabah.", "Petani ngemur gabah."],
            [365, "Gadai", "Gadek", "Gadek", "Ekonomi", "Ayah tidak ingin menggadai motor.", "Bapak ora gelem nggadek montor.", "Rama boten purun nggadek montor."],
            [366, "Gading", "Gading", "Gading", "Hewan", "Gajah memiliki gading panjang.", "Gajah nduweni gading dawa.", "Gajah gadhah gading dawa."],
            [367, "Gadis", "Prawan", "Putri enom", "Keluarga", "Gadis itu ramah.", "Prawan kuwi grapyak.", "Putri enom punika grapyak."],
            [368, "Gagal", "Gagal", "Gagal", "Kata Kerja", "Jangan takut gagal.", "Aja wedi gagal.", "Sampun ajrih gagal."],
            [369, "Gajah", "Gajah", "Gajah", "Hewan", "Gajah makan rumput.", "Gajah mangan suket.", "Gajah dhahar suket."],
            [370, "Gaji", "Gaji", "Gaji", "Pekerjaan", "Ayah menerima gaji.", "Bapak nampa gaji.", "Rama tampi gaji."],
            [371, "Galang", "Gelang", "Gelang", "Aksesori", "Ibu memakai gelang emas.", "Ibu nganggo gelang emas.", "Ibu ngagem gelang emas."],
            [372, "Gambar", "Gambar", "Gambar", "Pendidikan", "Adik menggambar rumah.", "Adhik nggambar omah.", "Adhi nggambar griya."],
            [373, "Gamelan", "Gamelan", "Gamelan", "Seni", "Guru memainkan gamelan.", "Guru nabuh gamelan.", "Guru nabuh gamelan."],
            [374, "Gampang", "Gampang", "Gampil", "Kata Sifat", "Soal ini sangat gampang.", "Soal iki gampang.", "Soal punika gampil."],
            [375, "Gandum", "Gandum", "Gandum", "Tumbuhan", "Gandum dipanen petani.", "Gandum dipanen petani.", "Gandum dipunpanen petani."],
            [376, "Gang", "Gang", "Gang", "Tempat", "Gang itu sempit.", "Gang kuwi ciut.", "Gang punika ciut."],
            [377, "Ganggu", "Ngganggu", "Ngganggu", "Kata Kerja", "Jangan mengganggu teman.", "Aja ngganggu kanca.", "Sampun ngganggu kanca."],
            [378, "Garam", "Uyah", "Saram", "Makanan", "Ibu menambahkan garam.", "Ibu nambahi uyah.", "Ibu nambahi saram."],
            [379, "Garis", "Garis", "Garis", "Matematika", "Guru menggambar garis lurus.", "Guru nggambar garis lurus.", "Guru nggambar garis lurus."],
            [380, "Garpu", "Garpu", "Garpu", "Peralatan Rumah", "Garpu berada di meja.", "Garpu ana ing meja.", "Garpu wonten meja."],
            [381, "Gas", "Gas", "Gas", "Teknologi", "Kompor memakai gas.", "Kompor nganggo gas.", "Kompor ngagem gas."],
            [382, "Gatal", "Gatel", "Gatel", "Kesehatan", "Tangan saya terasa gatal.", "Tanganku krasa gatel.", "Asta kula kraos gatel."],
            [383, "Gawang", "Gawang", "Gawang", "Olahraga", "Penjaga gawang menangkap bola.", "Kiper nyekel bal.", "Kiper nyepeng bal."],
            [384, "Gaya", "Gaya", "Gaya", "Kata Benda", "Dia memiliki gaya berjalan unik.", "Dheweke nduweni gaya mlaku unik.", "Piyambakipun gadhah gaya mlampah unik."],
            [385, "Gedung", "Gedhong", "Gedhong", "Bangunan", "Gedung sekolah sangat besar.", "Gedhong sekolah gedhe banget.", "Gedhong sekolah ageng sanget."],
            [386, "Gelap", "Peteng", "Peteng", "Alam", "Malam ini sangat gelap.", "Bengi iki peteng.", "Dalu punika peteng."],
            [387, "Gelas", "Gelas", "Gelas", "Peralatan Rumah", "Gelas itu berisi air.", "Gelas kuwi isi banyu.", "Gelas punika isi toya."],
            [388, "Gelang", "Gelang", "Gelang", "Aksesori", "Adik memakai gelang baru.", "Adhik nganggo gelang anyar.", "Adhi ngagem gelang enggal."],
            [389, "Gelembung", "Umpluk", "Umpluk", "Alam", "Gelembung muncul di air.", "Umpluk metu ing banyu.", "Umpluk medal wonten toya."],
            [390, "Gelisah", "Sumelang", "Sumelang", "Perasaan", "Ibu tampak gelisah.", "Ibu katon sumelang.", "Ibu katingal sumelang."],
            [391, "Gelombang", "Gelombang", "Gelombang", "Alam", "Gelombang laut sangat besar.", "Gelombang segara gedhe.", "Gelombang seganten ageng."],
            [392, "Gemar", "Seneng", "Remen", "Perasaan", "Saya gemar membaca buku.", "Aku seneng maca buku.", "Kula remen maos buku."],
            [393, "Gempa", "Lindhu", "Lindhu", "Alam", "Kemarin terjadi gempa.", "Wingi ana lindhu.", "Kala wingi wonten lindhu."],
            [394, "Gendang", "Gendhang", "Gendhang", "Seni", "Anak memainkan gendang.", "Bocah nabuh gendhang.", "Putra nabuh gendhang."],
            [395, "Gendut", "Lemu", "Lemu", "Kata Sifat", "Kucing itu gendut.", "Kucing kuwi lemu.", "Kucing punika lemu."],
            [396, "Generasi", "Generasi", "Generasi", "Pendidikan", "Generasi muda harus rajin.", "Generasi enom kudu sregep.", "Generasi enom kedah sregep."],
            [397, "Genit", "Genit", "Genit", "Kata Sifat", "Anak itu tidak genit.", "Bocah kuwi ora genit.", "Putra punika boten genit."],
            [398, "Genius", "Jenius", "Jenius", "Pendidikan", "Dia anak yang genius.", "Dheweke bocah jenius.", "Piyambakipun putra jenius."],
            [399, "Genjah", "Cepet tuwuh", "Cepet tuwuh", "Pertanian", "Pohon itu genjah.", "Wit kuwi cepet tuwuh.", "Uwit punika cepet tuwuh."],
            [400, "Genta", "Genta", "Genta", "Benda", "Genta berbunyi nyaring.", "Genta muni banter.", "Genta muni seru."],
            [401, "Gepeng", "Pepak", "Pepak", "Kata Sifat", "Batu itu gepeng.", "Watu kuwi pepak.", "Sela punika pepak."],
            [402, "Gerabah", "Gerendel", "Gerendel", "Kerajinan", "Ibu membeli gerabah.", "Ibu tuku gerendel.", "Ibu mundhut gerendel."],
            [403, "Gerak", "Obah", "Obah", "Kata Kerja", "Bumi terus bergerak.", "Bumi terus obah.", "Bumi tansah obah."],
            [404, "Gerbang", "Gapura", "Gapura", "Bangunan", "Gerbang sekolah terbuka.", "Gapura sekolah mbukak.", "Gapura sekolah kabikak."],
            [405, "Gereja", "Gereja", "Gereja", "Agama", "Mereka beribadah di gereja.", "Dheweke sembahyang ing gereja.", "Piyambakipun sembahyang wonten gereja."],
            [406, "Gergaji", "Gergaji", "Gergaji", "Peralatan", "Ayah memakai gergaji.", "Bapak nganggo gergaji.", "Rama ngagem gergaji."],
            [407, "Gerimis", "Grimis", "Grimis", "Cuaca", "Pagi ini gerimis.", "Esuk iki grimis.", "Enjing punika grimis."],
            [408, "Gerobak", "Grobag", "Grobag", "Kendaraan", "Pedagang mendorong gerobak.", "Bakul nyurung grobag.", "Bakul nyurung grobag."],
            [409, "Gesper", "Sabuk", "Sabuk", "Pakaian", "Ayah memakai gesper baru.", "Bapak nganggo sabuk anyar.", "Rama ngagem sabuk enggal."],
            [410, "Getar", "Geter", "Geter", "Kata Kerja", "Tangan saya bergetar.", "Tanganku geter.", "Asta kula geter."],
            [411, "Giat", "Sregep", "Sregep", "Kata Sifat", "Adik sangat giat belajar.", "Adhik sregep sinau.", "Adhi sregep sinau."],
            [412, "Gigi", "Untu", "Waja", "Anggota Tubuh", "Gigi saya bersih.", "Untuku resik.", "Waja kula resik."],
            [413, "Gigit", "Cokot", "Cokot", "Hewan", "Anjing menggigit sandal.", "Asu nyokot sendhal.", "Seyos nyokot selop."],
            [414, "Gilas", "Giles", "Giles", "Kata Kerja", "Roda menggilas batu kecil.", "Roda ngiles watu cilik.", "Roda ngiles sela alit."],
            [415, "Giling", "Giling", "Giling", "Kata Kerja", "Ibu menggiling cabai.", "Ibu nggiling lombok.", "Ibu nggiling lombok."],
            [416, "Ginjal", "Ginjel", "Ginjel", "Anggota Tubuh", "Ginjal harus dijaga sehat.", "Ginjel kudu dijaga.", "Ginjel kedah dipunjagi."],
            [417, "Gips", "Gips", "Gips", "Kesehatan", "Kaki adik memakai gips.", "Sikile adhik nganggo gips.", "Suku adhi ngagem gips."],
            [418, "Gitar", "Gitar", "Gitar", "Musik", "Kakak memainkan gitar.", "Mas nabuh gitar.", "Raka nabuh gitar."],
            [419, "Gizi", "Gizi", "Gizi", "Kesehatan", "Anak membutuhkan gizi seimbang.", "Bocah butuh gizi imbang.", "Putra mbutuhake gizi seimbang."],
            [420, "Gladi", "Gladi", "Gladi", "Pendidikan", "Siswa mengikuti gladi bersih.", "Murid melu gladi resik.", "Siswa ndherek gladi resik."],
            [421, "Globe", "Globe", "Globe", "Pendidikan", "Guru menunjukkan globe.", "Guru nuduhake globe.", "Guru nedahaken globe."],
            [422, "Godaan", "Godha", "Godha", "Perasaan", "Dia menahan godaan.", "Dheweke nahan godha.", "Piyambakipun nahan godha."],
            [423, "Gojek", "Ojek", "Ojek", "Transportasi", "Ayah naik ojek.", "Bapak numpak ojek.", "Rama nitih ojek."],
            [424, "Gol", "Gol", "Gol", "Olahraga", "Tim kami mencetak gol.", "Timku nyetak gol.", "Tim kula nyithak gol."],
            [425, "Golongan", "Golongan", "Golongan", "Kata Benda", "Darah saya golongan O.", "Getihku golongan O.", "Rah kula golongan O."],
            [426, "Gong", "Gong", "Gong", "Seni", "Gong berbunyi keras.", "Gong muni banter.", "Gong muni seru."],
            [427, "Goreng", "Goreng", "Goreng", "Makanan", "Ibu menggoreng tempe.", "Ibu nggoreng tempe.", "Ibu nggoreng tempe."],
            [428, "Got", "Got", "Got", "Lingkungan", "Air mengalir di got.", "Banyu mili ing got.", "Toya mili wonten got."],
            [429, "Gotong royong", "Gotong royong", "Gotong royong", "Budaya", "Kami bergotong royong membersihkan kelas.", "Kita gotong royong ngresiki kelas.", "Kula gotong royong ngresiki kelas."],
            [430, "Grafik", "Grafik", "Grafik", "Matematika", "Guru menjelaskan grafik.", "Guru nerangake grafik.", "Guru nerangaken grafik."],
            [431, "Gudang", "Gudhang", "Gudhang", "Bangunan", "Barang disimpan di gudang.", "Barang disimpen ing gudhang.", "Barang dipunsimpen wonten gudhang."],
            [432, "Gugur", "Gugur", "Gugur", "Tumbuhan", "Daun gugur tertiup angin.", "Godhong gugur kebur angin.", "Godhong gugur kabur angin."],
            [433, "Gula", "Gula", "Gendhis", "Makanan", "Ibu menambahkan gula.", "Ibu nambahi gula.", "Ibu nambahi gendhis."],
            [434, "Gulat", "Gulat", "Gulat", "Olahraga", "Mereka berlatih gulat.", "Dheweke latihan gulat.", "Piyambakipun latihan gulat."],
            [435, "Gulung", "Gulung", "Gulung", "Kata Kerja", "Tolong gulung tikar itu.", "Tulung gulung klasa kuwi.", "Sumangga gulung klasa punika."],
            [436, "Gunting", "Gunting", "Gunting", "Peralatan", "Saya memakai gunting.", "Aku nganggo gunting.", "Kula ngagem gunting."],
            [437, "Gunung", "Gunung", "Redi", "Alam", "Gunung itu sangat tinggi.", "Gunung kuwi dhuwur.", "Redi punika inggil."],
            [438, "Guru", "Guru", "Guru", "Profesi", "Guru mengajar di kelas.", "Guru mulang ing kelas.", "Guru mucal wonten kelas."],
            [439, "Gurita", "Gurita", "Gurita", "Hewan", "Gurita hidup di laut.", "Gurita urip ing segara.", "Gurita gesang wonten seganten."],
            [440, "Gusi", "Gusi", "Gusi", "Anggota Tubuh", "Gusi saya sehat.", "Gusiku sehat.", "Gusi kula sehat."],
            [441, "Guyur", "Ngguyur", "Ngguyur", "Cuaca", "Hujan mengguyur desa.", "Udan ngguyur desa.", "Udan ngguyur desa."],
            [442, "Guyon", "Guyon", "Guyon", "Aktivitas", "Mereka saling berguyon.", "Dheweke padha guyon.", "Piyambakipun sami guyon."],
            [443, "Habis", "Entek", "Entek", "Kata Sifat", "Air minum sudah habis.", "Banyu omben wis entek.", "Toya unjukan sampun entek."],
            [444, "Hadiah", "Hadiah", "Hadiah", "Kata Benda", "Ayah memberi hadiah.", "Bapak menehi hadiah.", "Rama maringi hadiah."],
            [445, "Hadir", "Teka", "Rawuh", "Pendidikan", "Semua murid hadir hari ini.", "Kabeh murid teka.", "Sedaya siswa rawuh."],
            [446, "Hafal", "Apal", "Apal", "Pendidikan", "Adik hafal doa pendek.", "Adhik apal donga cekak.", "Adhi apal dedonga cekak."],
            [447, "Hai", "Hai", "Hai", "Ungkapan", "Hai teman selamat pagi.", "Hai kanca sugeng esuk.", "Hai kanca sugeng enjing."],
            [448, "Haji", "Haji", "Haji", "Agama", "Paman sudah berhaji.", "Paklik wis haji.", "Paklik sampun haji."],
            [449, "Halaman", "Pekarangan", "Pekarangan", "Rumah", "Halaman rumah bersih.", "Pekarangan omah resik.", "Pekarangan griya resik."],
            [450, "Halus", "Alus", "Alus", "Kata Sifat", "Kulit bayi sangat halus.", "Kulit bayi alus banget.", "Kulit bayi alus sanget."],
            [451, "Hambar", "Anyep", "Anyep", "Makanan", "Sup ini terasa hambar.", "Sop iki anyep.", "Sop punika anyep."],
            [452, "Hambat", "Alangi", "Alangi", "Kata Kerja", "Jangan menghambat teman.", "Aja ngalangi kanca.", "Sampun ngalangi kanca."],
            [453, "Hamburger", "Hamburger", "Hamburger", "Makanan", "Saya membeli hamburger.", "Aku tuku hamburger.", "Kula mundhut hamburger."],
            [454, "Hamil", "Meteng", "Meteng", "Kesehatan", "Ibu sedang hamil.", "Ibu lagi meteng.", "Ibu saweg meteng."],
            [455, "Hampa", "Kosong", "Kosong", "Kata Sifat", "Ruangan itu terasa hampa.", "Ruangane krasa kosong.", "Ruangan punika kraos kosong."],
            [456, "Hancur", "Remuk", "Remuk", "Kata Sifat", "Gelas itu hancur.", "Gelas kuwi remuk.", "Gelas punika remuk."],
            [457, "Hangat", "Anget", "Anget", "Kata Sifat", "Teh masih hangat.", "Teh isih anget.", "Teh taksih anget."],
            [458, "Hangatkan", "Angetake", "Angetaken", "Kata Kerja", "Ibu menghangatkan susu.", "Ibu ngangetake susu.", "Ibu ngangetaken susu."],
            [459, "Hangatnya", "Angete", "Angetipun", "Kata Sifat", "Saya suka hangatnya matahari.", "Aku seneng angete srengenge.", "Kula remen angetipun surya."],
            [460, "Hangat suam-suam kuku", "Anget-anget", "Anget-anget", "Kata Sifat", "Air itu hangat suam-suam kuku.", "Banyu kuwi anget-anget.", "Toya punika anget-anget."],
            [461, "Hangatkan makanan", "Ngangetake panganan", "Ngangetaken dhaharan", "Kata Kerja", "Ibu menghangatkan makanan.", "Ibu ngangetake panganan.", "Ibu ngangetaken dhaharan."],
            [462, "Hantu", "Memedi", "Memedi", "Cerita", "Cerita itu tentang hantu.", "Crita kuwi bab memedi.", "Cariyos punika babagan memedi."],
            [463, "Hanyut", "Kaseret", "Kaseret", "Alam", "Kayu hanyut di sungai.", "Kayu kaseret ing kali.", "Kayu kaseret wonten kali."],
            [464, "Hapal", "Apal", "Apal", "Pendidikan", "Saya hapal perkalian.", "Aku apal pingan.", "Kula apal pingan."],
            [465, "Hapus", "Mbusak", "Mbusak", "Kata Kerja", "Guru menghapus tulisan.", "Guru mbusak tulisan.", "Guru mbusak seratan."],
            [466, "Harga", "Rega", "Regi", "Perdagangan", "Harga buku murah.", "Rega buku murah.", "Regi buku mirah."],
            [467, "Hari", "Dina", "Dinten", "Waktu", "Hari ini cerah.", "Dina iki cerah.", "Dinten punika cerah."],
            [468, "Harimau", "Macan", "Macan", "Hewan", "Harimau hidup di hutan.", "Macan urip ing alas.", "Macan gesang wonten wana."],
            [469, "Harum", "Wangi", "Wangi", "Kata Sifat", "Bunga itu harum.", "Kembang kuwi wangi.", "Sekar punika wangi."],
            [470, "Harus", "Kudu", "Kedah", "Tata Bahasa", "Kita harus belajar.", "Kita kudu sinau.", "Kita kedah sinau."],
            [471, "Hasanah", "Kabecikan", "Kabecikan", "Agama", "Semoga menjadi hasanah.", "Muga dadi kabecikan.", "Mugi dados kabecikan."],
            [472, "Hasil", "Asil", "Asil", "Pendidikan", "Hasil ujian sangat baik.", "Asil ujian apik.", "Asil ujian sae."],
            [473, "Hati", "Ati", "Panggalih", "Anggota Tubuh", "Hati ibu sangat lembut.", "Atine ibu alus.", "Panggalihipun ibu alus."],
            [474, "Haus", "Haus", "Sekeca", "Perasaan", "Saya merasa haus.", "Aku krasa haus.", "Kula kraos sekeca."],
            [475, "Hebat", "Hebat", "Linuwih", "Kata Sifat", "Guru itu sangat hebat.", "Guru kuwi hebat.", "Guru punika linuwih."],
            [476, "Hemat", "Irit", "Irit", "Kata Sifat", "Kita harus hemat air.", "Kita kudu irit banyu.", "Kita kedah irit toya."],
            [477, "Hembus", "Semribit", "Semribit", "Cuaca", "Angin berhembus pelan.", "Angin semribit alon.", "Angin semribit alon."],
            [478, "Hening", "Sepi", "Sepi", "Alam", "Malam terasa hening.", "Bengi krasa sepi.", "Dalu kraos sepi."],
            [479, "Henti", "Mandheg", "Mandheg", "Kata Kerja", "Bus berhenti di terminal.", "Bis mandheg ing terminal.", "Bis mandheg wonten terminal."],
            [480, "Hewan", "Kewan", "Sato", "Hewan", "Guru mengenalkan hewan.", "Guru ngenalake kewan.", "Guru ngenalaken sato."],
            [481, "Hias", "Hias", "Hias", "Kata Kerja", "Ibu menghias meja.", "Ibu nghias meja.", "Ibu nghias meja."],
            [482, "Hiasan", "Hiasan", "Hiasan", "Rumah", "Hiasan itu indah.", "Hiasan kuwi apik.", "Hiasan punika sae."],
            [483, "Hidung", "Irung", "Grona", "Anggota Tubuh", "Hidung saya pilek.", "Irungku pilek.", "Grona kula pilek."],
            [484, "Hijau", "Ijo", "Ijem", "Warna", "Daun berwarna hijau.", "Godhong ijo.", "Godhong ijem."],
            [485, "Hilang", "Ilang", "Ical", "Kata Kerja", "Buku saya hilang.", "Bukuku ilang.", "Buku kula ical."],
            [486, "Himpun", "Nglumpukake", "Nglumpukaken", "Kata Kerja", "Guru menghimpun tugas.", "Guru nglumpukake tugas.", "Guru nglumpukaken tugas."],
            [487, "Hina", "Ngeyek", "Ngasorake", "Kata Kerja", "Jangan menghina teman.", "Aja ngeyek kanca.", "Sampun ngasoraken kanca."],
            [488, "Hinggap", "Manggon", "Pinarak", "Hewan", "Burung hinggap di pohon.", "Manuk manggon ing wit.", "Manuk pinarak wonten uwit."],
            [489, "Hingus", "Upil irung", "Leler irung", "Kesehatan", "Anak membersihkan hingus.", "Bocah ngresiki upil irung.", "Putra ngresiki leler irung."],
            [490, "Hitam", "Ireng", "Cemeng", "Warna", "Kucing itu hitam.", "Kucing kuwi ireng.", "Kucing punika cemeng."],
        ];

        foreach ($dataset as $row) {
            $vocab = Vocabulary::updateOrCreate(
                ['id' => $row[0]],
                [
                    'indonesian_word' => $row[1],
                    'javanese_ngoko'  => $row[2],
                    'javanese_krama'  => $row[3],
                    'category'        => $row[4] ?? null,
                ]
            );

            if (!empty($row[5]) || !empty($row[6]) || !empty($row[7])) {
                VocabularyExample::updateOrCreate(
                    ['vocabulary_id' => $vocab->id],
                    [
                        'indonesian_sentence' => $row[5] ?? null,
                        'ngoko_sentence'      => $row[6] ?? null,
                        'krama_sentence'      => $row[7] ?? null,
                        'javanese_sentence'   => $row[6] ?? $row[7] ?? null,
                    ]
                );
            }
        }
    }
}
