<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatchSeeder491To820 extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            [491, "Hitung", "Ngetung", "Ngetang", "Pendidikan", "Guru menghitung nilai.", "Guru ngetung nilai.", "Guru ngetang biji."],
            [492, "Hitungan", "Itungan", "Itangan", "Matematika", "Hitungan itu mudah.", "Itungan kuwi gampang.", "Itangan punika gampil."],
            [493, "Hobi", "Kesenengan", "Kasenengan", "Aktivitas", "Hobi saya membaca.", "Kesenenganku maca buku.", "Kasenengan kula maos buku."],
            [494, "Hormat", "Ngurmati", "Ngajeni", "Unggah-ungguh", "Kita harus hormat kepada guru.", "Kita kudu ngurmati guru.", "Kita kedah ngajeni guru."],
            [495, "Hotel", "Hotel", "Hotel", "Bangunan", "Keluarga menginap di hotel.", "Kulawarga nginep ing hotel.", "Kulawarga nginep wonten hotel."],
            [496, "Hujan", "Udan", "Udan", "Cuaca", "Hari ini turun hujan.", "Dina iki udan.", "Dinten punika udan."],
            [497, "Hukum", "Ukum", "Hukum", "Pendidikan", "Guru menjelaskan hukum Newton.", "Guru nerangake ukum Newton.", "Guru nerangaken hukum Newton."],
            [498, "Hutan", "Alas", "Wana", "Alam", "Hutan itu sangat lebat.", "Alas kuwi rungkud.", "Wana punika rungkud."],
            [499, "Ibadah", "Sembahyang", "Sembahyang", "Agama", "Kami beribadah bersama.", "Kita sembahyang bareng.", "Kula sembahyang sesarengan."],
            [500, "Ibu", "Ibu", "Ibu", "Keluarga", "Ibu memasak di dapur.", "Ibu masak ing pawon.", "Ibu masak wonten pawon."],
            [501, "Ikan", "Iwak", "Iwak", "Hewan", "Ayah membeli ikan segar.", "Bapak tuku iwak seger.", "Rama mundhut iwak seger."],
            [502, "Ikat", "Ngiket", "Ngiket", "Kata Kerja", "Ayah mengikat tali.", "Bapak ngiket tali.", "Rama ngiket tali."],
            [503, "Ikhlas", "Lila", "Lila", "Perasaan", "Kita harus ikhlas membantu.", "Kita kudu lila nulungi.", "Kita kedah lila mitulungi."],
            [504, "Ikhtiar", "Usaha", "Usaha", "Agama", "Kita harus berikhtiar.", "Kita kudu usaha.", "Kita kedah usaha."],
            [505, "Iklan", "Iklan", "Iklan", "Teknologi", "Saya melihat iklan.", "Aku ndelok iklan.", "Kula mirsani iklan."],
            [506, "Iklim", "Iklim", "Iklim", "Alam", "Indonesia beriklim tropis.", "Indonesia nduweni iklim tropis.", "Indonesia gadhah iklim tropis."],
            [507, "Ikut", "Melu", "Ndherek", "Kata Kerja", "Adik ikut belajar.", "Adhik melu sinau.", "Adhi ndherek sinau."],
            [508, "Ilat", "Ilat", "Ilat", "Anggota Tubuh", "Ilat terasa pedas.", "Ilat krasa pedhes.", "Ilat kraos pedhes."],
            [509, "Ilmu", "Kawruh", "Kawruh", "Pendidikan", "Ilmu sangat bermanfaat.", "Kawruh migunani.", "Kawruh migunani sanget."],
            [510, "Iman", "Iman", "Iman", "Agama", "Kita harus menjaga iman.", "Kita kudu njaga iman.", "Kita kedah njagi iman."],
            [511, "Imbang", "Imbang", "Imbang", "Kata Sifat", "Makanan harus seimbang.", "Panganan kudu imbang.", "Dhaharan kedah imbang."],
            [512, "Imlek", "Imlek", "Imlek", "Budaya", "Kami mengucapkan selamat Imlek.", "Kita ngucapake sugeng Imlek.", "Kula ngaturaken sugeng Imlek."],
            [513, "Impor", "Impor", "Impor", "Ekonomi", "Toko menjual barang impor.", "Toko adol barang impor.", "Toko sade barang impor."],
            [514, "Indah", "Apik", "Sae", "Kata Sifat", "Pemandangan itu indah.", "Pemandangan kuwi apik.", "Pemandangan punika sae."],
            [515, "Indera", "Pancaindra", "Pancaindra", "Sains", "Manusia memiliki lima indera.", "Manungsa nduweni lima pancaindra.", "Manungsa gadhah gangsal pancaindra."],
            [516, "Induk", "Indhuk", "Indhuk", "Hewan", "Induk ayam mencari makan.", "Indhuk pitik golek pangan.", "Indhuk pitik pados pangan."],
            [517, "Industri", "Industri", "Industri", "Pekerjaan", "Ayah bekerja di industri.", "Bapak nyambut gawe ing industri.", "Rama nyambut damel wonten industri."],
            [518, "Infeksi", "Infeksi", "Infeksi", "Kesehatan", "Luka itu terkena infeksi.", "Tatune kena infeksi.", "Tatunipun kenging infeksi."],
            [519, "Informasi", "Informasi", "Informasi", "Teknologi", "Guru memberi informasi penting.", "Guru menehi informasi penting.", "Guru maringi informasi wigati."],
            [520, "Ingat", "Eling", "Emut", "Kata Kerja", "Saya ingat pesan ibu.", "Aku eling pesen ibu.", "Kula emut dhawuhipun ibu."],
            [521, "Ingin", "Pengin", "Kersa", "Perasaan", "Saya ingin belajar.", "Aku pengin sinau.", "Kula kersa sinau."],
            [522, "Injak", "Nginjak", "Nginjak", "Kata Kerja", "Jangan menginjak rumput.", "Aja nginjak suket.", "Sampun nginjak suket."],
            [523, "Inovasi", "Inovasi", "Inovasi", "Pendidikan", "Guru membuat inovasi pembelajaran.", "Guru nggawe inovasi sinau.", "Guru damel inovasi pasinaon."],
            [524, "Insinyur", "Insinyur", "Insinyur", "Profesi", "Paman seorang insinyur.", "Paklik insinyur.", "Paklik insinyur."],
            [525, "Internet", "Internet", "Internet", "Teknologi", "Saya belajar melalui internet.", "Aku sinau liwat internet.", "Kula sinau lumantar internet."],
            [526, "Iris", "Ngiris", "Ngiris", "Kata Kerja", "Ibu mengiris bawang.", "Ibu ngiris brambang.", "Ibu ngiris brambang."],
            [527, "Isi", "Isi", "Isi", "Kata Benda", "Isi tas sangat penuh.", "Isi tas kebak.", "Isi tas kebak."],
            [528, "Istimewa", "Mirunggan", "Mirunggan", "Kata Sifat", "Hari ini sangat istimewa.", "Dina iki mirunggan.", "Dinten punika mirunggan."],
            [529, "Istri", "Bojo", "Somah", "Keluarga", "Istri membantu suami.", "Bojo nulungi bojo.", "Somah mitulungi kakungipun."],
            [530, "Itik", "Bebek", "Meri", "Hewan", "Itik berenang di kolam.", "Bebek nglangi ing blumbang.", "Meri nglangi wonten blumbang."],
            [531, "Izin", "Idin", "Idin", "Unggah-ungguh", "Saya meminta izin guru.", "Aku njaluk idin guru.", "Kula nyuwun idin dhateng guru."],
            [532, "Izolasi", "Isolasi", "Isolasi", "Kesehatan", "Pasien menjalani isolasi.", "Pasien nglakoni isolasi.", "Pasien nglampahi isolasi."],
            [533, "Jabat", "Nyalami", "Salaman", "Kata Kerja", "Mereka berjabat tangan.", "Dheweke padha salaman.", "Piyambakipun sesarengan salaman."],
            [534, "Jabatan", "Jabatan", "Jabatan", "Pekerjaan", "Ayah mendapat jabatan baru.", "Bapak entuk jabatan anyar.", "Rama pikantuk jabatan enggal."],
            [535, "Jadi", "Dadi", "Dados", "Kata Kerja", "Adik ingin jadi guru.", "Adhik pengin dadi guru.", "Adhi kersa dados guru."],
            [536, "Jagung", "Jagung", "Jagung", "Tumbuhan", "Petani menanam jagung.", "Pak tani nandur jagung.", "Petani nandur jagung."],
            [537, "Jahit", "Jahit", "Jahit", "Kata Kerja", "Ibu menjahit baju.", "Ibu njahit klambi.", "Ibu njahit busana."],
            [538, "Jajan", "Jajan", "Jajan", "Makanan", "Adik membeli jajan.", "Adhik tuku jajan.", "Adhi mundhut jajan."],
            [539, "Jalan", "Dalan", "Margi", "Tempat", "Jalan itu sangat lebar.", "Dalan kuwi amba.", "Margi punika amba."],
            [540, "Jalan kaki", "Mlaku", "Mlampah", "Aktivitas", "Kami jalan kaki ke sekolah.", "Kita mlaku menyang sekolah.", "Kula mlampah dhateng sekolah."],
            [541, "Jam", "Jam", "Jam", "Waktu", "Jam dinding menunjukkan pukul tujuh.", "Jam tembok nuduhake jam pitu.", "Jam tembok nedahaken tabuh pitu."],
            [542, "Jambu", "Jambu", "Jambu", "Buah", "Saya makan jambu biji.", "Aku mangan jambu klutuk.", "Kula dhahar jambu kluthuk."],
            [543, "Jamur", "Jamur", "Jamur", "Tumbuhan", "Jamur tumbuh saat musim hujan.", "Jamur thukul nalika mangsa udan.", "Jamur tuwuh nalika mangsa udan."],
            [544, "Janji", "Janji", "Janji", "Unggah-ungguh", "Ayah menepati janji.", "Bapak netepi janji.", "Rama netepi janji."],
            [545, "Jantung", "Jantung", "Jantung", "Anggota Tubuh", "Jantung harus dijaga sehat.", "Jantung kudu dijaga sehat.", "Jantung kedah dipunjagi sehat."],
            [546, "Jarak", "Jarak", "Jarak", "Kata Benda", "Jarak rumah ke sekolah dekat.", "Jarak omah menyang sekolah cedhak.", "Jarak griya dhateng sekolah celak."],
            [547, "Jari", "Driji", "Driji", "Anggota Tubuh", "Jari adik terluka.", "Drijine adhik tatu.", "Drijinipun adhi tatu."],
            [548, "Jaring", "Jala", "Jala", "Peralatan", "Nelayan memakai jaring.", "Nelayan nganggo jala.", "Nelayan ngagem jala."],
            [549, "Jaring laba-laba", "Sarang lawa", "Sarang lawa", "Hewan", "Jaring laba-laba menempel di sudut.", "Sarang lawa nempel ing pojok.", "Sarang lawa nempel wonten pojok."],
            [550, "Jarum", "Jarum", "Jarum", "Peralatan", "Ibu membeli jarum jahit.", "Ibu tuku jarum jahit.", "Ibu mundhut jarum jahit."],
            [551, "Jatuh", "Tiba", "Tiba", "Kata Kerja", "Adik jatuh saat berlari.", "Adhik tiba nalika mlayu.", "Adhi tiba nalika mlayu."],
            [552, "Jauh", "Adoh", "Tebih", "Kata Sifat", "Sekolah kami jauh.", "Sekolahku adoh.", "Sekolah kula tebih."],
            [553, "Jawa", "Jawa", "Jawi", "Budaya", "Mereka belajar Bahasa Jawa.", "Dheweke sinau Basa Jawa.", "Piyambakipun sinau Basa Jawi."],
            [554, "Jawab", "Wangsuli", "Mangsuli", "Kata Kerja", "Saya menjawab pertanyaan guru.", "Aku wangsuli pitakon guru.", "Kula mangsuli pitaken guru."],
            [555, "Jawaban", "Wangsulan", "Wangsulan", "Pendidikan", "Jawabanmu sudah benar.", "Wangsulanmu wis bener.", "Wangsulan panjenengan sampun leres."],
            [556, "Jelas", "Cetha", "Cetha", "Kata Sifat", "Penjelasan guru sangat jelas.", "Penjelasan guru cetha.", "Panjelasan guru cetha."],
            [557, "Jelaskan", "Nerangake", "Nerangaken", "Kata Kerja", "Guru menjelaskan pelajaran.", "Guru nerangake pelajaran.", "Guru nerangaken piwulangan."],
            [558, "Jelatang", "Jelatang", "Jelatang", "Tumbuhan", "Jangan menyentuh jelatang.", "Aja nyekel jelatang.", "Sampun nyepeng jelatang."],
            [559, "Jelma", "Dadi", "Dados", "Kata Kerja", "Cerita itu tentang manusia yang menjelma.", "Crita kuwi babagan wong dadi kewan.", "Cariyos punika babagan tiyang dados kewan."],
            [560, "Jemari", "Driji", "Driji", "Anggota Tubuh", "Jemari ibu halus.", "Drijine ibu alus.", "Drijinipun ibu alus."],
            [561, "Jemput", "Njupuk", "Njemput", "Kata Kerja", "Ayah menjemput adik.", "Bapak njupuk adhik.", "Rama njemput adhi."],
            [562, "Jendela", "Jendhela", "Jendhela", "Rumah", "Jendela kamar terbuka.", "Jendhela kamar mbukak.", "Jendhela kamar kabikak."],
            [563, "Jenggot", "Jenggot", "Jenggot", "Anggota Tubuh", "Kakek memiliki jenggot putih.", "Mbah duwe jenggot putih.", "Eyang gadhah jenggot putih."],
            [564, "Jenuh", "Bosen", "Bosen", "Perasaan", "Saya mulai jenuh belajar.", "Aku wiwit bosen sinau.", "Kula wiwit bosen sinau."],
            [565, "Jepit", "Jepit", "Jepit", "Kata Kerja", "Ibu menjepit pakaian.", "Ibu njepit klambi.", "Ibu njepit busana."],
            [566, "Jerapah", "Jerapah", "Jerapah", "Hewan", "Jerapah memiliki leher panjang.", "Jerapah nduweni gulu dawa.", "Jerapah gadhah gulu dawa."],
            [567, "Jeruk", "Jeruk", "Jeruk", "Buah", "Ibu membeli jeruk manis.", "Ibu tuku jeruk legi.", "Ibu mundhut jeruk manis."],
            [568, "Jiwa", "Jiwa", "Jiwa", "Kata Benda", "Jiwa yang baik menolong sesama.", "Jiwa apik seneng nulungi.", "Jiwa sae remen mitulungi."],
            [569, "Jodoh", "Jodho", "Jodho", "Kata Benda", "Mereka percaya pada jodoh.", "Dheweke percaya jodho.", "Piyambakipun pitados jodho."],
            [570, "Joglo", "Omah Joglo", "Griya Joglo", "Budaya", "Rumah Joglo memiliki tiang besar.", "Omah Joglo nduweni saka gedhe.", "Griya Joglo gadhah saka ageng."],
            [571, "Jongkok", "Jongkok", "Jongkok", "Kata Kerja", "Adik jongkok di halaman.", "Adhik jongkok ing pekarangan.", "Adhi jongkok wonten pekarangan."],
            [572, "Jual", "Adol", "Sade", "Kata Kerja", "Ayah menjual sayur.", "Bapak adol sayur.", "Rama sade sayur."],
            [573, "Juara", "Juara", "Juara", "Pendidikan", "Kakak menjadi juara kelas.", "Mas dadi juara kelas.", "Raka dados juara kelas."],
            [574, "Jubah", "Jubah", "Jubah", "Pakaian", "Ustaz memakai jubah putih.", "Ustaz nganggo jubah putih.", "Ustaz ngagem jubah putih."],
            [575, "Jujur", "Jujur", "Jujur", "Kata Sifat", "Kita harus jujur.", "Kita kudu jujur.", "Kita kedah jujur."],
            [576, "Juli", "Juli", "Juli", "Waktu", "Sekolah mulai bulan Juli.", "Sekolah wiwit wulan Juli.", "Sekolah wiwit wulan Juli."],
            [577, "Jumat", "Jemuwah", "Jemuwah", "Waktu", "Hari Jumat kami beribadah.", "Dina Jemuwah kita sembahyang.", "Dinten Jemuwah kula sembahyang."],
            [578, "Jumlah", "Cacahe", "Cacahipun", "Matematika", "Jumlah buku ada sepuluh.", "Cacahe buku ana sepuluh.", "Cacahipun buku wonten sedasa."],
            [579, "Jumpa", "Ketemu", "Kepanggih", "Kata Kerja", "Saya jumpa teman lama.", "Aku ketemu kanca lawas.", "Kula kepanggih kanca kina."],
            [580, "Jurus", "Jurus", "Jurus", "Olahraga", "Guru mengajarkan jurus baru.", "Guru mulang jurus anyar.", "Guru mucal jurus enggal."],
            [581, "Junjung", "Njunjung", "Njunjung", "Kata Kerja", "Mereka menjunjung tinggi kejujuran.", "Dheweke njunjung kejujuran.", "Piyambakipun njunjung kajujuran."],
            [582, "Jurang", "Jurang", "Jurang", "Alam", "Jurang itu sangat dalam.", "Jurang kuwi jero.", "Jurang punika lebet."],
            [583, "Juru", "Juru", "Juru", "Profesi", "Juru masak sedang bekerja.", "Juru masak lagi nyambut gawe.", "Juru masak saweg nyambut damel."],
            [584, "Jus", "Jus", "Jus", "Minuman", "Saya minum jus mangga.", "Aku ngombe jus pelem.", "Kula ngunjuk jus pelem."],
            [585, "Kaca", "Kaca", "Kaca", "Peralatan Rumah", "Kaca jendela sangat bersih.", "Kaca jendhela resik.", "Kaca jendhela resik."],
            [586, "Kacang", "Kacang", "Kacang", "Tumbuhan", "Adik makan kacang rebus.", "Adhik mangan kacang godhog.", "Adhi dhahar kacang godhog."],
            [587, "Kacang hijau", "Kacang ijo", "Kacang ijem", "Tumbuhan", "Ibu memasak kacang hijau.", "Ibu masak kacang ijo.", "Ibu masak kacang ijem."],
            [588, "Kacamata", "Kacamata", "Kacamata", "Aksesori", "Kakek memakai kacamata.", "Mbah nganggo kacamata.", "Eyang ngagem kacamata."],
            [589, "Kacau", "Semrawut", "Semrawut", "Kata Sifat", "Kamarnya sangat kacau.", "Kamare semrawut.", "Kamaripun semrawut."],
            [590, "Kadal", "Cecak gedhe", "Kadal", "Hewan", "Kadal berjemur di batu.", "Cecak gedhe jemur ing watu.", "Kadal pinarak wonten sela."],
            [591, "Kadang", "Kadhang", "Kadhang", "Waktu", "Saya kadang terlambat.", "Aku kadhang telat.", "Kula kadhang telat."],
            [592, "Kader", "Kader", "Kader", "Organisasi", "Kader itu rajin bekerja.", "Kader kuwi sregep nyambut gawe.", "Kader punika sregep nyambut damel."],
            [593, "Hadang", "Adang", "Adang", "Kata Kerja", "Polisi menghadang kendaraan.", "Polisi adang montor.", "Polisi adang kendaraan."],
            [594, "Kado", "Hadiah", "Hadiah", "Kata Benda", "Saya memberi kado ulang tahun.", "Aku menehi hadiah ulang tahun.", "Kula maringi hadiah ambal warsa."],
            [595, "Kain", "Kain", "Kain", "Pakaian", "Ibu membeli kain batik.", "Ibu tuku kain batik.", "Ibu mundhut kain batik."],
            [596, "Kait", "Pancingan", "Pancingan", "Peralatan", "Kait itu terbuat dari besi.", "Pancingan kuwi digawe saka wesi.", "Pancingan punika kadamel saking wesi."],
            [597, "Kaki", "Sikil", "Suku", "Anggota Tubuh", "Kaki saya terasa pegal.", "Sikilku krasa pegel.", "Suku kula kraos pegel."],
            [598, "Kakak", "Mas/Mbak", "Raka/Yayi", "Keluarga", "Kakak sedang belajar.", "Mas lagi sinau.", "Raka saweg sinau."],
            [599, "Kakek", "Mbah Kakung", "Eyang Kakung", "Keluarga", "Kakek membaca koran.", "Mbah kakung maca koran.", "Eyang kakung maos koran."],
            [600, "Kakus", "WC", "Jamban", "Rumah", "Kakus selalu dibersihkan.", "WC tansah diresiki.", "Jamban tansah dipunresiki."],
            [601, "Kalajengking", "Kala jengking", "Kala jengking", "Hewan", "Kalajengking memiliki sengat.", "Kala jengking nduweni sengat.", "Kala jengking gadhah sengat."],
            [602, "Kalah", "Kalah", "Kalah", "Kata Kerja", "Tim kami kalah.", "Timku kalah.", "Tim kula kalah."],
            [603, "Kaldu", "Kaldu", "Kaldu", "Makanan", "Ibu membuat kaldu ayam.", "Ibu nggawe kaldu pitik.", "Ibu damel kaldu pitik."],
            [604, "Kalender", "Kalender", "Kalender", "Benda", "Kalender digantung di dinding.", "Kalender digantung ing tembok.", "Kalender dipungantung wonten tembok."],
            [605, "Kaleng", "Kaleng", "Kaleng", "Benda", "Susu itu dalam kaleng.", "Susu kuwi ana kaleng.", "Susu punika wonten kaleng."],
            [606, "Kali", "Kali", "Kali", "Alam", "Air kali sangat jernih.", "Banyu kali bening.", "Toya kali bening."],
            [607, "Kalimat", "Ukara", "Ukara", "Bahasa", "Guru menulis kalimat.", "Guru nulis ukara.", "Guru nyerat ukara."],
            [608, "Kalung", "Kalung", "Kalung", "Aksesori", "Ibu memakai kalung emas.", "Ibu nganggo kalung emas.", "Ibu ngagem kalung emas."],
            [609, "Kalut", "Bingung", "Bingung", "Perasaan", "Jangan kalut menghadapi masalah.", "Aja bingung ngadhepi masalah.", "Sampun bingung ngadhepi masalah."],
            [610, "Kamar", "Kamar", "Kamar", "Rumah", "Kamar adik sangat rapi.", "Kamar adhik rapi.", "Kamar adhi resik lan rapi."],
            [611, "Kambing", "Wedhus", "Menda", "Hewan", "Kambing makan rumput.", "Wedhus mangan suket.", "Menda dhahar suket."],
            [612, "Kambuh", "Kambuh", "Kambuh", "Kesehatan", "Penyakitnya kambuh lagi.", "Larane kambuh meneh.", "Gerahipun kambuh malih."],
            [613, "Kamis", "Kemis", "Kemis", "Waktu", "Hari Kamis kami olahraga.", "Dina Kemis kita olahraga.", "Dinten Kemis kula olahraga."],
            [614, "Kampung", "Desa", "Desa", "Tempat", "Kampung kami sangat damai.", "Desaku tentrem.", "Desa kula tentrem."],
            [615, "Kamus", "Kamus", "Kamus", "Pendidikan", "Saya membuka kamus Jawa.", "Aku mbukak kamus Jawa.", "Kula mbikak kamus Jawi."],
            [616, "Kandang", "Kandang", "Kandang", "Hewan", "Sapi masuk kandang.", "Sapi mlebu kandang.", "Sapi mlebet kandang."],
            [617, "Kangen", "Kangen", "Kangen", "Perasaan", "Saya kangen nenek.", "Aku kangen mbah putri.", "Kula kangen eyang putri."],
            [618, "Kantin", "Kantin", "Kantin", "Sekolah", "Siswa membeli makanan di kantin.", "Murid tuku panganan ing kantin.", "Siswa mundhut dhaharan wonten kantin."],
            [619, "Kantong", "Kanthong", "Kanthong", "Benda", "Masukkan buku ke kantong.", "Lebokna buku ing kanthong.", "Lebetaken buku wonten kanthong."],
            [620, "Kantor", "Kantor", "Kantor", "Bangunan", "Ayah bekerja di kantor.", "Bapak nyambut gawe ing kantor.", "Rama nyambut damel wonten kantor."],
            [621, "Kapas", "Kapas", "Kapas", "Tumbuhan", "Bantal itu berisi kapas.", "Bantal kuwi isi kapas.", "Bantal punika isi kapas."],
            [622, "Kapal", "Kapal", "Kapal", "Transportasi", "Kapal berlayar di laut.", "Kapal mlaku ing segara.", "Kapal mlampah wonten seganten."],
            [623, "Kapak", "Kapak", "Kapak", "Peralatan", "Ayah memakai kapak.", "Bapak nganggo kapak.", "Rama ngagem kapak."],
            [624, "Kapur", "Kapur", "Kapur", "Sekolah", "Guru menulis dengan kapur.", "Guru nulis nganggo kapur.", "Guru nyerat ngagem kapur."],
            [625, "Karangan", "Karangan", "Karangan", "Pendidikan", "Saya menulis karangan.", "Aku nulis karangan.", "Kula nyerat karangan."],
            [626, "Karang", "Karang", "Karang", "Alam", "Ikan hidup di karang.", "Iwak urip ing karang.", "Iwak gesang wonten karang."],
            [627, "Karet", "Karet", "Karet", "Benda", "Bola itu terbuat dari karet.", "Bal kuwi digawe saka karet.", "Bal punika kadamel saking karet."],
            [628, "Karisma", "Wibawa", "Kawibawan", "Kata Sifat", "Guru memiliki karisma tinggi.", "Guru nduweni wibawa.", "Guru gadhah kawibawan."],
            [629, "Karpet", "Karpet", "Karpet", "Peralatan Rumah", "Karpet ruang tamu bersih.", "Karpet ruang tamu resik.", "Karpet ruang tamu resik."],
            [630, "Karung", "Karung", "Karung", "Peralatan", "Padi dimasukkan ke karung.", "Pari dilebokake ing karung.", "Pari dipunlebetaken wonten karung."],
            [631, "Kasar", "Kasar", "Kasar", "Kata Sifat", "Batu itu kasar.", "Watu kuwi kasar.", "Sela punika kasar."],
            [632, "Kasih", "Tresna", "Tresna", "Perasaan", "Ibu memberi kasih sayang.", "Ibu menehi tresna.", "Ibu maringi tresna."],
            [633, "Kasihan", "Mesakake", "Melas", "Perasaan", "Saya kasihan pada anak itu.", "Aku mesakake bocah kuwi.", "Kula ngraos melas dhateng putra punika."],
            [634, "Kasur", "Kasur", "Kasur", "Peralatan Rumah", "Kasur itu sangat empuk.", "Kasur kuwi empuk.", "Kasur punika empuk."],
            [635, "Kata", "Tembung", "Tembung", "Bahasa", "Guru menjelaskan arti kata.", "Guru nerangake tegese tembung.", "Guru nerangaken tegesipun tembung."],
            [636, "Katak", "Kodhok", "Katak", "Hewan", "Katak melompat ke kolam.", "Kodhok mlumpat menyang blumbang.", "Katak mlumpat dhateng blumbang."],
            [637, "Katalog", "Katalog", "Katalog", "Teknologi", "Saya membaca katalog buku.", "Aku maca katalog buku.", "Kula maos katalog buku."],
            [638, "Katarak", "Katarak", "Katarak", "Kesehatan", "Kakek menjalani operasi katarak.", "Mbah operasi katarak.", "Eyang nglampahi operasi katarak."],
            [639, "Kategori", "Kategori", "Kategori", "Pendidikan", "Guru membuat kategori nilai.", "Guru nggawe kategori nilai.", "Guru damel kategori biji."],
            [640, "Kaus", "Kaos", "Kaos", "Pakaian", "Adik memakai kaus baru.", "Adhik nganggo kaos anyar.", "Adhi ngagem kaos enggal."],
            [641, "Kaus kaki", "Kaos sikil", "Kaos suku", "Pakaian", "Saya memakai kaus kaki.", "Aku nganggo kaos sikil.", "Kula ngagem kaos suku."],
            [642, "Kawah", "Kawah", "Kawah", "Alam", "Kawah gunung masih aktif.", "Kawah gunung isih aktif.", "Kawah redi taksih aktif."],
            [643, "Kaya", "Sugih", "Sugih", "Kata Sifat", "Tetangga kami kaya.", "Tanggaku sugih.", "Tanggi kula sugih."],
            [644, "Kayu", "Kayu", "Kayu", "Tumbuhan", "Meja itu terbuat dari kayu.", "Meja kuwi digawe saka kayu.", "Meja punika kadamel saking kayu."],
            [645, "Kebal", "Kebal", "Kebal", "Kata Sifat", "Tanaman itu kebal hama.", "Tanduran kuwi kebal hama.", "Tetuwuhan punika kebal hama."],
            [646, "Kebaya", "Kebaya", "Kebaya", "Pakaian", "Ibu memakai kebaya.", "Ibu nganggo kebaya.", "Ibu ngagem kebaya."],
            [647, "Kebersihan", "Karesikan", "Karesikan", "Kesehatan", "Kebersihan kelas dijaga bersama.", "Karesikan kelas dijaga bareng.", "Karesikan kelas dipunjagi sesarengan."],
            [648, "Kebisingan", "Rame banget", "Rame sanget", "Lingkungan", "Kebisingan mengganggu belajar.", "Rame banget ngganggu sinau.", "Rame sanget ngganggu sinau."],
            [649, "Kebun", "Kebon", "Kebon", "Tempat", "Kakek bekerja di kebun.", "Mbah nyambut gawe ing kebon.", "Eyang nyambut damel wonten kebon."],
            [650, "Kecap", "Kecap", "Kecap", "Makanan", "Ibu menambahkan kecap.", "Ibu nambahi kecap.", "Ibu nambahi kecap."],
            [651, "Kecelakaan", "Kacilakan", "Kecalan", "Kesehatan", "Tidak ada kecelakaan hari ini.", "Ora ana kacilakan dina iki.", "Boten wonten kecalan dinten punika."],
            [652, "Kecil", "Cilik", "Alit", "Kata Sifat", "Bola itu kecil.", "Bal kuwi cilik.", "Bal punika alit."],
            [653, "Kecoa", "Kecoak", "Kecoak", "Hewan", "Kecoa berlari cepat.", "Kecoak mlayu cepet.", "Kecoak mlayu rikat."],
            [654, "Kedai", "Kedai", "Kedai", "Tempat", "Ayah makan di kedai.", "Bapak mangan ing kedai.", "Rama dhahar wonten kedai."],
            [655, "Kedalaman", "Jero", "Lebet", "Alam", "Kedalaman sungai bertambah.", "Jerone kali tambah.", "Lebetipun kali saya tambah."],
            [656, "Kedatangan", "Teka", "Rawuh", "Kata Benda", "Kedatangan tamu disambut baik.", "Tekane tamu disambut apik.", "Rawuhipun tamu dipunsambut sae."],
            [657, "Kedip", "Kedhep", "Kedhep", "Kata Kerja", "Mata adik berkedip.", "Mripate adhik kedhep.", "Sochekipun adhi kedhep."],
            [658, "Kedokteran", "Ilmu dhokter", "Ilmu dhokter", "Pendidikan", "Kakak belajar kedokteran.", "Mas sinau ilmu dhokter.", "Raka sinau ilmu dhokter."],
            [659, "Kedondong", "Kedondhong", "Kedondhong", "Buah", "Kedondong rasanya asam.", "Kedondhong rasane kecut.", "Kedondhong raosipun kecut."],
            [660, "Kedua", "Loro-lorone", "Kalih-kalihipun", "Kata Bilangan", "Kedua teman itu rajin.", "Loro-lorone kanca kuwi sregep.", "Kalih-kalihipun kanca punika sregep."],
            [661, "Keesokan", "Besuke", "Mbenjing", "Waktu", "Keesokan hari kami berangkat.", "Besuke kita budhal.", "Mbenjing kula bidhal."],
            [662, "Kehendak", "Karep", "Kersa", "Kata Benda", "Kehendak ayah harus dihormati.", "Karepe bapak kudu diajeni.", "Kersanipun rama kedah dipunajeni."],
            [663, "Kehidupan", "Urip", "Panggesangan", "Kata Benda", "Kehidupan desa sangat tenang.", "Urip ing desa tentrem.", "Panggesangan wonten desa tentrem."],
            [664, "Keindahan", "Kaendahan", "Kaendahan", "Kata Benda", "Keindahan taman memukau.", "Kaendahan taman apik.", "Kaendahan taman sae."],
            [665, "Kejadian", "Kedadeyan", "Kedadeyan", "Kata Benda", "Kejadian itu mengejutkan.", "Kedadeyan kuwi ngagetake.", "Kedadeyan punika ngagetaken."],
            [666, "Keju", "Keju", "Keju", "Makanan", "Adik makan roti keju.", "Adhik mangan roti keju.", "Adhi dhahar roti keju."],
            [667, "Kelapa", "Klapa", "Klapa", "Tumbuhan", "Ayah memetik kelapa.", "Bapak methik klapa.", "Rama methik klapa."],
            [668, "Kelapa muda", "Degan", "Degan", "Minuman", "Saya minum air kelapa muda.", "Aku ngombe banyu degan.", "Kula ngunjuk toya degan."],
            [669, "Kelas", "Kelas", "Kelas", "Sekolah", "Kelas kami bersih.", "Kelasku resik.", "Kelas kula resik."],
            [670, "Kelelawar", "Codhot", "Codhot", "Hewan", "Kelelawar terbang malam hari.", "Codhot mabur bengi.", "Codhot mabur dalu."],
            [671, "Kelinci", "Terwelu", "Terwelu", "Hewan", "Kelinci makan wortel.", "Terwelu mangan wortel.", "Terwelu dhahar wortel."],
            [672, "Keliru", "Kleru", "Kliru", "Kata Sifat", "Jawaban saya keliru.", "Wangsulanku kleru.", "Wangsulan kula kliru."],
            [673, "Kelompok", "Klompok", "Klompok", "Pendidikan", "Guru membagi kelompok belajar.", "Guru mbagi klompok sinau.", "Guru mbagi klompok sinau."],
            [674, "Keluar", "Metu", "Medal", "Kata Kerja", "Ayah keluar rumah.", "Bapak metu omah.", "Rama medal griya."],
            [675, "Keluarga", "Kulawarga", "Kulawarga", "Keluarga", "Keluarga kami bahagia.", "Kulawargaku bungah.", "Kulawarga kula bingah."],
            [676, "Keluhan", "Sambat", "Sambat", "Kata Benda", "Ibu mendengar keluhan warga.", "Ibu krungu sambat warga.", "Ibu mireng sambat warga."],
            [677, "Kelulusan", "Lulus", "Lulus", "Pendidikan", "Kakak merayakan kelulusan.", "Mas ngrayakake lulus.", "Raka ngrayakaken lulus."],
            [678, "Kelinci percobaan", "Terwelu percobaan", "Terwelu percobaan", "Sains", "Guru menjelaskan kelinci percobaan.", "Guru nerangake terwelu percobaan.", "Guru nerangaken terwelu percobaan."],
            [679, "Kelopak", "Mahkota kembang", "Mahkota sekar", "Bunga", "Kelopak mawar berwarna merah.", "Mahkota kembang mawar abang.", "Mahkota sekar mawar abrit."],
            [680, "Keluhan", "Sambat", "Sambat", "Perasaan", "Ayah menyampaikan keluhan.", "Bapak nyampaikan sambat.", "Rama ngaturaken sambat."],
            [681, "Kemah", "Kemah", "Kemah", "Kegiatan", "Kami mendirikan kemah.", "Kita ngedegake kemah.", "Kula ngedegaken kemah."],
            [682, "Kemarin", "Wingi", "Kala wingi", "Waktu", "Kemarin saya belajar.", "Wingi aku sinau.", "Kala wingi kula sinau."],
            [683, "Kemas", "Ngepak", "Ngepak", "Kata Kerja", "Ibu mengemas makanan.", "Ibu ngepak panganan.", "Ibu ngepak dhaharan."],
            [684, "Kembang", "Kembang", "Sekar", "Bunga", "Kembang melati harum.", "Kembang melati wangi.", "Sekar melati wangi."],
            [685, "Kembar", "Kembar", "Kembar", "Keluarga", "Mereka anak kembar.", "Dheweke bocah kembar.", "Piyambakipun putra kembar."],
            [686, "Kemeja", "Klambi", "Klambi/Pangangge", "Pakaian", "Ayah memakai kemeja putih.", "Bapak nganggo klambi putih.", "Rama ngagem klambi putih."],
            [687, "Kemiri", "Kemiri", "Kemiri", "Tumbuhan", "Ibu memakai kemiri untuk memasak.", "Ibu nganggo kemiri kanggo masak.", "Ibu ngagem kemiri kangge masak."],
            [688, "Kemudi", "Kemudi", "Kemudi", "Transportasi", "Ayah memegang kemudi.", "Bapak nyekel kemudi.", "Rama nyepeng kemudi."],
            [689, "Kemungkinan", "Kamungkinan", "Kamungkinan", "Kata Benda", "Kemungkinan hujan besar.", "Kamungkinan udan deres.", "Kamungkinan udan deres."],
            [690, "Kena", "Kena", "Kenging", "Kata Kerja", "Bola kena kepala.", "Bal kena sirah.", "Bal kenging sirah."],
            [691, "Kenal", "Kenal", "Kenal", "Kata Kerja", "Saya kenal guru itu.", "Aku kenal guru kuwi.", "Kula kenal guru punika."],
            [692, "Kenalpot", "Kenalpot", "Kenalpot", "Kendaraan", "Kenalpot motor berbunyi keras.", "Kenalpot montor banter.", "Kenalpot montor seru."],
            [693, "Kencang", "Kenceng", "Kenceng", "Kata Sifat", "Angin bertiup kencang.", "Angin semilir kenceng.", "Angin kenceng."],
            [694, "Kencing", "Ngencing", "Nyedalaken toya seni", "Kesehatan", "Adik ingin kencing.", "Adhik arep ngencing.", "Adhi badhe nyedalaken toya seni."],
            [695, "Kendaraan", "Kendaraan", "Kendaraan", "Transportasi", "Kendaraan berhenti di lampu merah.", "Kendaraan mandheg ing lampu abang.", "Kendaraan mandheg wonten lampu abrit."],
            [696, "Kendi", "Kendi", "Kendi", "Peralatan Rumah", "Kendi itu berisi air.", "Kendi kuwi isi banyu.", "Kendi punika isi toya."],
            [697, "Kenduri", "Kenduren", "Kenduren", "Budaya", "Warga mengadakan kenduri.", "Warga nganakake kenduren.", "Warga nganakaken kenduren."],
            [698, "Kenyang", "Wareg", "Sarem", "Kata Sifat", "Saya sudah kenyang.", "Aku wis wareg.", "Kula sampun sarem."],
            [699, "Kepala", "Sirah", "Sirah", "Anggota Tubuh", "Kepala saya pusing.", "Sirahku mumet.", "Sirah kula mumet."],
            [700, "Kepiting", "Yuyu", "Yuyu", "Hewan", "Kepiting berjalan menyamping.", "Yuyu mlaku miring.", "Yuyu mlampah miring."],
            [701, "Keponakan", "Ponakan", "Ponakan", "Keluarga", "Keponakan bermain di halaman.", "Ponakan dolanan ing pekarangan.", "Ponakan dolanan wonten pekarangan."],
            [702, "Kepompong", "Kepompong", "Kepompong", "Hewan", "Kepompong menempel di daun.", "Kepompong nempel ing godhong.", "Kepompong nempel wonten godhong."],
            [703, "Keputusan", "Putusan", "Kaputusan", "Kata Benda", "Keputusan guru harus dipatuhi.", "Putusan kudu dituruti.", "Kaputusan guru kedah dipunturuti."],
            [704, "Kerah", "Kerah", "Kerah", "Pakaian", "Kerah baju itu bersih.", "Kerah klambi kuwi resik.", "Kerah klambi punika resik."],
            [705, "Keranjang", "Kranjang", "Kranjang", "Peralatan Rumah", "Ibu membawa keranjang belanja.", "Ibu nggawa kranjang blanja.", "Ibu ngasta kranjang blanja."],
            [706, "Kerbau", "Kebo", "Mahesa", "Hewan", "Kerbau membajak sawah.", "Kebo ngluku sawah.", "Mahesa ngluku sabin."],
            [707, "Kereta", "Sepur", "Sepur", "Transportasi", "Kereta tiba tepat waktu.", "Sepur teka pas wektu.", "Sepur rawuh pas wekdal."],
            [708, "Kereta api", "Sepur", "Sepur", "Transportasi", "Kami naik kereta api.", "Kita numpak sepur.", "Kula nitih sepur."],
            [709, "Kering", "Garing", "Garing", "Kata Sifat", "Pakaian sudah kering.", "Klambi wis garing.", "Klambi sampun garing."],
            [710, "Keringat", "Kringet", "Kringet", "Anggota Tubuh", "Keringat membasahi baju.", "Kringet mbasahi klambi.", "Kringet mbasahi klambi."],
            [711, "Keripik", "Kripik", "Kripik", "Makanan", "Saya makan keripik singkong.", "Aku mangan kripik tela.", "Kula dhahar kripik tela."],
            [712, "Keris", "Keris", "Keris", "Budaya", "Keris adalah pusaka Jawa.", "Keris kuwi pusaka Jawa.", "Keris punika pusaka Jawi."],
            [713, "Kerja", "Nyambut gawe", "Nyambut damel", "Profesi", "Ayah sedang bekerja.", "Bapak lagi nyambut gawe.", "Rama saweg nyambut damel."],
            [714, "Kerjakan", "Nggarap", "Nggarapaken", "Kata Kerja", "Siswa mengerjakan tugas.", "Murid nggarap tugas.", "Siswa nggarapaken tugas."],
            [715, "Kerudung", "Kudhung", "Kudhung", "Pakaian", "Ibu memakai kerudung biru.", "Ibu nganggo kudhung biru.", "Ibu ngagem kudhung biru."],
            [716, "Kerupuk", "Krupuk", "Krupuk", "Makanan", "Adik makan kerupuk.", "Adhik mangan krupuk.", "Adhi dhahar krupuk."],
            [717, "Kesal", "Mangkel", "Mangkel", "Perasaan", "Saya kesal karena terlambat.", "Aku mangkel merga telat.", "Kula mangkel amargi telat."],
            [718, "Kesalahan", "Kaluputan", "Kaluputan", "Kata Benda", "Kesalahan itu sudah diperbaiki.", "Kaluputan kuwi wis didandani.", "Kaluputan punika sampun dipundandosi."],
            [719, "Kesehatan", "Kaséhatan", "Kaséhatan", "Kesehatan", "Kesehatan sangat penting.", "Kaséhatan penting.", "Kaséhatan wigati."],
            [720, "Kesemek", "Kesemek", "Kesemek", "Buah", "Kesemek sudah matang.", "Kesemek wis mateng.", "Kesemek sampun mateng."],
            [721, "Keset", "Keset", "Keset", "Peralatan Rumah", "Keset ada di depan pintu.", "Keset ana ngarep lawang.", "Keset wonten ngajeng lawang."],
            [722, "Kesulitan", "Kangelan", "Kasangsaran", "Pendidikan", "Saya mengalami kesulitan belajar.", "Aku kangelan sinau.", "Kula ngalami kasangsaran sinau."],
            [723, "Ketela", "Tela", "Tela", "Tumbuhan", "Petani memanen ketela.", "Pak tani manen tela.", "Petani manen tela."],
            [724, "Keteladanan", "Tuladha", "Tuladha", "Pendidikan", "Guru memberi keteladanan baik.", "Guru menehi tuladha apik.", "Guru maringi tuladha sae."],
            [725, "Ketemu", "Ketemu", "Kepanggih", "Kata Kerja", "Saya ketemu teman lama.", "Aku ketemu kanca lawas.", "Kula kepanggih kanca kina."],
            [726, "Ketiga", "Katelu", "Kaping tiga", "Kata Bilangan", "Anak ketiga masih sekolah.", "Anak katelu isih sekolah.", "Putra kaping tiga taksih sekolah."],
            [727, "Ketimun", "Timun", "Timun", "Sayuran", "Timun itu segar.", "Timun kuwi seger.", "Timun punika seger."],
            [728, "Ketua", "Ketua", "Ketua", "Organisasi", "Ketua kelas memimpin doa.", "Ketua kelas mimpin donga.", "Ketua kelas mimpin pandonga."],
            [729, "Ketupat", "Kupat", "Kupat", "Makanan", "Ibu membuat ketupat.", "Ibu nggawe kupat.", "Ibu damel kupat."],
            [730, "Keuangan", "Keuangan", "Keuangan", "Ekonomi", "Ayah mengatur keuangan keluarga.", "Bapak ngatur keuangan kulawarga.", "Rama ngatur keuangan kulawarga."],
            [731, "Kewajiban", "Kewajiban", "Kewajiban", "Pendidikan", "Belajar adalah kewajiban siswa.", "Sinau kuwi kewajiban murid.", "Sinau punika kewajiban siswa."],
            [732, "Keyboard", "Keyboard", "Keyboard", "Komputer", "Saya mengetik memakai keyboard.", "Aku ngetik nganggo keyboard.", "Kula ngetik ngagem keyboard."],
            [733, "Khawatir", "Kuwatir", "Kuwatir", "Perasaan", "Ibu khawatir kepada adik.", "Ibu kuwatir karo adhik.", "Ibu kuwatir dhateng adhi."],
            [734, "Khotbah", "Khutbah", "Khutbah", "Agama", "Ustaz menyampaikan khotbah.", "Ustaz nyampaikan khutbah.", "Ustaz ngaturaken khutbah."],
            [735, "Khusus", "Mligi", "Mligi", "Kata Sifat", "Ruangan ini khusus guru.", "Ruangan iki mligi guru.", "Ruangan punika mligi guru."],
            [736, "Kipas", "Kipas", "Kipas", "Peralatan Rumah", "Kipas angin berputar pelan.", "Kipas angin muter alon.", "Kipas angin muter alon."],
            [737, "Kipas angin", "Kipas angin", "Kipas angin", "Peralatan Rumah", "Kipas angin membuat ruangan sejuk.", "Kipas angin nggawe ruangan adem.", "Kipas angin damel ruangan adem."],
            [738, "Kirim", "Ngirim", "Ngintun", "Kata Kerja", "Ayah mengirim surat.", "Bapak ngirim layang.", "Rama ngintun layang."],
            [739, "Kisah", "Crita", "Cariyos", "Sastra", "Guru membacakan kisah pendek.", "Guru maca crita cekak.", "Guru maos cariyos cekak."],
            [740, "Kismis", "Kismis", "Kismis", "Makanan", "Roti itu berisi kismis.", "Roti kuwi isi kismis.", "Roti punika isi kismis."],
            [741, "Kita", "Kita", "Kita", "Kata Ganti", "Kita belajar bersama.", "Kita sinau bareng.", "Kita sinau sesarengan."],
            [742, "Klakson", "Klakson", "Klakson", "Kendaraan", "Sopir membunyikan klakson.", "Sopir muni klakson.", "Sopir munyèkaken klakson."],
            [743, "Klambi", "Klambi", "Busana", "Pakaian", "Klambi itu sudah kering.", "Klambi kuwi wis garing.", "Busana punika sampun garing."],
            [744, "Klinik", "Klinik", "Klinik", "Kesehatan", "Adik berobat ke klinik.", "Adhik menyang klinik.", "Adhi dhateng klinik."],
            [745, "Klip", "Klip", "Klip", "Peralatan", "Guru memakai klip kertas.", "Guru nganggo klip kertas.", "Guru ngagem klip kertas."],
            [746, "Kode", "Kode", "Kode", "Teknologi", "Saya memasukkan kode sandi.", "Aku ngetik kode sandhi.", "Kula ngetik kode sandhi."],
            [747, "Koin", "Koin", "Koin", "Uang", "Adik menemukan koin.", "Adhik nemokake koin.", "Adhi manggihaken koin."],
            [748, "Kokoh", "Kukuh", "Kukuh", "Kata Sifat", "Jembatan itu kokoh.", "Kreteg kuwi kukuh.", "Kreteg punika kukuh."],
            [749, "Kolam", "Blumbang", "Blumbang", "Tempat", "Ikan berenang di kolam.", "Iwak nglangi ing blumbang.", "Iwak nglangi wonten blumbang."],
            [750, "Kolase", "Kolase", "Kolase", "Seni", "Siswa membuat kolase.", "Murid nggawe kolase.", "Siswa damel kolase."],
            [751, "Koleksi", "Koleksi", "Koleksi", "Kata Benda", "Kakek memiliki koleksi keris.", "Mbah duwe koleksi keris.", "Eyang gadhah koleksi keris."],
            [752, "Kolom", "Kolom", "Kolom", "Pendidikan", "Tulis jawaban pada kolom.", "Tulis wangsulan ing kolom.", "Serat wangsulan wonten kolom."],
            [753, "Komando", "Prentah", "Dhawuh", "Kata Benda", "Komandan memberi komando.", "Komandan menehi prentah.", "Komandan maringi dhawuh."],
            [754, "Komar", "Komar", "Komar", "Nama", "Nama anak itu Komar.", "Jenenge bocah kuwi Komar.", "Asmanipun putra punika Komar."],
            [755, "Kombinasi", "Kombinasi", "Kombinasi", "Pendidikan", "Warna itu kombinasi merah dan putih.", "Werna kuwi kombinasi abang lan putih.", "Warna punika kombinasi abrit lan putih."],
            [756, "Komedi", "Komedi", "Komedi", "Hiburan", "Kami menonton film komedi.", "Kita nonton film komedi.", "Kula mirsani film komedi."],
            [757, "Komet", "Komet", "Komet", "Alam", "Komet terlihat malam ini.", "Komet katon bengi iki.", "Komet katingal dalu punika."],
            [758, "Komik", "Komik", "Komik", "Buku", "Adik membaca komik.", "Adhik maca komik.", "Adhi maos komik."],
            [759, "Kompas", "Kompas", "Kompas", "Peralatan", "Kompas menunjukkan arah utara.", "Kompas nuduhake lor.", "Kompas nedahaken lér."],
            [760, "Kompor", "Kompor", "Kompor", "Dapur", "Ibu memasak memakai kompor.", "Ibu masak nganggo kompor.", "Ibu masak ngagem kompor."],
            [761, "Komputer", "Komputer", "Komputer", "Komputer", "Siswa belajar komputer.", "Murid sinau komputer.", "Siswa sinau komputer."],
            [762, "Komunitas", "Komunitas", "Komunitas", "Sosial", "Komunitas itu aktif berkegiatan.", "Komunitas kuwi aktif kegiyatan.", "Komunitas punika aktif kagiyatan."],
            [763, "Kondisi", "Kahanan", "Kawontenan", "Kata Benda", "Kondisi jalan baik.", "Kahanan dalan apik.", "Kawontenan margi sae."],
            [764, "Konferensi", "Konferensi", "Konferensi", "Pendidikan", "Guru mengikuti konferensi.", "Guru melu konferensi.", "Guru ndherek konferensi."],
            [765, "Konfirmasi", "Konfirmasi", "Konfirmasi", "Teknologi", "Saya menerima konfirmasi.", "Aku nampa konfirmasi.", "Kula tampi konfirmasi."],
            [766, "Konser", "Konser", "Konser", "Musik", "Mereka menonton konser.", "Dheweke nonton konser.", "Piyambakipun mirsani konser."],
            [767, "Konstitusi", "Konstitusi", "Konstitusi", "Pendidikan", "Guru menjelaskan konstitusi.", "Guru nerangake konstitusi.", "Guru nerangaken konstitusi."],
            [768, "Kontak", "Kontak", "Kontak", "Teknologi", "Saya menyimpan kontak baru.", "Aku nyimpen kontak anyar.", "Kula nyimpen kontak enggal."],
            [769, "Kontrol", "Ngontrol", "Ngontrol", "Kata Kerja", "Ayah mengontrol mesin.", "Bapak ngontrol mesin.", "Rama ngontrol mesin."],
            [770, "Kopi", "Kopi", "Kopi", "Minuman", "Ayah minum kopi hangat.", "Bapak ngombe kopi anget.", "Rama ngunjuk kopi anget."],
            [771, "Koran", "Koran", "Koran", "Buku", "Kakek membaca koran.", "Mbah maca koran.", "Eyang maos koran."],
            [772, "Korek", "Korek", "Korek", "Peralatan", "Ayah membawa korek api.", "Bapak nggawa korek.", "Rama ngasta korek."],
            [773, "Koridor", "Koridor", "Koridor", "Bangunan", "Siswa berjalan di koridor.", "Murid mlaku ing koridor.", "Siswa mlampah wonten koridor."],
            [774, "Kotak", "Kothak", "Kothak", "Benda", "Hadiah itu dalam kotak.", "Hadiah kuwi ana kothak.", "Hadiah punika wonten kothak."],
            [775, "Kotor", "Reged", "Reged", "Kata Sifat", "Sepatu saya kotor.", "Sepatuku reged.", "Sepatu kula reged."],
            [776, "Kran", "Kran", "Kran", "Peralatan Rumah", "Tutup kran setelah dipakai.", "Tutup kran sawise dienggo.", "Tutup kran sasampunipun dipunginakaken."],
            [777, "Kreatif", "Kreatif", "Kreatif", "Kata Sifat", "Anak itu sangat kreatif.", "Bocah kuwi kreatif.", "Putra punika kreatif."],
            [778, "Kresek", "Kresek", "Kresek", "Benda", "Sampah dimasukkan ke kresek.", "Sampah dilebokake ing kresek.", "Sampah dipunlebetaken wonten kresek."],
            [779, "Kreteg", "Kreteg", "Kreteg", "Bangunan", "Kreteg itu menghubungkan dua desa.", "Kreteg kuwi nyambungake loro desa.", "Kreteg punika nyambungaken kalih desa."],
            [780, "Krisan", "Krisan", "Krisan", "Bunga", "Bunga krisan berwarna kuning.", "Kembang krisan kuning.", "Sekar krisan kuning."],
            [781, "Krisis", "Krisis", "Krisis", "Kata Benda", "Desa menghadapi krisis air.", "Desa ngadhepi krisis banyu.", "Desa ngadhepi krisis toya."],
            [782, "Kristal", "Kristal", "Kristal", "Benda", "Gelas kristal itu bening.", "Gelas kristal kuwi bening.", "Gelas kristal punika bening."],
            [783, "Kritik", "Kritik", "Kritik", "Pendidikan", "Guru menerima kritik dengan baik.", "Guru nampa kritik kanthi apik.", "Guru tampi kritik kanthi sae."],
            [784, "Krokot", "Krokot", "Krokot", "Tumbuhan", "Tanaman krokot tumbuh subur.", "Krokot thukul subur.", "Krokot tuwuh subur."],
            [785, "Kubis", "Kobis", "Kobis", "Sayuran", "Ibu memasak kubis.", "Ibu masak kobis.", "Ibu masak kobis."],
            [786, "Kucing", "Kucing", "Kucing", "Hewan", "Kucing tidur di kursi.", "Kucing turu ing kursi.", "Kucing tilem wonten kursi."],
            [787, "Kuda", "Jaran", "Turangga", "Hewan", "Kuda berlari cepat.", "Jaran mlayu banter.", "Turangga mlayu rikat."],
            [788, "Kudapan", "Cemilan", "Sesawisan", "Makanan", "Adik membawa kudapan.", "Adhik nggawa cemilan.", "Adhi ngasta sesawisan."],
            [789, "Kudis", "Kudis", "Kudis", "Penyakit", "Anak itu terkena kudis.", "Bocah kuwi kena kudis.", "Putra punika kenging kudis."],
            [790, "Kue", "Jajan", "Jajan", "Makanan", "Ibu membuat kue.", "Ibu nggawe jajan.", "Ibu damel jajan."],
            [791, "Kuil", "Kuil", "Kuil", "Agama", "Mereka beribadah di kuil.", "Dheweke sembahyang ing kuil.", "Piyambakipun sembahyang wonten kuil."],
            [792, "Kuku", "Kuku", "Kuku", "Anggota Tubuh", "Kuku adik dipotong pendek.", "Kuku adhik dipotong cendhak.", "Kuku adhi dipuntugel cekak."],
            [793, "Kukus", "Ngukus", "Ngukus", "Kata Kerja", "Ibu mengukus ubi.", "Ibu ngukus tela.", "Ibu ngukus tela."],
            [794, "Kulit", "Kulit", "Kulit", "Anggota Tubuh", "Kulit bayi lembut.", "Kulit bayi alus.", "Kulit bayi alus."],
            [795, "Kulit manggis", "Kulit manggis", "Kulit manggis", "Tumbuhan", "Kulit manggis dimanfaatkan sebagai obat.", "Kulit manggis dienggo obat.", "Kulit manggis dipunginakaken obat."],
            [796, "Kulkas", "Kulkas", "Kulkas", "Peralatan Rumah", "Susu disimpan di kulkas.", "Susu disimpen ing kulkas.", "Susu dipunsimpen wonten kulkas."],
            [797, "Kulon", "Kulon", "Kulon", "Arah", "Rumah kami di sebelah barat.", "Omahku ana sisih kulon.", "Griya kula wonten sisih kulon."],
            [798, "Kumis", "Kumis", "Kumis", "Anggota Tubuh", "Ayah memiliki kumis tebal.", "Bapak duwe kumis kandel.", "Rama gadhah kumis kandel."],
            [799, "Kumpul", "Klumpuk", "Kempal", "Kata Kerja", "Kami berkumpul di aula.", "Kita klumpuk ing aula.", "Kula kempal wonten aula."],
            [800, "Kunci", "Kunci", "Kunci", "Peralatan", "Ayah mencari kunci motor.", "Bapak golek kunci montor.", "Rama pados kunci montor."],
            [801, "Kuning", "Kuning", "Kuning", "Warna", "Pisang itu kuning.", "Gedhang kuwi kuning.", "Pisang punika kuning."],
            [802, "Kunyit", "Kunyit", "Kunyit", "Tumbuhan", "Ibu memakai kunyit untuk memasak.", "Ibu nganggo kunyit kanggo masak.", "Ibu ngagem kunyit kangge masak."],
            [803, "Kupas", "Nglupas", "Nglupas", "Kata Kerja", "Adik mengupas jeruk.", "Adhik nglupas jeruk.", "Adhi nglupas jeruk."],
            [804, "Kupu-kupu", "Kupu-kupu", "Kupu-kupu", "Hewan", "Kupu-kupu hinggap di bunga.", "Kupu-kupu hinggap ing kembang.", "Kupu-kupu pinarak wonten sekar."],
            [805, "Kuramus", "Kuramus", "Kuramus", "Ikan", "Ikan kuramus hidup di sungai.", "Iwak kuramus urip ing kali.", "Iwak kuramus gesang wonten kali."],
            [806, "Kurma", "Kurma", "Kurma", "Buah", "Saya makan kurma.", "Aku mangan kurma.", "Kula dhahar kurma."],
            [807, "Kursi", "Kursi", "Kursi", "Peralatan Rumah", "Kursi itu terbuat dari kayu.", "Kursi kuwi digawe saka kayu.", "Kursi punika kadamel saking kayu."],
            [808, "Kurus", "Kurus", "Kurus", "Kata Sifat", "Anak itu kurus.", "Bocah kuwi kurus.", "Putra punika kurus."],
            [809, "Kusut", "Ruwet", "Ruwet", "Kata Sifat", "Rambut saya kusut.", "Rambutku ruwet.", "Rikma kula ruwet."],
            [810, "Kutu", "Kutu", "Kutu", "Hewan", "Kutu ada di rambut.", "Kutu ana ing rambut.", "Kutu wonten rikma."],
            [811, "Kuwali", "Kuwali", "Kuwali", "Peralatan Dapur", "Ibu memasak memakai kuwali.", "Ibu masak nganggo kuwali.", "Ibu masak ngagem kuwali."],
            [812, "Kwalitas", "Kualitas", "Kualitas", "Kata Benda", "Kualitas beras sangat baik.", "Kualitas beras apik.", "Kualitas beras sae."],
            [813, "Kwitansi", "Kwitansi", "Kwitansi", "Administrasi", "Ayah menyimpan kwitansi.", "Bapak nyimpen kwitansi.", "Rama nyimpen kwitansi."],
            [814, "Laba", "Laba", "Laba", "Ekonomi", "Toko memperoleh laba.", "Toko entuk laba.", "Toko pikantuk laba."],
            [815, "Laba-laba", "Lawa-lawa", "Lawa-lawa", "Hewan", "Laba-laba membuat sarang.", "Lawa-lawa nggawe sarang.", "Lawa-lawa damel sarang."],
            [816, "Label", "Label", "Label", "Teknologi", "Tempelkan label pada buku.", "Tempelna label ing buku.", "Tempelaken label wonten buku."],
            [817, "Laci", "Laci", "Laci", "Peralatan Rumah", "Kunci ada di laci.", "Kunci ana ing laci.", "Kunci wonten laci."],
            [818, "Ladang", "Ladang", "Ladang", "Pertanian", "Petani pergi ke ladang.", "Pak tani lunga menyang ladang.", "Petani tindak dhateng ladang."],
            [819, "Lagu", "Lagu", "Lagu", "Musik", "Kami menyanyikan lagu daerah.", "Kita nyanyi lagu daerah.", "Kula nembang lagu daerah."],
            [820, "Lahir", "Lair", "Lair", "Kata Kerja", "Adik lahir bulan Mei.", "Adhik lair wulan Mei.", "Adhi lair wulan Mei."],
        ];

        foreach ($dataset as $row) {
            $vocab = Vocabulary::updateOrCreate(
                ['id' => $row[0]],
                [
                    'indonesian_word' => $row[1],
                    'javanese_ngoko'  => $row[2],
                    'javanese_krama'  => $row[3],
                    'category'        => $row[4] ?? null,
                ]
            );

            if (!empty($row[5]) || !empty($row[6]) || !empty($row[7])) {
                VocabularyExample::updateOrCreate(
                    ['vocabulary_id' => $vocab->id],
                    [
                        'indonesian_sentence' => $row[5] ?? null,
                        'ngoko_sentence'      => $row[6] ?? null,
                        'krama_sentence'      => $row[7] ?? null,
                        'javanese_sentence'   => $row[6] ?? $row[7] ?? null,
                    ]
                );
            }
        }
    }
}
