<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatchSeeder1301To1740 extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            [1301, "Rebung", "Rebung", "Rebung", "Sayuran", "Ibu memasak rebung.", "Ibu masak rebung.", "Ibu masak rebung."],
            [1302, "Reda", "Mandheg", "Mandheg", "Kata Kerja", "Hujan mulai reda.", "Udan wiwit mandheg.", "Udan wiwit mandheg."],
            [1303, "Redup", "Surem", "Surem", "Kata Sifat", "Lampu itu redup.", "Lampu kuwi surem.", "Lampu punika surem."],
            [1304, "Referensi", "Referensi", "Referensi", "Pendidikan", "Guru memberikan referensi buku.", "Guru menehi referensi buku.", "Guru maringi referensi buku."],
            [1305, "Regu", "Regu", "Regu", "Olahraga", "Regu kami menang lomba.", "Reguku menang lomba.", "Regu kula menang lomba."],
            [1306, "Rekening", "Rekening", "Rekening", "Ekonomi", "Ayah membuka rekening baru.", "Bapak mbukak rekening anyar.", "Rama mbikak rekening enggal."],
            [1307, "Rel", "Rel", "Rel", "Transportasi", "Kereta berjalan di atas rel.", "Sepur mlaku ing rel.", "Sepur lumampah wonten rel."],
            [1308, "Relawan", "Relawan", "Relawan", "Profesi", "Relawan membantu korban banjir.", "Relawan nulungi korban banjir.", "Relawan mitulungi korban banjir."],
            [1309, "Religius", "Religius", "Religius", "Agama", "Anak itu religius.", "Bocah kuwi religius.", "Putra punika religius."],
            [1310, "Rembulan", "Rembulan", "Rembulan", "Alam", "Rembulan bersinar terang.", "Rembulan padhang.", "Rembulan padhang."],
            [1311, "Rempah", "Rempah", "Rempah", "Tumbuhan", "Ibu membeli rempah dapur.", "Ibu tuku rempah pawon.", "Ibu mundhut rempah pawon."],
            [1312, "Rendah", "Chekak/Endhek", "Andhap", "Kata Sifat", "Meja itu rendah.", "Meja kuwi endhek.", "Meja punika andhap."],
            [1313, "Rendam", "Ngrendem", "Ngrendem", "Kata Kerja", "Ibu merendam kacang.", "Ibu ngrendem kacang.", "Ibu ngrendem kacang."],
            [1314, "Renggang", "Renggang", "Renggang", "Kata Sifat", "Jarak rumah berjauhan.", "Omah-omah renggang.", "Griya-griya renggang."],
            [1315, "Renjang", "Ranjang", "Ranjang", "Perabot", "Ranjang bayi sangat bersih.", "Ranjang bayi resik.", "Ranjang bayi resik."],
            [1316, "Rentan", "Rentan", "Rentan", "Kata Sifat", "Bayi rentan sakit.", "Bayi rentan lara.", "Bayi rentan gerah."],
            [1317, "Renyah", "Kriuk", "Kriuk", "Kata Sifat", "Kerupuk itu renyah.", "Krupuk kuwi kriuk.", "Krupuk punika kriuk."],
            [1318, "Resep", "Resep", "Resep", "Kesehatan", "Dokter menulis resep.", "Dhokter nulis resep.", "Dhokter nyerat resep."],
            [1319, "Resmi", "Resmi", "Resmi", "Kata Sifat", "Pengumuman itu resmi.", "Pengumuman kuwi resmi.", "Pengumuman punika resmi."],
            [1320, "Restoran", "Restoran", "Restoran", "Tempat", "Keluarga makan di restoran.", "Kulawarga mangan ing restoran.", "Kulawarga dhahar wonten restoran."],
            [1321, "Retak", "Retak", "Retak", "Kata Sifat", "Gelas itu retak.", "Gelas kuwi retak.", "Gelas punika retak."],
            [1322, "Retas", "Retas", "Retas", "Teknologi", "Akun itu diretas.", "Akun kuwi diretas.", "Akun punika diretas."],
            [1323, "Riang", "Bungah", "Bingah", "Perasaan", "Anak-anak riang bermain.", "Bocah-bocah bungah dolanan.", "Para putra bingah dolanan."],
            [1324, "Ribu", "Ewu", "Sewu", "Kata Bilangan", "Saya memiliki seribu rupiah.", "Aku duwe sewu rupiah.", "Kula gadhah sewu rupiah."],
            [1325, "Rimba", "Alas", "Wana", "Alam", "Banyak hewan hidup di rimba.", "Akeh kewan urip ing alas.", "Kathah sato gesang wonten wana."],
            [1326, "Rindu", "Kangen", "Kangen", "Perasaan", "Saya rindu nenek.", "Aku kangen mbah.", "Kula kangen eyang."],
            [1327, "Ringan", "Entheng", "Entheng", "Kata Sifat", "Tas itu ringan.", "Tas kuwi entheng.", "Tas punika entheng."],
            [1328, "Ringkasan", "Ringkesan", "Ringkesan", "Pendidikan", "Guru memberi ringkasan materi.", "Guru menehi ringkesan materi.", "Guru maringi ringkesan materi."],
            [1329, "Ringin", "Beringin", "Waringin", "Pohon", "Pohon ringin sangat besar.", "Wit beringin gedhe.", "Uwit waringin ageng."],
            [1330, "Rintik", "Greneng", "Greneng", "Cuaca", "Hujan rintik turun pagi.", "Udan greneng esuk.", "Udan greneng enjing."],
            [1331, "Risalah", "Risalah", "Risalah", "Dokumen", "Risalah rapat sudah selesai.", "Risalah rapat wis rampung.", "Risalah rapat sampun rampung."],
            [1332, "Riset", "Panaliten", "Panaliten", "Pendidikan", "Mahasiswa melakukan riset.", "Mahasiswa nindakake panaliten.", "Mahasiswa nindakaken panaliten."],
            [1333, "Rok", "Rok", "Rok", "Pakaian", "Adik memakai rok merah.", "Adhik nganggo rok abang.", "Adhi ngagem rok abrit."],
            [1334, "Roket", "Roket", "Roket", "Teknologi", "Roket meluncur ke angkasa.", "Roket mabur menyang langit.", "Roket mabur dhateng akasa."],
            [1335, "Roti", "Roti", "Roti", "Makanan", "Ibu membeli roti hangat.", "Ibu tuku roti anget.", "Ibu mundhut roti anget."],
            [1336, "Ruang", "Ruangan", "Ruangan", "Bangunan", "Ruangan kelas sangat bersih.", "Ruangan kelas resik.", "Ruangan kelas resik."],
            [1337, "Ruang tamu", "Ruang tamu", "Ruang tamu", "Rumah", "Tamu duduk di ruang tamu.", "Tamu lungguh ing ruang tamu.", "Tamu lenggah wonten ruang tamu."],
            [1338, "Ruas", "Ruas", "Ruas", "Tumbuhan", "Bambu memiliki banyak ruas.", "Pring nduweni akeh ruas.", "Pring gadhah kathah ruas."],
            [1339, "Rubah", "Rubah", "Rubah", "Hewan", "Rubah sangat cerdik.", "Rubah pinter.", "Rubah pinter."],
            [1340, "Rumah", "Omah", "Griya", "Rumah", "Rumah kami bersih.", "Omahku resik.", "Griya kula resik."],
            [1341, "Rumput", "Suket", "Rumput", "Tumbuhan", "Sapi makan rumput.", "Sapi mangan suket.", "Sapi dhahar rumput."],
            [1342, "Rusa", "Kijang", "Kijang", "Hewan", "Rusa berlari di hutan.", "Kijang mlayu ing alas.", "Kijang mlayu wonten wana."],
            [1343, "Rusak", "Rusak", "Rusak", "Kata Sifat", "Sepeda itu rusak.", "Pit kuwi rusak.", "Pit punika risak."],
            [1344, "Rusun", "Rusun", "Rusun", "Bangunan", "Mereka tinggal di rusun.", "Dheweke manggon ing rusun.", "Piyambakipun manggèn wonten rusun."],
            [1345, "Rute", "Rute", "Rute", "Transportasi", "Sopir memilih rute tercepat.", "Sopir milih rute paling cepet.", "Sopir milih rute paling enggal."],
            [1346, "Saat", "Nalika", "Nalika", "Kata Hubung", "Saya datang saat hujan.", "Aku teka nalika udan.", "Kula rawuh nalika udan."],
            [1347, "Saban", "Saben", "Saben", "Kata Keterangan", "Ayah berjalan saban pagi.", "Bapak mlaku saben esuk.", "Rama mlampah saben enjing."],
            [1348, "Sabar", "Sabar", "Sabar", "Kata Sifat", "Guru selalu sabar.", "Guru tansah sabar.", "Guru tansah sabar."],
            [1349, "Sabit", "Arit", "Arit", "Peralatan", "Petani membawa sabit.", "Petani nggawa arit.", "Petani ngasta arit."],
            [1350, "Sabtu", "Setu", "Sabtu", "Waktu", "Hari Sabtu kami libur.", "Dina Setu kita prei.", "Dinten Sabtu kula prei."],
            [1351, "Sagu", "Sagu", "Sagu", "Makanan", "Papeda dibuat dari sagu.", "Papeda digawe saka sagu.", "Papeda kadamel saking sagu."],
            [1352, "Sahabat", "Kanca cedhak", "Rencang raket", "Keluarga", "Sahabat selalu membantu.", "Kanca cedhak tansah nulungi.", "Rencang raket tansah mitulungi."],
            [1353, "Sahur", "Sahur", "Sahur", "Agama", "Kami makan sahur bersama.", "Kita mangan sahur bareng.", "Kula dhahar sahur sesarengan."],
            [1354, "Sakit", "Lara", "Gerah", "Kesehatan", "Adik sedang sakit.", "Adhik lagi lara.", "Adhi saweg gerah."],
            [1355, "Sakit kepala", "Sirah lara", "Sirah gerah", "Kesehatan", "Ayah sakit kepala.", "Bapak sirah lara.", "Rama sirah gerah."],
            [1356, "Sakit perut", "Weteng lara", "Padharan gerah", "Kesehatan", "Anak itu sakit perut.", "Bocah kuwi weteng lara.", "Putra punika padharan gerah."],
            [1357, "Saksi", "Seksi", "Seksi", "Hukum", "Saksi memberikan keterangan.", "Seksi menehi katerangan.", "Seksi maringi katerangan."],
            [1358, "Saku", "Saku", "Saku", "Pakaian", "Uang ada di saku baju.", "Dhuwit ana ing saku klambi.", "Arta wonten saku busana."],
            [1359, "Salad", "Salad", "Salad", "Makanan", "Ibu membuat salad buah.", "Ibu nggawe salad woh.", "Ibu damel salad woh."],
            [1360, "Salak", "Salak", "Salak", "Buah", "Buah salak rasanya manis.", "Salak rasane legi.", "Salak raosipun manis."],
            [1361, "Salam", "Salam", "Salam", "Ungkapan", "Anak memberi salam.", "Bocah menehi salam.", "Putra maringi salam."],
            [1362, "Salat", "Salat", "Sembahyang", "Agama", "Kami salat berjamaah.", "Kita salat berjamaah.", "Kula sembahyang berjamaah."],
            [1363, "Salep", "Salep", "Salep", "Obat", "Dokter memberi salep.", "Dhokter menehi salep.", "Dhokter maringi salep."],
            [1364, "Salju", "Salju", "Salju", "Alam", "Salju berwarna putih.", "Salju putih.", "Salju putih."],
            [1365, "Saluran", "Saluran", "Saluran", "Bangunan", "Saluran air dibersihkan.", "Saluran banyu diresiki.", "Saluran toya dipunresiki."],
            [1366, "Sama", "Padha", "Sami", "Kata Sifat", "Mereka memakai baju sama.", "Dheweke nganggo klambi padha.", "Piyambakipun ngagem busana sami."],
            [1367, "Sambar", "Nyamber", "Nyamber", "Kata Kerja", "Elang menyambar ikan.", "Manuk garudha nyamber iwak.", "Garudha nyamber iwak."],
            [1368, "Sambal", "Sambel", "Sambel", "Makanan", "Ibu membuat sambal pedas.", "Ibu nggawe sambel pedhes.", "Ibu damel sambel pedhes."],
            [1369, "Sambil", "Nalika", "Nalika", "Kata Hubung", "Adik belajar sambil mendengar musik.", "Adhik sinau nalika ngrungokake musik.", "Adhi sinau nalika mireng musik."],
            [1370, "Sambung", "Nyambung", "Nyambung", "Kata Kerja", "Ayah menyambung kabel.", "Bapak nyambung kabel.", "Rama nyambung kabel."],
            [1371, "Sampah", "Sampah", "Sampah", "Lingkungan", "Buang sampah pada tempatnya.", "Buwang sampah ing panggonane.", "Bucal sampah wonten papanipun."],
            [1372, "Samping", "Sisih", "Sisih", "Kata Depan", "Rumahku di samping sekolah.", "Omahku ana sisih sekolah.", "Griya kula wonten sisih sekolah."],
            [1373, "Sampul", "Sampul", "Sampul", "Benda", "Buku itu memakai sampul baru.", "Buku kuwi nganggo sampul anyar.", "Buku punika ngagem sampul enggal."],
            [1374, "Santri", "Santri", "Santri", "Agama", "Santri belajar mengaji.", "Santri sinau ngaji.", "Santri sinau ngaji."],
            [1375, "Santan", "Santen", "Santen", "Makanan", "Ibu memasak gulai dengan santan.", "Ibu masak gulai nganggo santen.", "Ibu masak gulai ngagem santen."],
            [1376, "Santai", "Santai", "Santai", "Kata Sifat", "Kami duduk santai.", "Kita lungguh santai.", "Kula lenggah santai."],
            [1377, "Sapu", "Sapu", "Sapu", "Peralatan", "Ibu membeli sapu baru.", "Ibu tuku sapu anyar.", "Ibu mundhut sapu enggal."],
            [1378, "Sarang", "Sarang", "Sarang", "Hewan", "Burung membuat sarang.", "Manuk nggawe sarang.", "Manuk damel sarang."],
            [1379, "Sarapan", "Nyarap", "Dhahar enjing", "Aktivitas", "Kami sarapan bersama.", "Kita nyarap bareng.", "Kula dhahar enjing sesarengan."],
            [1380, "Sarung", "Sarung", "Sarung", "Pakaian", "Ayah memakai sarung.", "Bapak nganggo sarung.", "Rama ngagem sarung."],
            [1381, "Sastra", "Sastra", "Sastra", "Pendidikan", "Saya belajar sastra Jawa.", "Aku sinau sastra Jawa.", "Kula sinau sastra Jawi."],
            [1382, "Satelit", "Satelit", "Satelit", "Teknologi", "Satelit mengelilingi bumi.", "Satelit ngubengi bumi.", "Satelit ngubengi bumi."],
            [1383, "Satpam", "Satpam", "Satpam", "Profesi", "Satpam menjaga sekolah.", "Satpam njaga sekolah.", "Satpam njagi sekolah."],
            [1384, "Satuan", "Satuan", "Satuan", "Pendidikan", "Guru menjelaskan satuan panjang.", "Guru nerangake satuan dawa.", "Guru nerangaken satuan dawa."],
            [1385, "Satwa", "Kewan", "Sato", "Hewan", "Kebun binatang melindungi satwa.", "Kebon kewan nglindhungi kewan.", "Kebon satwa nglindhungi sato."],
            [1386, "Sawah", "Sawah", "Sabin", "Pertanian", "Petani bekerja di sawah.", "Petani nyambut gawe ing sawah.", "Petani nyambut damel wonten sabin."],
            [1387, "Sawi", "Sawi", "Sawi", "Sayuran", "Ibu memasak sawi hijau.", "Ibu masak sawi ijo.", "Ibu masak sawi ijem."],
            [1388, "Sayang", "Tresna", "Asih", "Perasaan", "Ibu sangat sayang kepada adik.", "Ibu tresna adhik.", "Ibu asih dhateng adhi."],
            [1389, "Sayap", "Swiwi", "Laras", "Hewan", "Burung mengepakkan sayap.", "Manuk ngepak swiwi.", "Manuk ngepak laras."],
            [1390, "Sayur", "Sayur", "Sayur", "Makanan", "Adik makan sayur setiap hari.", "Adhik mangan sayur saben dina.", "Adhi dhahar sayur saben dinten."],
            [1391, "Sebab", "Sebab", "Sebab", "Kata Hubung", "Saya tahu sebabnya.", "Aku ngerti sebabe.", "Kula mangertos sebabipun."],
            [1392, "Sebelah", "Sisih", "Sisih", "Kata Depan", "Rumahnya di sebelah masjid.", "Omahe ana sisih masjid.", "Griyanipun wonten sisih masjid."],
            [1393, "Sebelum", "Sadurunge", "Saderengipun", "Kata Hubung", "Cuci tangan sebelum makan.", "Wisuh tangan sadurunge mangan.", "Wasuh asta saderengipun dhahar."],
            [1394, "Sebentar", "Sedhela", "Sekedhap", "Kata Keterangan", "Tunggu sebentar.", "Ngenteni sedhela.", "Ngentosi sekedhap."],
            [1395, "Sebrang", "Nyabrang", "Nyabrang", "Kata Kerja", "Kami menyeberang jalan.", "Kita nyabrang dalan.", "Kula nyabrang margi."],
            [1396, "Sebutan", "Sebutan", "Sebutan", "Bahasa", "Nama itu hanya sebutan.", "Jeneng kuwi mung sebutan.", "Asma punika namung sebutan."],
            [1397, "Secara bertahap", "Alon-alon", "Sakedhik mbaka setunggal", "Kata Keterangan", "Pohon tumbuh secara bertahap.", "Wit thukul alon-alon.", "Uwit tuwuh sakedhik mbaka setunggal."],
            [1398, "Sedang", "Lagi", "Saweg", "Kata Keterangan", "Ayah sedang membaca.", "Bapak lagi maca.", "Rama saweg maos."],
            [1399, "Sedap", "Enaak", "Sae raos", "Kata Sifat", "Sup ini sangat sedap.", "Sop iki enak.", "Sop punika sae raos."],
            [1400, "Sedekah", "Sedhekah", "Sedhekah", "Agama", "Kita suka bersedekah.", "Kita seneng sedhekah.", "Kula remen sedhekah."],
            [1401, "Sederhana", "Gampang/Sederhana", "Sederhana", "Kata Sifat", "Rumah mereka sederhana.", "Omahe sederhana.", "Griyanipun sederhana."],
            [1402, "Sedih", "Susah/Bingung", "Sedhih", "Perasaan", "Adik terlihat sedih.", "Adhik katon susah.", "Adhi katingal sedhih."],
            [1403, "Sendal", "Sandal", "Sandal", "Pakaian", "Sendal saya baru.", "Sandalku anyar.", "Sandal kula enggal."],
            [1404, "Segar", "Seger", "Enggal/Kesah", "Kata Sifat", "Udara pagi sangat segar.", "Hawa esuk seger.", "Hawa enjing seger."],
            [1405, "Sehat", "Sehat", "Sehat", "Kesehatan", "Semoga ayah selalu sehat.", "Muga bapak tansah sehat.", "Mugi rama tansah sehat."],
            [1406, "Seikat", "Saket", "Saket", "Kata Bilangan", "Ibu membeli seikat bayam.", "Ibu tuku saket bayem.", "Ibu mundhut saket bayem."],
            [1407, "Seimbang", "Imbang", "Imbang", "Kata Sifat", "Timbangan itu seimbang.", "Timbangan kuwi imbang.", "Timbangan punika imbang."],
            [1408, "Sejarah", "Sejarah", "Sejarah", "Pendidikan", "Kami belajar sejarah Indonesia.", "Kita sinau sejarah Indonesia.", "Kula sinau sejarah Indonesia."],
            [1409, "Sejuk", "Adem", "Asrep", "Kata Sifat", "Udara pegunungan sangat sejuk.", "Hawa pagunungan adem.", "Hawa pagunungan asrep."],
            [1410, "Sekarang", "Saiki", "Sapunika", "Waktu", "Sekarang waktunya belajar.", "Saiki wayahe sinau.", "Sapunika wekdalipun sinau."],
            [1411, "Sekolah", "Sekolah", "Sekolah", "Pendidikan", "Adik pergi ke sekolah.", "Adhik lunga sekolah.", "Adhi tindak sekolah."],
            [1412, "Sekop", "Sekop", "Sekop", "Peralatan", "Ayah memakai sekop.", "Bapak nganggo sekop.", "Rama ngagem sekop."],
            [1413, "Sekrup", "Sekrup", "Sekrup", "Peralatan", "Tukang memasang sekrup.", "Tukang masang sekrup.", "Tukang masang sekrup."],
            [1414, "Seksi", "Seksi", "Seksi", "Kata Sifat", "Ruangan tampak rapi dan seksi.", "Ruangan katon apik lan seksi.", "Ruangan katingal sae lan seksi."],
            [1415, "Sekul", "Sega", "Sekul", "Makanan", "Nenek memasak sekul hangat.", "Mbah masak sega anget.", "Eyang masak sekul anget."],
            [1416, "Selada", "Selada", "Selada", "Sayuran", "Ibu mencuci selada.", "Ibu ngumbah selada.", "Ibu ngumbah selada."],
            [1417, "Selalu", "Tansah", "Tansah", "Kata Keterangan", "Guru selalu tersenyum.", "Guru tansah mesem.", "Guru tansah mesem."],
            [1418, "Selamat", "Wilujeng", "Wilujeng", "Ungkapan", "Guru mengucapkan selamat pagi.", "Guru ngomong wilujeng enjing.", "Guru ngaturaken wilujeng enjing."],
            [1419, "Selasa", "Selasa", "Selasa", "Waktu", "Hari Selasa ada upacara.", "Dina Selasa ana upacara.", "Dinten Selasa wonten upacara."],
            [1420, "Selatan", "Kidul", "Kidul", "Arah", "Rumah kami menghadap selatan.", "Omahku madhep kidul.", "Griya kula madhep kidul."],
            [1421, "Selang", "Slang", "Slang", "Peralatan", "Ayah menyiram tanaman dengan selang.", "Bapak nyirami tanduran nganggo slang.", "Rama nyirami tetuwuhan ngagem slang."],
            [1422, "Selasar", "Selasar", "Selasar", "Bangunan", "Siswa berjalan di selasar.", "Murid mlaku ing selasar.", "Siswa mlampah wonten selasar."],
            [1423, "Seledri", "Seledri", "Seledri", "Sayuran", "Ibu menambahkan seledri ke sup.", "Ibu nambah seledri ing sop.", "Ibu nambah seledri wonten sop."],
            [1424, "Selempang", "Selempang", "Selempang", "Pakaian", "Dia memakai selempang merah.", "Dheweke nganggo selempang abang.", "Piyambakipun ngagem selempang abrit."],
            [1425, "Selesai", "Rampung", "Sampun rampung", "Kata Kerja", "Tugas saya sudah selesai.", "Tugasku wis rampung.", "Tugas kula sampun rampung."],
            [1426, "Selimut", "Kemul", "Kemul", "Peralatan Rumah", "Adik memakai selimut saat tidur.", "Adhik nganggo kemul turu.", "Adhi ngagem kemul nalika tilem."],
            [1427, "Selokan", "Got", "Got", "Bangunan", "Air mengalir di selokan.", "Banyu mili ing got.", "Toya mili wonten got."],
            [1428, "Seluncur", "Ngluncur", "Ngluncur", "Olahraga", "Anak bermain seluncur.", "Bocah dolanan ngluncur.", "Putra dolanan ngluncur."],
            [1429, "Semangka", "Semangka", "Semangka", "Buah", "Semangka rasanya segar.", "Semangka rasane seger.", "Semangka raosipun seger."],
            [1430, "Semangat", "Semangat", "Semangat", "Perasaan", "Siswa belajar dengan semangat.", "Murid sinau semangat.", "Siswa sinau kanthi semangat."],
            [1431, "Semak", "Grumbul", "Grumbul", "Tumbuhan", "Burung bersembunyi di semak.", "Manuk ndhelik ing grumbul.", "Manuk ndhelik wonten grumbul."],
            [1432, "Sembah", "Sembah", "Sembah", "Budaya", "Abdi melakukan sembah kepada raja.", "Abdi sembah marang raja.", "Abdi sembah dhateng raja."],
            [1433, "Sembahyang", "Sembahyang", "Sembahyang", "Agama", "Keluarga sembahyang bersama.", "Kulawarga sembahyang bareng.", "Kulawarga sembahyang sesarengan."],
            [1434, "Sembilan", "Sanga", "Sangang", "Kata Bilangan", "Adik memiliki sembilan balon.", "Adhik duwe sanga balon.", "Adhi gadhah sangang balon."],
            [1435, "Sembuh", "Mari", "Waras", "Kesehatan", "Adik sudah sembuh.", "Adhik wis mari.", "Adhi sampun waras."],
            [1436, "Sembunyi", "Ndhelik", "Ndhelik", "Kata Kerja", "Kucing sembunyi di bawah meja.", "Kucing ndhelik ngisor meja.", "Kucing ndhelik ngandhap meja."],
            [1437, "Semesta", "Jagad", "Jagad", "Alam", "Tuhan menciptakan semesta.", "Gusti nggawe jagad.", "Gusti nitahaken jagad."],
            [1438, "Semoga", "Muga", "Mugi", "Ungkapan", "Semoga kamu sehat selalu.", "Muga kowe tansah sehat.", "Mugi panjenengan tansah sehat."],
            [1439, "Sempit", "Ciyut", "Ciyut", "Kata Sifat", "Gang itu sangat sempit.", "Gang kuwi ciyut.", "Gang punika ciyut."],
            [1440, "Semut", "Semut", "Semut", "Hewan", "Semut membawa makanan.", "Semut nggawa panganan.", "Semut ngasta dhaharan."],
            [1441, "Senang", "Seneng", "Remen", "Perasaan", "Saya senang bermain.", "Aku seneng dolanan.", "Kula remen dolanan."],
            [1442, "Sendi", "Sendhi", "Sendhi", "Anggota Tubuh", "Sendi lutut terasa sakit.", "Sendhi dhengkul lara.", "Sendhi jengku kraos lara."],
            [1443, "Sendok", "Sendhok", "Sendhok", "Peralatan Rumah", "Ibu membeli sendok baru.", "Ibu tuku sendhok anyar.", "Ibu mundhut sendhok enggal."],
            [1444, "Senja", "Sore", "Surup", "Alam", "Langit indah saat senja.", "Langit apik wektu sore.", "Langit endah nalika surup."],
            [1445, "Senyum", "Mesem", "Mesem", "Kata Kerja", "Adik selalu tersenyum.", "Adhik tansah mesem.", "Adhi tansah mesem."],
            [1446, "Sepak", "Nyepak", "Nyepak", "Kata Kerja", "Anak menendang bola.", "Bocah nyepak bal.", "Putra nyepak bal."],
            [1447, "Sepak bola", "Bal-balan", "Sepak bola", "Olahraga", "Kami bermain sepak bola.", "Kita bal-balan.", "Kula dolanan sepak bola."],
            [1448, "Sepanjang", "Sakdawane", "Sakdawanipun", "Kata Depan", "Pohon tumbuh sepanjang jalan.", "Wit thukul sakdawane dalan.", "Uwit tuwuh sakdawanipun margi."],
            [1449, "Sepatu", "Sepatu", "Sepatu", "Pakaian", "Sepatu saya bersih.", "Sepatuku resik.", "Sepatu kula resik."],
            [1450, "Sepeda", "Pit", "Sepeda", "Transportasi", "Adik naik sepeda.", "Adhik numpak pit.", "Adhi nitih sepeda."],
            [1451, "Sepeda motor", "Montor", "Montor", "Transportasi", "Ayah berangkat naik sepeda motor.", "Bapak mangkat numpak montor.", "Rama tindak nitih montor."],
            [1452, "Sepeda ontel", "Pit onthel", "Sepeda onthel", "Transportasi", "Kakek masih memakai sepeda ontel.", "Mbah isih numpak pit onthel.", "Eyang taksih nitih sepeda onthel."],
            [1453, "Sepi", "Sepi", "Sepi", "Kata Sifat", "Jalan itu sepi malam hari.", "Dalan kuwi sepi bengi.", "Margi punika sepi dalu."],
            [1454, "Seprai", "Laken", "Laken", "Peralatan Rumah", "Ibu mengganti seprai tempat tidur.", "Ibu ngganti laken amben.", "Ibu nggantos laken paturon."],
            [1455, "September", "September", "September", "Waktu", "Sekolah mulai aktif bulan September.", "Sekolah aktif wulan September.", "Sekolah aktif wulan September."],
            [1456, "Seragam", "Seragam", "Seragam", "Pakaian", "Siswa memakai seragam putih.", "Murid nganggo seragam putih.", "Siswa ngagem seragam putih."],
            [1457, "Serai", "Sereh", "Sereh", "Tumbuhan", "Ibu memakai serai untuk memasak.", "Ibu nganggo sereh kanggo masak.", "Ibu ngagem sereh kangge masak."],
            [1458, "Serambi", "Serambi", "Serambi", "Rumah", "Kakek duduk di serambi.", "Mbah lungguh ing serambi.", "Eyang lenggah wonten serambi."],
            [1459, "Serangga", "Serangga", "Serangga", "Hewan", "Kupu-kupu adalah serangga.", "Kupu-kupu kuwi serangga.", "Kupu-kupu punika serangga."],
            [1460, "Serbuk", "Bubuk", "Bubuk", "Benda", "Serbuk kayu bertebaran.", "Bubuk kayu sumebar.", "Bubuk kajeng sumebar."],
            [1461, "Serdadu", "Prajurit", "Prajurit", "Profesi", "Serdadu menjaga perbatasan.", "Prajurit njaga tapel wates.", "Prajurit njagi tapel wates."],
            [1462, "Sereal", "Sereal", "Sereal", "Makanan", "Adik makan sereal pagi ini.", "Adhik mangan sereal esuk iki.", "Adhi dhahar sereal enjing punika."],
            [1463, "Seret", "Abot", "Awrat", "Kata Sifat", "Pintu itu seret dibuka.", "Lawang kuwi abot dibukak.", "Lawang punika awrat dipunbikak."],
            [1464, "Seribu", "Sewu", "Sewu", "Kata Bilangan", "Ayah memiliki seribu rupiah.", "Bapak nduweni sewu rupiah.", "Rama gadhah sewu rupiah."],
            [1465, "Sering", "Asring", "Asring", "Kata Keterangan", "Saya sering membaca buku.", "Aku asring maca buku.", "Kula asring maos buku."],
            [1466, "Serius", "Tenanan", "Saestu", "Kata Sifat", "Guru berbicara serious.", "Guru ngomong tenanan.", "Guru ngendika saestu."],
            [1467, "Seruling", "Suling", "Suling", "Musik", "Kakek memainkan seruling.", "Mbah main suling.", "Eyang nabuh suling."],
            [1468, "Servis", "Ndandani", "Ndandosi", "Kata Kerja", "Ayah servis sepeda.", "Bapak ndandani pit.", "Rama ndandosi sepeda."],
            [1469, "Sesak", "Sesek", "Sesek", "Kesehatan", "Dadanya terasa sesak.", "Dhadhane krasa sesek.", "Dhadanipun kraos sesek."],
            [1470, "Sesuai", "Cocog", "Cocog", "Kata Sifat", "Jawabanmu sudah sesuai.", "Jawabanmu wis cocog.", "Wangsulan panjenengan sampun cocog."],
            [1471, "Setelah", "Sawise", "Sasampunipun", "Kata Hubung", "Kami belajar setelah makan.", "Kita sinau sawise mangan.", "Kula sinau sasampunipun dhahar."],
            [1472, "Setengah", "Separo", "Sasekawan", "Kata Bilangan", "Gelas itu berisi setengah air.", "Gelas kuwi isi separo banyu.", "Gelas punika isi sasekawan toya."],
            [1473, "Setrika", "Setlika", "Setrika", "Peralatan Rumah", "Ibu menyetrika baju.", "Ibu nyetrika klambi.", "Ibu nyetrika busana."],
            [1474, "Setuju", "Setuju", "Sarujuk", "Kata Kerja", "Kami setuju dengan usulan itu.", "Kita setuju usulan kuwi.", "Kula sarujuk kaliyan usul punika."],
            [1475, "Siang", "Awan", "Siang", "Waktu", "Kami belajar siang hari.", "Kita sinau awan.", "Kula sinau siang."],
            [1476, "Siapa", "Sapa", "Sinten", "Kata Tanya", "Siapa guru itu?", "Sapa guru kuwi?", "Sinten guru punika?"],
            [1477, "Siap", "Siyap", "Siyap", "Kata Sifat", "Siswa siap mengikuti ujian.", "Murid siyap melu ujian.", "Siswa siyap ndherek ujian."],
            [1478, "Siaran", "Siaran", "Siaran", "Media", "Kami mendengar siaran radio.", "Kita ngrungokake siaran radio.", "Kula mireng siaran radio."],
            [1479, "Sifat", "Sipat", "Sipat", "Kata Benda", "Sifat jujur harus dijaga.", "Sipat jujur kudu dijaga.", "Sipat jujur kedah dipunjagi."],
            [1480, "Sikat", "Sikat", "Sikat", "Peralatan", "Ayah membeli sikat baru.", "Bapak tuku sikat anyar.", "Rama mundhut sikat enggal."],
            [1481, "Siku", "Sikut", "Sikut", "Anggota Tubuh", "Siku adik terluka.", "Sikute adhik tatu.", "Sikutipun adhi tatu."],
            [1482, "Simpan", "Nyimpen", "Nyimpen/Kasimpen", "Kata Kerja", "Ibu menyimpan uang.", "Ibu nyimpen dhuwit.", "Ibu nyimpen arta."],
            [1483, "Singa", "Singa", "Singa", "Hewan", "Singa hidup di kebun binatang.", "Singa urip ing kebon kewan.", "Singa gesang wonten kebon satwa."],
            [1484, "Singgah", "Mampir", "Mampir", "Kata Kerja", "Kami singgah ke rumah paman.", "Kita mampir omahe paklik.", "Kula mampir griyanipun paman."],
            [1485, "Singkong", "Tela pohung", "Tela pohung", "Tumbuhan", "Ibu merebus singkong.", "Ibu nggodhog tela pohung.", "Ibu nggodhog tela pohung."],
            [1486, "Sirkus", "Sirkus", "Sirkus", "Hiburan", "Anak-anak menonton sirkus.", "Bocah-bocah nonton sirkus.", "Para putra mirsani sirkus."],
            [1487, "Sirup", "Sirup", "Sirup", "Minuman", "Ibu membuat sirup dingin.", "Ibu nggawe sirup adhem.", "Ibu damel sirup asrep."],
            [1488, "Sisa", "Sisa", "Sisa", "Kata Benda", "Masih ada sisa makanan.", "Isih ana sisa panganan.", "Taksih wonten sisa dhaharan."],
            [1489, "Sisir", "Sisir", "Sisir", "Peralatan", "Ibu membeli sisir baru.", "Ibu tuku sisir anyar.", "Ibu mundhut sisir enggal."],
            [1490, "Siswa", "Murid", "Siswa", "Pendidikan", "Siswa belajar di kelas.", "Murid sinau ing kelas.", "Siswa sinau wonten kelas."],
            [1491, "Sistem", "Sistem", "Sistem", "Teknologi", "Sistem berjalan dengan baik.", "Sistem mlaku apik.", "Sistem lumampah sae."],
            [1492, "Siul", "Singsot", "Singsot", "Kata Kerja", "Anak itu suka bersiul.", "Bocah kuwi seneng singsot.", "Putra punika remen singsot."],
            [1493, "Skala", "Skala", "Skala", "Pendidikan", "Guru menjelaskan skala peta.", "Guru nerangake skala peta.", "Guru nerangaken skala peta."],
            [1494, "Sketsa", "Sketsa", "Sketsa", "Seni", "Adik menggambar sketsa.", "Adhik nggambar sketsa.", "Adhi nggambar sketsa."],
            [1495, "Smartphone", "Ponsel", "Ponsel", "Teknologi", "Ayah membeli smartphone baru.", "Bapak tuku ponsel anyar.", "Rama mundhut ponsel enggal."],
            [1496, "Solat", "Salat", "Sembahyang", "Agama", "Kami salat berjamaah.", "Kita salat berjamaah.", "Kula sembahyang berjamaah."],
            [1497, "Solusi", "Solusi", "Solusi", "Pendidikan", "Guru memberikan solusi.", "Guru menehi solusi.", "Guru maringi solusi."],
            [1498, "Sopan", "Sopan", "Sopan", "Kata Sifat", "Anak itu sangat sopan.", "Bocah kuwi sopan.", "Putra punika sopan."],
            [1499, "Sore", "Sore", "Sonten", "Waktu", "Ayah pulang sore.", "Bapak mulih sore.", "Rama kondur sonten."],
            [1500, "Sosis", "Sosis", "Sosis", "Makanan", "Adik makan sosis goreng.", "Adhik mangan sosis goreng.", "Adhi dhahar sosis goreng."],
            [1501, "Sotong", "Cumi-cumi", "Cumi-cumi", "Hewan", "Sotong hidup di laut.", "Cumi-cumi urip ing segara.", "Cumi-cumi gesang wonten seganten."],
            [1502, "Sop", "Sop", "Sop", "Makanan", "Ibu memasak sop ayam.", "Ibu masak sop pitik.", "Ibu masak sop pitik."],
            [1503, "Sopan santun", "Tata krama", "Tata krama", "Unggah-ungguh", "Siswa harus menjaga sopan santun.", "Murid kudu njaga tata krama.", "Siswa kedah njagi tata krama."],
            [1504, "Sopir", "Sopir", "Sopir", "Profesi", "Sopir mengemudikan bus.", "Sopir nyopir bis.", "Sopir nyetir bis."],
            [1505, "Sorban", "Surban", "Surban", "Pakaian", "Kakek memakai sorban putih.", "Mbah nganggo surban putih.", "Eyang ngagem surban putih."],
            [1506, "Sorot", "Cahya", "Cahya", "Kata Benda", "Sorot lampu sangat terang.", "Cahya lampu padhang.", "Cahya lampu padhang."],
            [1507, "Sosis ayam", "Sosis pitik", "Sosis pitik", "Makanan", "Adik menyukai sosis ayam.", "Adhik seneng sosis pitik.", "Adhi remen sosis pitik."],
            [1508, "Soto", "Soto", "Soto", "Makanan", "Kami makan soto pagi.", "Kita mangan soto esuk.", "Kula dhahar soto enjing."],
            [1509, "Spanduk", "Spanduk", "Spanduk", "Benda", "Spanduk dipasang di depan sekolah.", "Spanduk dipasang ngarep sekolah.", "Spanduk dipunpasang ngajeng sekolah."],
            [1510, "Speaker", "Speaker", "Speaker", "Teknologi", "Speaker mengeluarkan suara keras.", "Speaker ngetokake swara banter.", "Speaker ngedalaken swanten seru."],
            [1511, "Spidol", "Spidol", "Spidol", "Alat Tulis", "Guru menulis memakai spidol.", "Guru nulis nganggo spidol.", "Guru nyerat ngagem spidol."],
            [1512, "Spinner", "Spinner", "Spinner", "Permainan", "Anak memainkan spinner.", "Bocah dolanan spinner.", "Putra dolanan spinner."],
            [1513, "Spion", "Spion", "Spion", "Kendaraan", "Ayah membersihkan spion motor.", "Bapak ngresiki spion montor.", "Rama ngresiki spion montor."],
            [1514, "Spons", "Spons", "Spons", "Peralatan", "Ibu mencuci piring memakai spons.", "Ibu ngumbah piring nganggo spons.", "Ibu ngumbah piring ngagem spons."],
            [1515, "Stadion", "Stadion", "Stadion", "Tempat", "Pertandingan diadakan di stadion.", "Pertandhingan dianakake ing stadion.", "Pertandhingan dipunadani wonten stadion."],
            [1516, "Stempel", "Stempel", "Stempel", "Peralatan", "Kepala sekolah memberi stempel.", "Kepala sekolah menehi stempel.", "Kepala sekolah maringi stempel."],
            [1517, "Stopkontak", "Stop kontak", "Stop kontak", "Listrik", "Colokkan kabel ke stopkontak.", "Colokna kabel menyang stop kontak.", "Colokna kabel dhateng stop kontak."],
            [1518, "Strawberi", "Stroberi", "Stroberi", "Buah", "Stroberi rasanya manis.", "Stroberi rasane legi.", "Stroberi raosipun manis."],
            [1519, "Suami", "Bojo lanang", "Somah kakung", "Keluarga", "Suami membantu istrinya.", "Bojo lanang nulungi bojone.", "Somah kakung mitulungi garwanipun."],
            [1520, "Suara", "Swara", "Swanten", "Kata Benda", "Suara burung merdu.", "Swara manuk apik.", "Swanten manuk sae."],
            [1521, "Subur", "Subur", "Subur", "Kata Sifat", "Tanah ini sangat subur.", "Lemah iki subur.", "Lemah punika subur."],
            [1522, "Suci", "Suci", "Suci", "Agama", "Hati harus tetap suci.", "Ati kudu tetep suci.", "Manah kedah tansah suci."],
            [1523, "Sudah", "Wis", "Sampun", "Kata Keterangan", "Saya sudah selesai.", "Aku wis rampung.", "Kula sampun rampung."],
            [1524, "Sudut", "Pojok", "Pojok", "Bentuk", "Bola itu berada di sudut.", "Bal ana ing pojok.", "Bal wonten pojok."],
            [1525, "Suhu", "Suhu", "Suhu", "Sains", "Suhu udara meningkat.", "Suhu hawa mundhak.", "Suhu hawa mundhak."],
            [1526, "Sujud", "Sujud", "Sujud", "Agama", "Umat Islam melakukan sujud.", "Umat Islam sujud.", "Umat Islam sujud."],
            [1527, "Suka", "Seneng", "Remen", "Perasaan", "Saya suka membaca buku.", "Aku seneng maca buku.", "Kula remen maos buku."],
            [1528, "Sukun", "Sukun", "Sukun", "Buah", "Sukun digoreng ibu.", "Sukun digoreng ibu.", "Sukun dipungoreng ibu."],
            [1529, "Suku", "Suku", "Suku", "Sosial", "Indonesia memiliki banyak suku.", "Indonesia nduweni akeh suku.", "Indonesia gadhah kathah suku."],
            [1530, "Suling", "Suling", "Suling", "Musik", "Anak memainkan suling.", "Bocah main suling.", "Putra nabuh suling."],
            [1531, "Sulit", "Angel", "Awrat", "Kata Sifat", "Soal itu sulit.", "Soal kuwi angel.", "Pitaken punika awrat."],
            [1532, "Sultan", "Sultan", "Sultan", "Keraton", "Sultan memimpin keraton.", "Sultan mimpin keraton.", "Sultan mimpin karaton."],
            [1533, "Sumber", "Sumber", "Sumber", "Kata Benda", "Air berasal dari sumber.", "Banyu saka sumber.", "Toya saking sumber."],
            [1534, "Sumur", "Sumur", "Sumur", "Rumah", "Air sumur sangat jernih.", "Banyu sumur bening.", "Toya sumur bening."],
            [1535, "Sungai", "Kali", "Kali", "Alam", "Sungai mengalir ke laut.", "Kali mili menyang segara.", "Kali mili dhateng seganten."],
            [1536, "Suntik", "Nyuntik", "Nyuntik", "Kesehatan", "Dokter menyuntik pasien.", "Dhokter nyuntik pasien.", "Dhokter nyuntik pasien."],
            [1537, "Surat", "Layang", "Layang", "Dokumen", "Ayah menerima surat.", "Bapak nampa layang.", "Rama nampi layang."],
            [1538, "Surga", "Swarga", "Swarga", "Agama", "Semoga masuk surga.", "Muga mlebu swarga.", "Mugi mlebet swarga."],
            [1539, "Suruh", "Ngongkon", "Ngusung/Ngutus", "Kata Kerja", "Ibu menyuruh adik belajar.", "Ibu ngongkon adhik sinau.", "Ibu ngutus adhi sinau."],
            [1540, "Susu", "Susu", "Susu", "Minuman", "Adik minum susu hangat.", "Adhik ngombe susu anget.", "Adhi ngunjuk susu anget."],
            [1541, "Susut", "Susut", "Susut", "Kata Kerja", "Air sungai mulai susut.", "Banyu kali wiwit susut.", "Toya kali wiwit susut."],
            [1542, "Sutra", "Sutra", "Sutra", "Bahan", "Kain sutra terasa halus.", "Kain sutra alus.", "Kain sutra alus."],
            [1543, "Swadaya", "Gotong royong", "Gotong royong", "Sosial", "Warga bekerja secara swadaya.", "Warga gotong royong.", "Warga gotong royong."],
            [1544, "Swakarya", "Swakarya", "Swakarya", "Sosial", "Program swakarya berjalan baik.", "Program swakarya mlaku apik.", "Program swakarya lumampah sae."],
            [1545, "Swalayan", "Toko swalayan", "Toko swalayan", "Tempat", "Ibu berbelanja di swalayan.", "Ibu blanja ing toko swalayan.", "Ibu blanja wonten toko swalayan."],
            [1546, "Swapraja", "Swapraja", "Swapraja", "Sejarah", "Daerah itu dahulu swapraja.", "Dhisik daerah kuwi swapraja.", "Rumiyin tlatah punika swapraja."],
            [1547, "Swasembada", "Swasembada", "Swasembada", "Pertanian", "Negara menuju swasembada pangan.", "Negara menyang swasembada pangan.", "Negari tumuju swasembada pangan."],
            [1548, "Sweater", "Sweater", "Sweater", "Pakaian", "Adik memakai sweater biru.", "Adhik nganggo sweater biru.", "Adhi ngagem sweater biru."],
            [1549, "Syair", "Syair", "Syair", "Sastra", "Guru membacakan syair.", "Guru maca syair.", "Guru maos syair."],
            [1550, "Syarat", "Syarat", "Syarat", "Kata Benda", "Semua syarat sudah lengkap.", "Kabeh syarat wis jangkep.", "Sedaya syarat sampun jangkep."],
            [1551, "Syukur", "Sukur", "Sukur", "Perasaan", "Kita harus selalu bersyukur.", "Kita kudu tansah sukur.", "Kita kedah tansah sukur."],
            [1552, "Tabib", "Tabib", "Tabib", "Profesi", "Tabib mengobati pasien.", "Tabib ngobati pasien.", "Tabib nambani pasien."],
            [1553, "Tabrak", "Nabrak", "Nabrak", "Kata Kerja", "Sepeda menabrak batu.", "Pit nabrak watu.", "Sepeda nabrak sela."],
            [1554, "Tabung", "Tabung", "Tabung", "Benda", "Gas disimpan dalam tabung.", "Gas disimpen ing tabung.", "Gas dipunsimpen wonten tabung."],
            [1555, "Tadah", "Nadah", "Nadah", "Kata Kerja", "Ember menadah air hujan.", "Ember nadah banyu udan.", "Ember nadah toya jawah."],
            [1556, "Tafsir", "Tafsir", "Tafsir", "Agama", "Guru menjelaskan tafsir ayat.", "Guru nerangake tafsir ayat.", "Guru nerangaken tafsir ayat."],
            [1557, "Tagih", "Nagih", "Nagih", "Kata Kerja", "Pedagang menagih pembayaran.", "Bakul nagih bayaran.", "Bakul nagih pambayaran."],
            [1558, "Tahan", "Nahan", "Nahan", "Kata Kerja", "Ayah menahan pintu.", "Bapak nahan lawang.", "Rama nahan lawang."],
            [1559, "Tahu", "Tahu", "Tahu", "Makanan", "Ibu menggoreng tahu.", "Ibu nggoreng tahu.", "Ibu nggoreng tahu."],
            [1560, "Tahu", "Mangerti/Ngerti", "Ngertos", "Kata Kerja", "Saya tahu jawabannya.", "Aku ngerti wangsulane.", "Kula ngertos wangsulanipun."],
            [1561, "Tahun", "Taun", "Taun", "Waktu", "Adik berumur tujuh tahun.", "Adhik umur pitung taun.", "Adhi yuswa pitu taun."],
            [1562, "Tajam", "Landhep", "Landhep", "Kata Sifat", "Pisau itu sangat tajam.", "Lading kuwi landhep.", "Lading punika landhep."],
            [1563, "Takdir", "Takdir", "Takdir", "Agama", "Kita percaya kepada takdir.", "Kita percaya takdir.", "Kula pitados dhateng takdir."],
            [1564, "Taksi", "Taksi", "Taksi", "Transportasi", "Mereka naik taksi ke bandara.", "Dheweke numpak taksi menyang bandara.", "Piyambakipun nitih taksi dhateng bandara."],
            [1565, "Tali", "Tali", "Tali", "Benda", "Ayah mengikat kayu dengan tali.", "Bapak naleni kayu nganggo tali.", "Rama naleni kajeng ngagem tali."],
            [1566, "Taman", "Taman", "Taman", "Tempat", "Anak bermain di taman.", "Bocah dolanan ing taman.", "Putra dolanan wonten taman."],
            [1567, "Tamasya", "Tamasya", "Tamasya", "Aktivitas", "Kami pergi tamasya sekolah.", "Kita tamasya sekolah.", "Kula tamasya sekolah."],
            [1568, "Tambah", "Nambah", "Nambah", "Kata Kerja", "Ibu menambah gula.", "Ibu nambah gula.", "Ibu nambah gula."],
            [1569, "Tambak", "Tambak", "Tambak", "Pertanian", "Petani memelihara ikan di tambak.", "Petani ngingu iwak ing tambak.", "Petani ngingu iwak wonten tambak."],
            [1570, "Tambal", "Nambal", "Nambal", "Kata Kerja", "Ayah menambal ban bocor.", "Bapak nambal ban bocor.", "Rama nambal ban bocor."],
            [1571, "Tambang", "Tambang", "Tambang", "Pertambangan", "Tambang batu bara sangat luas.", "Tambang batu bara amba.", "Tambang batu bara amba."],
            [1572, "Tamu", "Tamu", "Tamu", "Kata Benda", "Tamu datang sore hari.", "Tamu teka sore.", "Tamu rawuh sonten."],
            [1573, "Tanda", "Tandha", "Tetenger", "Kata Benda", "Rambu menjadi tanda jalan.", "Rambu dadi tandha dalan.", "Rambu dados tetenger margi."],
            [1574, "Tandan", "Tandan", "Tandan", "Tumbuhan", "Satu tandan pisang dipanen.", "Sak tandan gedhang dipanen.", "Setunggal tandan pisang dipunpanen."],
            [1575, "Tangan", "Tangan", "Asta", "Anggota Tubuh", "Cuci tangan sebelum makan.", "Wisuh tangan sadurunge mangan.", "Wasuh asta saderengipun dhahar."],
            [1576, "Tangga", "Undhakan", "Undhakan", "Rumah", "Adik naik tangga.", "Adhik munggah undhakan.", "Adhi minggah undhakan."],
            [1577, "Tanggal", "Tanggal", "Tanggal", "Waktu", "Hari ini tanggal lima.", "Dina iki tanggal lima.", "Dinten punika tanggal gangsal."],
            [1578, "Tangguh", "Kuwat", "Kiyat", "Kata Sifat", "Dia anak yang tangguh.", "Dheweke bocah kuwat.", "Piyambakipun putra kiyat."],
            [1579, "Tangkap", "Nangkep", "Nangkep", "Kata Kerja", "Ayah menangkap ikan.", "Bapak nangkep iwak.", "Rama nangkep iwak."],
            [1580, "Tangki", "Tangki", "Tangki", "Benda", "Air disimpan dalam tangki.", "Banyu disimpen ing tangki.", "Toya dipunsimpen wonten tangki."],
            [1581, "Tanjak", "Tanjakan", "Tanjakan", "Jalan", "Jalan itu memiliki tanjakan curam.", "Dalan kuwi nduweni tanjakan curam.", "Margi punika gadhah tanjakan curam."],
            [1582, "Tanjung", "Tanjung", "Tanjung", "Geografi", "Kapal berhenti di tanjung.", "Kapal mandheg ing tanjung.", "Kapal kendel wonten tanjung."],
            [1583, "Tanya", "Takon", "Nyos/Pitaken", "Kata Kerja", "Adik bertanya kepada guru.", "Adhik takon marang guru.", "Adhi pitaken dhateng guru."],
            [1584, "Tape", "Tape", "Tape", "Makanan", "Nenek membuat tape singkong.", "Mbah nggawe tape tela.", "Eyang damel tape tela."],
            [1585, "Tapak", "Tlapak", "Tlapak", "Anggota Tubuh", "Tapak kaki terkena lumpur.", "Tlapak sikil kena lendhut.", "Tlapak suku kenging lendhut."],
            [1586, "Tapel batas", "Tapel wates", "Tapel wates", "Geografi", "Petugas menjaga tapel batas.", "Petugas njaga tapel wates.", "Petugas njagi tapel wates."],
            [1587, "Tarik", "Narik", "Narik", "Kata Kerja", "Ayah menarik gerobak.", "Bapak narik grobag.", "Rama narik grobag."],
            [1588, "Tari", "Joged/Tari", "Tari", "Seni", "Siswa belajar tari Jawa.", "Murid sinau joged Jawa.", "Siswa sinau tari Jawi."],
            [1589, "Taring", "Taring", "Taring", "Hewan", "Harimau memiliki taring tajam.", "Macan nduweni taring landhep.", "Macan gadhah taring landhep."],
            [1590, "Taruh", "Naruh", "Nyelehaken", "Kata Kerja", "Ibu menaruh buku di meja.", "Ibu naruh buku ing meja.", "Ibu nyelehaken buku wonten meja."],
            [1591, "Tas", "Tas", "Tas", "Benda", "Tas sekolah saya berat.", "Tasku abot.", "Tas kula awrat."],
            [1592, "Tasbih", "Tasbih", "Tasbih", "Agama", "Kakek membawa tasbih.", "Mbah nggawa tasbih.", "Eyang ngasta tasbih."],
            [1593, "Tata bahasa", "Tata basa", "Tata basa", "Bahasa", "Guru mengajarkan tata bahasa.", "Guru mulang tata basa.", "Guru mucal tata basa."],
            [1594, "Tata krama", "Tata krama", "Tata krama", "Unggah-ungguh", "Anak harus memiliki tata krama.", "Bocah kudu nduweni tata krama.", "Putra kedah gadhah tata krama."],
            [1595, "Tatap", "Ndelok", "Ningali", "Kata Kerja", "Adik menatap langit.", "Adhik ndelok langit.", "Adhi ningali langit."],
            [1596, "Tawa", "Guyu", "Gujeng", "Perasaan", "Tawa mereka sangat lepas.", "Guyune banter.", "Gujengipun bingah."],
            [1597, "Tawar", "Hambar", "Hambar", "Kata Sifat", "Sup itu terasa tawar.", "Sop kuwi hambar.", "Sop punika hambar."],
            [1598, "Tawon", "Tawon", "Tawon", "Hewan", "Tawon membuat sarang.", "Tawon nggawe sarang.", "Tawon damel sarang."],
            [1599, "Tebal", "Kandel", "Kandel", "Kata Sifat", "Buku itu sangat tebal.", "Buku kuwi kandel.", "Buku punika kandel."],
            [1600, "Tebang", "Nebang", "Nebang", "Kata Kerja", "Petani menebang bambu.", "Petani nebang pring.", "Petani nebang pring."],
            [1601, "Tebing", "Tebing", "Tebing", "Alam", "Tebing itu sangat tinggi.", "Tebing kuwi dhuwur.", "Tebing punika inggil."],
            [1602, "Tebu", "Tebu", "Tebu", "Tumbuhan", "Tebu rasanya manis.", "Tebu rasane legi.", "Tebu raosipun manis."],
            [1603, "Teduh", "Rindhang", "Rindhang", "Kata Sifat", "Pohon itu sangat teduh.", "Wit kuwi rindhang.", "Uwit punika rindhang."],
            [1604, "Tegak", "Ngadeg jejeg", "Jejeg", "Kata Sifat", "Bendera berdiri tegak.", "Gendera ngadeg jejeg.", "Gendéra jejeg."],
            [1605, "Tegar", "Kukuh", "Kukuh", "Kata Sifat", "Ayah tetap tegar.", "Bapak tetep kukuh.", "Rama tansah kukuh."],
            [1606, "Tegas", "Tegas", "Tegas", "Kata Sifat", "Guru bersikap tegas.", "Guru tumindak tegas.", "Guru tumindak tegas."],
            [1607, "Teguk", "Ngombe", "Ngunjuk", "Kata Kerja", "Adik meneguk air.", "Adhik ngombe banyu.", "Adhi ngunjuk toya."],
            [1608, "Teh", "Teh", "Teh", "Minuman", "Ibu membuat teh hangat.", "Ibu nggawe teh anget.", "Ibu damel teh anget."],
            [1609, "Teladan", "Tuladha", "Tuladha", "Kata Benda", "Guru menjadi teladan siswa.", "Guru dadi tuladha murid.", "Guru dados tuladha siswa."],
            [1610, "Telapak", "Tlapak", "Tlapak", "Anggota Tubuh", "Telapak tangan bersih.", "Tlapak tangan resik.", "Tlapak asta resik."],
            [1611, "Telepon", "Telpon", "Telepon", "Teknologi", "Ayah menerima telepon.", "Bapak nampa telpon.", "Rama nampi telepon."],
            [1612, "Televisi", "Televisi", "Televisi", "Elektronik", "Kami menonton televisi bersama.", "Kita nonton televisi bareng.", "Kula mirsani televisi sesarengan."],
            [1613, "Telinga", "Kuping", "Talinga", "Anggota Tubuh", "Telinga harus dijaga kebersihannya.", "Kuping kudu dijaga resik.", "Talinga kedah dipunjagi resikipun."],
            [1614, "Teliti", "Teliti", "Teliti", "Kata Sifat", "Siswa harus teliti mengerjakan soal.", "Murid kudu teliti nggarap soal.", "Siswa kedah teliti nggarap soal."],
            [1615, "Telor", "Endhog", "Tigan", "Makanan", "Adik makan telur rebus.", "Adhik mangan endhog godhog.", "Adhi dhahar tigan godhog."],
            [1616, "Teluk", "Teluk", "Teluk", "Geografi", "Kapal berlabuh di teluk.", "Kapal mandheg ing teluk.", "Kapal kendel wonten teluk."],
            [1617, "Teman", "Kanca", "Rencang", "Keluarga", "Teman saya baik hati.", "Kancaku apikan.", "Rencang kula sae manah."],
            [1620, "Tempat", "Panggonan", "Papan", "Kata Benda", "Buku diletakkan pada tempatnya.", "Buku diseleh ing panggonane.", "Buku dipunpasang wonten papanipun."],
            [1621, "Tempat duduk", "Panggonan lungguh", "Papan lenggah", "Perabot", "Semua tempat duduk sudah penuh.", "Kabeh panggonan lungguh wis kebak.", "Sedaya papan lenggah sampun kebak."],
            [1622, "Tempat tidur", "Amben", "Paturon", "Perabot Rumah", "Adik merapikan tempat tidur.", "Adhik ngrapekake amben.", "Adhi ngresiki paturon."],
            [1623, "Tempayan", "Genthong", "Genthong", "Peralatan Rumah", "Air disimpan di tempayan.", "Banyu disimpen ing genthong.", "Toya dipunsimpen wonten genthong."],
            [1624, "Tempel", "Nempel", "Nempel", "Kata Kerja", "Adik menempel gambar.", "Adhik nempel gambar.", "Adhi nempel gambar."],
            [1625, "Tempurung", "Batok", "Batok", "Tumbuhan", "Tempurung kelapa sangat keras.", "Batok klapa atos.", "Batok klapa atos."],
            [1626, "Tenaga", "Tenaga", "Tenaga", "Kata Benda", "Ayah masih memiliki tenaga.", "Bapak isih nduweni tenaga.", "Rama taksih gadhah tenaga."],
            [1627, "Tenang", "Anteng", "Tentrem", "Kata Sifat", "Suasana kelas sangat tenang.", "Kahanan kelas anteng.", "Kawontenan kelas tentrem."],
            [1628, "Tenda", "Kemah/Tenda", "Tenda", "Peralatan", "Kami mendirikan tenda.", "Kita ngedegake tenda.", "Kula ngedegaken tenda."],
            [1629, "Tendang", "Nyepak", "Nyepak", "Kata Kerja", "Anak menendang bola.", "Bocah nyepak bal.", "Putra nyepak bal."],
            [1630, "Tenggelam", "Kelem", "Kelem", "Kata Kerja", "Matahari mulai tenggelam.", "Srengenge wiwit kelem.", "Surya wiwit kelem."],
            [1631, "Tenggorokan", "Tenggorokan", "Tenggorokan", "Anggota Tubuh", "Tenggorokan saya sakit.", "Tenggorokanku lara.", "Tenggorokan kula gerah."],
            [1632, "Tengik", "Apek", "Apek", "Kata Sifat", "Minyak itu tengik.", "Lenga kuwi apek.", "Lenga punika apek."],
            [1633, "Tengok", "Ndelok", "Ningali", "Kata Kerja", "Ayah menengok tetangga.", "Bapak ndelok tangga.", "Rama ningali tanggi."],
            [1634, "Tenis", "Tenis", "Tenis", "Olahraga", "Mereka bermain tenis.", "Dheweke dolanan tenis.", "Piyambakipun dolanan tenis."],
            [1635, "Tentu", "T mesthi", "Temtu", "Kata Keterangan", "Hasilnya tentu baik.", "Asile mesthi apik.", "Asilipun temtu sae."],
            [1636, "Tepat", "Pas", "Leres", "Kata Sifat", "Jawabanmu tepat.", "Jawabanmu pas.", "Wangsulan panjenengan leres."],
            [1637, "Tepi", "Pinggir", "Sisih", "Letak", "Rumahnya di tepi sungai.", "Omahe ana pinggir kali.", "Griyanipun wonten sisih kali."],
            [1638, "Tepuk", "Tepuk", "Tepuk", "Kata Kerja", "Siswa bertepuk tangan.", "Murid tepuk tangan.", "Siswa tepuk asta."],
            [1639, "Terang", "Padhang", "Padhang", "Kata Sifat", "Lampu itu sangat terang.", "Lampu kuwi padhang.", "Lampu punika padhang."],
            [1640, "Terbang", "Mabur", "Mabur", "Kata Kerja", "Burung terbang tinggi.", "Manuk mabur dhuwur.", "Manuk mabur inggil."],
            [1641, "Terbit", "Methuk", "Methuk", "Kata Kerja", "Matahari terbit pagi.", "Srengenge methuk esuk.", "Surya methuk enjing."],
            [1642, "Terbuka", "Mbukak", "Kabikak", "Kata Sifat", "Pintu sudah terbuka.", "Lawang wis mbukak.", "Lawang sampun kabikak."],
            [1643, "Tercemar", "Kecemar", "Kacemar", "Lingkungan", "Air sungai tercemar.", "Banyu kali kecemar.", "Toya kali kacemar."],
            [1644, "Terdengar", "Krungu", "Kapireng", "Kata Kerja", "Suaranya terdengar jelas.", "Swarane krungu cetha.", "Swantenipun kapireng cetha."],
            [1645, "Terik", "Sumuk", "Sumuk", "Cuaca", "Matahari sangat terik.", "Srengenge sumuk.", "Surya sumuk."],
            [1646, "Terima", "Nampa", "Nampi", "Kata Kerja", "Saya menerima hadiah.", "Aku nampa hadiah.", "Kula nampi bebungah."],
            [1647, "Terima kasih", "Matur nuwun", "Matur nuwun", "Ungkapan", "Terima kasih atas bantuanmu.", "Matur nuwun tulungmu.", "Matur nuwun pitulungan panjenengan."],
            [1648, "Terlambat", "Kasep", "Kasep", "Kata Sifat", "Adik datang terlambat.", "Adhik teka kasep.", "Adhi rawuh kasep."],
            [1649, "Terlalu", "Kakehan", "Kakehan", "Kata Keterangan", "Jangan terlalu banyak makan.", "Aja kakehan mangan.", "Sampun kakehan dhahar."],
            [1650, "Terluka", "Tatu", "Tatu", "Kesehatan", "Tangannya terluka ringan.", "Tangane tatu entheng.", "Astanipun tatu entheng."],
            [1651, "Ternak", "Ternak", "Ternak", "Peternakan", "Ayah memelihara ternak.", "Bapak ngingu ternak.", "Rama ngingu ternak."],
            [1652, "Ternyata", "Jebul", "Jebul", "Kata Keterangan", "Ternyata jawabannya benar.", "Jebul wangsulane bener.", "Jebul wangsulanipun leres."],
            [1653, "Tersenyum", "Mesem", "Mesem", "Kata Kerja", "Nenek tersenyum bahagia.", "Mbah mesem bungah.", "Eyang mesem bingah."],
            [1654, "Tersesat", "Kesasar", "Kesasar", "Kata Kerja", "Anak itu tersesat di hutan.", "Bocah kuwi kesasar ing alas.", "Putra punika kesasar wonten wana."],
            [1655, "Tertawa", "Guyu", "Gujeng", "Kata Kerja", "Mereka tertawa bersama.", "Dheweke guyu bareng.", "Piyambakipun gujeng sesarengan."],
            [1656, "Tertib", "Tertib", "Tertib", "Kata Sifat", "Siswa harus tertib.", "Murid kudu tertib.", "Siswa kedah tertib."],
            [1657, "Tertidur", "Keturon", "Keturon", "Kata Kerja", "Adik tertidur di sofa.", "Adhik keturon ing kursi.", "Adhi keturon wonten kursi."],
            [1658, "Terus", "Terus", "Terus", "Kata Keterangan", "Terus belajar setiap hari.", "Terus sinau saben dina.", "Terus sinau saben dinten."],
            [1659, "Tes", "Tes", "Tes", "Pendidikan", "Guru memberikan tes.", "Guru menehi tes.", "Guru maringi tes."],
            [1660, "Tewas", "Mati", "Seda", "Kata Kerja", "Hewan itu tewas.", "Kewan kuwi mati.", "Sato punika seda."],
            [1661, "Tiang", "Tiang", "Tiang", "Bangunan", "Tiang rumah terbuat dari kayu.", "Tiang omah digawe saka kayu.", "Tiang griya kadamel saking kajeng."],
            [1662, "Tiba", "Tiba", "Dumugi", "Kata Kerja", "Pesawat tiba tepat waktu.", "Pesawat tiba pas wektu.", "Pesawat dumugi leres wekdal."],
            [1663, "Tidur", "Turu", "Tilem", "Kata Kerja", "Adik tidur siang.", "Adhik turu awan.", "Adhi tilem siyang."],
            [1664, "Tiga", "Telu", "Tiga", "Kata Bilangan", "Saya memiliki tiga buku.", "Aku duwe telu buku.", "Kula gadhah tiga buku."],
            [1665, "Tikar", "Tikar", "Tikar", "Peralatan Rumah", "Kami duduk di atas tikar.", "Kita lungguh ing tikar.", "Kula lenggah wonten tikar."],
            [1666, "Tikus", "Tikus", "Tikus", "Hewan", "Tikus mencari makanan.", "Tikus golek panganan.", "Tikus pados dhaharan."],
            [1667, "Tilang", "Tilang", "Tilang", "Transportasi", "Polisi memberi tilang.", "Polisi menehi tilang.", "Polisi maringi tilang."],
            [1668, "Tim", "Tim", "Tim", "Olahraga", "Tim kami memenangkan lomba.", "Timku menang lomba.", "Tim kula menang lomba."],
            [1669, "Timba", "Timba", "Timba", "Peralatan", "Ayah mengambil air dengan timba.", "Bapak njupuk banyu nganggo timba.", "Rama mundhut toya ngagem timba."],
            [1670, "Timbang", "Nimbang", "Nimbang", "Kata Kerja", "Ibu menimbang buah.", "Ibu nimbang woh.", "Ibu nimbang woh."],
            [1671, "Timbangan", "Timbangan", "Timbangan", "Peralatan", "Timbangan itu sangat akurat.", "Timbangan kuwi pas.", "Timbangan punika leres."],
            [1672, "Timbul", "Muncul", "Muncul", "Kata Kerja", "Masalah baru mulai timbul.", "Masalah anyar wiwit muncul.", "Masalah enggal wiwit muncul."],
            [1673, "Timur", "Wetan", "Wetan", "Arah", "Matahari terbit di timur.", "Srengenge methuk ing wetan.", "Surya methuk wonten wetan."],
            [1674, "Tindak", "Lunga", "Tindak", "Kata Kerja", "Ayah pergi ke kantor.", "Bapak lunga kantor.", "Rama tindak kantor."],
            [1675, "Tinggi", "Dhuwur", "Inggil", "Kata Sifat", "Gunung itu sangat tinggi.", "Gunung kuwi dhuwur.", "Redi punika inggil."],
            [1676, "Tinggal", "Manggon", "Manggèn", "Kata Kerja", "Kami tinggal di Surabaya.", "Kita manggon ing Surabaya.", "Kula manggèn wonten Surabaya."],
            [1677, "Tingkap", "Jendhela", "Jendhela", "Rumah", "Tingkap kamar terbuka.", "Jendhela kamar mbukak.", "Jendhela kamar kabikak."],
            [1678, "Tiongkok", "Tiongkok", "Tiongkok", "Negara", "Tiongkok berada di Asia.", "Tiongkok ana ing Asia.", "Tiongkok wonten Asia."],
            [1679, "Tiup", "Niup", "Niup", "Kata Kerja", "Angin meniup daun.", "Angin niup godhong.", "Angin niup ron."],
            [1680, "Tiwul", "Tiwul", "Tiwul", "Makanan", "Nenek memasak tiwul.", "Mbah masak tiwul.", "Eyang masak tiwul."],
            [1681, "Toa", "Pengeras suara", "Pengeras swanten", "Elektronik", "Toa masjid berbunyi keras.", "Pengeras swara masjid muni banter.", "Pengeras swanten masjid muni seru."],
            [1682, "Toilet", "Jamban", "Jamban", "Tempat", "Toilet sekolah sangat bersih.", "Jamban sekolah resik.", "Jamban sekolah resik."],
            [1683, "Tolak", "Nolak", "Nampik", "Kata Kerja", "Dia menolak ajakan itu.", "Dheweke nolak ajakan kuwi.", "Piyambakipun nampik ajakan punika."],
            [1684, "Tolong", "Tulung", "Tulung", "Ungkapan", "Tolong ambilkan buku itu.", "Tulung jupukna buku kuwi.", "Tulung pendhetaken buku punika."],
            [1685, "Tomat", "Tomat", "Tomat", "Buah", "Ibu membeli tomat segar.", "Ibu tuku tomat seger.", "Ibu mundhut tomat seger."],
            [1686, "Tombak", "Tombak", "Tombak", "Senjata", "Tombak itu disimpan rapi.", "Tombak kuwi disimpen rapi.", "Tombak punika dipunsimpen rapi."],
            [1687, "Tombol", "Tombol", "Tombol", "Teknologi", "Tekan tombol hijau.", "Pencet tombol ijo.", "Pencet tombol ijem."],
            [1688, "Ton", "Ton", "Ton", "Satuan", "Muatan truk lima ton.", "Muatan truk limang ton.", "Muatan truk gangsal ton."],
            [1689, "Topi", "Kopiah/Topi", "Topi", "Pakaian", "Adik memakai topi merah.", "Adhik nganggo topi abang.", "Adhi ngagem topi abrit."],
            [1690, "Toren", "Tandon", "Tandon", "Peralatan", "Air disimpan dalam toren.", "Banyu disimpen ing tandon.", "Toya dipunsimpen wonten tandon."],
            [1691, "Tos", "Tos", "Tos", "Ungkapan", "Mereka saling tos setelah menang.", "Dheweke tos sawise menang.", "Piyambakipun tos sasampunipun menang."],
            [1692, "Total", "Total", "Total", "Kata Benda", "Total nilainya seratus.", "Total nilaine satus.", "Total bijinipun satunggal atus."],
            [1693, "Tradisi", "Tradhisi", "Tradhisi", "Budaya", "Tradisi Jawa masih dijaga.", "Tradhisi Jawa isih dijaga.", "Tradhisi Jawi taksih dipunjagi."],
            [1694, "Traktor", "Traktor", "Traktor", "Pertanian", "Petani memakai traktor.", "Petani nganggo traktor.", "Petani ngagem traktor."],
            [1695, "Trampil", "Trampil", "Trampil", "Kata Sifat", "Kakak sangat trampil memasak.", "Mbakyu trampil masak.", "Mbakayu trampil masak."],
            [1696, "Transfer", "Transfer", "Transfer", "Teknologi", "Ayah melakukan transfer uang.", "Bapak transfer dhuwit.", "Rama transfer arta."],
            [1697, "Transparan", "Tembus pandang", "Transparan", "Kata Sifat", "Kaca itu transparan.", "Kaca kuwi tembus pandang.", "Kaca punika transparan."],
            [1698, "Transportasi", "Transportasi", "Transportasi", "Transportasi", "Transportasi umum sangat membantu.", "Transportasi umum migunani.", "Transportasi umum migunani."],
            [1699, "Trap", "Trap", "Trap", "Bangunan", "Trap tangga licin.", "Trap undhakan lunyu.", "Trap undhakan lunyu."],
            [1700, "Truk", "Truk", "Truk", "Kendaraan", "Truk membawa pasir.", "Truk nggawa pasir.", "Truk ngasta pasir."],
            [1701, "Tua", "Tuwa", "Sepuh", "Kata Sifat", "Kakek sudah tua.", "Mbah wis tuwa.", "Eyang sampun sepuh."],
            [1702, "Tuang", "Nuang", "Nuang", "Kata Kerja", "Ibu menuang air ke gelas.", "Ibu nuang banyu menyang gelas.", "Ibu nuang toya dhateng gelas."],
            [1703, "Tubruk", "Nabrak", "Nabrak", "Kata Kerja", "Sepeda menubruk pagar.", "Pit nabrak pager.", "Sepeda nabrak pager."],
            [1704, "Tubuh", "Awak", "Sarira", "Anggota Tubuh", "Tubuh harus dijaga sehat.", "Awak kudu dijaga sehat.", "Sarira kedah dipunjagi sehat."],
            [1705, "Tudung", "Tudhung", "Tudhung", "Pakaian", "Ibu memakai tudung saji.", "Ibu nganggo tudhung saji.", "Ibu ngagem tudhung saji."],
            [1706, "Tudung saji", "Tudhung saji", "Tudhung saji", "Peralatan Rumah", "Tudung saji menutup makanan.", "Tudhung saji nutupi panganan.", "Tudhung saji nutupi dhaharan."],
            [1707, "Tugas", "Tugas", "Tugas", "Pendidikan", "Saya mengerjakan tugas sekolah.", "Aku nggarap tugas sekolah.", "Kula nggarap tugas sekolah."],
            [1708, "Tugu", "Tugu", "Tugu", "Bangunan", "Tugu itu sangat tinggi.", "Tugu kuwi dhuwur.", "Tugu punika inggil."],
            [1709, "Tujuan", "Tujuan", "Tujuan", "Kata Benda", "Kami memiliki tujuan yang baik.", "Kita nduweni tujuan apik.", "Kula gadhah tujuan sae."],
            [1710, "Tujuh", "Pitu", "Pitu", "Kata Bilangan", "Adik mempunyai tujuh pensil.", "Adhik duwe pitu potlot.", "Adhi gadhah pitu potlot."],
            [1711, "Tukar", "Ngijol", "Ngijol", "Kata Kerja", "Mereka menukar buku.", "Dheweke ngijol buku.", "Piyambakipun ngijol buku."],
            [1712, "Tulang", "Balung", "Balung", "Anggota Tubuh", "Tulang ayam sangat keras.", "Balung pitik atos.", "Balung pitik atos."],
            [1713, "Tulis", "Nulis", "Nyerat", "Kata Kerja", "Adik menulis surat.", "Adhik nulis layang.", "Adhi nyerat layang."],
            [1714, "Tulisan", "Tulisan", "Tulisan", "Bahasa", "Tulisan itu sangat rapi.", "Tulisan kuwi rapi.", "Tulisan punika rapi."],
            [1715, "Tulus", "Tulus", "Tulus", "Kata Sifat", "Ia membantu dengan tulus.", "Dheweke nulungi kanthi tulus.", "Piyambakipun mitulungi kanthi tulus."],
            [1716, "Tumbuh", "Thukul", "Tuwuh", "Kata Kerja", "Bunga tumbuh subur.", "Kembang thukul subur.", "Sekar tuwuh subur."],
            [1717, "Tumpah", "Mblesek/Tumpah", "Tumpah", "Kata Kerja", "Air minum tumpah.", "Banyu ngombe tumpah.", "Toya ngunjuk tumpah."],
            [1718, "Tumpuk", "Numpuk", "Numpuk", "Kata Kerja", "Buku ditumpuk rapi.", "Buku ditumpuk rapi.", "Buku dipuntumpuk rapi."],
            [1719, "Tunas", "Tunas", "Tunas", "Tumbuhan", "Tunas baru mulai tumbuh.", "Tunas anyar wiwit thukul.", "Tunas enggal wiwit tuwuh."],
            [1720, "Tunda", "Nunda", "Nunda", "Kata Kerja", "Jangan menunda pekerjaan.", "Aja nunda gawean.", "Sampun nunda pedamelan."],
            [1721, "Tungau", "Tungau", "Tungau", "Hewan", "Tungau sangat kecil.", "Tungau cilik banget.", "Tungau alit sanget."],
            [1722, "Tunggu", "Ngenteni", "Ngentosi", "Kata Kerja", "Tunggu ayah pulang.", "Ngenteni bapak mulih.", "Ngentosi rama kondur."],
            [1723, "Tungku", "Pawon/Pawon geni", "Pawon geni", "Dapur", "Ibu memasak dengan tungku.", "Ibu masak nganggo pawon geni.", "Ibu masak ngagem pawon geni."],
            [1724, "Tunjuk", "Nuding", "Nuding/Kawedhar", "Kata Kerja", "Guru menunjuk siswa.", "Guru nuding murid.", "Guru nuding siswa."],
            [1725, "Tupai", "Bajing", "Bajing", "Hewan", "Tupai memanjat pohon.", "Bajing menek wit.", "Bajing minggah uwit."],
            [1726, "Turun", "Mudhun", "Mandhap", "Kata Kerja", "Adik turun tangga.", "Adhik mudhun undhakan.", "Adhi mandhap undhakan."],
            [1727, "Turut", "Melu", "Ndherek", "Kata Kerja", "Adik turut bermain.", "Adhik melu dolanan.", "Adhi ndherek dolanan."],
            [1728, "Tutup", "Nutup", "Nyekapi/Katutup", "Kata Kerja", "Tolong tutup pintu.", "Tulung nutup lawang.", "Tulung tutupaken lawang."],
            [1729, "Tutur", "Tutur", "Tutur", "Bahasa", "Tutur kata harus sopan.", "Tutur kudu sopan.", "Tutur kedah sopan."],
            [1730, "TV", "TV/Televisi", "Televisi", "Elektronik", "Kami menonton TV bersama.", "Kita nonton TV bareng.", "Kula mirsani televisi sesarengan."],
            [1731, "Uang", "Dhuwit", "Arta", "Ekonomi", "Ayah menyimpan uang.", "Bapak nyimpen dhuwit.", "Rama nyimpen arta."],
            [1732, "Uap", "Uap", "Uap", "Sains", "Uap air terlihat jelas.", "Uap banyu katon cetha.", "Uap toya katingal cetha."],
            [1733, "Uban", "Uban", "Uban", "Anggota Tubuh", "Rambut kakek mulai ubanan.", "Rambute mbah wiwit ubanan.", "Rikmanipun eyang wiwit ubanan."],
            [1734, "Ubi jalar", "Tela", "Tela", "Makanan", "Ibu merebus ubi jalar.", "Ibu nggodhog tela.", "Ibu nggodhog tela."],
            [1735, "Ubi kayu", "Tela pohung", "Tela pohung", "Makanan", "Petani memanen ubi kayu.", "Petani manen tela pohung.", "Petani panen tela pohung."],
            [1736, "Udang", "Urang", "Urang", "Hewan", "Ibu memasak udang goreng.", "Ibu masak urang goreng.", "Ibu masak urang goreng."],
            [1737, "Udang rebon", "Rebon", "Rebon", "Hewan", "Rebon dibuat menjadi terasi.", "Rebon digawe trasi.", "Rebon dipundamel trasi."],
            [1738, "Udara", "Hawa", "Hawa", "Alam", "Udara pagi sangat segar.", "Hawa esuk seger.", "Hawa enjing seger."],
            [1739, "Udang windu", "Urang windu", "Urang windu", "Hewan", "Udang windu hidup di tambak.", "Urang windu urip ing tambak.", "Urang windu gesang wonten tambak."],
            [1740, "Udik", "Ndesa", "Ndesa", "Kata Sifat", "Daerah itu masih udik.", "Daerah kuwi isih ndesa.", "Tlatah punika taksih ndesa."],
        ];

        foreach ($dataset as $row) {
            $vocab = Vocabulary::updateOrCreate(
                ['id' => $row[0]],
                [
                    'indonesian_word' => $row[1],
                    'javanese_ngoko'  => $row[2],
                    'javanese_krama'  => $row[3],
                    'category'        => $row[4] ?? null,
                ]
            );

            if (!empty($row[5]) || !empty($row[6]) || !empty($row[7])) {
                VocabularyExample::updateOrCreate(
                    ['vocabulary_id' => $vocab->id],
                    [
                        'indonesian_sentence' => $row[5] ?? null,
                        'ngoko_sentence'      => $row[6] ?? null,
                        'krama_sentence'      => $row[7] ?? null,
                        'javanese_sentence'   => $row[6] ?? $row[7] ?? null,
                    ]
                );
            }
        }
    }
}
