<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatchSeeder821To1300 extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            [821, "Laki-laki", "Lanang", "Kakung", "Keluarga", "Anak laki-laki itu rajin.", "Bocah lanang kuwi sregep.", "Putra kakung punika sregep."],
            [822, "Laku", "Laku", "Lampah", "Kata Kerja", "Perbuatannya menjadi teladan.", "Lakune dadi tuladha.", "Lampahipun dados tuladha."],
            [823, "Lalang", "Alang-alang", "Alang-alang", "Tumbuhan", "Lalang tumbuh di sawah.", "Alang-alang thukul ing sawah.", "Alang-alang tuwuh wonten sabin."],
            [824, "Lama", "Suwe", "Dangu", "Kata Sifat", "Kami menunggu lama.", "Kita ngenteni suwe.", "Kula ngentosi dangu."],
            [825, "Lampion", "Lampion", "Lampion", "Hiasan", "Lampion merah digantung.", "Lampion abang digantung.", "Lampion abrit dipungantung."],
            [826, "Lampu", "Lampu", "Lampu", "Peralatan Rumah", "Lampu kamar menyala.", "Lampu kamar urip.", "Lampu kamar murub."],
            [827, "Lampu lalu lintas", "Lampu lalu lintas", "Lampu lalu lintas", "Transportasi", "Kendaraan berhenti di lampu lalu lintas.", "Kendaraan mandheg ing lampu lalu lintas.", "Kendaraan mandheg wonten lampu lalu lintas."],
            [828, "Landak", "Landak", "Landak", "Hewan", "Landak memiliki duri tajam.", "Landak nduweni eri landhep.", "Landak gadhah eri landhep."],
            [829, "Langgar", "Langgar", "Langgar", "Agama", "Anak belajar mengaji di langgar.", "Bocah sinau ngaji ing langgar.", "Putra sinau ngaji wonten langgar."],
            [830, "Langit", "Langit", "Langit", "Alam", "Langit hari ini cerah.", "Langit dina iki padhang.", "Langit dinten punika padhang."],
            [831, "Langka", "Langka", "Langka", "Kata Sifat", "Hewan itu sangat langka.", "Kewan kuwi langka.", "Sato punika langka."],
            [832, "Langkah", "Langkah", "Lampah", "Kata Benda", "Langkah pertama sangat penting.", "Langkah pisanan penting.", "Lampah kapisan wigati."],
            [833, "Langsat", "Langsat", "Langsat", "Buah", "Buah langsat rasanya manis.", "Langsat rasane legi.", "Langsat raosipun manis."],
            [834, "Langsung", "Langsung", "Langsung", "Kata Keterangan", "Kami langsung pulang.", "Kita langsung mulih.", "Kula langsung kondur."],
            [835, "Lantai", "Lantai", "Lantai", "Rumah", "Lantai rumah bersih.", "Lantai omah resik.", "Lantai griya resik."],
            [836, "Lantai atas", "Lantai nduwur", "Lantai inggil", "Rumah", "Kamar berada di lantai atas.", "Kamar ana ing lantai nduwur.", "Kamar wonten lantai inggil."],
            [837, "Lapar", "Luwe", "Luwe", "Perasaan", "Adik merasa lapar.", "Adhik krasa luwe.", "Adhi kraos luwe."],
            [838, "Lapangan", "Lapangan", "Lapangan", "Tempat", "Siswa bermain di lapangan.", "Murid dolanan ing lapangan.", "Siswa dolanan wonten lapangan."],
            [839, "Lapor", "Lapor", "Lapor", "Kata Kerja", "Saya melapor kepada guru.", "Aku lapor marang guru.", "Kula lapor dhateng guru."],
            [840, "Laporan", "Laporan", "Laporan", "Pendidikan", "Saya mengumpulkan laporan.", "Aku nglumpukake laporan.", "Kula nglumpukaken laporan."],
            [841, "Larang", "Larang", "Ngalang", "Kata Kerja", "Ibu melarang bermain malam.", "Ibu nglarang dolanan bengi.", "Ibu ngalang dolanan dalu."],
            [842, "Lari", "Mlayu", "Mlampah rikat", "Kata Kerja", "Anak itu lari cepat.", "Bocah kuwi mlayu banter.", "Putra punika mlampah rikat."],
            [843, "Larut", "Larut", "Larut", "Kata Sifat", "Gula larut dalam air.", "Gula larut ing banyu.", "Gendhis larut wonten toya."],
            [844, "Laut", "Segara", "Seganten", "Alam", "Laut terlihat biru.", "Segara katon biru.", "Seganten katingal biru."],
            [845, "Lawak", "Lawak", "Lawak", "Tumbuhan", "Lawak digunakan sebagai obat.", "Lawak dienggo obat.", "Lawak dipunginakaken obat."],
            [846, "Lawang", "Lawang", "Lawang", "Rumah", "Lawang rumah tertutup.", "Lawang omah ketutup.", "Lawang griya katutup."],
            [847, "Layar", "Layar", "Layar", "Teknologi", "Layar komputer sangat terang.", "Layar komputer padhang.", "Layar komputer padhang."],
            [848, "Lebah", "Tawon", "Tawon", "Hewan", "Lebah membuat madu.", "Tawon nggawe madu.", "Tawon damel madu."],
            [849, "Lebar", "Amba", "Amba", "Kata Sifat", "Jalan itu lebar.", "Dalan kuwi amba.", "Margi punika amba."],
            [850, "Lebih", "Luwih", "Langkung", "Kata Keterangan", "Adik lebih tinggi sekarang.", "Adhik luwih dhuwur saiki.", "Adhi langkung inggil sapunika."],
            [851, "Leci", "Leci", "Leci", "Buah", "Ibu membeli buah leci.", "Ibu tuku woh leci.", "Ibu mundhut woh leci."],
            [852, "Ledakan", "Jeblugan", "Jeblugan", "Kata Benda", "Ledakan terdengar keras.", "Jeblugan keprungu banter.", "Jeblugan kapireng seru."],
            [853, "Lega", "Lega", "Lega", "Perasaan", "Saya merasa lega.", "Aku krasa lega.", "Kula kraos lega."],
            [854, "Leher", "Gulu", "Gulu", "Anggota Tubuh", "Leher jerapah panjang.", "Gulu jerapah dawa.", "Gulu jerapah dawa."],
            [855, "Lejit", "Melesat", "Melesat", "Kata Kerja", "Roket melesat ke langit.", "Roket melesat menyang langit.", "Roket melesat dhateng langit."],
            [856, "Lekas", "Cepet", "Enggal", "Kata Keterangan", "Lekas pulang ke rumah.", "Cepet mulih.", "Enggal kondur."],
            [857, "Lelah", "Kesel", "Kesel", "Perasaan", "Ayah terlihat lelah.", "Bapak katon kesel.", "Rama katingal kesel."],
            [858, "Lelaki", "Lanang", "Kakung", "Keluarga", "Lelaki itu sopan.", "Lanang kuwi sopan.", "Kakung punika sopan."],
            [859, "Lele", "Iwak lele", "Iwak lele", "Hewan", "Lele hidup di kolam.", "Iwak lele urip ing blumbang.", "Iwak lele gesang wonten blumbang."],
            [860, "Lem", "Lem", "Lem", "Peralatan", "Adik memakai lem kertas.", "Adhik nganggo lem kertas.", "Adhi ngagem lem kertas."],
            [861, "Lemari", "Lemari", "Lemari", "Peralatan Rumah", "Buku disimpan di lemari.", "Buku disimpen ing lemari.", "Buku dipunsimpen wonten lemari."],
            [862, "Lembah", "Lembah", "Lembah", "Alam", "Lembah itu sangat indah.", "Lembah kuwi apik.", "Lembah punika sae."],
            [863, "Lembap", "Legembab", "Legembab", "Kata Sifat", "Udara pagi terasa lembap.", "Udhara esuk legembab.", "Udhara enjing legembab."],
            [864, "Lembaran", "Lembaran", "Lembaran", "Benda", "Saya mengambil selembar kertas.", "Aku njupuk saklembar kertas.", "Kula mundhut satunggal lembar kertas."],
            [865, "Lembut", "Alus", "Alus", "Kata Sifat", "Bantal itu lembut.", "Bantal kuwi alus.", "Bantal punika alus."],
            [866, "Lemon", "Lemon", "Lemon", "Buah", "Air lemon terasa segar.", "Banyu lemon seger.", "Toya lemon seger."],
            [867, "Lempar", "Mbalang", "Mbalang", "Kata Kerja", "Anak melempar bola.", "Bocah mbalang bal.", "Putra mbalang bal."],
            [868, "Lengang", "Sepi", "Sepi", "Kata Sifat", "Jalan pagi masih lengang.", "Dalan esuk isih sepi.", "Margi enjing taksih sepi."],
            [869, "Lengan", "Lengen", "Lengen", "Anggota Tubuh", "Lengan ayah kuat.", "Lengene bapak kuwat.", "Lengenipun rama kiyat."],
            [870, "Lengkap", "Jangkep", "Jangkep", "Kata Sifat", "Peralatan belajar sudah lengkap.", "Piranti sinau wis jangkep.", "Piranti sinau sampun jangkep."],
            [871, "Lengkuas", "Laos", "Laos", "Tumbuhan", "Ibu memakai lengkuas untuk memasak.", "Ibu nganggo laos kanggo masak.", "Ibu ngagem laos kangge masak."],
            [872, "Lensa", "Lensa", "Lensa", "Teknologi", "Kamera itu memakai lensa baru.", "Kamera kuwi nganggo lensa anyar.", "Kamera punika ngagem lensa enggal."],
            [873, "Lentera", "Lentera", "Lentera", "Peralatan", "Lentera itu menyala terang.", "Lentera kuwi murub padhang.", "Lentera punika murub padhang."],
            [874, "Lentur", "Luwes", "Luwes", "Kata Sifat", "Bambu sangat lentur.", "Pring kuwi luwes.", "Pring punika luwes."],
            [875, "Leopard", "Macan tutul", "Macan tutul", "Hewan", "Leopard berlari cepat.", "Macan tutul mlayu banter.", "Macan tutul mlayu rikat."],
            [876, "Lepas", "Uwal", "Uwal", "Kata Kerja", "Burung lepas dari sangkar.", "Manuk uwal saka kurungan.", "Manuk uwal saking kurungan."],
            [877, "Lepat", "Kupat lepat", "Kupat lepat", "Makanan", "Nenek membuat lepat.", "Mbah nggawe kupat lepat.", "Eyang damel kupat lepat."],
            [878, "Leri", "Banyu leri", "Toya leri", "Rumah", "Ibu memakai air leri.", "Ibu nganggo banyu leri.", "Ibu ngagem toya leri."],
            [879, "Lereng", "Lereng", "Lereng", "Alam", "Rumah itu di lereng gunung.", "Omah kuwi ana lereng gunung.", "Griya punika wonten lereng redi."],
            [880, "Les", "Les", "Les", "Pendidikan", "Adik mengikuti les matematika.", "Adhik melu les matematika.", "Adhi ndherek les matematika."],
            [881, "Lesung", "Lesung", "Lesung", "Peralatan", "Lesung dipakai menumbuk padi.", "Lesung dienggo numbuk pari.", "Lesung dipunginakaken numbuk pari."],
            [882, "Letak", "Panggonan", "Papan", "Kata Benda", "Letak sekolah sangat strategis.", "Panggonan sekolah strategis.", "Papan sekolah strategis."],
            [883, "Letih", "Kesel", "Kesel", "Perasaan", "Setelah bekerja ayah letih.", "Sawise nyambut gawe bapak kesel.", "Sasampunipun nyambut damel rama kesel."],
            [884, "Letus", "Njeblug", "Njeblug", "Kata Kerja", "Gunung itu meletus.", "Gunung kuwi njeblug.", "Redi punika njeblug."],
            [885, "Lezat", "Enaak", "Sedhep", "Makanan", "Masakan ibu sangat lezat.", "Masakane ibu enak.", "Masakan ibu sedhep."],
            [886, "Libur", "Prei", "Prei", "Waktu", "Besok hari libur.", "Sesuk prei.", "Mbenjang prei."],
            [887, "Licin", "Lisut", "Lisut", "Kata Sifat", "Jalan menjadi licin saat hujan.", "Dalan dadi lisut wektu udan.", "Margi dados lisut nalika udan."],
            [888, "Lidah", "Ilat", "Ilat", "Anggota Tubuh", "Lidah terasa pahit.", "Ilat krasa pait.", "Ilat kraos pait."],
            [889, "Lilin", "Lilin", "Lilin", "Peralatan", "Lilin menyala saat mati listrik.", "Lilin murub nalika listrik mati.", "Lilin murub nalika listrik pejah."],
            [890, "Lima", "Lima", "Gangsal", "Kata Bilangan", "Saya mempunyai lima pensil.", "Aku duwe lima potlot.", "Kula gadhah gangsal potlot."],
            [891, "Limbah", "Limbah", "Limbah", "Lingkungan", "Limbah harus diolah dahulu.", "Limbah kudu diolah dhisik.", "Limbah kedah dipunolah rumiyin."],
            [892, "Lincah", "Lincah", "Lincah", "Kata Sifat", "Anak itu sangat lincah.", "Bocah kuwi lincah.", "Putra punika lincah."],
            [893, "Lindung", "Nglindhungi", "Nglindhungi", "Kata Kerja", "Pohon melindungi rumah.", "Wit nglindhungi omah.", "Uwit nglindhungi griya."],
            [894, "Lingkar", "Bunder", "Bunder", "Bentuk", "Bola berbentuk lingkar.", "Bal wujude bunder.", "Bal wujudipun bunder."],
            [895, "Lingkungan", "Lingkungan", "Lingkungan", "Lingkungan", "Kita menjaga lingkungan bersih.", "Kita njaga lingkungan resik.", "Kita njagi lingkungan resik."],
            [896, "Lintah", "Lintah", "Lintah", "Hewan", "Lintah hidup di sawah.", "Lintah urip ing sawah.", "Lintah gesang wonten sabin."],
            [897, "Liontin", "Liontin", "Liontin", "Aksesori", "Ibu memakai liontin emas.", "Ibu nganggo liontin emas.", "Ibu ngagem liontin emas."],
            [898, "Lipat", "Melu", "Nglipet", "Kata Kerja", "Adik melipat baju.", "Adhik nglipet klambi.", "Adhi nglipet klambi."],
            [899, "Listrik", "Listrik", "Listrik", "Teknologi", "Rumah kami memakai listrik.", "Omahku nganggo listrik.", "Griya kula ngagem listrik."],
            [900, "Lobak", "Lobak", "Lobak", "Sayuran", "Ibu memasak lobak.", "Ibu masak lobak.", "Ibu masak lobak."],
            [901, "Lobi", "Lobi", "Lobi", "Bangunan", "Kami menunggu di lobi.", "Kita ngenteni ing lobi.", "Kula ngentosi wonten lobi."],
            [902, "Loceng", "Lonceng", "Lonceng", "Peralatan", "Sekolah membunyikan lonceng.", "Sekolah muni lonceng.", "Sekolah munyèkaken lonceng."],
            [903, "Lompat", "Mlumpat", "Mlumpat", "Kata Kerja", "Anak itu lompat tinggi.", "Bocah kuwi mlumpat dhuwur.", "Putra punika mlumpat inggil."],
            [904, "Lontar", "Lontar", "Lontar", "Tumbuhan", "Daun lontar dipakai menulis.", "Godhong lontar dienggo nulis.", "Godhong lontar dipunginakaken nyerat."],
            [905, "Lontong", "Lontong", "Lontong", "Makanan", "Ibu memasak lontong.", "Ibu masak lontong.", "Ibu masak lontong."],
            [906, "Lor", "Lor", "Lor", "Arah", "Rumah kami di utara desa.", "Omahku ana sisih lor desa.", "Griya kula wonten sisih lor desa."],
            [907, "Lori", "Lori", "Lori", "Transportasi", "Lori membawa hasil tambang.", "Lori nggawa asil tambang.", "Lori ngasta asil tambang."],
            [908, "Lotion", "Losion", "Losion", "Kesehatan", "Ibu memakai losion kulit.", "Ibu nganggo losion kulit.", "Ibu ngagem losion kulit."],
            [909, "Lubang", "Bolong", "Bolong", "Kata Benda", "Ada lubang di jalan.", "Ana bolong ing dalan.", "Wonten bolong wonten margi."],
            [910, "Lucu", "Lucu", "Lucu", "Kata Sifat", "Cerita itu lucu.", "Crita kuwi lucu.", "Cariyos punika lucu."],
            [911, "Ludah", "Idu", "Idu", "Anggota Tubuh", "Jangan membuang ludah sembarangan.", "Aja ngidu sembarangan.", "Sampun ngidu sembarangan."],
            [912, "Luka", "Tatu", "Tatu", "Kesehatan", "Luka itu sudah sembuh.", "Tatu kuwi wis mari.", "Tatu punika sampun waras."],
            [913, "Lukis", "Nggambar", "Nggambar", "Kata Kerja", "Adik melukis bunga.", "Adhik nggambar kembang.", "Adhi nggambar sekar."],
            [914, "Lukisan", "Gambar", "Gambar", "Seni", "Lukisan itu sangat indah.", "Gambar kuwi apik.", "Gambar punika sae."],
            [915, "Lulus", "Lulus", "Lulus", "Pendidikan", "Kakak lulus ujian.", "Mas lulus ujian.", "Raka lulus ujian."],
            [916, "Lumba-lumba", "Lumba-lumba", "Lumba-lumba", "Hewan", "Lumba-lumba berenang bersama.", "Lumba-lumba nglangi bareng.", "Lumba-lumba nglangi sesarengan."],
            [917, "Lumpur", "Lempung", "Lempung", "Alam", "Sepatu terkena lumpur.", "Sepatu kena lempung.", "Sepatu kenging lempung."],
            [918, "Lunak", "Empuk", "Empuk", "Kata Sifat", "Roti itu lunak.", "Roti kuwi empuk.", "Roti punika empuk."],
            [919, "Lupa", "Lali", "Lalimpur/Lali", "Kata Kerja", "Saya lupa membawa buku.", "Aku lali nggawa buku.", "Kula lali ngasta buku."],
            [920, "Lurah", "Lurah", "Lurah", "Profesi", "Lurah menemui warga.", "Lurah ketemu warga.", "Lurah kepanggih warga."],
            [921, "Lurus", "Lurus", "Lurus", "Kata Sifat", "Garis itu lurus.", "Garis kuwi lurus.", "Garis punika lurus."],
            [922, "Lutut", "Dhengkul", "Jengku", "Anggota Tubuh", "Lutut saya sakit.", "Dhengkulku lara.", "Jengku kula gerah."],
            [923, "Mabuk", "Mabuk", "Mabuk", "Kesehatan", "Penumpang mabuk perjalanan.", "Penumpang mabuk lelungan.", "Penumpang mabuk lelampahan."],
            [924, "Macam", "Werna", "Jinis", "Kata Benda", "Ada banyak macam buah.", "Ana akeh werna woh.", "Wonten kathah jinis woh."],
            [925, "Macan", "Macan", "Macan", "Hewan", "Macan hidup di hutan.", "Macan urip ing alas.", "Macan gesang wonten wana."],
            [926, "Macet", "Macet", "Macet", "Transportasi", "Jalan raya sedang macet.", "Dalan gedhe lagi macet.", "Margi ageng saweg macet."],
            [927, "Madu", "Madu", "Madu", "Makanan", "Lebah menghasilkan madu.", "Tawon ngasilake madu.", "Tawon ngasilaken madu."],
            [928, "Magang", "Magang", "Magang", "Pendidikan", "Kakak mengikuti magang.", "Mas melu magang.", "Raka ndherek magang."],
            [929, "Magrib", "Magrib", "Magrib", "Agama", "Kami salat Magrib bersama.", "Kita salat Magrib bareng.", "Kula salat Magrib sesarengan."],
            [930, "Mahasiswa", "Mahasiswa", "Mahasiswa", "Pendidikan", "Kakak seorang mahasiswa.", "Mas mahasiswa.", "Raka mahasiswa."],
            [931, "Mahkota", "Mahkota", "Mahkota", "Benda", "Raja memakai mahkota.", "Raja nganggo mahkota.", "Raja ngagem mahkota."],
            [932, "Mahir", "Minter", "Saged", "Kata Sifat", "Dia mahir membaca.", "Dheweke pinter maca.", "Piyambakipun saged maos."],
            [933, "Main", "Dolanan", "Dolanan", "Kata Kerja", "Anak-anak bermain bola.", "Bocah-bocah dolanan bal.", "Para putra dolanan bal."],
            [934, "Mainan", "Dolanan", "Dolanan", "Permainan", "Adik membeli mainan baru.", "Adhik tuku dolanan anyar.", "Adhi mundhut dolanan enggal."],
            [935, "Majalah", "Majalah", "Majalah", "Buku", "Ibu membaca majalah.", "Ibu maca majalah.", "Ibu maos majalah."],
            [936, "Maju", "Maju", "Maju", "Kata Kerja", "Siswa maju ke depan kelas.", "Murid maju menyang ngarep kelas.", "Siswa maju dhateng ngajeng kelas."],
            [937, "Makam", "Pasarean", "Pasarean", "Tempat", "Kami berziarah ke makam.", "Kita nyekar ing pasarean.", "Kula nyekar wonten pasarean."],
            [938, "Makamkan", "Ngubur", "Makemaken", "Kata Kerja", "Warga memakamkan jenazah.", "Warga ngubur jenazah.", "Warga makemaken jenazah."],
            [939, "Makan", "Mangan", "Dhahar/Nedha", "Kata Kerja", "Kami makan bersama.", "Kita mangan bareng.", "Kula dhahar sesarengan."],
            [940, "Makanan", "Panganan", "Dhaharan", "Makanan", "Ibu menyiapkan makanan.", "Ibu nyiapake panganan.", "Ibu nyawisaken dhaharan."],
            [941, "Makhluk", "Makhluk", "Makhluk", "Kata Benda", "Semua makhluk membutuhkan air.", "Kabeh makhluk butuh banyu.", "Sedaya makhluk mbetahaken toya."],
            [942, "Makna", "Teges", "Teges", "Kata Benda", "Guru menjelaskan makna kata.", "Guru nerangake teges tembung.", "Guru nerangaken teges tembung."],
            [943, "Makmur", "Makmur", "Makmur", "Kata Sifat", "Desa kami makmur.", "Desaku makmur.", "Desa kula makmur."],
            [944, "Malas", "Kesed", "Kesed", "Kata Sifat", "Jangan malas belajar.", "Aja kesed sinau.", "Sampun kesed sinau."],
            [945, "Malam", "Bengi", "Dalu", "Waktu", "Malam ini udaranya sejuk.", "Bengi iki hawane adem.", "Dalu punika hawanipun adem."],
            [946, "Malu", "Isin", "Lingsem", "Perasaan", "Adik malu bernyanyi.", "Adhik isin nembang.", "Adhi lingsem nembang."],
            [947, "Mambu", "Mambu", "Mambu", "Kata Sifat", "Sampah itu mambu.", "Sampah kuwi mambu.", "Sampah punika mambu."],
            [948, "Mampu", "Bisa", "Saged", "Kata Sifat", "Saya mampu mengerjakan tugas.", "Aku bisa nggarap tugas.", "Kula saged nggarap tugas."],
            [949, "Manasik", "Manasik", "Manasik", "Agama", "Mereka mengikuti manasik haji.", "Dheweke melu manasik haji.", "Piyambakipun ndherek manasik haji."],
            [950, "Mandi", "Adus", "Siram", "Kata Kerja", "Adik mandi pagi.", "Adhik adus esuk.", "Adhi siram enjing."],
            [951, "Mandor", "Mandor", "Mandor", "Profesi", "Mandor memeriksa pekerjaan.", "Mandor mriksa gawean.", "Mandor mriksa pedamelan."],
            [952, "Mangga", "Mangga", "Pelem", "Buah", "Saya makan mangga matang.", "Aku mangan pelem mateng.", "Kula dhahar pelem sampun mateng."],
            [953, "Mangkuk", "Mangkok", "Mangkok", "Peralatan Rumah", "Sup ada di mangkuk.", "Sop ana ing mangkok.", "Sop wonten mangkok."],
            [954, "Manis", "Legi/Enak", "Manis", "Kata Sifat", "Teh ini manis.", "Teh iki legi.", "Tèh punika manis."],
            [955, "Manusia", "Wong", "Tiyang", "Kata Benda", "Manusia harus saling membantu.", "Wong kudu padha tulung-tinulung.", "Tiyang kedah silih tulung."],
            [956, "Marah", "Nesu", "Duka", "Kata Kerja", "Ayah marah kepada adik.", "Bapak nesu karo adhik.", "Rama duka dhateng adhi."],
            [957, "Maret", "Maret", "Maret", "Waktu", "Sekolah mulai bulan Maret.", "Sekolah wiwit wulan Maret.", "Sekolah wiwit wulan Maret."],
            [958, "Marmer", "Marmer", "Marmer", "Benda", "Lantai rumah dari marmer.", "Lantai omah saka marmer.", "Lantai griya saking marmer."],
            [959, "Masak", "Masak", "Masak", "Kata Kerja", "Ibu sedang memasak.", "Ibu lagi masak.", "Ibu saweg masak."],
            [960, "Masakan", "Masakan", "Dhaharan", "Makanan", "Masakan ibu sangat enak.", "Masakane ibu enak.", "Dhaharan ibu sanget eca."],
            [961, "Masjid", "Masjid", "Masjid", "Agama", "Kami salat di masjid.", "Kita salat ing masjid.", "Kula salat wonten masjid."],
            [962, "Masuk", "Mlebu", "Mlebet", "Kata Kerja", "Siswa masuk kelas.", "Murid mlebu kelas.", "Siswa mlebet kelas."],
            [963, "Mata", "Mripat", "Sochek/Netra", "Anggota Tubuh", "Mata saya terkena debu.", "Mripatku kelilip bledug.", "Netra kula kenging bledug."],
            [964, "Mata air", "Tuk", "Belik", "Alam", "Mata air itu sangat jernih.", "Tuk kuwi bening.", "Belik punika bening sanget."],
            [965, "Matahari", "Srengenge", "Raditya", "Alam", "Matahari terbit di timur.", "Srengenge metu saka wetan.", "Raditya medal saking wetan."],
            [966, "Matang", "Mateng", "Sampun Mateng", "Kata Sifat", "Pisang itu sudah matang.", "Gedhang kuwi wis mateng.", "Pisang punika sampun mateng."],
            [967, "Matematika", "Matematika", "Matematika", "Mata Pelajaran", "Saya belajar matematika.", "Aku sinau matematika.", "Kula sinau matematika."],
            [968, "Mati", "Mati/Pejah", "Pejah", "Kata Kerja", "Lampu itu mati.", "Lampu kuwi mati.", "Lampu punika pejah."],
            [969, "Matras", "Matras", "Matras", "Olahraga", "Matras digunakan saat senam.", "Matras dienggo senam.", "Matras dipunginakaken senam."],
            [970, "Mawar", "Mawar", "Mawar", "Bunga", "Mawar merah sangat harum.", "Mawar abang wangi.", "Mawar abrit wangi."],
            [971, "Meja", "Meja", "Meja", "Peralatan Rumah", "Buku ada di atas meja.", "Buku ana ing ndhuwur meja.", "Buku wonten inggil meja."],
            [972, "Melati", "Melati", "Melati", "Bunga", "Bunga melati berwarna putih.", "Melati putih.", "Melati putih."],
            [973, "Melihat", "Deleng/Mirsani", "Mirsani", "Kata Kerja", "Saya melihat pelangi.", "Aku deleng pelangi.", "Kula mirsani pelangi."],
            [974, "Melon", "Melon", "Melon", "Buah", "Melon itu rasanya manis.", "Melon kuwi legi.", "Melon punika manis."],
            [975, "Memakai", "Nganggo", "Ngagem", "Kata Kerja", "Ayah memakai topi.", "Bapak nganggo topi.", "Rama ngagem topi."],
            [976, "Memasak", "Masak", "Masak", "Kata Kerja", "Ibu memasak sayur.", "Ibu masak sayur.", "Ibu masak sayur."],
            [977, "Memilih", "Milih", "Milih", "Kata Kerja", "Saya memilih buku baru.", "Aku milih buku anyar.", "Kula milih buku enggal."],
            [978, "Meminta", "Nyuwun", "Nyuwun/Kalem", "Kata Kerja", "Adik meminta izin.", "Adhik nyuwun idin.", "Adhi nyuwun idin."],
            [979, "Memotong", "Ngethok", "Ngethok", "Kata Kerja", "Ayah memotong kayu.", "Bapak ngethok kayu.", "Rama ngethok kayu."],
            [980, "Menabung", "Nabung", "Nabung", "Kata Kerja", "Saya menabung setiap minggu.", "Aku nabung saben minggu.", "Kula nabung saben minggu."],
            [981, "Menang", "Menang", "Menang", "Kata Kerja", "Tim kami menang lomba.", "Timku menang lomba.", "Tim kula menang lomba."],
            [982, "Menantu", "Mantu", "Mantu", "Keluarga", "Menantu membantu ibu.", "Mantu nulungi ibu.", "Mantu mitulungi ibu."],
            [983, "Menarik", "Narik", "Narik", "Kata Kerja", "Adik menarik kursi.", "Adhik narik kursi.", "Adhi narik kursi."],
            [984, "Mencari", "Golek", "Pados", "Kata Kerja", "Saya mencari buku.", "Aku golek buku.", "Kula pados buku."],
            [985, "Mencuci", "Ngumbah", "Ngumbah", "Kata Kerja", "Ibu mencuci pakaian.", "Ibu ngumbah klambi.", "Ibu ngumbah busana."],
            [986, "Mendengar", "Krungu", "Mireng", "Kata Kerja", "Saya mendengar suara burung.", "Aku krungu swara manuk.", "Kula mireng swanten manuk."],
            [987, "Mendung", "Mendung", "Mendung", "Cuaca", "Langit tampak mendung.", "Langit katon mendung.", "Langit katingal mendung."],
            [988, "Mendorong", "Nyorong", "Nyurung", "Kata Kerja", "Ayah mendorong mobil.", "Bapak nyorong mobil.", "Rama nyurung mobil."],
            [989, "Mengajar", "Mulang", "Mucal", "Kata Kerja", "Guru mengajar di kelas.", "Guru mulang ing kelas.", "Guru mucal wonten kelas."],
            [990, "Mengecat", "Ngecet", "Ngecet", "Kata Kerja", "Ayah mengecat pagar.", "Bapak ngecet pager.", "Rama ngecet pager."],
            [991, "Mengejar", "Ngoyak", "Ngejar", "Kata Kerja", "Anak mengejar kupu-kupu.", "Bocah ngoyak kupu-kupu.", "Putra ngejar kupu-kupu."],
            [992, "Mengelap", "Ngelap", "Ngelap", "Kata Kerja", "Ibu mengelap meja.", "Ibu ngelap meja.", "Ibu ngelap meja."],
            [993, "Mengerti", "Ngerti", "Ngertos", "Kata Kerja", "Saya mengerti pelajaran.", "Aku ngerti pelajaran.", "Kula ngertos piwulangan."],
            [994, "Menggambar", "Nggambar", "Nggambar", "Kata Kerja", "Adik menggambar rumah.", "Adhik nggambar omah.", "Adhi nggambar griya."],
            [995, "Menggosok", "Ngosok", "Ngosok", "Kata Kerja", "Adik menggosok gigi.", "Adhik ngosok untu.", "Adhi ngosok untu."],
            [996, "Menghafal", "Ngapalaken", "Napalaken", "Kata Kerja", "Siswa menghafal doa.", "Murid ngapalake donga.", "Siswa napalaken pandonga."],
            [997, "Menghitung", "Ngetung", "Ngetang", "Kata Kerja", "Saya menghitung uang.", "Aku ngetung dhuwit.", "Kula ngetang arta."],
            [998, "Mengirim", "Ngirim", "Ngintun", "Kata Kerja", "Ibu mengirim paket.", "Ibu ngirim paket.", "Ibu ngintun paket."],
            [999, "Mengobati", "Nambani", "Nambani", "Kata Kerja", "Dokter mengobati pasien.", "Dhokter nambani pasien.", "Dhokter nambani pasien."],
            [1000, "Mengucap", "Ngucap", "Ngaturaken", "Kata Kerja", "Ayah mengucap terima kasih.", "Bapak ngucap matur nuwun.", "Rama ngaturaken matur nuwun."],
            [1001, "Mengundang", "Ngundang", "Ngundang", "Kata Kerja", "Kami mengundang tetangga.", "Kita ngundang tangga.", "Kula ngundang tanggi."],
            [1002, "Menit", "Menit", "Menit", "Waktu", "Pelajaran dimulai lima menit lagi.", "Pelajaran diwiwiti limang menit maneh.", "Piwulangan dipunwiwiti gangsal menit malih."],
            [1003, "Menolong", "Nulungi", "Mitulungi", "Kata Kerja", "Kakak menolong adik.", "Mas nulungi adhik.", "Raka mitulungi adhi."],
            [1004, "Menonton", "Nonton", "Mirsani", "Kata Kerja", "Kami menonton wayang.", "Kita nonton wayang.", "Kula mirsani wayang."],
            [1005, "Menulis", "Nulis", "Nyerat", "Kata Kerja", "Saya menulis surat.", "Aku nulis layang.", "Kula nyerat layang."],
            [1006, "Merah", "Abang", "Abrit", "Warna", "Bunga itu berwarna merah.", "Kembang kuwi abang.", "Sekar punika abrit."],
            [1007, "Merasa", "Krasa", "Kraos", "Kata Kerja", "Saya merasa senang.", "Aku krasa seneng.", "Kula kraos remen."],
            [1008, "Merdeka", "Mardika", "Mardika", "Kata Sifat", "Indonesia sudah merdeka.", "Indonesia wis mardika.", "Indonesia sampun mardika."],
            [1009, "Merpati", "Dara", "Dara", "Hewan", "Merpati terbang tinggi.", "Dara mabur dhuwur.", "Dara mabur inggil."],
            [1010, "Mesin", "Mesin", "Mesin", "Teknologi", "Mesin itu bekerja baik.", "Mesin kuwi nyambut gawe apik.", "Mesin punika nyambut damel sae."],
            [1011, "Mesjid", "Masjid", "Masjid", "Agama", "Kami beribadah di masjid.", "Kita sembahyang ing masjid.", "Kula sembahyang wonten masjid."],
            [1012, "Mei", "Mei", "Mei", "Waktu", "Bulan Mei banyak libur.", "Wulan Mei akeh prei.", "Wulan Mei kathah prei."],
            [1013, "Mie", "Mi", "Mi", "Makanan", "Ibu memasak mi goreng.", "Ibu masak mi goreng.", "Ibu masak mi goreng."],
            [1014, "Mikrofon", "Mikrofon", "Mikrofon", "Teknologi", "Guru memakai mikrofon.", "Guru nganggo mikrofon.", "Guru ngagem mikrofon."],
            [1015, "Minat", "Minat", "Minat", "Pendidikan", "Saya memiliki minat membaca.", "Aku duwe minat maca.", "Kula gadhah minat maos."],
            [1016, "Minggu", "Minggu", "Minggu", "Waktu", "Hari Minggu kami bersepeda.", "Dina Minggu kita numpak pit.", "Dinten Minggu kula nitih pit."],
            [1017, "Minum", "Ngombe", "Ngunjuk", "Kata Kerja", "Adik minum susu.", "Adhik ngombe susu.", "Adhi ngunjuk susu."],
            [1018, "Minuman", "Ombenan", "Unjukan", "Minuman", "Ibu membuat minuman hangat.", "Ibu nggawe ombenan anget.", "Ibu damel unjukan anget."],
            [1019, "Minyak", "Lenga", "Lenga", "Kebutuhan Rumah", "Ibu membeli minyak goreng.", "Ibu tuku lenga goreng.", "Ibu mundhut lenga goreng."],
            [1020, "Minyak kayu putih", "Lenga kayu putih", "Lenga kayu putih", "Obat", "Ibu mengoleskan minyak kayu putih.", "Ibu nggunakake lenga kayu putih.", "Ibu ngagem lenga kayu putih."],
            [1021, "Minyak tanah", "Lenga tanah", "Lenga tanah", "Kebutuhan Rumah", "Lampu memakai minyak tanah.", "Lampu nganggo lenga tanah.", "Lampu ngagem lenga tanah."],
            [1022, "Miris", "Nyedhihaken", "Nyedhihaken", "Perasaan", "Cerita itu sangat miris.", "Crita kuwi nyedhihake.", "Cariyos punika nyedhihaken."],
            [1023, "Miskin", "Mlarat", "Sekeca", "Kata Sifat", "Kita tidak boleh menghina orang miskin.", "Aja ngenyek wong mlarat.", "Sampun ngremehaken tiyang sekeca."],
            [1024, "Mobil", "Mobil", "Mobil", "Kendaraan", "Ayah mencuci mobil.", "Bapak ngumbah mobil.", "Rama ngumbah mobil."],
            [1025, "Modal", "Modal", "Modal", "Ekonomi", "Pedagang membutuhkan modal.", "Bakul butuh modal.", "Bakul mbetahaken modal."],
            [1026, "Modern", "Modern", "Modern", "Kata Sifat", "Sekolah memiliki gedung modern.", "Sekolah nduweni gedhong modern.", "Sekolah gadhah gedhong modern."],
            [1027, "Modul", "Modul", "Modul", "Pendidikan", "Guru membagikan modul belajar.", "Guru mbagekke modul sinau.", "Guru mbagekaken modul sinau."],
            [1028, "Moge", "Montor gedhe", "Montor ageng", "Kendaraan", "Dia membeli moge baru.", "Dheweke tuku montor gedhe anyar.", "Piyambakipun mundhut montor ageng enggal."],
            [1029, "Mohon", "Nyuwun", "Nyuwun", "Ungkapan", "Mohon tunggu sebentar.", "Nyuwun ngenteni sedhela.", "Nyuwun ngentosi sekedhap."],
            [1030, "Monyet", "Kethek", "Kethek", "Hewan", "Monyet memanjat pohon.", "Kethek menek wit.", "Kethek minggah uwit."],
            [1031, "Motor", "Montor", "Montor", "Kendaraan", "Ayah mengendarai motor.", "Bapak numpak montor.", "Rama nitih montor."],
            [1032, "Muara", "Cangkem kali", "Cangkem kali", "Alam", "Sungai bermuara di laut.", "Kali mili menyang cangkem kali.", "Kali mili dhateng cangkem kali."],
            [1033, "Mudah", "Gampang", "Gampil", "Kata Sifat", "Soal ini mudah.", "Soal iki gampang.", "Pitaken punika gampil."],
            [1034, "Mudi", "Mudi", "Mudi", "Transportasi", "Mudi kapal sangat berpengalaman.", "Mudi kapal wis pengalaman.", "Mudi kapal sampun pengalaman."],
            [1035, "Mufakat", "Mufakat", "Mufakat", "Sosial", "Warga mencapai mufakat.", "Warga entuk mufakat.", "Warga pikantuk mufakat."],
            [1036, "Muka", "Rai", "Pasuryan", "Anggota Tubuh", "Mukanya tampak ceria.", "Raine katon bungah.", "Pasuryanipun katingal bingah."],
            [1037, "Mulai", "Miwiti", "Miwiti", "Kata Kerja", "Guru mulai pelajaran.", "Guru miwiti pelajaran.", "Guru miwiti piwulangan."],
            [1038, "Mulut", "Cangkem", "Lathi/Karana", "Anggota Tubuh", "Jangan berkata kasar.", "Aja nganggo cangkem kasar.", "Sampun ngagem lathi kasar."],
            [1039, "Muncul", "Metu", "Medal", "Kata Kerja", "Pelangi muncul setelah hujan.", "Pelangi metu sawise udan.", "Pelangi medal sasampunipun udan."],
            [1040, "Mundur", "Mundur", "Mundur", "Kata Kerja", "Siswa mundur satu langkah.", "Murid mundur sak langkah.", "Siswa mundur satunggal lampah."],
            [1041, "Murid", "Murid", "Siswa", "Pendidikan", "Murid belajar dengan rajin.", "Murid sinau sregep.", "Siswa sinau sregep."],
            [1042, "Murah", "Murah", "Murah", "Kata Sifat", "Harga buku itu murah.", "Rega buku kuwi murah.", "Reginipun buku punika mirah."],
            [1043, "Murid baru", "Murid anyar", "Siswa enggal", "Pendidikan", "Murid baru mulai belajar.", "Murid anyar wiwit sinau.", "Siswa enggal wiwit sinau."],
            [1044, "Musang", "Luwak", "Luwak", "Hewan", "Musang mencari makanan malam hari.", "Luwak golek panganan bengi.", "Luwak pados dhaharan dalu."],
            [1045, "Musik", "Musik", "Musik", "Seni", "Kami belajar musik tradisional.", "Kita sinau musik tradisional.", "Kula sinau musik tradisional."],
            [1046, "Musim", "Mangsa", "Mangsa", "Alam", "Sekarang musim hujan.", "Saiki mangsa udan.", "Sapunika mangsa udan."],
            [1047, "Musim kemarau", "Mangsa ketiga", "Mangsa ketiga", "Cuaca", "Musim kemarau mulai datang.", "Mangsa ketiga wiwit teka.", "Mangsa ketiga wiwit rawuh."],
            [1048, "Musim hujan", "Mangsa udan", "Mangsa udan", "Cuaca", "Musim hujan membuat sawah subur.", "Mangsa udan nggawe sawah subur.", "Mangsa udan damel sabin subur."],
            [1049, "Musyawarah", "Rembugan", "Rembagan", "Sosial", "Warga mengadakan musyawarah.", "Warga rembugan bareng.", "Warga rembagan sesarengan."],
            [1050, "Mutiara", "Mutiara", "Mutiara", "Benda", "Ibu memakai kalung mutiara.", "Ibu nganggo kalung mutiara.", "Ibu ngagem kalung mutiara."],
            [1051, "Nabi", "Nabi", "Nabi", "Agama", "Umat Islam mencintai nabi.", "Umat Islam tresna nabi.", "Umat Islam tresna nabi."],
            [1052, "Nada", "Nada", "Nada", "Musik", "Guru mengajarkan nada dasar.", "Guru mulang nada dhasar.", "Guru mucal nada dhasar."],
            [1053, "Nafas", "Ambegan", "Ambegan", "Kesehatan", "Nafasnya teratur.", "Ambegane teratur.", "Ambeganipun teratur."],
            [1054, "Naga", "Naga", "Naga", "Hewan", "Cerita itu tentang naga.", "Crita kuwi babagan naga.", "Cariyos punika babagan naga."],
            [1055, "Naik", "Numpak", "Nitih", "Kata Kerja", "Kami naik bus ke sekolah.", "Kita numpak bis menyang sekolah.", "Kula nitih bis dhateng sekolah."],
            [1056, "Nakal", "Nakal", "Nakal", "Kata Sifat", "Anak itu tidak nakal.", "Bocah kuwi ora nakal.", "Putra punika boten nakal."],
            [1057, "Nama", "Jeneng", "Asma", "Kata Benda", "Siapa nama gurumu?", "Sapa jeneng gurumu?", "Sinten asma guru panjenengan?"],
            [1058, "Nanas", "Nanas", "Nanas", "Buah", "Nanas rasanya manis.", "Nanas rasane legi.", "Nanas raosipun manis."],
            [1059, "Nanas muda", "Nanas enom", "Nanas anem", "Buah", "Nanas muda rasanya asam.", "Nanas enom rasane kecut.", "Nanas anem raosipun kecut."],
            [1060, "Napas", "Ambegan", "Ambegan", "Kesehatan", "Ambil napas yang dalam.", "Ambegan sing jero.", "Ambegan ingkang lebet."],
            [1061, "Narapidana", "Narapidana", "Narapidana", "Profesi", "Narapidana mengikuti pelatihan.", "Narapidana melu pelatihan.", "Narapidana ndherek pelatihan."],
            [1062, "Nasi", "Sega", "Sekul", "Makanan", "Kami makan nasi hangat.", "Kita mangan sega anget.", "Kula dhahar sekul anget."],
            [1063, "Nasi goreng", "Sega goreng", "Sekul goreng", "Makanan", "Ibu memasak nasi goreng.", "Ibu masak sega goreng.", "Ibu masak sekul goreng."],
            [1064, "Nasi kuning", "Sega kuning", "Sekul kuning", "Makanan", "Mereka membawa nasi kuning.", "Dheweke nggawa sega kuning.", "Piyambakipun ngasta sekul kuning."],
            [1065, "Nasi putih", "Sega putih", "Sekul putih", "Makanan", "Saya makan nasi putih.", "Aku mangan sega putih.", "Kula dhahar sekul putih."],
            [1066, "Natal", "Natal", "Natal", "Agama", "Mereka merayakan Natal.", "Dheweke ngrayakake Natal.", "Piyambakipun ngrayakaken Natal."],
            [1067, "Natap", "Ndelok", "Mirsani", "Kata Kerja", "Adik menatap pelangi.", "Adhik ndelok pelangi.", "Adhi mirsani pelangi."],
            [1068, "Nenek", "Mbah Putri", "Eyang Putri", "Keluarga", "Nenek sedang memasak.", "Mbah putri lagi masak.", "Eyang putri saweg masak."],
            [1069, "Neraca", "Neraca", "Neraca", "Ekonomi", "Neraca itu seimbang.", "Neraca kuwi imbang.", "Neraca punika imbang."],
            [1070, "Netral", "Netral", "Netral", "Kata Sifat", "Warna dinding netral.", "Werna tembok netral.", "Warna tembok netral."],
            [1071, "Niat", "Niyat", "Niyat", "Kata Benda", "Niat baik harus dijaga.", "Niyat apik kudu dijaga.", "Niyat sae kedah dipunjagi."],
            [1072, "Nilai", "Biji", "Biji", "Pendidikan", "Nilai matematikaku bagus.", "Bijiku matematika apik.", "Biji matematika kula sae."],
            [1073, "Nimba", "Nimba", "Nimba", "Kata Kerja", "Ibu menimba air.", "Ibu nimba banyu.", "Ibu nimba toya."],
            [1074, "Nisan", "Nisan", "Nisan", "Tempat", "Nisan itu terbuat dari batu.", "Nisan kuwi digawe saka watu.", "Nisan punika kadamel saking sela."],
            [1075, "Nomor", "Nomer", "Nomer", "Kata Benda", "Tulis nomor halaman.", "Tulis nomer kaca.", "Serat nomer kaca."],
            [1076, "Nona", "Nona", "Nona", "Sapaan", "Nona itu sangat ramah.", "Nona kuwi grapyak.", "Nona punika grapyak."],
            [1077, "Normal", "Normal", "Normal", "Kata Sifat", "Suhu tubuhnya normal.", "Suhu awake normal.", "Suhu badanipun normal."],
            [1078, "November", "November", "November", "Waktu", "Ujian dimulai bulan November.", "Ujian diwiwiti wulan November.", "Ujian dipunwiwiti wulan November."],
            [1079, "Nujum", "Nujum", "Nujum", "Budaya", "Kakek tidak percaya nujum.", "Mbah ora percaya nujum.", "Eyang boten pitados nujum."],
            [1080, "Numpang", "Numpang", "Numpang", "Kata Kerja", "Saya numpang sepeda teman.", "Aku numpang pit kanca.", "Kula numpang pit rencang."],
            [1081, "Nurut", "Nurut", "Nurut", "Kata Kerja", "Anak itu selalu nurut orang tua.", "Bocah kuwi tansah nurut wong tuwa.", "Putra punika tansah nurut tiyang sepuh."],
            [1082, "Nusantara", "Nusantara", "Nusantara", "Geografi", "Indonesia disebut Nusantara.", "Indonesia diarani Nusantara.", "Indonesia dipunwastani Nusantara."],
            [1083, "Nyala", "Murub", "Murub", "Kata Kerja", "Lampu mulai menyala.", "Lampu wiwit murub.", "Lampu wiwit murub."],
            [1084, "Nyamuk", "Nyamuk", "Nyamuk", "Hewan", "Nyamuk menggigit tangan saya.", "Nyamuk nyokot tanganku.", "Nyamuk nyakot tangan kula."],
            [1085, "Nyanyi", "Nembang", "Nembang", "Kata Kerja", "Adik suka menyanyi.", "Adhik seneng nembang.", "Adhi remen nembang."],
            [1086, "Nyanyian", "Tembang", "Tembang", "Musik", "Guru mengajarkan nyanyian daerah.", "Guru mulang tembang daerah.", "Guru mucal tembang daerah."],
            [1087, "Nyaring", "Banter", "Seru", "Kata Sifat", "Suaranya sangat nyaring.", "Swarane banter.", "Swantenipun seru."],
            [1088, "Nyata", "Nyata", "Nyata", "Kata Sifat", "Buktinya sudah nyata.", "Buktine wis nyata.", "Buktinipun sampun nyata."],
            [1089, "Nyawa", "Nyawa", "Nyawa", "Kata Benda", "Semua makhluk memiliki nyawa.", "Kabeh makhluk nduweni nyawa.", "Sedaya makhluk gadhah nyawa."],
            [1090, "Nyeri", "Lara", "Lara", "Kesehatan", "Lutut saya terasa nyeri.", "Dhengkulku krasa lara.", "Jengku kula kraos lara."],
            [1091, "Nyiru", "Nyiru", "Nyiru", "Peralatan Rumah", "Ibu memakai nyiru untuk menampi beras.", "Ibu nganggo nyiru kanggo nampek beras.", "Ibu ngagem nyiru kangge nampek beras."],
            [1092, "Obat", "Obat", "Obat", "Kesehatan", "Dokter memberi obat.", "Dhokter menehi obat.", "Dhokter maringi obat."],
            [1093, "Obeng", "Obeng", "Obeng", "Peralatan", "Ayah memakai obeng.", "Bapak nganggo obeng.", "Rama ngagem obeng."],
            [1094, "Obor", "Obor", "Obor", "Peralatan", "Obor menyala terang.", "Obor murub padhang.", "Obor murub padhang."],
            [1095, "Olah raga", "Olahraga", "Olahraga", "Olahraga", "Kami berolahraga setiap pagi.", "Kita olahraga saben esuk.", "Kula olahraga saben enjing."],
            [1096, "Ombak", "Ombak", "Ombak", "Alam", "Ombak di pantai besar.", "Ombak ing pantai gedhe.", "Ombak wonten pasisir ageng."],
            [1097, "Omong", "Ngomong", "Nutur", "Kata Kerja", "Jangan omong kasar.", "Aja ngomong kasar.", "Sampun nutur kasar."],
            [1098, "Ondel-ondel", "Ondel-ondel", "Ondel-ondel", "Budaya", "Kami melihat ondel-ondel.", "Kita ndelok ondel-ondel.", "Kula mirsani ondel-ondel."],
            [1099, "Ongkos", "Ongkos", "Ongkos", "Ekonomi", "Ongkos bus sangat murah.", "Ongkos bis murah.", "Ongkos bis mirah."],
            [1100, "Orang", "Wong", "Tiyang", "Kata Benda", "Orang itu sangat baik.", "Wong kuwi apik.", "Tiyang punika sae."],
            [1101, "Orang tua", "Wong tuwa", "Tiyang sepuh", "Keluarga", "Orang tua menyayangi anak.", "Wong tuwa tresna anak.", "Tiyang sepuh tresna putra."],
            [1102, "Organ", "Organ", "Organ", "Anggota Tubuh", "Setiap organ memiliki fungsi.", "Saben organ nduweni guna.", "Saben organ gadhah ginanipun."],
            [1103, "Organisasi", "Organisasi", "Organisasi", "Pendidikan", "Saya mengikuti organisasi sekolah.", "Aku melu organisasi sekolah.", "Kula ndherek organisasi sekolah."],
            [1104, "Otak", "Utek", "Panggalih", "Anggota Tubuh", "Otak manusia sangat penting.", "Utek manungsa penting.", "Panggalih manungsa wigati."],
            [1105, "Otomatis", "Otomatis", "Otomatis", "Teknologi", "Pintu itu otomatis terbuka.", "Lawang kuwi otomatis mbukak.", "Lawang punika otomatis kabikak."],
            [1106, "Oven", "Oven", "Oven", "Dapur", "Ibu memanggang roti dengan oven.", "Ibu manggang roti nganggo oven.", "Ibu manggang roti ngagem oven."],
            [1107, "Pacar", "Pacar", "Pacar", "Tumbuhan", "Ibu menanam bunga pacar.", "Ibu nandur kembang pacar.", "Ibu nandur sekar pacar."],
            [1108, "Pacar kuku", "Pacar kuku", "Pacar kuku", "Tumbuhan", "Nenek memakai pacar kuku.", "Mbah nganggo pacar kuku.", "Eyang ngagem pacar kuku."],
            [1109, "Pacu", "Pacu", "Pacu", "Olahraga", "Kuda mengikuti lomba pacu.", "Jaran melu lomba pacu.", "Turangga ndherek lomba pacu."],
            [1110, "Padi", "Pari", "Pari", "Pertanian", "Petani menanam padi.", "Pak tani nandur pari.", "Petani nandur pari."],
            [1111, "Padam", "Mati", "Pejah", "Kata Kerja", "Lampu padam saat hujan.", "Lampu mati wektu udan.", "Lampu pejah nalika udan."],
            [1112, "Padat", "Padhet", "Padhet", "Kata Sifat", "Jadwal hari ini padat.", "Jadwal dina iki padhet.", "Jadwal dinten punika padhet."],
            [1113, "Padi gogo", "Pari gaga", "Pari gaga", "Pertanian", "Petani menanam padi gogo.", "Pak tani nandur pari gaga.", "Petani nandur pari gaga."],
            [1114, "Pagar", "Pager", "Pager", "Rumah", "Ayah mengecat pagar.", "Bapak ngecet pager.", "Rama ngecet pager."],
            [1115, "Pagi", "Esuk", "Enjing", "Waktu", "Pagi ini udara sejuk.", "Esuk iki hawane adem.", "Enjing punika hawanipun adem."],
            [1116, "Paha", "Pupu", "Pupu", "Anggota Tubuh", "Paha adik terluka.", "Pupune adhik tatu.", "Pupunipun adhi tatu."],
            [1117, "Pahit", "Pait", "Pait", "Kata Sifat", "Obat ini pahit.", "Obat iki pait.", "Obat punika pait."],
            [1118, "Pahlawan", "Pahlawan", "Pahlawan", "Sejarah", "Kita menghormati pahlawan.", "Kita ngajeni pahlawan.", "Kula ngurmati pahlawan."],
            [1119, "Paku", "Paku", "Paku", "Peralatan", "Ayah memukul paku.", "Bapak mukul paku.", "Rama mukul paku."],
            [1120, "Paku bumi", "Paku bumi", "Paku bumi", "Tumbuhan", "Paku bumi tumbuh di hutan.", "Paku bumi thukul ing alas.", "Paku bumi tuwuh wonten wana."],
            [1121, "Pala", "Pala", "Pala", "Tumbuhan", "Pala digunakan sebagai bumbu.", "Pala dienggo bumbu.", "Pala dipunginakaken bumbu."],
            [1122, "Palang", "Palang", "Palang", "Benda", "Palang pintu ditutup.", "Palang lawang ditutup.", "Palang lawang dipuntutup."],
            [1123, "Palu", "Palu", "Palu", "Peralatan", "Tukang memakai palu.", "Tukang nganggo palu.", "Tukang ngagem palu."],
            [1124, "Paman", "Paklik/Paman", "Paman/Kanjeng Paman", "Keluarga", "Paman datang berkunjung.", "Paklik teka.", "Paman rawuh."],
            [1125, "Panas", "Panas", "Benter", "Kata Sifat", "Hari ini sangat panas.", "Dina iki panas.", "Dinten punika benter."],
            [1126, "Panci", "Panci", "Panci", "Dapur", "Ibu merebus air di panci.", "Ibu nggodhog banyu ing panci.", "Ibu nggodhog toya wonten panci."],
            [1127, "Panda", "Panda", "Panda", "Hewan", "Panda makan bambu.", "Panda mangan pring.", "Panda dhahar pring."],
            [1128, "Pandang", "Ndeleng", "Mirsani", "Kata Kerja", "Saya memandang gunung.", "Aku ndeleng gunung.", "Kula mirsani redi."],
            [1129, "Panjang", "Dawa", "Dawa", "Kata Sifat", "Tali itu panjang.", "Tali kuwi dawa.", "Tali punika dawa."],
            [1130, "Pantai", "Pantai", "Pasisir", "Alam", "Kami bermain di pantai.", "Kita dolanan ing pantai.", "Kula dolanan wonten pasisir."],
            [1131, "Pantat", "Bokong", "Bokong", "Anggota Tubuh", "Bayi duduk dengan pantatnya.", "Bayi lungguh nganggo bokong.", "Bayi lenggah ngagem bokong."],
            [1132, "Papan", "Papan", "Papan", "Benda", "Papan tulis dibersihkan guru.", "Papan tulis diresiki guru.", "Papan serat dipunresiki guru."],
            [1133, "Parang", "Parang", "Parang", "Peralatan", "Ayah menebang pohon dengan parang.", "Bapak negor wit nganggo parang.", "Rama negor uwit ngagem parang."],
            [1134, "Parasut", "Parasut", "Parasut", "Transportasi", "Prajurit memakai parasut.", "Prajurit nganggo parasut.", "Prajurit ngagem parasut."],
            [1135, "Pari manta", "Pari manta", "Pari manta", "Hewan", "Pari manta hidup di laut.", "Pari manta urip ing segara.", "Pari manta gesang wonten seganten."],
            [1136, "Parkir", "Parkir", "Parkir", "Transportasi", "Motor diparkir di halaman.", "Montor diparkir ing pekarangan.", "Montor dipunparkir wonten pekarangan."],
            [1137, "Paruh", "Cucuk", "Cucuk", "Hewan", "Paruh burung sangat kuat.", "Cucuk manuk kuwat.", "Cucuk manuk kiyat."],
            [1138, "Pasar", "Pasar", "Pasar", "Tempat", "Ibu pergi ke pasar.", "Ibu lunga menyang pasar.", "Ibu tindak dhateng pasar."],
            [1139, "Pasien", "Pasien", "Pasien", "Kesehatan", "Dokter memeriksa pasien.", "Dhokter mriksa pasien.", "Dhokter mriksa pasien."],
            [1140, "Pasir", "Wedhi", "Wedhi", "Alam", "Anak bermain pasir.", "Bocah dolanan wedhi.", "Putra dolanan wedhi."],
            [1141, "Paspor", "Paspor", "Paspor", "Dokumen", "Ayah membuat paspor baru.", "Bapak nggawe paspor anyar.", "Rama damel paspor enggal."],
            [1142, "Pasta gigi", "Pasta untu", "Pasta untu", "Kesehatan", "Adik memakai pasta gigi.", "Adhik nganggo pasta untu.", "Adhi ngagem pasta untu."],
            [1143, "Patung", "Patung", "Arca", "Seni", "Patung itu terbuat dari batu.", "Patung kuwi digawe saka watu.", "Arca punika kadamel saking sela."],
            [1144, "Paus", "Paus", "Paus", "Hewan", "Paus hidup di laut.", "Paus urip ing segara.", "Paus gesang wonten seganten."],
            [1145, "Payung", "Payung", "Songsong", "Peralatan", "Saya membawa payung saat hujan.", "Aku nggawa payung nalika udan.", "Kula ngasta songsong nalika udan."],
            [1146, "Pecah", "Pecah", "Pecah", "Kata Kerja", "Gelas itu pecah.", "Gelas kuwi pecah.", "Gelas punika pecah."],
            [1147, "Pedal", "Pedhal", "Pedhal", "Kendaraan", "Pedal sepeda diinjak pelan.", "Pedhal pit diinjak alon.", "Pedhal pit dipuninjak alon."],
            [1148, "Pedas", "Pedhes", "Pedhes", "Kata Sifat", "Sambal ini sangat pedas.", "Sambel iki pedhes.", "Sambel punika pedhes."],
            [1149, "Pedagang", "Bakul", "Bakul", "Profesi", "Pedagang menjual sayur.", "Bakul adol sayur.", "Bakul sade sayur."],
            [1150, "Pedang", "Pedhang", "Pedhang", "Peralatan", "Prajurit membawa pedang.", "Prajurit nggawa pedhang.", "Prajurit ngasta pedhang."],
            [1151, "Peduli", "Nggatekake", "Nggatekaken", "Kata Kerja", "Kita harus peduli lingkungan.", "Kita kudu nggatekake lingkungan.", "Kita kedah nggatekaken lingkungan."],
            [1152, "Pegawai", "Pegawé", "Pegawé", "Profesi", "Pegawai datang tepat waktu.", "Pegawé teka pas wektu.", "Pegawé rawuh leres wekdal."],
            [1153, "Pegunungan", "Pagunungan", "Pagunungan", "Alam", "Udara pegunungan sangat sejuk.", "Hawa pagunungan adem.", "Hawa pagunungan seger."],
            [1154, "Peka", "Peka", "Peka", "Kata Sifat", "Dia peka terhadap suara.", "Dheweke peka marang swara.", "Piyambakipun peka dhateng swanten."],
            [1155, "Pekarangan", "Pekarangan", "Pekarangan", "Rumah", "Ayah menyapu pekarangan.", "Bapak nyapu pekarangan.", "Rama nyapu pekarangan."],
            [1156, "Pekerjaan", "Gawean/Pakaryan", "Pakaryan", "Profesi", "Pekerjaan ayah sangat berat.", "Gaweane bapak abot.", "Pakaryan rama awrat."],
            [1157, "Pelabuhan", "Pelabuhan", "Pelabuhan", "Transportasi", "Kapal berlabuh di pelabuhan.", "Kapal mampir ing pelabuhan.", "Kapal sesandharan wonten pelabuhan."],
            [1158, "Pelajar", "Murid/Siswa", "Siswa", "Pendidikan", "Pelajar mengikuti upacara.", "Murid melu upacara.", "Siswa ndherek upacara."],
            [1159, "Pelangi", "Pelangi", "Pelangi", "Alam", "Pelangi muncul setelah hujan.", "Pelangi metu sawise udan.", "Pelangi medal sasampunipun udan."],
            [1160, "Pelan", "Alon", "Alon", "Kata Keterangan", "Berjalanlah pelan.", "Mlakua alon.", "Mlampaha alon."],
            [1161, "Pelatih", "Pelatih", "Pelatih", "Profesi", "Pelatih memberi arahan.", "Pelatih menehi pituduh.", "Pelatih maringi pitedah."],
            [1162, "Pelatihan", "Pelatihan", "Pelatihan", "Pendidikan", "Guru mengikuti pelatihan.", "Guru melu pelatihan.", "Guru ndherek pelatihan."],
            [1163, "Pelayan", "Pelayan", "Pelados", "Profesi", "Pelayan melayani pembeli.", "Pelayan ngladeni panuku.", "Pelados ngladosi panuku."],
            [1164, "Pelihara", "Ngingu", "Ngingu", "Kata Kerja", "Kami memelihara ayam.", "Kita ngingu pitik.", "Kula ngingu pitik."],
            [1165, "Peliharaan", "Kewan piaraan", "Sato piaraan", "Hewan", "Kucing adalah peliharaan kami.", "Kucing kewan piaraanku.", "Kucing sato piaraan kula."],
            [1166, "Pelita", "Pelita", "Pelita", "Peralatan", "Pelita menyala saat malam.", "Pelita murub bengi.", "Pelita murub dalu."],
            [1167, "Peluk", "Ngrangkul", "Ngrangkul", "Kata Kerja", "Ibu memeluk adik.", "Ibu ngrangkul adhik.", "Ibu ngrangkul adhi."],
            [1168, "Pemadam kebakaran", "Petugas pemadam", "Petugas pemadam", "Profesi", "Pemadam kebakaran datang cepat.", "Petugas pemadam teka cepet.", "Petugas pemadam rawuh enggal."],
            [1169, "Pemalu", "Isinan", "Lingseman", "Kata Sifat", "Anak itu pemalu.", "Bocah kuwi isinan.", "Putra punika lingseman."],
            [1170, "Pembeli", "Panuku", "Panuku", "Profesi", "Pembeli memilih buah.", "Panuku milih woh.", "Panuku milih woh."],
            [1171, "Pembelajaran", "Pasinaon", "Pasinaon", "Pendidikan", "Pembelajaran berlangsung lancar.", "Pasinaon lumaku lancar.", "Pasinaon lumampah lancar."],
            [1172, "Pemburu", "Pamburu", "Pamburu", "Profesi", "Pemburu masuk hutan.", "Pamburu mlebu alas.", "Pamburu mlebet wana."],
            [1173, "Pena", "Pena", "Pena", "Alat Tulis", "Saya membeli pena baru.", "Aku tuku pena anyar.", "Kula mundhut pena enggal."],
            [1174, "Penari", "Penari", "Penari", "Seni", "Penari tampil di panggung.", "Penari tampil ing panggung.", "Penari tampil wonten panggung."],
            [1175, "Pencak silat", "Pencak silat", "Pencak silat", "Olahraga", "Kakak belajar pencak silat.", "Mas sinau pencak silat.", "Raka sinau pencak silat."],
            [1176, "Pencuci piring", "Tukang ngumbah piring", "Tukang ngumbah piring", "Profesi", "Pencuci piring bekerja rajin.", "Tukang ngumbah piring sregep.", "Tukang ngumbah piring sregep."],
            [1177, "Pendek", "Cendhak", "Cekak", "Kata Sifat", "Pensil itu pendek.", "Potlot kuwi cendhak.", "Potlot punika cekak."],
            [1178, "Pendeta", "Pandhita", "Pandhita", "Agama", "Pendeta memimpin ibadah.", "Pandhita mimpin ibadah.", "Pandhita mimpin ibadah."],
            [1179, "Pendidikan", "Pendidikan", "Pendidikan", "Pendidikan", "Pendidikan sangat penting.", "Pendidikan penting banget.", "Pendidikan sanget wigati."],
            [1180, "Penggaris", "Penggaris", "Penggaris", "Alat Tulis", "Saya memakai penggaris.", "Aku nganggo penggaris.", "Kula ngagem penggaris."],
            [1181, "Penghapus", "Penghapus", "Penghapus", "Alat Tulis", "Adik memakai penghapus baru.", "Adhik nganggo penghapus anyar.", "Adhi ngagem penghapus enggal."],
            [1182, "Penghargaan", "Penghargaan", "Penghargaan", "Pendidikan", "Sekolah memberikan penghargaan.", "Sekolah menehi penghargaan.", "Sekolah maringi penghargaan."],
            [1183, "Penglihatan", "Pandelengan", "Pandelengan", "Kesehatan", "Penglihatan kakek berkurang.", "Pandelengane mbah saya kurang.", "Pandelenganipun eyang saya kirang."],
            [1184, "Pengrajin", "Pengrajin", "Pengrajin", "Profesi", "Pengrajin membuat anyaman bambu.", "Pengrajin nggawe anyaman pring.", "Pengrajin damel anyaman pring."],
            [1185, "Pengumuman", "Pengumuman", "Pengumuman", "Pendidikan", "Guru membacakan pengumuman.", "Guru maca pengumuman.", "Guru maos pengumuman."],
            [1186, "Penisilin", "Penisilin", "Penisilin", "Obat", "Dokter memberikan penisilin.", "Dhokter menehi penisilin.", "Dhokter maringi penisilin."],
            [1187, "Penuh", "Kebak", "Kebak", "Kata Sifat", "Gelas itu penuh air.", "Gelas kuwi kebak banyu.", "Gelas punika kebak toya."],
            [1188, "Penyu", "Penyu", "Penyu", "Hewan", "Penyu hidup di laut.", "Penyu urip ing segara.", "Penyu gesang wonten seganten."],
            [1189, "Penyakit", "Penyakit", "Penyakit", "Kesehatan", "Penyakit itu sudah sembuh.", "Penyakit kuwi wis mari.", "Penyakit punika sampun waras."],
            [1190, "Penyanyi", "Penyanyi", "Penyanyi", "Profesi", "Penyanyi itu bersuara merdu.", "Penyanyi kuwi swarane apik.", "Penyanyi punika swantenipun sae."],
            [1191, "Penyapu", "Sapu", "Sapu", "Peralatan", "Ibu membeli penyapu baru.", "Ibu tuku sapu anyar.", "Ibu mundhut sapu enggal."],
            [1192, "Penyelam", "Penyilem", "Penyilem", "Profesi", "Penyelam mencari mutiara.", "Penyilem golek mutiara.", "Penyilem pados mutiara."],
            [1193, "Penyihir", "Tukang sihir", "Tukang sihir", "Cerita", "Penyihir muncul dalam dongeng.", "Tukang sihir ana ing dongeng.", "Tukang sihir wonten dongeng."],
            [1194, "Pepaya", "Gedhang kates", "Kates", "Buah", "Pepaya itu sudah matang.", "Kates kuwi wis mateng.", "Kates punika sampun mateng."],
            [1195, "Perahu", "Prahu", "Prahu", "Transportasi", "Perahu berlayar di sungai.", "Prahu mlaku ing kali.", "Prahu lumampah wonten kali."],
            [1196, "Perak", "Perak", "Perak", "Logam", "Cincin itu terbuat dari perak.", "Cincin kuwi digawe saka perak.", "Cincin punika kadamel saking perak."],
            [1197, "Peralatan", "Piranti", "Piranti", "Kata Benda", "Peralatan dapur lengkap.", "Piranti pawon jangkep.", "Piranti pawon jangkep."],
            [1198, "Perang", "Perang", "Perang", "Sejarah", "Perang telah berakhir.", "Perang wis rampung.", "Perang sampun rampung."],
            [1199, "Perawat", "Perawat", "Juru rawat", "Profesi", "Perawat membantu dokter.", "Perawat nulungi dhokter.", "Juru rawat mitulungi dhokter."],
            [1200, "Perban", "Perban", "Perban", "Obat", "Perban membalut luka.", "Perban mbungkus tatu.", "Perban mbalut tatu."],
            [1201, "Percaya", "Precaya", "Pitados", "Kata Kerja", "Saya percaya kepada ayah.", "Aku precaya karo bapak.", "Kula pitados dhateng rama."],
            [1202, "Percakapan", "Pacelathon", "Pacelathon", "Bahasa", "Percakapan itu sangat sopan.", "Pacelathon kuwi sopan.", "Pacelathon punika sopan."],
            [1203, "Percobaan", "Percobaan", "Percobaan", "Pendidikan", "Siswa melakukan percobaan.", "Murid nindakake percobaan.", "Siswa nindakaken percobaan."],
            [1204, "Percuma", "Sia-sia", "Sia-sia", "Kata Sifat", "Usaha itu tidak percuma.", "Usaha kuwi ora sia-sia.", "Usaha punika boten sia-sia."],
            [1205, "Perdamaian", "Rukun", "Rukun", "Sosial", "Kita menjaga perdamaian.", "Kita njaga kerukunan.", "Kula njagi karukunan."],
            [1206, "Pergi", "Lunga", "Tindak/Kondur", "Kata Kerja", "Ayah pergi ke kantor.", "Bapak lunga menyang kantor.", "Rama tindak dhateng kantor."],
            [1207, "Perhatian", "Gatek", "Gatos", "Kata Benda", "Guru memberi perhatian kepada siswa.", "Guru menehi gatek marang murid.", "Guru maringi gatos dhateng siswa."],
            [1208, "Periksa", "Mriksa", "Mriksa", "Kata Kerja", "Dokter memeriksa pasien.", "Dhokter mriksa pasien.", "Dhokter mriksa pasien."],
            [1209, "Perjalanan", "Lelungan", "Lelampahan", "Transportasi", "Perjalanan kami menyenangkan.", "Lelungan kita nyenengake.", "Lelampahan kula nyenengaken."],
            [1210, "Perkakas", "Piranti", "Piranti", "Peralatan", "Ayah menyimpan perkakas.", "Bapak nyimpen piranti.", "Rama nyimpen piranti."],
            [1211, "Perkebunan", "Kebon", "Kebon", "Pertanian", "Perkebunan teh sangat luas.", "Kebon teh amba.", "Kebon tèh amba."],
            [1212, "Perlahan", "Alon-alon", "Alon-alon", "Kata Keterangan", "Adik berjalan perlahan.", "Adhik mlaku alon-alon.", "Adhi mlampah alon-alon."],
            [1213, "Permainan", "Dolanan", "Dolanan", "Permainan", "Permainan itu sangat seru.", "Dolanan kuwi nyenengake.", "Dolanan punika nyenengaken."],
            [1214, "Permen", "Permen", "Permen", "Makanan", "Adik membeli permen.", "Adhik tuku permen.", "Adhi mundhut permen."],
            [1215, "Permisi", "Nuwun sewu", "Nuwun sewu", "Ungkapan", "Permisi, saya ingin lewat.", "Nuwun sewu, aku arep liwat.", "Nuwun sewu, kula badhe langkung."],
            [1216, "Pernah", "Tau", "Natetah", "Kata Keterangan", "Saya pernah ke Solo.", "Aku tau menyang Solo.", "Kula natetah dhateng Solo."],
            [1217, "Perpustakaan", "Perpustakan", "Perpustakan", "Tempat", "Siswa membaca di perpustakaan.", "Murid maca ing perpustakan.", "Siswa maos wonten perpustakan."],
            [1218, "Persegi", "Papat sisi", "Pasegi", "Bentuk", "Meja itu berbentuk persegi.", "Meja kuwi papat sisi.", "Meja punika pasegi."],
            [1219, "Persik", "Persik", "Persik", "Buah", "Buah persik rasanya manis.", "Persik rasane legi.", "Persik raosipun manis."],
            [1220, "Pertandingan", "Pertandhingan", "Pertandhingan", "Olahraga", "Pertandingan dimulai pagi.", "Pertandhingan diwiwiti esuk.", "Pertandhingan dipunwiwiti enjing."],
            [1221, "Pertanian", "Tetanen", "Pertanian", "Pertanian", "Pertanian sangat penting.", "Tetanen kuwi penting.", "Pertanian punika wigati."],
            [1222, "Pertanyaan", "Pitakon", "Pitaken", "Bahasa", "Guru menjawab pertanyaan siswa.", "Guru njawab pitakone murid.", "Guru mangsuli pitakenipun siswa."],
            [1223, "Pertolongan", "Tulungan", "Pitulungan", "Sosial", "Pertolongan datang tepat waktu.", "Tulungan teka pas wektu.", "Pitulungan rawuh leres wekdal."],
            [1224, "Perut", "Weteng", "Padharan", "Anggota Tubuh", "Perut saya terasa kenyang.", "Wetengku krasa wareg.", "Padharan kula kraos wareg."],
            [1225, "Pesan", "Pesen", "Pesen", "Kata Kerja", "Ibu memesan makanan.", "Ibu pesen panganan.", "Ibu pesen dhaharan."],
            [1226, "Pesawat", "Pesawat", "Pesawat", "Transportasi", "Pesawat terbang tinggi.", "Pesawat mabur dhuwur.", "Pesawat mabur inggil."],
            [1227, "Peserta", "Peserta", "Peserta", "Pendidikan", "Peserta mengikuti lomba.", "Peserta melu lomba.", "Peserta ndherek lomba."],
            [1228, "Pesisir", "Pasisir", "Pasisir", "Alam", "Nelayan tinggal di pesisir.", "Nelayan manggon ing pasisir.", "Nelayan manggèn wonten pasisir."],
            [1229, "Petai", "Petai", "Petai", "Tumbuhan", "Ibu memasak petai.", "Ibu masak petai.", "Ibu masak petai."],
            [1230, "Petani", "Petani", "Petani", "Profesi", "Petani menanam jagung.", "Petani nandur jagung.", "Petani nandur jagung."],
            [1231, "Peternak", "Peternak", "Peternak", "Profesi", "Peternak memberi makan sapi.", "Peternak menehi pangan sapi.", "Peternak maringi pakan sapi."],
            [1232, "Petik", "Metik", "Metik", "Kata Kerja", "Adik memetik bunga.", "Adhik metik kembang.", "Adhi metik sekar."],
            [1233, "Petir", "Gludhug", "Gludhug", "Alam", "Petir menyambar pohon.", "Gludhug nyamber wit.", "Gludhug nyamber uwit."],
            [1234, "Petugas", "Petugas", "Petugas", "Profesi", "Petugas membantu pengunjung.", "Petugas nulungi tamu.", "Petugas mitulungi tamu."],
            [1235, "Piala", "Piala", "Piala", "Olahraga", "Tim kami mendapat piala.", "Timku entuk piala.", "Tim kula pikantuk piala."],
            [1236, "Pijat", "Pijet", "Pijet", "Kesehatan", "Ibu memijat punggung ayah.", "Ibu mijet gegere bapak.", "Ibu pijet pengkeranipun rama."],
            [1237, "Pikiran", "Pikiran", "Panggalih", "Perasaan", "Pikiran harus tetap tenang.", "Pikiran kudu tetep anteng.", "Panggalih kedah tansah tentrem."],
            [1238, "Pilih", "Milih", "Milih", "Kata Kerja", "Saya memilih tas biru.", "Aku milih tas biru.", "Kula milih tas biru."],
            [1239, "Pimpin", "Mimpin", "Mimpin", "Kata Kerja", "Ketua memimpin rapat.", "Ketua mimpin rapat.", "Ketua mimpin rapat."],
            [1240, "Pinjam", "Nyaminjam", "Nyaminjam/Kinjam", "Kata Kerja", "Saya meminjam buku.", "Aku nyilih buku.", "Kula nyilih buku."],
            [1241, "Pintu", "Lawang", "Lawang", "Rumah", "Pintu rumah terbuka.", "Lawang omah mbukak.", "Lawang griya kabikak."],
            [1242, "Pipa", "Pipa", "Pipa", "Peralatan", "Air mengalir melalui pipa.", "Banyu mili liwat pipa.", "Toya mili ngliwati pipa."],
            [1243, "Piring", "Piring", "Piring", "Peralatan Rumah", "Ibu mencuci piring.", "Ibu ngumbah piring.", "Ibu ngumbah piring."],
            [1244, "Pisang", "Gedhang", "Pisang", "Buah", "Pisang itu manis.", "Gedhang kuwi legi.", "Pisang punika manis."],
            [1245, "Pisau", "Lading", "Lading", "Peralatan", "Dapur memiliki pisau tajam.", "Pawon nduweni lading landhep.", "Pawon gadhah lading landhep."],
            [1246, "Plafon", "Plafon", "Plafon", "Rumah", "Plafon rumah berwarna putih.", "Plafon omah putih.", "Plafon griya putih."],
            [1247, "Planet", "Planet", "Planet", "Alam", "Bumi adalah sebuah planet.", "Bumi kuwi planet.", "Bumi punika planet."],
            [1248, "Plastik", "Plastik", "Plastik", "Benda", "Kantong plastik berwarna hitam.", "Kresek plastik ireng.", "Kantong plastik cemeng."],
            [1249, "Plat nomor", "Plat nomer", "Plat nomer", "Kendaraan", "Motor memiliki plat nomor.", "Montor nduweni plat nomer.", "Montor gadhah plat nomer."],
            [1250, "Pohon", "Uwit", "Uwit", "Tumbuhan", "Pohon mangga sangat rindang.", "Uwit pelem rindhang.", "Uwit pelem rindhang."],
            [1251, "Pojok", "Pojok", "Pojok", "Bangunan", "Buku diletakkan di pojok.", "Buku diseleh ing pojok.", "Buku dipunpasang wonten pojok."],
            [1252, "Polisi", "Polisi", "Polisi", "Profesi", "Polisi mengatur lalu lintas.", "Polisi ngatur lalu lintas.", "Polisi ngatur lalu lintas."],
            [1253, "Polos", "Lugu", "Lugu", "Kata Sifat", "Anak itu polos.", "Bocah kuwi lugu.", "Putra punika lugu."],
            [1254, "Pompa", "Pompa", "Pompa", "Peralatan", "Ayah memperbaiki pompa air.", "Bapak ndandani pompa banyu.", "Rama ndandosi pompa toya."],
            [1255, "Pondok", "Pondhok", "Pondhok", "Bangunan", "Mereka tinggal di pondok.", "Dheweke manggon ing pondhok.", "Piyambakipun manggèn wonten pondhok."],
            [1256, "Pos", "Pos", "Pos", "Tempat", "Surat dikirim melalui pos.", "Layang dikirim liwat pos.", "Layang dipunkintun lumantar pos."],
            [1257, "Posyandu", "Posyandu", "Posyandu", "Kesehatan", "Bayi diperiksa di posyandu.", "Bayi dipriksa ing posyandu.", "Bayi dipunpriksa wonten posyandu."],
            [1258, "Pot", "Pot", "Pot", "Peralatan", "Bunga tumbuh di dalam pot.", "Kembang thukul ing pot.", "Sekar tuwuh wonten pot."],
            [1259, "Potong", "Ngethok", "Ngethok", "Kata Kerja", "Ayah memotong kayu.", "Bapak ngethok kayu.", "Rama ngethok kayu."],
            [1260, "Pramuka", "Pramuka", "Pramuka", "Pendidikan", "Siswa mengikuti pramuka.", "Murid melu pramuka.", "Siswa ndherek pramuka."],
            [1261, "Prasasti", "Prasasti", "Prasasti", "Sejarah", "Prasasti itu sangat tua.", "Prasasti kuwi tuwa.", "Prasasti punika sepuh."],
            [1262, "Pria", "Lanang", "Kakung", "Keluarga", "Pria itu sangat ramah.", "Lanang kuwi grapyak.", "Kakung punika grapyak."],
            [1263, "Printer", "Printer", "Printer", "Komputer", "Guru mencetak soal dengan printer.", "Guru nyithak soal nganggo printer.", "Guru nyithak soal ngagem printer."],
            [1264, "Proyektor", "Proyektor", "Proyektor", "Teknologi", "Guru menyalakan proyektor.", "Guru nguripake proyektor.", "Guru nguripaken proyektor."],
            [1265, "Pulau", "Pulo", "Pulo", "Geografi", "Indonesia memiliki banyak pulau.", "Indonesia nduweni akeh pulo.", "Indonesia gadhah kathah pulo."],
            [1266, "Pulpen", "Bolpen", "Bolpen", "Alat Tulis", "Saya membeli pulpen baru.", "Aku tuku bolpen anyar.", "Kula mundhut bolpen enggal."],
            [1267, "Pulang", "Mulih", "Kondur", "Kata Kerja", "Kami pulang sore.", "Kita mulih sore.", "Kula kondur sonten."],
            [1268, "Pulih", "Mari", "Waras", "Kesehatan", "Adik sudah pulih.", "Adhik wis mari.", "Adhi sampun waras."],
            [1269, "Pulpen warna", "Bolpen warna", "Bolpen warna", "Alat Tulis", "Guru memakai pulpen merah.", "Guru nganggo bolpen abang.", "Guru ngagem bolpen abrit."],
            [1270, "Punggung", "Geger", "Pengkeran", "Anggota Tubuh", "Punggung ayah terasa pegal.", "Gegere bapak pegel.", "Pengkeranipun rama kraos pegel."],
            [1271, "Puncak", "Pucak", "Pucak", "Alam", "Mereka mencapai puncak gunung.", "Dheweke tekan pucak gunung.", "Piyambakipun dumugi pucak redi."],
            [1272, "Pundi", null, "Pundi", "Kata Tanya", "Pundi rumah guru?", null, "Pundi griyanipun guru?"],
            [1273, "Pupuk", "Pupuk", "Pupuk", "Pertanian", "Petani menabur pupuk.", "Petani nyebar pupuk.", "Petani nyebar pupuk."],
            [1274, "Pura", "Pura", "Pura", "Agama", "Umat Hindu beribadah di pura.", "Umat Hindu sembahyang ing pura.", "Umat Hindu sembahyang wonten pura."],
            [1275, "Pusat", "Pusat", "Pusat", "Tempat", "Perpustakaan berada di pusat kota.", "Perpustakan ana tengah kutha.", "Perpustakan wonten pusat kitha."],
            [1276, "Putih", "Putih", "Putih", "Warna", "Baju itu berwarna putih.", "Klambi kuwi putih.", "Busana punika putih."],
            [1277, "Putra", "Anak lanang", "Putra", "Keluarga", "Putra itu rajin belajar.", "Anak lanang kuwi sregep sinau.", "Putra punika sregep sinau."],
            [1278, "Putri", "Anak wadon", "Putri", "Keluarga", "Putri itu pandai menari.", "Anak wadon kuwi pinter nari.", "Putri punika pinter njoged."],
            [1279, "Rabu", "Rabu", "Rabu", "Waktu", "Hari Rabu ada olahraga.", "Dina Rabu ana olahraga.", "Dinten Rabu wonten olahraga."],
            [1280, "Racun", "Racun", "Racun", "Kesehatan", "Racun harus disimpan aman.", "Racun kudu disimpen aman.", "Racun kedah dipunsimpen kanthi aman."],
            [1281, "Radang", "Radang", "Radang", "Penyakit", "Radang tenggorokan sudah sembuh.", "Radang tenggorokan wis mari.", "Radang tenggorokan sampun waras."],
            [1282, "Ragam", "Werna", "Jinis", "Kata Benda", "Ada beragam buah di pasar.", "Ana werna-werna woh ing pasar.", "Wonten maneka jinis woh wonten pasar."],
            [1283, "Rahang", "Rahang", "Rahang", "Anggota Tubuh", "Rahangnya terasa sakit.", "Rahange krasa lara.", "Rahangipun kraos lara."],
            [1284, "Rahasia", "Rahasia", "Rahasia", "Kata Benda", "Jangan membuka rahasia teman.", "Aja mbukak rahasia kanca.", "Sampun mbikak rahasia rencang."],
            [1285, "Rajin", "Sregep", "Sregep", "Kata Sifat", "Adik rajin belajar.", "Adhik sregep sinau.", "Adhi sregep sinau."],
            [1286, "Raja", "Raja", "Raja", "Sejarah", "Raja memimpin kerajaan.", "Raja mimpin kraton.", "Raja mimpin karaton."],
            [1287, "Rajin membaca", "Sregep maca", "Sregep maos", "Pendidikan", "Siswa rajin membaca buku.", "Murid sregep maca buku.", "Siswa sregep maos buku."],
            [1288, "Rambut", "Rambut", "Rikma", "Anggota Tubuh", "Rambut adik hitam.", "Rambute adhik ireng.", "Rikmanipun adhi cemeng."],
            [1289, "Rambu lalu lintas", "Rambu lalu lintas", "Rambu lalu lintas", "Transportasi", "Kita harus mematuhi rambu lalu lintas.", "Kita kudu manut rambu lalu lintas.", "Kita kedah manut rambu lalu lintas."],
            [1290, "Rame", "Ramai", "Rame", "Kata Sifat", "Pasar pagi sangat ramai.", "Pasar esuk rame.", "Pasar enjing rame."],
            [1291, "Rantai", "Rantai", "Rantai", "Peralatan", "Rantai sepeda putus.", "Rantai pit pedhot.", "Rantai pit pedhot."],
            [1292, "Rapat", "Rapat", "Rapat", "Kegiatan", "Guru mengikuti rapat.", "Guru melu rapat.", "Guru ndherek rapat."],
            [1293, "Rasa", "Rasa", "Rasa", "Kata Benda", "Rasa buah itu manis.", "Rasa woh kuwi legi.", "Raos woh punika manis."],
            [1294, "Rasa sakit", "Lara", "Gerah", "Kesehatan", "Rasa sakit mulai berkurang.", "Larane wiwit suda.", "Gerahipun wiwit kirang."],
            [1295, "Rasa syukur", "Syukur", "Sukur", "Perasaan", "Kita harus memiliki rasa syukur.", "Kita kudu nduweni rasa syukur.", "Kita kedah gadhah raos sukur."],
            [1296, "Rawat", "Ngrumat", "Ngrumat", "Kata Kerja", "Ibu merawat tanaman.", "Ibu ngrumat tanduran.", "Ibu ngrumat tetuwuhan."],
            [1297, "Rayap", "Rayap", "Rayap", "Hewan", "Rayap memakan kayu.", "Rayap mangan kayu.", "Rayap dhahar kajeng."],
            [1298, "Rayon", "Rayon", "Rayon", "Bahan", "Kain rayon terasa halus.", "Kain rayon alus.", "Kain rayon alus."],
            [1299, "Rebana", "Terbang/Rebana", "Rebana", "Musik", "Anak memainkan rebana.", "Bocah main rebana.", "Putra nabuh rebana."],
            [1300, "Rebus", "Nggodhog", "Nggodhog", "Kata Kerja", "Ibu merebus telur.", "Ibu nggodhog endhog.", "Ibu nggodhog tigan."],
        ];

        foreach ($dataset as $row) {
            $vocab = Vocabulary::updateOrCreate(
                ['id' => $row[0]],
                [
                    'indonesian_word' => $row[1],
                    'javanese_ngoko'  => $row[2],
                    'javanese_krama'  => $row[3],
                    'category'        => $row[4] ?? null,
                ]
            );

            if (!empty($row[5]) || !empty($row[6]) || !empty($row[7])) {
                VocabularyExample::updateOrCreate(
                    ['vocabulary_id' => $vocab->id],
                    [
                        'indonesian_sentence' => $row[5] ?? null,
                        'ngoko_sentence'      => $row[6] ?? null,
                        'krama_sentence'      => $row[7] ?? null,
                        'javanese_sentence'   => $row[6] ?? $row[7] ?? null,
                    ]
                );
            }
        }
    }
}
