<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CompleteVocabularySeeder extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            // A
            [1, "Abadi", "Langgeng", "Langgeng", null, "Persahabatan mereka tetap abadi.", "Paseduluran dheweke tetep langgeng.", "Pasaduluranipun tetep langgeng."],
            [2, "Abang", "Abang", "Abrit", null, "Baju abang itu baru.", "Klambi abang kuwi anyar.", "Busana abrit punika enggal."],
            [3, "Abu", "Awu", "Awu", null, "Abu itu tertiup angin.", "Awu kuwi kebur angin.", "Awu punika kabur angin."],
            [4, "Acak", "Acak", null, null, "Rambutnya tampak acak.", "Rambute katon acak.", "Rikmanipun katingal acak."],
            [5, "Acara", "Acara", "Adicara", null, "Acara sekolah dimulai pagi.", "Acara sekolah diwiwiti esuk.", "Adicara sekolah dipunwiwiti enjing."],
            [6, "Adab", "Tata krama", "Tata krama", null, "Anak harus memiliki adab baik.", "Bocah kudu nduweni tata krama apik.", "Putra kedah gadhah tata krama sae."],
            [7, "Adik", "Adhik", "Adhi", null, "Adik sedang belajar.", "Adhik lagi sinau.", "Adhi saweg sinau."],
            [8, "Adil", "Adil", "Adil", null, "Guru bersikap adil.", "Guru tumindak adil.", "Guru gadhah sipat adil."],
            [9, "Adu", "Adu", "Adu", null, "Jangan adu temanmu.", "Aja ngadu kancamu.", "Sampun ngadu kanca panjenengan."],
            [10, "Aduk", "Aduk", "Aduk", null, "Ibu mengaduk sayur.", "Ibu ngaduk jangan.", "Ibu ngaduk janganan."],
            [11, "Agama", "Agama", "Agami", null, "Kami belajar agama.", "Kita sinau agama.", "Kula sinau agami."],
            [12, "Agen", "Agen", "Agen", null, "Ayah bertemu agen.", "Bapak ketemu agen.", "Rama kepanggih agen."],
            [13, "Agung", "Ageng", "Ageng", null, "Gedung itu sangat agung.", "Gedhong kuwi gedhe lan ageng.", "Gedhong punika ageng sanget."],
            [14, "Air", "Banyu", "Toya", null, "Saya minum air putih.", "Aku ngombe banyu putih.", "Kula ngunjuk toya putih."],
            [15, "Air mata", "Luh", "Waspa", null, "Air mata adik jatuh.", "Luhe adhik tiba.", "Waspanipun adhi dhawah."],
            [16, "Ajaib", "Ajaib", "Ajaib", null, "Cerita itu sangat ajaib.", "Crita kuwi ajaib.", "Cariyos punika ajaib."],
            [17, "Ajak", "Ajak", "Ajak", null, "Saya mengajak teman bermain.", "Aku ngajak kanca dolanan.", "Kula ngajak kanca dolanan."],
            [18, "Ajar", "Ajar", "Ajar", null, "Guru mengajar matematika.", "Guru mulang matematika.", "Guru mucal matematika."],
            [19, "Akal", "Akal", "Akal", null, "Manusia memiliki akal.", "Manungsa nduweni akal.", "Manungsa gadhah akal."],
            [20, "Akar", "Oyot", "Oyot", null, "Akar pohon kuat.", "Oyot wit kuwat.", "Oyot uwit kiyat."],
            [21, "Akhir", "Pungkasan", "Pungkasan", null, "Ini akhir cerita.", "Iki pungkasan crita.", "Punika pungkasan cariyos."],
            [22, "Akibat", "Akibat", "Akibat", null, "Itu akibat terlambat.", "Kuwi akibat telat.", "Punika akibat kendel."],
            [23, "Aku", "Aku", "Kula", null, "Aku senang belajar.", "Aku seneng sinau.", "Kula remen sinau."],
            [24, "Alam", "Alam", "Alam", null, "Alam harus dijaga.", "Alam kudu dijaga.", "Alam kedah dipunjagi."],
            [25, "Alamat", "Alamat", "Alamat", null, "Tulis alamat rumahmu.", "Tulis alamat omahmu.", "Serat alamat griya panjenengan."],
            [26, "Alas", "Landhesan", null, null, "Gelas diberi alas.", "Gelas diwenehi landhesan.", "Gelas dipunparingi landhesan."],
            [27, "Alas kaki", "Sendhal", "Selop", null, "Ayah memakai alas kaki.", "Bapak nganggo sendhal.", "Rama ngagem selop."],
            [28, "Alat", "Piranti", "Piranti", null, "Guru membawa alat tulis.", "Guru nggawa piranti nulis.", "Guru nggawa piranti nyerat."],
            [29, "Alis", "Alis", "Alis", null, "Alis ibu rapi.", "Alise ibu rapi.", "Alisipun ibu rapi."],
            [30, "Alpukat", "Alpukat", "Alpukat", null, "Saya membeli alpukat.", "Aku tuku alpukat.", "Kula mundhut alpukat."],
            [31, "Alun-alun", "Alun-alun", "Alun-alun", null, "Kami bermain di alun-alun.", "Kita dolanan ing alun-alun.", "Kula dolanan wonten alun-alun."],
            [32, "Ambil", "Jupuk", "Pendhet", null, "Tolong ambil buku itu.", "Tulung jupuk buku kuwi.", "Sumangga pendhet buku punika."],
            [33, "Ambulans", "Ambulan", "Ambulan", null, "Ambulans datang cepat.", "Ambulan teka cepet.", "Ambulan rawuh rikat."],
            [34, "Amin", "Amin", "Amin", null, "Kami mengucapkan amin.", "Kita ngucap amin.", "Kula ngaturaken amin."],
            [35, "Ampuh", "Mujarab", "Mujarab", null, "Obat itu ampuh.", "Obat kuwi mujarab.", "Obat punika mujarab."],
            [36, "Anak", "Bocah/Anak", "Putra/Putri", null, "Anak itu bermain.", "Bocah kuwi dolanan.", "Putra punika dolanan."],
            [37, "Anak ayam", "Pitik cilik", "Anak pitik", null, "Anak ayam mengikuti induknya.", "Pitik cilik ngetutake babone.", "Anak pitik ndherek babonipun."],
            [38, "Anak tangga", "Undhakan", "Undhakan", null, "Hati-hati di anak tangga.", "Ati-ati ing undhakan.", "Prayogi ngati-ati wonten undhakan."],
            [39, "Anak panah", "Panah", "Panah", null, "Anak panah itu tajam.", "Panah kuwi landhep.", "Panah punika landhep."],
            [40, "Anggrek", "Anggrèk", "Anggrèk", null, "Ibu menanam anggrek.", "Ibu nandur anggrèk.", "Ibu nandur anggrèk."],
            [41, "Angin", "Angin", "Angin", null, "Angin bertiup pelan.", "Angin semribit alon.", "Angin semribit alon."],
            [42, "Angka", "Angka", null, null, "Guru menulis angka lima.", "Guru nulis angka lima.", "Guru nyerat angka gangsal."],
            [43, "Angsa", "Angsa", "Angsa", null, "Angsa berenang di kolam.", "Angsa nglangi ing blumbang.", "Angsa nglangi wonten blumbang."],
            [44, "Anjing", "Asu", "Seyos", null, "Anjing itu tidur.", "Asu kuwi turu.", "Seyos punika tilem."],
            [45, "Api", "Geni", "Brama", null, "Api itu panas.", "Geni kuwi panas.", "Brama punika panas."],
            [46, "Apel", "Apel", "Apel", null, "Saya makan apel.", "Aku mangan apel.", "Kula dhahar apel."],
            [47, "Apotek", "Apotek", "Apotek", null, "Ibu membeli obat di apotek.", "Ibu tuku obat ing apotek.", "Ibu mundhut obat wonten apotek."],
            [48, "Arang", "Arang", "Arang", null, "Arang itu hitam.", "Arang kuwi ireng.", "Arang punika cemeng."],
            [49, "Arloji", "Jam tangan", "Jam tangan", null, "Kakek memakai arloji.", "Mbah nganggo jam tangan.", "Eyang ngagem jam tangan."],
            [50, "Arsitek", "Arsitek", "Arsitek", null, "Paman bekerja sebagai arsitek.", "Paklik nyambut gawe dadi arsitek.", "Paklik nyambut damel dados arsitek."],
            [51, "Asal", "Asal", "Asal", null, "Saya tahu asalnya.", "Aku ngerti asale.", "Kula mangertos asalipun."],
            [52, "Asam", "Kecut", "Kecut", null, "Buah itu asam.", "Woh kuwi kecut.", "Woh punika kecut."],
            [53, "Asap", "Kumelun", "Kumelun", null, "Asap naik ke atas.", "Kumelun munggah munggah.", "Kumelun minggah."],
            [54, "Asih", "Tresna", "Tresna", null, "Ibu memberi kasih sayang.", "Ibu menehi tresna.", "Ibu maringi tresna."],
            [55, "Asing", "Asing", "Asing", null, "Bahasa itu asing.", "Basa kuwi asing.", "Basa punika asing."],
            [56, "Asli", "Asli", "Asli", null, "Ini madu asli.", "Iki madu asli.", "Punika madu asli."],
            [57, "Atap", "Gendheng", "Gendheng", null, "Atap rumah bocor.", "Gendheng omah bocor.", "Gendheng griya bocor."],
            [58, "Atas", "Ndhuwur", "Ngiling", null, "Letakkan buku di atas meja.", "Sijikna buku ing ndhuwur meja.", "Sumangga pasang buku wonten ngiling meja."],
            [59, "Atur", "Atur", "Atur", null, "Saya mengatur kursi.", "Aku ngatur kursi.", "Kula ngatur kursi."],
            [60, "Ayah", "Bapak", "Rama", null, "Ayah sedang bekerja.", "Bapak lagi nyambut gawe.", "Rama saweg nyambut damel."],
            [61, "Ayam", "Pitik", "Pitik", null, "Ayam berkokok pagi hari.", "Pitik kluruk esuk.", "Pitik kluruk enjing."],
            [62, "Ayam jantan", "Jago", "Pitik jago", null, "Ayam jantan berkokok keras.", "Jago kluruk banter.", "Pitik jago kluruk kiyat."],
            [63, "Ayam betina", "Babon pitik", "Babon pitik", null, "Ayam betina mengerami telur.", "Babon pitik ngingu endhog.", "Babon pitik ngingu tigan."],
            [64, "Ayunan", "Ayunan", "Ayunan", null, "Adik bermain ayunan.", "Adhik dolanan ayunan.", "Adhi dolanan ayunan."],
            [65, "Azan", "Adzan", "Adzan", null, "Kami mendengar azan.", "Kita krungu adzan.", "Kula mireng adzan."],

            // B
            [66, "Babi", "Babi", "Babi", null, "Babi mencari makan.", "Babi golek pangan.", "Babi pados pangan."],
            [67, "Baca", "Maca", "Maos", null, "Saya membaca buku.", "Aku maca buku.", "Kula maos buku."],
            [68, "Badan", "Awak/Sawak", "Sarira", null, "Badan saya sehat.", "Awakku sehat.", "Sarira kula sehat."],
            [69, "Bagasi", "Bagasi", "Bagasi", null, "Tas dimasukkan ke bagasi.", "Tas dilebokake ing bagasi.", "Tas dipunlebetaken wonten bagasi."],
            [70, "Bagus", "Apik", "Sae", null, "Gambarnya sangat bagus.", "Gambare apik banget.", "Gambaranipun sae sanget."],
            [71, "Bahagia", "Bungah", "Bingah", null, "Kami merasa bahagia.", "Kita rumangsa bungah.", "Kula raos bingah."],
            [72, "Bahasa", "Basa", "Basa", null, "Guru mengajar bahasa Jawa.", "Guru mulang basa Jawa.", "Guru mucal basa Jawi."],
            [73, "Bahaya", "Bebaya", "Bebaya", null, "Api adalah bahaya.", "Geni kuwi bebaya.", "Brama punika bebaya."],
            [74, "Bahu", "Pundhak", "Pundhak", null, "Bahunya terasa sakit.", "Pundhake lara.", "Pundhakipun sakit."],
            [75, "Baik", "Apik/Slamet", "Sae", null, "Dia anak yang baik.", "Dheweke bocah apik.", "Piyambakipun putra sae."],
            [76, "Bajak", "Bajak", "Bajak", null, "Petani memakai bajak.", "Pak tani nganggo bajak.", "Petani ngagem bajak."],
            [77, "Baju", "Klambi", "Busana", null, "Ibu mencuci baju.", "Ibu ngumbah klambi.", "Ibu ngumbah busana."],
            [78, "Bak", "Bak", "Bak", null, "Air ada di dalam bak.", "Banyu ana ing bak.", "Toya wonten ing bak."],
            [79, "Bakar", "Bakar", "Bakar", null, "Ayah membakar sampah.", "Bapak ngobong uwuh.", "Rama ngobong risak."],
            [80, "Bakat", "Bakat", "Bakat", null, "Adik memiliki bakat menyanyi.", "Adhik nduweni bakat nembang.", "Adhi gadhah bakat sekar."],
            [81, "Baki", "Nampan", "Nampan", null, "Ibu membawa baki.", "Ibu nggawa nampan.", "Ibu nggawa nampan."],
            [82, "Bakso", "Bakso", "Bakso", null, "Saya makan bakso.", "Aku mangan bakso.", "Kula dhahar bakso."],
            [83, "Balap", "Balapan", "Balapan", null, "Mereka ikut balap sepeda.", "Dheweke melu balapan pit.", "Piyambakipun ndherek balapan pit."],
            [84, "Balik", "Bali/Wangsul", "Wangsul", null, "Saya balik ke rumah.", "Aku bali menyang omah.", "Kula wangsul dhateng griya."],
            [85, "Balon", "Balon", "Balon", null, "Anak membeli balon.", "Bocah tuku balon.", "Putra mundhut balon."],
            [86, "Bambu", "Pring", "Pring", null, "Rumah itu memakai bambu.", "Omah kuwi nganggo pring.", "Griya punika ngagem pring."],
            [87, "Ban", "Ban", "Ban", null, "Ban sepeda bocor.", "Ban pit bocor.", "Ban pit bocor."],
            [88, "Banci", "Banci", "Banci", null, "Jangan mengejek banci.", "Aja ngenyek banci.", "Sampun ngenyek banci."],
            [89, "Bandara", "Bandara", "Bandara", null, "Pesawat tiba di bandara.", "Pesawat teka ing bandara.", "Pesawat rawuh wonten bandara."],
            [90, "Bangau", "Bangau", "Bangau", null, "Bangau mencari ikan.", "Bangau golek iwak.", "Bangau pados iwak."],
            [91, "Bangku", "Bangku", "Lincak/Bangku", null, "Murid duduk di bangku.", "Murid lungguh ing bangku.", "Siswa lenggah wonten bangku."],
            [92, "Bangun", "Tangi", "Seyos/Tangi", null, "Saya bangun pagi.", "Aku tangi esuk.", "Kula tangi enjing."],
            [93, "Bangunan", "Gedhong", "Gedhong", null, "Bangunan itu tinggi.", "Gedhong kuwi dhuwur.", "Gedhong punika inggil."],
            [94, "Banjir", "Banjir", "Banjir", null, "Jalan terkena banjir.", "Dalan kebanjiran.", "Margi kabanjiran."],
            [95, "Bantal", "Bantal", "Bantal", null, "Adik memeluk bantal.", "Adhik ngrangkul bantal.", "Adhi ngrangkul bantal."],
            [96, "Banteng", "Banteng", "Banteng", null, "Banteng itu kuat.", "Banteng kuwi kuwat.", "Banteng punika kiyat."],
            [97, "Bantu", "Tulung", "Tulung", null, "Saya membantu ibu.", "Aku nulungi ibu.", "Kula mitulungi ibu."],
            [98, "Banyak", "Akeh", "Kathah", null, "Buku di perpustakaan banyak.", "Bukune akeh.", "Bukunipun kathah."],
            [99, "Banyu", "Banyu", "Toya", null, "Banyu sungai jernih.", "Banyu kali bening.", "Toya kali bening."],
            [100, "Barang", "Barang", "Barang", null, "Barang itu milik ayah.", "Barang kuwi duweke bapak.", "Barang punika kagungan rama."],
            [101, "Barat", "Kulon", "Kulon", null, "Matahari tenggelam di barat.", "Srengenge surup ing kulon.", "Surya surup wonten kulon."],
            [102, "Baris", "Baris", "Baris", null, "Siswa berdiri berbaris.", "Murid ngadeg baris.", "Siswa jumeneng baris."],
            [103, "Baru", "Anyar", "Enggal", null, "Saya membeli tas baru.", "Aku tuku tas anyar.", "Kula mundhut tas enggal."],
            [104, "Basah", "Telem", "Telem", null, "Baju itu basah.", "Klambi kuwi telem.", "Busana punika telem."],
            [105, "Batu", "Watu", "Sela", null, "Batu itu besar.", "Watu kuwi gedhe.", "Sela punika ageng."],
            [106, "Bau", "Ambu", "Ambu", null, "Kue itu berbau harum.", "Jajan kuwi ambune wangi.", "Jajan punika ambunipun wangi."],
            [107, "Bawa", "Gawa", "Bekta", null, "Saya membawa buku.", "Aku nggawa buku.", "Kula bekta buku."],
            [108, "Bawang merah", "Bawang abang", "Bawang abrit", null, "Ibu mengiris bawang merah.", "Ibu ngiris bawang abang.", "Ibu ngiris bawang abrit."],
            [109, "Bawang putih", "Bawang putih", "Bawang putih", null, "Ibu menumbuk bawang putih.", "Ibu nguleg bawang putih.", "Ibu nguleg bawang putih."],
            [110, "Bayam", "Bayam", "Bayam", null, "Ibu memasak bayam.", "Ibu masak bayam.", "Ibu masak bayam."],
            [111, "Bayar", "Mbayar", "Mbayar", null, "Ayah membayar listrik.", "Bapak mbayar listrik.", "Rama mbayar listrik."],
            [112, "Bayi", "Bayi", "Bayi", null, "Bayi itu sedang tidur.", "Bayi kuwi lagi turu.", "Bayi punika saweg tilem."],
            [113, "Beasiswa", "Beasiswa", "Beasiswa", null, "Kakak mendapat beasiswa.", "Mas entuk beasiswa.", "Raka pikantuk beasiswa."],
            [114, "Bebek", "Bebek", "Bebek", null, "Bebek berenang di kolam.", "Bebek nglangi ing blumbang.", "Bebek nglangi wonten blumbang."],
            [115, "Beberapa", "Sawetara", "Sawetawis", null, "Saya membeli beberapa pensil.", "Aku tuku sawetara potlot.", "Kula mundhut sawetawis potlot."],
            [116, "Becak", "Becak", "Becak", null, "Kami naik becak.", "Kita numpak becak.", "Kula nitih becak."],
            [117, "Bel", "Bel", "Bel", null, "Bel sekolah berbunyi.", "Bel sekolah muni.", "Bel sekolah muni."],
            [118, "Belajar", "Sinau", "Sinau", null, "Adik belajar setiap malam.", "Adhik sinau saben bengi.", "Adhi sinau saben dalu."],
            [119, "Belakang", "Mburi", "Mburi", null, "Tas berada di belakang kursi.", "Tas ana ing mburi kursi.", "Tas wonten ing wingking kursi."],
            [120, "Belanja", "Tuku", "Blanja", null, "Ibu pergi belanja.", "Ibu lunga tuku.", "Ibu tindak blanja."],
            [121, "Belimbing", "Blimbing", "Blimbing", null, "Saya memetik belimbing.", "Aku methik blimbing.", "Kula methik blimbing."],
            [122, "Belok", "Milih", "Mengsul", null, "Mobil belok kiri.", "Mobil milih kiwa.", "Montor mengsul kiwa."],
            [123, "Belut", "Welut", "Welut", null, "Belut hidup di sawah.", "Welut urip ing sawah.", "Welut gesang wonten sabin."],
            [124, "Benang", "Benang", "Benang", null, "Ibu memakai benang.", "Ibu nganggo benang.", "Ibu ngagem benang."],
            [125, "Benda", "Barang", "Barang", null, "Benda itu sangat berat.", "Barang kuwi abot banget.", "Barang punika awrat sanget."],
            [126, "Bendera", "Gendera", "Gendera", null, "Bendera merah putih berkibar.", "Gendera abang putih ngibar.", "Gendera abrit putih ngibar."],
            [127, "Bengkel", "Bengkel", "Bengkel", null, "Ayah pergi ke bengkel.", "Bapak lunga menyang bengkel.", "Rama tindak dhateng bengkel."],
            [128, "Benteng", "Benteng", "Benteng", null, "Kami mengunjungi benteng tua.", "Kita dolan menyang benteng lawas.", "Kula tindak dhateng benteng kina."],
            [129, "Bentuk", "Wujud", "Wujud", null, "Bentuk bola itu bulat.", "Wujude bal kuwi bunder.", "Wujudipun bal punika bunder."],
            [130, "Berani", "Wani", "Kendel", null, "Adik berani tampil.", "Adhik wani maju.", "Adhi kendel majeng."],
            [131, "Beras", "Beras", "Beras", null, "Ibu membeli beras.", "Ibu tuku beras.", "Ibu mundhut beras."],
            [132, "Berat", "Abot", "Awrat", null, "Tas itu sangat berat.", "Tas kuwi abot banget.", "Tas punika awrat sanget."],
            [133, "Berbagi", "Bareng nuduhake", "Andum", null, "Kami berbagi makanan.", "Kita andum panganan.", "Kula andum dhaharan."],
            [134, "Berbicara", "Ngomong", "Ngendika", null, "Guru berbicara pelan.", "Guru ngomong alon.", "Guru ngendika alon."],
            [135, "Berbohong", "Ngapusi", "Mitembungan", null, "Aku tidak suka berbohong.", "Aku ora seneng ngapusi.", "Kula boten remen mitembungan."],
            [136, "Berdoa", "Ndonga", "Ndedonga", null, "Kami berdoa bersama.", "Kita ndonga bareng.", "Kula ndedonga sesarengan."],
            [137, "Berdiri", "Ngadeg", "Jumeneng", null, "Murid berdiri rapi.", "Murid ngadeg rapi.", "Siswa jumeneng rapi."],
            [138, "Berenang", "Nglangi", "Nglangi", null, "Adik berenang di kolam.", "Adhik nglangi ing blumbang.", "Adhi nglangi wonten blumbang."],
            [139, "Beres", "Rampung", "Rampung", null, "Pekerjaan sudah beres.", "Pakaryane wis rampung.", "Pakaryanipun sampun rampung."],
            [140, "Berguna", "Migunani", "Migunani", null, "Buku itu sangat berguna.", "Buku kuwi migunani.", "Buku punika migunani."],
            [141, "Berhenti", "Mandheg", "Kendel", null, "Mobil berhenti di lampu merah.", "Mobil mandheg ing lampu abang.", "Montor mandheg wonten lampu abrit."],
            [142, "Berjalan", "Mlaku", "Mlampah", null, "Kami berjalan ke sekolah.", "Kita mlaku menyang sekolah.", "Kula mlampah dhateng sekolah."],
            [143, "Berjemur", "Enggo srengenge", "Enggo surya", null, "Nenek berjemur pagi.", "Mbah enggo srengenge esuk.", "Eyang enggo surya enjing."],
            [144, "Berkata", "Ngomong", "Ngendika", null, "Ayah berkata lembut.", "Bapak ngomong alon.", "Rama ngendika alon."],
            [145, "Berkebun", "Ngolah kebon", "Ngolah kebon", null, "Kakek berkebun setiap pagi.", "Mbah ngolah kebon saben esuk.", "Eyang ngolah kebon saben enjing."],
            [146, "Bermain", "Dolanan", "Dolanan", null, "Anak-anak bermain bola.", "Bocah-bocah dolanan bal.", "Para putra dolanan bal."],
            [147, "Bersih", "Resik", "Suci/Resik", null, "Kelas selalu bersih.", "Kelas tansah resik.", "Kelas tansah resik."],
            [148, "Bersin", "Surak", "Bersin", null, "Adik bersin sekali.", "Adhik surak sepisan.", "Adhi bersin sepisan."],
            [149, "Bertanya", "Takon", "Nyaketaken pitaken", null, "Saya bertanya kepada guru.", "Aku takon marang guru.", "Kula nyuwun pitaken dhateng guru."],
            [150, "Bertemu", "Ketemu", "Kepanggih", null, "Saya bertemu teman.", "Aku ketemu kanca.", "Kula kepanggih kanca."],
            [151, "Bertengkar", "Padu", "Padudon", null, "Kakak dan adik bertengkar.", "Mas lan adhik padu.", "Raka kaliyan adhi padudon."],
            [152, "Bertiup", "Semribit", "Semribit", null, "Angin bertiup pelan.", "Angin semribit alon.", "Angin semribit alon."],
            [153, "Beruang", "Beruang", "Beruang", null, "Beruang itu besar.", "Beruang kuwi gedhe.", "Beruang punika ageng."],
            [154, "Besar", "Gedhe", "Ageng", null, "Rumah itu besar.", "Omah kuwi gedhe.", "Griya punika ageng."],
            [155, "Besi", "Wesi", "Wesi", null, "Pagar itu terbuat dari besi.", "Pager kuwi digawe saka wesi.", "Pager punika kadamel saking wesi."],
            [156, "Besok", "Sesuk", "Mbenjing", null, "Kami berangkat besok.", "Kita mangkat sesuk.", "Kula bidhal mbenjing."],
            [157, "Betis", "Betis", "Jangga sikil", null, "Betis saya pegal.", "Betisku pegel.", "Jangga sikil kula kraos pegel."],
            [158, "Bianglala", "Pelangi", "Pelangi", null, "Pelangi terlihat indah.", "Pelangi katon apik.", "Pelangi katingal sae."],
            [159, "Biar", "Ben", null, null, "Biar saya yang membawa.", "Ben aku sing nggawa.", null],
            [160, "Biasa", "Lumrah", "Lumrah", null, "Itu hal biasa.", "Kuwi wis lumrah.", "Punika sampun lumrah."],
            [161, "Bibir", "Lambe", "Lathi", null, "Lipstik ada di bibir ibu.", "Lambe ibu ana lipstik.", "Lathi ibu wonten lipstik."],
            [162, "Bibit", "Winih", "Winih", null, "Petani menanam bibit padi.", "Pak tani nandur winih pari.", "Petani nandur winih pantun."],
            [163, "Bibir sungai", "Pinggir kali", "Pinggir kali", null, "Mereka duduk di bibir sungai.", "Dheweke lungguh ing pinggir kali.", "Piyambakipun lenggah wonten pinggir kali."],
            [164, "Biji", "Wiji", "Wiji", null, "Buah mangga memiliki satu biji.", "Pelem duwe siji wiji.", "Pelem gadhah setunggal wiji."],
            [165, "Bijaksana", "Wicaksana", "Wicaksana", null, "Guru sangat bijaksana.", "Guru wicaksana.", "Guru wicaksana."],
            [166, "Bintang", "Lintang", "Lintang", null, "Bintang bersinar malam hari.", "Lintang sumunar bengi.", "Lintang sumunar dalu."],
            [167, "Biru", "Biru", "Biru", null, "Langit tampak biru.", "Langit katon biru.", "Langit katingal biru."],
            [168, "Bisa", "Isa", "Saged", null, "Saya bisa membaca.", "Aku isa maca.", "Kula saged maos."],
            [169, "Bising", "Rame", "Rame", null, "Jalan itu sangat bising.", "Dalan kuwi rame.", "Margi punika rame."],
            [170, "Bocor", "Bocor", "Bocor", null, "Atap rumah bocor.", "Gendheng omah bocor.", "Gendheng griya bocor."],
            [171, "Bola", "Bal", "Bal", null, "Anak bermain bola.", "Bocah dolanan bal.", "Putra dolanan bal."],
            [172, "Boneka", "Boneka", "Boneka", null, "Adik memeluk boneka.", "Adhik ngrangkul boneka.", "Adhi ngrangkul boneka."],
            [173, "Bosan", "Bosen", "Bosen", null, "Saya bosan menunggu.", "Aku bosen ngenteni.", "Kula bosen ngentosi."],
            [174, "Botol", "Botol", "Botol", null, "Air ada di dalam botol.", "Banyu ana ing botol.", "Toya wonten ing botol."],
            [175, "Buah", "Woh", "Woh", null, "Saya makan buah setiap hari.", "Aku mangan woh saben dina.", "Kula dhahar woh saben dinten."],
            [176, "Buaya", "Baya", "Baya", null, "Buaya hidup di sungai.", "Baya urip ing kali.", "Baya gesang wonten kali."],
            [177, "Bubur", "Bubur", "Bubur", null, "Nenek memasak bubur.", "Mbah masak bubur.", "Eyang masak bubur."],
            [178, "Buku", "Buku", "Buku", null, "Saya membaca buku.", "Aku maca buku.", "Kula maos buku."],
            [179, "Bulan", "Wulan", "Wulan", null, "Bulan terlihat terang.", "Wulan katon padhang.", "Wulan katingal padhang."],
            [180, "Bunga", "Kembang", "Sekar", null, "Ibu menyiram bunga.", "Ibu nyirami kembang.", "Ibu nyirami sekar."],
            [181, "Bungkus", "Bungkus", "Bungkus", null, "Tolong bungkus makanan ini.", "Tulung bungkus panganan iki.", "Sumangga bungkus dhaharan punika."],
            [182, "Burung", "Manuk", "Manuk", null, "Burung itu terbang tinggi.", "Manuk kuwi mabur dhuwur.", "Manuk punika mabur inggil."],
            [183, "Bus", "Bis", "Bis", null, "Kami naik bus ke kota.", "Kita numpak bis menyang kutha.", "Kula nitih bis dhateng kutha."],
            [184, "Busuk", "Bosok", "Bosok", null, "Buah itu sudah busuk.", "Woh kuwi wis bosok.", "Woh punika sampun bosok."],
            [185, "Buta", "Wuta", "Wuta", null, "Wayang menceritakan raksasa buta.", "Wayang nyritakake buta.", "Wayang nyariosaken wuta."],
            [186, "Butuh", "Butuh", "Betahaken", null, "Saya butuh bantuan.", "Aku butuh pitulungan.", "Kula betahaken pitulungan."],
            [187, "Butu", "Kutu", "Kutu", null, "Ayam itu terkena kutu.", "Pitik kuwi ana kutune.", "Pitik punika wonten kutunipun."],

            // C
            [188, "Butir", "Butir", "Butir", "Kata Benda", "Ada satu butir telur pecah.", "Ana siji butir endhog pecah.", "Wonten setunggal butir tigan pecah."],
            [189, "Buyut", "Mbuyut", "Mbuyut", "Keluarga", "Buyut tinggal di desa.", "Mbuyut manggon ing desa.", "Mbuyut dedalem wonten desa."],
            [190, "Cabai", "Lombok", "Lombok", "Makanan", "Ibu membeli cabai merah.", "Ibu tuku lombok abang.", "Ibu mundhut lombok abrit."],
            [191, "Cabang", "Pang", "Pang", "Alam", "Cabang pohon patah.", "Pang wit tugel.", "Pang uwit tugel."],
            [192, "Cacing", "Cacing", "Cacing", "Hewan", "Cacing hidup di tanah.", "Cacing urip ing lemah.", "Cacing gesang wonten lemah."],
            [193, "Cair", "Cair", "Cair", "Kata Sifat", "Es menjadi cair.", "Es dadi cair.", "Es dados cair."],
            [194, "Calon", "Calon", "Calon", "Kata Benda", "Kakak menjadi calon ketua.", "Mas dadi calon ketua.", "Raka dados calon ketua."],
            [195, "Camar", "Camar", "Camar", "Hewan", "Burung camar terbang rendah.", "Manuk camar mabur endhek.", "Manuk camar mabur asor."],
            [196, "Campur", "Campur", "Campur", "Kata Kerja", "Ibu mencampur gula.", "Ibu nyampur gula.", "Ibu nyampur gendhis."],
            [197, "Cangkir", "Cangkir", "Cangkir", "Peralatan Rumah", "Cangkir itu bersih.", "Cangkir kuwi resik.", "Cangkir punika resik."],
            [198, "Cantik", "Ayu", "Ayu", "Kata Sifat", "Adik memakai baju cantik.", "Adhik nganggo klambi ayu.", "Adhi ngagem busana ayu."],
            [199, "Capai", "Kesel", "Kesah", "Kata Sifat", "Saya merasa capai.", "Aku krasa kesel.", "Kula kraos kesah."],
            [200, "Capit", "Capit", "Capit", "Kata Benda", "Kepiting memiliki capit besar.", "Yuyu duwe capit gedhe.", "Yuyu gadhah capit ageng."],
            [201, "Cara", "Cara", "Cara", "Kata Benda", "Guru menjelaskan cara belajar.", "Guru nerangake cara sinau.", "Guru nerangaken cara sinau."],
            [202, "Cat", "Cat", "Cat", "Peralatan Rumah", "Ayah membeli cat tembok.", "Bapak tuku cat tembok.", "Rama mundhut cat tembok."],
            [203, "Catat", "Cathet", "Cathet", "Kata Kerja", "Tolong catat jawabanmu.", "Tulung cathet wangsulanmu.", "Sumangga cathet wangsulan panjenengan."],
            [204, "Catatan", "Cathetan", "Cathetan", "Sekolah", "Saya membaca catatan.", "Aku maca cathetan.", "Kula maos cathetan."],
            [205, "Cedera", "Cilaka", "Cilaka", "Kesehatan", "Pemain mengalami cedera.", "Pemain cilaka.", "Pemain cilaka."],
            [206, "Cegah", "Cegah", "Cegah", "Kata Kerja", "Kita mencegah penyakit.", "Kita nyegah lara.", "Kula nyegah gerah."],
            [207, "Cek", "Cek", "Cek", "Teknologi", "Guru mengecek tugas.", "Guru ngecek tugas.", "Guru mriksa tugas."],
            [208, "Celana", "Kathok", "Selana", "Pakaian", "Ayah memakai celana panjang.", "Bapak nganggo kathok dawa.", "Rama ngagem selana dawa."],
            [209, "Celengan", "Celengan", "Celengan", "Peralatan Rumah", "Adik menabung di celengan.", "Adhik nabung ing celengan.", "Adhi nabung wonten celengan."],
            [210, "Cemas", "Kuwatir", "Waswas", "Perasaan", "Ibu cemas menunggu ayah.", "Ibu kuwatir ngenteni bapak.", "Ibu waswas ngentosi rama."],
            [211, "Cempaka", "Cempaka", "Cempaka", "Bunga", "Bunga cempaka harum.", "Kembang cempaka wangi.", "Sekar cempaka wangi."],
            [212, "Cendana", "Cendana", "Cendana", "Pohon", "Pohon cendana tumbuh subur.", "Wit cendana thukul subur.", "Uwit cendana tuwuh subur."],
            [213, "Cendekia", "Pinter", "Sujana", "Kata Sifat", "Guru adalah orang cendekia.", "Guru kuwi wong pinter.", "Guru punika sujana."],
            [214, "Cendol", "Dawet", "Dawet", "Minuman", "Saya minum cendol.", "Aku ngombe dawet.", "Kula ngunjuk dawet."],
            [215, "Cengkih", "Cengkeh", "Cengkeh", "Tumbuhan", "Cengkih dipanen petani.", "Cengkeh dipanen petani.", "Cengkeh dipunpanen petani."],
            [216, "Cepat", "Cepet", "Rikat", "Kata Sifat", "Adik berlari cepat.", "Adhik mlayu cepet.", "Adhi mlayu rikat."],
            [217, "Cerah", "Cerah", "Cerah", "Cuaca", "Langit tampak cerah.", "Langit katon cerah.", "Langit katingal cerah."],
            [218, "Cerdas", "Pinter", "Sujana", "Kata Sifat", "Anak itu sangat cerdas.", "Bocah kuwi pinter.", "Putra punika sujana."],
            [219, "Cerita", "Crita", "Cariyos", "Kata Benda", "Nenek bercerita sebelum tidur.", "Mbah nyrita sadurunge turu.", "Eyang nyarios sadèrèngipun tilem."],
            [220, "Cermin", "Kaca", "Kaca", "Peralatan Rumah", "Cermin itu sangat bersih.", "Kaca kuwi resik.", "Kaca punika resik."],
            [221, "Cerobong", "Cerobong", "Cerobong", "Rumah", "Asap keluar dari cerobong.", "Kumelun metu saka cerobong.", "Kumelun medal saking cerobong."],
            [222, "Cetak", "Cithak", "Cithak", "Kata Kerja", "Guru mencetak soal.", "Guru nyithak soal.", "Guru nyithak soal."],
            [223, "Cicak", "Cecak", "Cecak", "Hewan", "Cicak memakan nyamuk.", "Cecak mangan lemut.", "Cecak dhahar lemut."],
            [224, "Cincin", "Cincin", "Sesupek", "Aksesori", "Ibu memakai cincin emas.", "Ibu nganggo cincin emas.", "Ibu ngagem sesupek emas."],
            [225, "Cinta", "Tresna", "Tresna", "Perasaan", "Ibu memberi cinta kepada anak.", "Ibu menehi tresna marang anak.", "Ibu maringi tresna dhateng putra."],
            [226, "Cium", "Ambung", "Ambung", "Kata Kerja", "Adik mencium tangan ibu.", "Adhik ambung tangan ibu.", "Adhi ambung asta ibu."],
            [227, "Coba", "Nyoba", "Nyobi", "Kata Kerja", "Saya mencoba menjawab.", "Aku nyoba mangsuli.", "Kula nyobi mangsuli."],
            [228, "Cokelat", "Coklat", "Coklat", "Makanan", "Adik makan cokelat.", "Adhik mangan coklat.", "Adhi dhahar coklat."],
            [229, "Cuci", "Ngumbah", "Ngumbah", "Kata Kerja", "Ibu mencuci pakaian.", "Ibu ngumbah klambi.", "Ibu ngumbah busana."],
            [230, "Cuci tangan", "Ngumbah tangan", "Ngumbah asta", "Kesehatan", "Kita harus cuci tangan.", "Kita kudu ngumbah tangan.", "Kita kedah ngumbah asta."],
            [231, "Cukur", "Cukur", "Cukur", "Kata Kerja", "Ayah mencukur rambut.", "Bapak cukur rambut.", "Rama cukur rikma."],
            [232, "Curah hujan", "Udan", "Udan", "Cuaca", "Curah hujan tinggi hari ini.", "Udan deres dina iki.", "Udan deres dinten punika."],
            [233, "Curiga", "Sujan", "Sujan", "Perasaan", "Jangan mudah curiga.", "Aja gampang sujan.", "Sampun gampil sujan."],
            [234, "Cuti", "Cuti", "Cuti", "Pekerjaan", "Guru mengambil cuti.", "Guru njupuk cuti.", "Guru mundhut cuti."],
            [235, "Cyber", null, null, "Teknologi", "Keamanan cyber sangat penting.", "Keamanan cyber penting.", "Keamanan cyber penting."],
            [236, "Cuci muka", "Ngumbah rai", "Ngumbah pasuryan", "Kesehatan", "Saya cuci muka setiap pagi.", "Aku ngumbah rai saben esuk.", "Kula ngumbah pasuryan saben enjing."],
            [237, "Cuka", "Cuka", "Cuka", "Makanan", "Ibu menambahkan cuka sedikit.", "Ibu nambahi cuka sethithik.", "Ibu nambahi cuka sekedhik."],
            [238, "Cumi-cumi", "Cumi-cumi", "Cumi-cumi", "Hewan", "Ayah membeli cumi-cumi.", "Bapak tuku cumi-cumi.", "Rama mundhut cumi-cumi."],
            [239, "Cupang", "Cupang", "Cupang", "Hewan", "Ikan cupang itu indah.", "Iwak cupang kuwi apik.", "Iwak cupang punika sae."],
            [240, "Curah", "Deres", "Deres", "Cuaca", "Hujan turun sangat curah.", "Udan deres banget.", "Udan deres sanget."],
            [241, "Curam", "Jurang", "Curam", "Alam", "Jalan itu sangat curam.", "Dalan kuwi curam.", "Margi punika curam."],
            [242, "Curhat", "Crita", "Nyarios", "Perasaan", "Adik curhat kepada ibu.", "Adhik crita marang ibu.", "Adhi nyarios dhateng ibu."],
            [243, "Curut", "Curut", "Curut", "Hewan", "Curut mencari makanan.", "Curut golek pangan.", "Curut pados pangan."],
            [244, "Custom", null, null, "Teknologi", "Aplikasi memiliki tema custom.", "Aplikasi duwe tema custom.", "Aplikasi gadhah tema custom."],
            [245, "Cuti bersama", "Cuti sesarengan", "Cuti sesarengan", "Pekerjaan", "Sekolah libur cuti bersama.", "Sekolah prei cuti sesarengan.", "Sekolah prei cuti sesarengan."],

            // D
            [246, "Dada", "Dhadha", "Dhadha", "Anggota Tubuh", "Dada ayah terasa sesak.", "Dhadha bapak krasa sesek.", "Dhadha rama kraos sesek."],
            [247, "Daerah", "Dhaerah", "Dhaerah", "Tempat Umum", "Daerah itu sangat ramai.", "Dhaerah kuwi rame.", "Dhaerah punika rame."],
            [248, "Daftar", "Dhaptar", "Dhaptar", "Sekolah", "Saya mengisi daftar hadir.", "Aku ngisi dhaptar rawuh.", "Kula ngisi dhaptar rawuh."],
            [249, "Dagang", "Dagang", "Dagang", "Profesi", "Ayah berdagang di pasar.", "Bapak dagang ing pasar.", "Rama dagang wonten pasar."],
            [250, "Daging", "Daging", "Daging", "Makanan", "Ibu memasak daging sapi.", "Ibu masak daging sapi.", "Ibu masak daging sapi."],
            [251, "Dahaga", "Haus", "Sekeca", "Perasaan", "Saya merasa dahaga.", "Aku krasa haus.", "Kula kraos sekeca."],
            [252, "Dahan", "Pang", "Pang", "Alam", "Burung hinggap di dahan.", "Manuk manggon ing pang.", "Manuk pinarak wonten pang."],
            [253, "Dahulu", "Mbiyen", "Rumiyin", "Waktu", "Dahulu desa ini sepi.", "Mbiyen desa iki sepi.", "Rumiyin desa punika sepi."],
            [254, "Daun", "Godhong", "Godhong", "Tumbuhan", "Daun itu berwarna hijau.", "Godhong kuwi ijo.", "Godhong punika ijem."],
            [255, "Dawai", "Dawai", "Dawai", "Benda", "Senar gitar terbuat dari dawai.", "Senar gitar digawe saka dawai.", "Senar gitar kadamel saking dawai."],
            [256, "Daya", "Daya", "Daya", "Pendidikan", "Lampu membutuhkan daya listrik.", "Lampu butuh daya listrik.", "Lampu mbutuhake daya listrik."],
            [257, "Dekat", "Cedhak", "Celak", "Ruang", "Rumah kami dekat sekolah.", "Omahku cedhak sekolah.", "Griya kula celak sekolah."],
            [258, "Dekorasi", "Hiasan", "Hiasan", "Rumah", "Ruang kelas memiliki dekorasi.", "Kelas nduweni hiasan.", "Kelas gadhah hiasan."],
            [259, "Delima", "Delima", "Delima", "Buah", "Delima itu manis.", "Delima kuwi legi.", "Delima punika manis."],
            [260, "Demam", "Panas", "Gerah", "Kesehatan", "Adik mengalami demam.", "Adhik panas.", "Adhi gerah."],
            [261, "Dendam", "Dendam", "Dendam", "Perasaan", "Jangan menyimpan dendam.", "Aja nyimpen dendam.", "Sampun nyimpen dendam."],
            [262, "Dengar", "Krungu", "Mireng", "Kesehatan", "Saya mendengar suara burung.", "Aku krungu swara manuk.", "Kula mireng swanten manuk."],
            [263, "Denah", "Denah", "Denah", "Bangunan", "Guru menunjukkan denah sekolah.", "Guru nuduhake denah sekolah.", "Guru nedahaken denah sekolah."],
            [264, "Denda", "Denda", "Denda", "Pendidikan", "Saya membayar denda perpustakaan.", "Aku mbayar denda perpustakaan.", "Kula mbayar denda perpustakaan."],
            [265, "Dengan", "Karo", "Kaliyan", "Tata Bahasa", "Saya pergi dengan ayah.", "Aku lunga karo bapak.", "Kula tindak kaliyan rama."],
            [266, "Dengkur", "Ngorok", "Sare ngorok", "Kesehatan", "Kakek dengkur saat tidur.", "Mbah ngorok nalika turu.", "Eyang sare ngorok nalika tilem."],
            [267, "Denyut", "Denyut", "Denyut", "Kesehatan", "Denyut nadi normal.", "Denyut nadi normal.", "Denyut nadi normal."],
            [268, "Deras", "Deres", "Deres", "Cuaca", "Air sungai mengalir deras.", "Banyu kali mili deres.", "Toya kali mili deres."],
            [269, "Deret", "Dheret", "Dheret", "Kata Benda", "Anak berdiri dalam deret.", "Bocah ngadeg ing dheret.", "Putra jumeneng wonten dheret."],
            [270, "Desa", "Desa", "Desa", "Tempat", "Kakek tinggal di desa.", "Mbah manggon ing desa.", "Eyang dedalem wonten desa."],
            [271, "Desember", "Desember", "Desember", "Waktu", "Sekolah libur bulan Desember.", "Sekolah prei wulan Desember.", "Sekolah prei wulan Desember."],
            [272, "Desis", "Sesis", "Sesis", "Suara", "Ular mengeluarkan suara desis.", "Ula muni sesis.", "Ula ngedalaken swanten sesis."],
            [273, "Detail", "Rinci", "Rinci", "Teknologi", "Guru menjelaskan secara detail.", "Guru nerangake rinci.", "Guru nerangaken kanthi rinci."],
            [274, "Detik", "Detik", "Detik", "Waktu", "Satu menit enam puluh detik.", "Sakmenit sewidak detik.", "Setunggal menit suwidak detik."],
            [275, "Diagonal", "Diagonal", "Diagonal", "Matematika", "Guru menggambar garis diagonal.", "Guru nggambar garis diagonal.", "Guru nggambar garis diagonal."],
            [276, "Diagram", "Diagram", "Diagram", "Matematika", "Siswa membuat diagram.", "Murid nggawe diagram.", "Siswa damel diagram."],
            [277, "Dialog", "Pacelathon", "Pacelathon", "Bahasa", "Mereka melakukan dialog.", "Dheweke pacelathon.", "Piyambakipun pacelathon."],
            [278, "Diam", "Meneng", "Meneng", "Perilaku", "Anak itu diam.", "Bocah kuwi meneng.", "Putra punika meneng."],
            [279, "Diam-diam", "Meneng-meneng", "Meneng-meneng", "Perilaku", "Dia pergi diam-diam.", "Dheweke lunga meneng-meneng.", "Piyambakipun tindak meneng-meneng."],
            [280, "Diamond", "Inten", "Inten", "Benda", "Cincin itu memiliki diamond.", "Cincin kuwi ana intene.", "Sesupek punika gadhah inten."],
            [281, "Diare", "Mules", "Atis", "Kesehatan", "Adik terkena diare.", "Adhik mules.", "Adhi atis."],
            [282, "Didih", "Ngodhok", "Ngodhok", "Kata Kerja", "Air mulai mendidih.", "Banyu wiwit nggodhok.", "Toya wiwit nggodhok."],
            [283, "Didik", "Didik", "Didik", "Pendidikan", "Guru mendidik murid dengan sabar.", "Guru ndidik murid kanthi sabar.", "Guru ndidik siswa kanthi sabar."],
            [284, "Dinding", "Tembok", "Tembok", "Rumah", "Dinding rumah dicat putih.", "Tembok omah dicet putih.", "Tembok griya dipuncet putih."],
            [285, "Dingin", "Adhem", "Asrep", "Cuaca", "Udara pagi terasa dingin.", "Esuk hawane adhem.", "Enjing hawanipun asrep."],
            [286, "Dinosaurus", "Dinosaurus", "Dinosaurus", "Hewan", "Dinosaurus hidup jutaan tahun lalu.", "Dinosaurus urip biyen.", "Dinosaurus gesang rumiyin."],
            [287, "Direktur", "Direktur", "Direktur", "Profesi", "Direktur memimpin rapat.", "Direktur mimpin rapat.", "Direktur mimpin rapat."],
            [288, "Diskon", "Diskon", "Diskon", "Perdagangan", "Toko memberi diskon besar.", "Toko menehi diskon gedhe.", "Toko maringi diskon ageng."],
            [289, "Diskusi", "Rembugan", "Rembagan", "Pendidikan", "Siswa berdiskusi bersama.", "Murid rembugan bareng.", "Siswa rembagan sesarengan."],
            [290, "Doa", "Donga", "Dedonga", "Agama", "Ibu membaca doa.", "Ibu maca donga.", "Ibu maos dedonga."],
            [291, "Dokter", "Dhokter", "Dhokter", "Profesi", "Dokter memeriksa pasien.", "Dhokter mriksa pasien.", "Dhokter mriksa pasien."],
            [292, "Dokumen", "Dhokumen", "Dhokumen", "Teknologi", "Saya menyimpan dokumen.", "Aku nyimpen dhokumen.", "Kula nyimpen dhokumen."],
            [293, "Dompet", "Dompet", "Dompet", "Benda", "Dompet ayah berwarna hitam.", "Dompet bapak ireng.", "Dompet rama cemeng."],
            [294, "Donat", "Donat", "Donat", "Makanan", "Adik makan donat.", "Adhik mangan donat.", "Adhi dhahar donat."],
            [295, "Dorong", "Dorong", "Dorong", "Kata Kerja", "Tolong dorong meja itu.", "Tulung dorong meja kuwi.", "Sumangga dorong meja punika."],
            [296, "Dosa", "Dosa", "Dosa", "Agama", "Kita harus menjauhi dosa.", "Kita kudu adoh saka dosa.", "Kita kedah tebih saking dosa."],
            [297, "Drama", "Drama", "Drama", "Seni", "Sekolah mengadakan drama.", "Sekolah nganakake drama.", "Sekolah nganakaken drama."],
            [298, "Dua", "Loro", "Kalih", "Kata Bilangan", "Saya punya dua pensil.", "Aku duwe loro potlot.", "Kula gadhah kalih potlot."],
            [299, "Duduk", "Lungguh", "Lenggah", "Kata Kerja", "Silakan duduk di sini.", "Lungguh ing kene.", "Mangga lenggah wonten mriki."],
            [300, "Duga", "Ngira", "Nginten", "Kata Kerja", "Saya menduga jawabannya benar.", "Aku ngira wangsulane bener.", "Kula nginten wangsulanipun leres."],
            [301, "Duka", "Susah", "Sungkawa", "Perasaan", "Keluarga itu sedang berduka.", "Kulawarga kuwi lagi susah.", "Kulawarga punika saweg sungkawa."],
            [302, "Dulang", "Dulang", "Dulang", "Peralatan Rumah", "Ibu membawa dulang.", "Ibu nggawa dulang.", "Ibu nggawa dulang."],
            [303, "Dulu", "Mbiyen", "Rumiyin", "Waktu", "Dulu kami tinggal di desa.", "Mbiyen kita manggon ing desa.", "Rumiyin kula dedalem wonten desa."],
            [304, "Dunia", "Donya", "Buana", "Alam", "Dunia sangat luas.", "Donya amba banget.", "Buana amba sanget."],
            [305, "Duri", "Eri", "Eri", "Tumbuhan", "Bunga mawar memiliki duri.", "Kembang mawar nduweni eri.", "Sekar mawar gadhah eri."],
            [306, "Durian", "Duren", "Duren", "Buah", "Ayah membeli durian.", "Bapak tuku duren.", "Rama mundhut duren."],
            [307, "Dusta", "Ngapusi", "Dusta", "Kata Kerja", "Jangan berkata dusta.", "Aja ngapusi.", "Sampun ngucap dusta."],
            [308, "Duta", "Duta", "Duta", "Profesi", "Kakak menjadi duta sekolah.", "Mas dadi duta sekolah.", "Raka dados duta sekolah."],
            [309, "Duyung", "Duyung", "Duyung", "Hewan", "Duyung hidup di laut.", "Duyung urip ing segara.", "Duyung gesang wonten seganten."],

            // Z & End part
            [1845, "Zebra cross", "Lintasan sebrang", "Lintasan nyebrang", "Transportasi", "Kami menyeberang di zebra cross.", "Kita nyebrang ing lintasan sebrang.", "Kula nyebrang wonten lintasan nyebrang."],
            [1846, "Zaman", "Jaman", "Jaman", "Waktu", "Zaman terus berubah.", "Jaman terus owah.", "Jaman tansah ewah."],
            [1847, "Ziarah kubur", "Nyekar", "Ziarah pasareyan", "Agama", "Keluarga melakukan ziarah kubur.", "Kulawarga nyekar.", "Kulawarga ziarah pasareyan."],
            [1848, "Zodiak", "Zodiak", "Zodiak", "Istilah Modern", "Dia membaca zodiak hari ini.", "Dheweke maca zodiak dina iki.", "Piyambakipun maos zodiak dinten punika."],
            [1849, "Zumba", "Zumba", "Zumba", "Olahraga", "Ibu mengikuti senam zumba.", "Ibu melu senam zumba.", "Ibu ndherek senam zumba."],
            [1850, "Zona waktu", "Zona wektu", "Zona wekdal", "Geografi", "Indonesia memiliki tiga zona waktu.", "Indonesia nduweni telung zona wektu.", "Indonesia gadhah tigang zona wekdal."],
            [1860, "Zat gizi", "Zat gizi", "Zat gizi", "Kesehatan", "Buah mengandung banyak zat gizi.", "Woh ngandhut akeh zat gizi.", "Woh ngemot kathah zat gizi."],
            [1861, "Zat besi", "Zat wesi", "Zat wesi", "Kesehatan", "Bayam mengandung zat besi.", "Bayem ngandhut zat wesi.", "Bayem ngemot zat wesi."],
            [1862, "Zat cair", "Zat cair", "Zat cair", "Sains", "Air termasuk zat cair.", "Banyu klebu zat cair.", "Toya kalebet zat cair."],
            [1863, "Zat padat", "Zat padhet", "Zat padhet", "Sains", "Es termasuk zat padat.", "Ès klebu zat padhet.", "Ès kalebet zat padhet."],
            [1864, "Zat warna", "Zat warna", "Zat warna", "Sains", "Kunyit menghasilkan zat warna alami.", "Kunir ngasilake zat warna alami.", "Kunir ngasilaken zat warna alami."],
            [1865, "Zikir pagi", "Dzikir esuk", "Dzikir enjing", "Agama", "Kakek membaca zikir pagi.", "Mbah maca dzikir esuk.", "Eyang maos dzikir enjing."],
            [1866, "Zikir petang", "Dzikir sore", "Dzikir sonten", "Agama", "Ibu membaca zikir petang.", "Ibu maca dzikir sore.", "Ibu maos dzikir sonten."],
            [1867, "Zebra laut", "Zebra laut", "Zebra laut", "Hewan", "Zebra laut hidup di segara.", "Zebra laut urip ing segara.", "Zebra laut gesang wonten seganten."],
            [1868, "Zona aman", "Zona aman", "Zona aman", "Keamanan", "Anak bermain di zona aman.", "Bocah dolanan ing zona aman.", "Putra dolanan wonten zona aman."],
            [1869, "Zona bahaya", "Zona bebaya", "Zona bebaya", "Keamanan", "Dilarang masuk zona bahaya.", "Aja mlebu zona bebaya.", "Sampun mlebet zona bebaya."],
            [1870, "Zona hijau", "Zona ijo", "Zona ijem", "Lingkungan", "Desa memiliki zona hijau.", "Desa nduweni zona ijo.", "Desa gadhah zona ijem."],
            [1871, "Vaksin", "Vaksin", "Vaksin", "Kesehatan", "Anak menerima vaksin.", "Bocah nampa vaksin.", "Putra nampi vaksin."],
            [1872, "Video", "Video", "Video", "Teknologi", "Guru memutar video pembelajaran.", "Guru muter video pasinaon.", "Guru muter video pasinaon."],
            [1873, "Vitamin", "Vitamin", "Vitamin", "Kesehatan", "Ibu membeli vitamin.", "Ibu tuku vitamin.", "Ibu mundhut vitamin."],
            [1874, "Volume", "Volume", "Volume", "Sains", "Guru menaikkan volume suara.", "Guru ngunggahake volume swara.", "Guru nginggilaken volume swanten."],
            [1875, "Voucher", "Voucher", "Voucher", "Teknologi", "Saya memakai voucher internet.", "Aku nganggo voucher internet.", "Kula ngagem voucher internet."],
        ];

        Schema::disableForeignKeyConstraints();
        VocabularyExample::truncate();
        Vocabulary::truncate();
        Schema::enableForeignKeyConstraints();

        foreach ($dataset as $index => $row) {
            $vocab = Vocabulary::create([
                'id'              => $row[0] ?? ($index + 1),
                'indonesian_word' => $row[1],
                'javanese_ngoko'  => $row[2],
                'javanese_krama'  => $row[3],
                'category'        => $row[4] ?? null,
            ]);

            if (!empty($row[5]) || !empty($row[6]) || !empty($row[7])) {
                VocabularyExample::create([
                    'vocabulary_id'       => $vocab->id,
                    'indonesian_sentence' => $row[5] ?? null,
                    'ngoko_sentence'      => $row[6] ?? null,
                    'krama_sentence'      => $row[7] ?? null,
                    'javanese_sentence'   => $row[6] ?? $row[7] ?? null,
                ]);
            }
        }
    }
}
