<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MacapatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('macapat_details')->truncate();
        DB::table('macapat_categories')->truncate();
        Schema::enableForeignKeyConstraints();

        $categories = [
            [
                'id' => 1,
                'name' => 'Maskumambang',
                'guru_gatra' => 4,
                'guru_wilangan' => '12, 6, 8, 8',
                'guru_lagu' => 'i, a, i, a',
                'watak' => 'Prihatin, kesedihan, keprihatinan, dan suasana duka.',
                'description' => 'Maskumambang menggambarkan tahap awal kehidupan manusia dan sering digunakan untuk menyampaikan nasihat dalam suasana prihatin.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Mijil',
                'guru_gatra' => 6,
                'guru_wilangan' => '10, 6, 10, 10, 6, 6',
                'guru_lagu' => 'i, o, e, i, i, u',
                'watak' => 'Kasih sayang, nasihat, pengharapan, dan keterbukaan.',
                'description' => 'Mijil menggambarkan kelahiran atau awal kehidupan serta sering digunakan untuk menyampaikan nasihat dan tuntunan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Kinanthi',
                'guru_gatra' => 6,
                'guru_wilangan' => '8, 8, 8, 8, 8, 8',
                'guru_lagu' => 'u, i, a, i, a, i',
                'watak' => 'Kasih sayang, tuntunan, persahabatan, dan pendidikan.',
                'description' => 'Kinanthi menggambarkan tuntunan dan kasih sayang dalam kehidupan serta cocok untuk menyampaikan ajaran dan nasihat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Sinom',
                'guru_gatra' => 9,
                'guru_wilangan' => '8, 8, 8, 8, 7, 8, 7, 8, 12',
                'guru_lagu' => 'a, i, a, i, i, u, a, i, a',
                'watak' => 'Semangat muda, pendidikan, nasihat, dan kegembiraan.',
                'description' => 'Sinom menggambarkan masa muda yang penuh semangat dan sering digunakan untuk menyampaikan pendidikan serta nasihat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Asmaradana',
                'guru_gatra' => 7,
                'guru_wilangan' => '8, 8, 8, 8, 7, 8, 8',
                'guru_lagu' => 'i, a, é/o, a, a, u, a',
                'watak' => 'Cinta, kasih sayang, kerinduan, dan perasaan.',
                'description' => 'Asmaradana banyak digunakan untuk menggambarkan perasaan cinta, kasih sayang, kerinduan, dan pergulatan batin.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Gambuh',
                'guru_gatra' => 5,
                'guru_wilangan' => '7, 10, 12, 8, 8',
                'guru_lagu' => 'u, u, i, u, o',
                'watak' => 'Persahabatan, kecocokan, keselarasan, dan nasihat.',
                'description' => 'Gambuh menggambarkan hubungan yang telah menemukan kecocokan dan sering digunakan untuk menyampaikan nasihat kehidupan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Dhandhanggula',
                'guru_gatra' => 10,
                'guru_wilangan' => '10, 10, 8, 7, 9, 7, 6, 8, 12, 7',
                'guru_lagu' => 'i, a, é, u, i, a, u, a, i, a',
                'watak' => 'Kebahagiaan, keindahan, keharmonisan, dan keberhasilan.',
                'description' => 'Dhandhanggula menggambarkan kehidupan yang indah, bahagia, dan penuh harapan serta dapat digunakan untuk berbagai tujuan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Durma',
                'guru_gatra' => 7,
                'guru_wilangan' => '12, 7, 6, 7, 8, 5, 7',
                'guru_lagu' => 'a, i, a, a, i, a, i',
                'watak' => 'Tegas, keras, berani, semangat, dan nasihat.',
                'description' => 'Durma memiliki watak tegas dan keras serta sering digunakan untuk menyampaikan nasihat, keberanian, dan perjuangan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Pangkur',
                'guru_gatra' => 7,
                'guru_wilangan' => '8, 11, 8, 7, 12, 8, 8',
                'guru_lagu' => 'a, i, u, a, u, a, i',
                'watak' => 'Nasihat, pengendalian diri, keteguhan, dan menjauhi hawa nafsu.',
                'description' => 'Pangkur menggambarkan sikap manusia yang mampu mengendalikan hawa nafsu dan mengutamakan kehidupan yang baik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Pocung',
                'guru_gatra' => 4,
                'guru_wilangan' => '12, 6, 8, 12',
                'guru_lagu' => 'u, a, i, a',
                'watak' => 'Santai, humor, teka-teki, nasihat, dan renungan.',
                'description' => 'Pocung sering digunakan untuk menyampaikan nasihat dengan suasana ringan, humor, teka-teki, dan renungan tentang kehidupan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('macapat_categories')->insert($categories);

        $details = [
            [
                'id' => 1,
                'macapat_category_id' => 1,
                'verse' => "Wong urip kudu tansah eling\nMarang Gusti Kang Maha Kuwasa\nSupaya urip tentrem ing ati\nLan adoh saka dosa",
                'meaning' => 'Manusia hidup harus selalu ingat kepada Tuhan Yang Maha Kuasa agar hidup tenteram dan jauh dari dosa.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'macapat_category_id' => 1,
                'verse' => "Aja lali marang kabecikan\nIng saben lampah kita\nTansah eling marang Gusti\nSupaya tentrem ing manah",
                'meaning' => 'Jangan melupakan kebaikan dalam setiap langkah dan selalu ingat kepada Tuhan agar hati tenteram.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'macapat_category_id' => 1,
                'verse' => "Urip iku mung sawatara\nKudu tansah ngati-ati\nAja tumindak ala\nSupaya slamet ing donya",
                'meaning' => 'Hidup hanya sementara, sehingga harus selalu berhati-hati dan tidak berbuat buruk agar selamat di dunia.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'macapat_category_id' => 2,
                'verse' => "Wong urip kudu sregep sinau\nSupaya dadi pinter\nIlmu iku migunani\nTumrap urip saben dina\nAja gampang nyerah\nNgudi kawruh kanthi tekun",
                'meaning' => 'Manusia harus rajin belajar agar menjadi pintar. Ilmu bermanfaat dalam kehidupan sehari-hari. Jangan mudah menyerah dan tekun mencari ilmu.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'macapat_category_id' => 2,
                'verse' => "Bocah kudu sregep maca\nSupaya tambah pinter\nBuku akeh isine\nKanggo nambah kawruh kita\nSaben dina diwaca\nSupaya migunani",
                'meaning' => 'Anak harus rajin membaca agar semakin pintar. Buku berisi banyak pengetahuan yang berguna jika dibaca setiap hari.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'macapat_category_id' => 2,
                'verse' => "Guru menehi piwulang\nMarang para siswa\nKudu tansah dirungokake\nSupaya dadi pinter\nLan nduweni budi\nKanggo urip bebrayan",
                'meaning' => 'Guru memberikan pelajaran kepada siswa. Nasihat guru harus didengarkan agar menjadi pintar dan memiliki budi pekerti dalam kehidupan bermasyarakat.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'macapat_category_id' => 3,
                'verse' => "Padha sinau saben wektu\nNgudi ilmu kang migunani\nSupaya dadi wong utama\nNgajeni marang sesami\nTumindak becik saben dina\nDadi tuladha tumrap liyan",
                'meaning' => 'Rajinlah belajar setiap waktu dan mencari ilmu yang bermanfaat agar menjadi manusia utama, menghormati sesama, serta menjadi teladan bagi orang lain.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'macapat_category_id' => 3,
                'verse' => "Kudu ngajeni wong tuwa\nLan tresna marang sesami\nAja gawe susah liyan\nTansah tulung-tinulung\nUrip rukun bebarengan\nSupaya tentrem ing ati",
                'meaning' => 'Harus menghormati orang tua dan menyayangi sesama. Jangan menyusahkan orang lain dan selalu saling membantu agar hidup rukun dan tenteram.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'macapat_category_id' => 3,
                'verse' => "Para siswa padha sregep\nSinau kanthi ati suci\nAja seneng males-malesan\nTansah ngurmati guru\nSupaya dadi utama\nLan migunani tumrap bangsa",
                'meaning' => 'Para siswa hendaknya rajin belajar dengan sungguh-sungguh, tidak malas, dan selalu menghormati guru agar menjadi manusia utama yang berguna bagi bangsa.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'macapat_category_id' => 4,
                'verse' => "Para mudha padha sinau\nNgudi kawruh kang migunani\nTumrap urip ing tembe\nAja males lan kendho ati\nSregep maca saben dina\nSupaya tambah ilmu\nLan dadi wong utama\nNgajeni guru lan wong tuwi\nSupaya urip becik ing tembe",
                'meaning' => 'Para pemuda hendaknya rajin belajar dan mencari ilmu yang bermanfaat agar memiliki masa depan yang baik serta menjadi manusia utama yang menghormati guru dan orang tua.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'macapat_category_id' => 4,
                'verse' => "Sinau iku perlu banget\nKanggo nggayuh gegayuhan\nAja wedi marang kang angel\nAmarga kabeh bisa disinaoni\nYen tekun saben dina\nIlmu bakal tambah akeh\nLan ati dadi lega\nAmarga wis nduweni kawruh\nKanggo bekal ing tembe mburi",
                'meaning' => 'Belajar sangat penting untuk mencapai cita-cita. Jangan takut menghadapi kesulitan karena semuanya dapat dipelajari dengan ketekunan.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'macapat_category_id' => 4,
                'verse' => "Mudha kudu duwe cita\nLan sregep ngudi kawruh\nSupaya tekan gegayuhan\nAja mung ngenteni wektu\nKudu wani tumindak\nLan gelem sinau\nNgajeni wong tuwa\nSarta ngajeni guru\nSupaya dadi wong kang migunani",
                'meaning' => 'Pemuda harus memiliki cita-cita dan rajin mencari ilmu. Jangan hanya menunggu waktu, tetapi harus berani bertindak, belajar, serta menghormati orang tua dan guru.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'macapat_category_id' => 5,
                'verse' => "Rasa tresna tuwuh ing ati\nMarang wong kang ditresnani\nKatresnan kudu dijaga\nKanthi ati kang setya\nAja nganti gawe lara\nAmarga tresna iku suci\nYen tulus bakal mulya",
                'meaning' => 'Rasa cinta tumbuh di dalam hati kepada orang yang dicintai. Cinta harus dijaga dengan kesetiaan dan ketulusan karena cinta itu suci.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'macapat_category_id' => 5,
                'verse' => "Tresna marang wong tuwa\nAja nganti gawe susah\nTansah bekti saben dina\nKanthi ati kang tulus\nAmarga wong tuwa\nWis ngopeni kita\nSaka cilik nganti diwasa",
                'meaning' => 'Sayangilah orang tua dan jangan membuat mereka susah. Berbaktilah dengan tulus karena orang tua telah merawat kita sejak kecil hingga dewasa.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'macapat_category_id' => 5,
                'verse' => "Katresnan marang sesami\nKudu tansah dijaga\nAja gawe lara ati\nTansah jujur lan setya\nSupaya urip tentrem\nLan kebak kabegjan\nBebarengan saklawase",
                'meaning' => 'Kasih sayang kepada sesama harus dijaga. Jangan menyakiti hati, selalu jujur dan setia agar hidup tenteram dan penuh kebahagiaan.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'macapat_category_id' => 6,
                'verse' => "Yen kanca kudu rukun\nPadha tulung-tinulung saben wektu\nAja seneng gawe lara ati\nUrip kudu gotong royong\nSupaya tentrem uripe",
                'meaning' => 'Dalam berteman harus hidup rukun dan saling membantu. Jangan menyakiti hati orang lain dan biasakan bergotong royong agar hidup tenteram.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'macapat_category_id' => 6,
                'verse' => "Kanca becik kudu jujur\nAja seneng ngapusi kanca\nTansah tulung yen ana kang perlu\nRukun saben dina\nSupaya awet paseduluran",
                'meaning' => 'Teman yang baik harus jujur dan tidak suka berbohong. Saling membantu ketika diperlukan agar persaudaraan tetap terjaga.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'macapat_category_id' => 6,
                'verse' => "Urip bebarengan iku perlu\nKudu bisa ngajeni liyan\nAja mung mikir awak dhewe\nPadha kerja bebarengan\nSupaya kabeh seneng",
                'meaning' => 'Hidup bersama membutuhkan sikap saling menghormati. Jangan hanya memikirkan diri sendiri dan biasakan bekerja bersama agar semua merasa senang.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'macapat_category_id' => 7,
                'verse' => "Urip becik kudu migunani\nTumrap bangsa lan negara\nKanthi ati kang suci\nSregep makarya\nNgudi ilmu saben wengi\nLan tansah sabar\nIng saben laku\nNgajeni marang sapadha\nSupaya urip kebak kabegjan\nLan tentrem raharja",
                'meaning' => 'Hidup harus bermanfaat bagi bangsa dan negara dengan hati yang bersih, rajin bekerja, mencari ilmu, sabar, dan menghormati sesama agar hidup bahagia dan tenteram.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'macapat_category_id' => 7,
                'verse' => "Kabegjan ora mung bandha\nNanging uga ati kang tentrem\nUrip kudu prasaja\nAja seneng gumunggung\nTansah syukur saben dina\nLan eling Gusti\nSupaya ati ayem\nBisa nulungi sapadha\nUrip rukun kebak kabungahan\nLan adoh saka susah",
                'meaning' => 'Kebahagiaan bukan hanya harta, tetapi juga hati yang tenteram. Hidup harus sederhana, bersyukur, dan selalu ingat kepada Tuhan.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'macapat_category_id' => 7,
                'verse' => "Ilmu iku madhangi ati\nYen digunakake kanthi becik\nBakal dadi pepadhang\nTumrap urip saben dina\nSregep sinau terus\nAja kendho ngudi kawruh\nSupaya urip migunani\nTumrap kulawarga kita\nLan kanggo bangsa lan negara\nSarta nambah kabecikan",
                'meaning' => 'Ilmu menerangi hati jika digunakan dengan baik. Rajinlah belajar dan terus mencari pengetahuan agar bermanfaat bagi keluarga, bangsa, dan negara.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'macapat_category_id' => 8,
                'verse' => "Aja seneng tumindak ala\nMarang kanca kabeh\nElinga marang Gusti\nSupaya ora cidra\nTumindak becik saben dina\nKanthi ati resik\nUrip tentrem ing ati",
                'meaning' => 'Jangan suka berbuat buruk kepada teman. Ingatlah kepada Tuhan agar tidak berbuat curang, selalu berbuat baik, dan hidup tenteram.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'macapat_category_id' => 8,
                'verse' => "Yen weruh kanca kesusahan\nAja mung meneng wae\nEnggal paring pitulungan\nKanthi ati kang tulus\nAja njaluk piwales\nTulung iku utama\nLan becik tumrap liyan",
                'meaning' => 'Jika melihat teman kesusahan, jangan hanya diam. Segera berikan pertolongan dengan tulus tanpa mengharapkan balasan.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'macapat_category_id' => 8,
                'verse' => "Aja seneng gawe padu\nAmarga mung gawe susah\nRukun iku utama\nKudu bisa ngendhaleni ati\nYen ana masalah\nRembugan kanthi sabar\nSupaya ora ana padu",
                'meaning' => 'Jangan suka membuat pertengkaran karena hanya menimbulkan kesusahan. Kerukunan penting dan masalah sebaiknya diselesaikan dengan sabar melalui musyawarah.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'macapat_category_id' => 9,
                'verse' => "Wong urip kudu bisa ngempet hawa\nAja nuruti karep kang ora becik\nNgudi ilmu saben wektu\nSupaya dadi utama\nAja gampang nesu marang wong liya\nTansah sabar ing ati\nLan seneng nulungi",
                'meaning' => 'Manusia harus mampu mengendalikan hawa nafsu dan tidak mengikuti keinginan buruk. Hendaknya selalu sabar dan suka membantu.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'macapat_category_id' => 9,
                'verse' => "Mingkura saka tumindak ala\nAja nganti gawe susah liyan\nTansah eling marang Gusti\nLan ngedohi tumindak nistha\nUrip kudu nduweni tata\nSupaya tentrem ing ati\nLan migunani tumrap liyan",
                'meaning' => 'Jauhilah perbuatan buruk dan jangan menyusahkan orang lain. Selalu ingat kepada Tuhan dan menjauhi perbuatan tercela agar hidup tenteram dan bermanfaat.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'macapat_category_id' => 9,
                'verse' => "Kudu sabar nalika susah\nAja gampang nesu marang liyan\nTansah eling marang Gusti\nLan nglakoni kabecikan\nAja nuruti hawa nepsu\nSupaya urip raharja\nLan ati tansah resik",
                'meaning' => 'Harus sabar ketika menghadapi kesusahan dan tidak mudah marah kepada orang lain. Selalu ingat kepada Tuhan dan menjauhi hawa nafsu.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'macapat_category_id' => 10,
                'verse' => "Urip iki mung mampir ing donya\nAja lali\nNgudi becik saben dina\nAmarga urip bakal bali marang Gusti",
                'meaning' => 'Hidup di dunia hanya sementara. Manusia harus selalu berbuat baik karena pada akhirnya akan kembali kepada Tuhan.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'macapat_category_id' => 10,
                'verse' => "Ana bocah nggawa klasa\nLungguh ing ngisor wit\nKancane teka nggawa sega\nPadha mangan bebarengan",
                'meaning' => 'Ada seorang anak membawa tikar dan duduk di bawah pohon. Temannya datang membawa nasi lalu mereka makan bersama.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'macapat_category_id' => 10,
                'verse' => "Urip aja mung golek bandha\nNanging elinga\nKabecikan iku utama\nBakal dadi bekal nalika wis seda",
                'meaning' => 'Hidup jangan hanya mencari harta, tetapi ingatlah bahwa kebaikan adalah hal utama yang akan menjadi bekal setelah meninggal.',
                'audio_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('macapat_details')->insert($details);
    }
}
