<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyExample;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserAddedVocabularySeeder extends Seeder
{
    public function run(): void
    {
        DB::disableQueryLog();

        $dataset = [
            // Batch Babi - Benang
            ["Babi", "Babi", "Babi", "Hewan", "Babi mencari makan.", "Babi golek pangan.", "Babi pados pangan."],
            ["Baca", "Maca", "Maos", "Kata Kerja", "Saya membaca buku.", "Aku maca buku.", "Kula maos buku."],
            ["Badan", "Awak/Sawak", "Sarira", "Anggota Tubuh", "Badan saya sehat.", "Awakku sehat.", "Sarira kula sehat."],
            ["Bagasi", "Bagasi", "Bagasi", "Benda", "Tas dimasukkan ke bagasi.", "Tas dilebokake ing bagasi.", "Tas dipunlebetaken wonten bagasi."],
            ["Bagus", "Apik", "Sae", "Kata Sifat", "Gambarnya sangat bagus.", "Gambare apik banget.", "Gambaranipun sae sanget."],
            ["Bahagia", "Bungah", "Bingah", "Perasaan", "Kami merasa bahagia.", "Kita rumangsa bungah.", "Kula raos bingah."],
            ["Bahasa", "Basa", "Basa", "Pendidikan", "Guru mengajar bahasa Jawa.", "Guru mulang basa Jawa.", "Guru mucal basa Jawi."],
            ["Bahaya", "Bebaya", "Bebaya", "Umum", "Api adalah bahaya.", "Geni kuwi bebaya.", "Brama punika bebaya."],
            ["Bahu", "Pundhak", "Pundhak", "Anggota Tubuh", "Bahunya terasa sakit.", "Pundhake lara.", "Pundhakipun sakit."],
            ["Baik", "Apik/Slamet", "Sae", "Kata Sifat", "Dia anak yang baik.", "Dheweke bocah apik.", "Piyambakipun putra sae."],
            ["Bajak", "Bajak", "Bajak", "Pertanian", "Petani memakai bajak.", "Pak tani nganggo bajak.", "Petani ngagem bajak."],
            ["Baju", "Klambi", "Busana", "Pakaian", "Ibu mencuci baju.", "Ibu ngumbah klambi.", "Ibu ngumbah busana."],
            ["Bak", "Bak", "Bak", "Peralatan Rumah", "Air ada di dalam bak.", "Banyu ana ing bak.", "Toya wonten ing bak."],
            ["Bakar", "Bakar", "Bakar", "Kata Kerja", "Ayah membakar sampah.", "Bapak ngobong uwuh.", "Rama ngobong risak."],
            ["Bakat", "Bakat", "Bakat", "Umum", "Adik memiliki bakat menyanyi.", "Adhik nduweni bakat nembang.", "Adhi gadhah bakat sekar."],
            ["Baki", "Nampan", "Nampan", "Peralatan Rumah", "Ibu membawa baki.", "Ibu nggawa nampan.", "Ibu nggawa nampan."],
            ["Bakso", "Bakso", "Bakso", "Makanan", "Saya makan bakso.", "Aku mangan bakso.", "Kula dhahar bakso."],
            ["Balap", "Balapan", "Balapan", "Olahraga", "Mereka ikut balap sepeda.", "Dheweke melu balapan pit.", "Piyambakipun ndherek balapan pit."],
            ["Balik", "Bali/Wangsul", "Wangsul", "Kata Kerja", "Saya balik ke rumah.", "Aku bali menyang omah.", "Kula wangsul dhateng griya."],
            ["Balon", "Balon", "Balon", "Mainan", "Anak membeli balon.", "Bocah tuku balon.", "Putra mundhut balon."],
            ["Bambu", "Pring", "Pring", "Tumbuhan", "Rumah itu memakai bambu.", "Omah kuwi nganggo pring.", "Griya punika ngagem pring."],
            ["Ban", "Ban", "Ban", "Otomotif", "Ban sepeda bocor.", "Ban pit bocor.", "Ban pit bocor."],
            ["Banci", "Banci", "Banci", "Umum", "Jangan mengejek banci.", "Aja ngenyek banci.", "Sampun ngenyek banci."],
            ["Bandara", "Bandara", "Bandara", "Tempat Umum", "Pesawat tiba di bandara.", "Pesawat teka ing bandara.", "Pesawat rawuh wonten bandara."],
            ["Bangau", "Bangau", "Bangau", "Hewan", "Bangau mencari ikan.", "Bangau golek iwak.", "Bangau pados iwak."],
            ["Bangku", "Bangku", "Lincak/Bangku", "Peralatan Rumah", "Murid duduk di bangku.", "Murid lungguh ing bangku.", "Siswa lenggah wonten bangku."],
            ["Bangun", "Tangi", "Seyos/Tangi", "Kata Kerja", "Saya bangun pagi.", "Aku tangi esuk.", "Kula tangi enjing."],
            ["Bangunan", "Gedhong", "Gedhong", "Bangunan", "Bangunan itu tinggi.", "Gedhong kuwi dhuwur.", "Gedhong punika inggil."],
            ["Banjir", "Banjir", "Banjir", "Bencana", "Jalan terkena banjir.", "Dalan kebanjiran.", "Margi kabanjiran."],
            ["Bantal", "Bantal", "Bantal", "Peralatan Rumah", "Adik memeluk bantal.", "Adhik ngrangkul bantal.", "Adhi ngrangkul bantal."],
            ["Banteng", "Banteng", "Banteng", "Hewan", "Banteng itu kuat.", "Banteng kuwi kuwat.", "Banteng punika kiyat."],
            ["Bantu", "Tulung", "Tulung", "Kata Kerja", "Saya membantu ibu.", "Aku nulungi ibu.", "Kula mitulungi ibu."],
            ["Banyak", "Akeh", "Kathah", "Jumlah", "Buku di perpustakaan banyak.", "Bukune akeh.", "Bukunipun kathah."],
            ["Banyu", "Banyu", "Toya", "Alam", "Banyu sungai jernih.", "Banyu kali bening.", "Toya kali bening."],
            ["Barang", "Barang", "Barang", "Benda", "Barang itu milik ayah.", "Barang kuwi duweke bapak.", "Barang punika kagungan rama."],
            ["Barat", "Kulon", "Kulon", "Arah", "Matahari tenggelam di barat.", "Srengenge surup ing kulon.", "Surya surup wonten kulon."],
            ["Baris", "Baris", "Baris", "Posisi", "Siswa berdiri berbaris.", "Murid ngadeg baris.", "Siswa jumeneng baris."],
            ["Baru", "Anyar", "Enggal", "Kata Sifat", "Saya membeli tas baru.", "Aku tuku tas anyar.", "Kula mundhut tas enggal."],
            ["Basah", "Telem", "Telem", "Kata Sifat", "Baju itu basah.", "Klambi kuwi telem.", "Busana punika telem."],
            ["Batu", "Watu", "Sela", "Alam", "Batu itu besar.", "Watu kuwi gedhe.", "Sela punika ageng."],
            ["Bau", "Ambu", "Ambu", "Indera", "Kue itu berbau harum.", "Jajan kuwi ambune wangi.", "Jajan punika ambunipun wangi."],
            ["Bawa", "Gawa", "Bekta", "Kata Kerja", "Saya membawa buku.", "Aku nggawa buku.", "Kula bekta buku."],
            ["Bawang merah", "Bawang abang", "Bawang abrit", "Bumbu", "Ibu mengiris bawang merah.", "Ibu ngiris bawang abang.", "Ibu ngiris bawang abrit."],
            ["Bawang putih", "Bawang putih", "Bawang putih", "Bumbu", "Ibu menumbuk bawang putih.", "Ibu nguleg bawang putih.", "Ibu nguleg bawang putih."],
            ["Bayam", "Bayam", "Bayam", "Sayuran", "Ibu memasak bayam.", "Ibu masak bayam.", "Ibu masak bayam."],
            ["Bayar", "Mbayar", "Mbayar", "Transaksi", "Ayah membayar listrik.", "Bapak mbayar listrik.", "Rama mbayar listrik."],
            ["Bayi", "Bayi", "Bayi", "Keluarga", "Bayi itu sedang tidur.", "Bayi kuwi lagi turu.", "Bayi punika saweg tilem."],
            ["Beasiswa", "Beasiswa", "Beasiswa", "Pendidikan", "Kakak mendapat beasiswa.", "Mas entuk beasiswa.", "Raka pikantuk beasiswa."],
            ["Bebek", "Bebek", "Bebek", "Hewan", "Bebek berenang di kolam.", "Bebek nglangi ing blumbang.", "Bebek nglangi wonten blumbang."],
            ["Beberapa", "Sawetara", "Sawetawis", "Jumlah", "Saya membeli beberapa pensil.", "Aku tuku sawetara potlot.", "Kula mundhut sawetawis potlot."],
            ["Becak", "Becak", "Becak", "Transportasi", "Kami naik becak.", "Kita numpak becak.", "Kula nitih becak."],
            ["Bel", "Bel", "Bel", "Sekolah", "Bel sekolah berbunyi.", "Bel sekolah muni.", "Bel sekolah muni."],
            ["Belajar", "Sinau", "Sinau", "Pendidikan", "Adik belajar setiap malam.", "Adhik sinau saben bengi.", "Adhi sinau saben dalu."],
            ["Belakang", "Mburi", "Mburi", "Posisi", "Tas berada di belakang kursi.", "Tas ana ing mburi kursi.", "Tas wonten ing wingking kursi."],
            ["Belanja", "Tuku", "Blanja", "Aktivitas", "Ibu pergi belanja.", "Ibu lunga tuku.", "Ibu tindak blanja."],
            ["Belimbing", "Blimbing", "Blimbing", "Buah", "Saya memetik belimbing.", "Aku methik blimbing.", "Kula methik blimbing."],
            ["Belok", "Milih", "Mengsul", "Arah", "Mobil belok kiri.", "Mobil milih kiwa.", "Montor mengsul kiwa."],
            ["Belut", "Welut", "Welut", "Hewan", "Belut hidup di sawah.", "Welut urip ing sawah.", "Welut gesang wonten sabin."],
            ["Benang", "Benang", "Benang", "Benda", "Ibu memakai benang.", "Ibu nganggo benang.", "Ibu ngagem benang."],

            // Batch Benda - Butu
            ["Benda", "Barang", "Barang", "Benda", "Benda itu sangat berat.", "Barang kuwi abot banget.", "Barang punika awrat sanget."],
            ["Bendera", "Gendera", "Gendera", "Simbol", "Bendera merah putih berkibar.", "Gendera abang putih ngibar.", "Gendera abrit putih ngibar."],
            ["Bengkel", "Bengkel", "Bengkel", "Tempat", "Ayah pergi ke bengkel.", "Bapak lunga menyang bengkel.", "Rama tindak dhateng bengkel."],
            ["Benteng", "Benteng", "Benteng", "Bangunan", "Kami mengunjungi benteng tua.", "Kita dolan menyang benteng lawas.", "Kula tindak dhateng benteng kina."],
            ["Bentuk", "Wujud", "Wujud", "Kata Sifat", "Bentuk bola itu bulat.", "Wujude bal kuwi bunder.", "Wujudipun bal punika bunder."],
            ["Berani", "Wani", "Kendel", "Perilaku", "Adik berani tampil.", "Adhik wani maju.", "Adhi kendel majeng."],
            ["Beras", "Beras", "Beras", "Makanan", "Ibu membeli beras.", "Ibu tuku beras.", "Ibu mundhut beras."],
            ["Berat", "Abot", "Awrat", "Kata Sifat", "Tas itu sangat berat.", "Tas kuwi abot banget.", "Tas punika awrat sanget."],
            ["Berbagi", "Bareng nuduhake", "Andum", "Perilaku", "Kami berbagi makanan.", "Kita andum panganan.", "Kula andum dhaharan."],
            ["Berbicara", "Ngomong", "Ngendika", "Komunikasi", "Guru berbicara pelan.", "Guru ngomong alon.", "Guru ngendika alon."],
            ["Berbohong", "Ngapusi", "Mitembungan", "Perilaku", "Aku tidak suka berbohong.", "Aku ora seneng ngapusi.", "Kula boten remen mitembungan."],
            ["Berdoa", "Ndonga", "Ndedonga", "Ibadah", "Kami berdoa bersama.", "Kita ndonga bareng.", "Kula ndedonga sesarengan."],
            ["Berdiri", "Ngadeg", "Jumeneng", "Posisi", "Murid berdiri rapi.", "Murid ngadeg rapi.", "Siswa jumeneng rapi."],
            ["Berenang", "Nglangi", "Nglangi", "Olahraga", "Adik berenang di kolam.", "Adhik nglangi ing blumbang.", "Adhi nglangi wonten blumbang."],
            ["Beres", "Rampung", "Rampung", "Status", "Pekerjaan sudah beres.", "Pakaryane wis rampung.", "Pakaryanipun sampun rampung."],
            ["Berguna", "Migunani", "Migunani", "Kata Sifat", "Buku itu sangat berguna.", "Buku kuwi migunani.", "Buku punika migunani."],
            ["Berhenti", "Mandheg", "Kendel", "Posisi", "Mobil berhenti di lampu merah.", "Mobil mandheg ing lampu abang.", "Montor mandheg wonten lampu abrit."],
            ["Berjalan", "Mlaku", "Mlampah", "Aktivitas", "Kami berjalan ke sekolah.", "Kita mlaku menyang sekolah.", "Kula mlampah dhateng sekolah."],
            ["Berjemur", "Enggo srengenge", "Enggo surya", "Kesehatan", "Nenek berjemur pagi.", "Mbah enggo srengenge esuk.", "Eyang enggo surya enjing."],
            ["Berkata", "Ngomong", "Ngendika", "Komunikasi", "Ayah berkata lembut.", "Bapak ngomong alon.", "Rama ngendika alon."],
            ["Berkebun", "Ngolah kebon", "Ngolah kebon", "Aktivitas", "Kakek berkebun setiap pagi.", "Mbah ngolah kebon saben esuk.", "Eyang ngolah kebon saben enjing."],
            ["Bermain", "Dolanan", "Dolanan", "Aktivitas", "Anak-anak bermain bola.", "Bocah-bocah dolanan bal.", "Para putra dolanan bal."],
            ["Bersih", "Resik", "Suci/Resik", "Kata Sifat", "Kelas selalu bersih.", "Kelas tansah resik.", "Kelas tansah resik."],
            ["Bersin", "Surak", "Bersin", "Kesehatan", "Adik bersin sekali.", "Adhik surak sepisan.", "Adhi bersin sepisan."],
            ["Bertanya", "Takon", "Nyaketaken pitaken", "Komunikasi", "Saya bertanya kepada guru.", "Aku takon marang guru.", "Kula nyuwun pitaken dhateng guru."],
            ["Bertemu", "Ketemu", "Kepanggih", "Komunikasi", "Saya bertemu teman.", "Aku ketemu kanca.", "Kula kepanggih kanca."],
            ["Bertengkar", "Padu", "Padudon", "Perilaku", "Kakak dan adik bertengkar.", "Mas lan adhik padu.", "Raka kaliyan adhi padudon."],
            ["Bertiup", "Semribit", "Semribit", "Cuaca", "Angin bertiup pelan.", "Angin semribit alon.", "Angin semribit alon."],
            ["Beruang", "Beruang", "Beruang", "Hewan", "Beruang itu besar.", "Beruang kuwi gedhe.", "Beruang punika ageng."],
            ["Besar", "Gedhe", "Ageng", "Ukuran", "Rumah itu besar.", "Omah kuwi gedhe.", "Griya punika ageng."],
            ["Besi", "Wesi", "Wesi", "Benda", "Pagar itu terbuat dari besi.", "Pager kuwi digawe saka wesi.", "Pager punika kadamel saking wesi."],
            ["Besok", "Sesuk", "Mbenjing", "Waktu", "Kami berangkat besok.", "Kita mangkat sesuk.", "Kula bidhal mbenjing."],
            ["Betis", "Betis", "Jangga sikil", "Anggota Tubuh", "Betis saya pegal.", "Betisku pegel.", "Jangga sikil kula kraos pegel."],
            ["Bianglala", "Pelangi", "Pelangi", "Alam", "Pelangi terlihat indah.", "Pelangi katon apik.", "Pelangi katingal sae."],
            ["Biar", "Ben", null, "Kata Keterangan", "Biar saya yang membawa.", "Ben aku sing nggawa.", null],
            ["Biasa", "Lumrah", "Lumrah", "Kata Sifat", "Itu hal biasa.", "Kuwi wis lumrah.", "Punika sampun lumrah."],
            ["Bibir", "Lambe", "Lathi", "Anggota Tubuh", "Lipstik ada di bibir ibu.", "Lambe ibu ana lipstik.", "Lathi ibu wonten lipstik."],
            ["Bibit", "Winih", "Winih", "Pertanian", "Petani menanam bibit padi.", "Pak tani nandur winih pari.", "Petani nandur winih pantun."],
            ["Bibir sungai", "Pinggir kali", "Pinggir kali", "Alam", "Mereka duduk di bibir sungai.", "Dheweke lungguh ing pinggir kali.", "Piyambakipun lenggah wonten pinggir kali."],
            ["Biji", "Wiji", "Wiji", "Tumbuhan", "Buah mangga memiliki satu biji.", "Pelem duwe siji wiji.", "Pelem gadhah setunggal wiji."],
            ["Bijaksana", "Wicaksana", "Wicaksana", "Kata Sifat", "Guru sangat bijaksana.", "Guru wicaksana.", "Guru wicaksana."],
            ["Bintang", "Lintang", "Lintang", "Alam", "Bintang bersinar malam hari.", "Lintang sumunar bengi.", "Lintang sumunar dalu."],
            ["Biru", "Biru", "Biru", "Warna", "Langit tampak biru.", "Langit katon biru.", "Langit katingal biru."],
            ["Bisa", "Isa", "Saged", "Kemampuan", "Saya bisa membaca.", "Aku isa maca.", "Kula saged maos."],
            ["Bising", "Rame", "Rame", "Suara", "Jalan itu sangat bising.", "Dalan kuwi rame.", "Margi punika rame."],
            ["Bocor", "Bocor", "Bocor", "Kondisi", "Atap rumah bocor.", "Gendheng omah bocor.", "Gendheng griya bocor."],
            ["Bola", "Bal", "Bal", "Olahraga", "Anak bermain bola.", "Bocah dolanan bal.", "Putra dolanan bal."],
            ["Boneka", "Boneka", "Boneka", "Mainan", "Adik memeluk boneka.", "Adhik ngrangkul boneka.", "Adhi ngrangkul boneka."],
            ["Bosan", "Bosen", "Bosen", "Perasaan", "Saya bosan menunggu.", "Aku bosen ngenteni.", "Kula bosen ngentosi."],
            ["Botol", "Botol", "Botol", "Wadah", "Air ada di dalam botol.", "Banyu ana ing botol.", "Toya wonten ing botol."],
            ["Buah", "Woh", "Woh", "Makanan", "Saya makan buah setiap hari.", "Aku mangan woh saben dina.", "Kula dhahar woh saben dinten."],
            ["Buaya", "Baya", "Baya", "Hewan", "Buaya hidup di sungai.", "Baya urip ing kali.", "Baya gesang wonten kali."],
            ["Bubur", "Bubur", "Bubur", "Makanan", "Nenek memasak bubur.", "Mbah masak bubur.", "Eyang masak bubur."],
            ["Buku", "Buku", "Buku", "Pendidikan", "Saya membaca buku.", "Aku maca buku.", "Kula maos buku."],
            ["Bulan", "Wulan", "Wulan", "Alam", "Bulan terlihat terang.", "Wulan katon padhang.", "Wulan katingal padhang."],
            ["Bunga", "Kembang", "Sekar", "Tumbuhan", "Ibu menyiram bunga.", "Ibu nyirami kembang.", "Ibu nyirami sekar."],
            ["Bungkus", "Bungkus", "Bungkus", "Kata Kerja", "Tolong bungkus makanan ini.", "Tulung bungkus panganan iki.", "Sumangga bungkus dhaharan punika."],
            ["Burung", "Manuk", "Manuk", "Hewan", "Burung itu terbang tinggi.", "Manuk kuwi mabur dhuwur.", "Manuk punika mabur inggil."],
            ["Bus", "Bis", "Bis", "Transportasi", "Kami naik bus ke kota.", "Kita numpak bis menyang kutha.", "Kula nitih bis dhateng kutha."],
            ["Busuk", "Bosok", "Bosok", "Kondisi", "Buah itu sudah busuk.", "Woh kuwi wis bosok.", "Woh punika sampun bosok."],
            ["Buta", "Wuta", "Wuta", "Kondisi", "Wayang menceritakan raksasa buta.", "Wayang nyritakake buta.", "Wayang nyariosaken wuta."],
            ["Butuh", "Butuh", "Betahaken", "Kebutuhan", "Saya butuh bantuan.", "Aku butuh pitulungan.", "Kula betahaken pitulungan."],
            ["Butu", "Kutu", "Kutu", "Hewan", "Ayam itu terkena kutu.", "Pitik kuwi ana kutune.", "Pitik punika wonten kutunipun."],

            // Batch 188 - 280 (Butir - Diamond)
            ["Butir", "Butir", "Butir", "Kata Benda", "Ada satu butir telur pecah.", "Ana siji butir endhog pecah.", "Wonten setunggal butir tigan pecah."],
            ["Buyut", "Mbuyut", "Mbuyut", "Keluarga", "Buyut tinggal di desa.", "Mbuyut manggon ing desa.", "Mbuyut dedalem wonten desa."],
            ["Cabai", "Lombok", "Lombok", "Makanan", "Ibu membeli cabai merah.", "Ibu tuku lombok abang.", "Ibu mundhut lombok abrit."],
            ["Cabang", "Pang", "Pang", "Alam", "Cabang pohon patah.", "Pang wit tugel.", "Pang uwit tugel."],
            ["Cacing", "Cacing", "Cacing", "Hewan", "Cacing hidup di tanah.", "Cacing urip ing lemah.", "Cacing gesang wonten lemah."],
            ["Cair", "Cair", "Cair", "Kata Sifat", "Es menjadi cair.", "Es dadi cair.", "Es dados cair."],
            ["Calon", "Calon", "Calon", "Kata Benda", "Kakak menjadi calon ketua.", "Mas dadi calon ketua.", "Raka dados calon ketua."],
            ["Camar", "Camar", "Camar", "Hewan", "Burung camar terbang rendah.", "Manuk camar mabur endhek.", "Manuk camar mabur asor."],
            ["Campur", "Campur", "Campur", "Kata Kerja", "Ibu mencampur gula.", "Ibu nyampur gula.", "Ibu nyampur gendhis."],
            ["Cangkir", "Cangkir", "Cangkir", "Peralatan Rumah", "Cangkir itu bersih.", "Cangkir kuwi resik.", "Cangkir punika resik."],
            ["Cantik", "Ayu", "Ayu", "Kata Sifat", "Adik memakai baju cantik.", "Adhik nganggo klambi ayu.", "Adhi ngagem busana ayu."],
            ["Capai", "Kesel", "Kesah", "Kata Sifat", "Saya merasa capai.", "Aku krasa kesel.", "Kula kraos kesah."],
            ["Capit", "Capit", "Capit", "Kata Benda", "Kepiting memiliki capit besar.", "Yuyu duwe capit gedhe.", "Yuyu gadhah capit ageng."],
            ["Cara", "Cara", "Cara", "Kata Benda", "Guru menjelaskan cara belajar.", "Guru nerangake cara sinau.", "Guru nerangaken cara sinau."],
            ["Cat", "Cat", "Cat", "Peralatan Rumah", "Ayah membeli cat tembok.", "Bapak tuku cat tembok.", "Rama mundhut cat tembok."],
            ["Catat", "Cathet", "Cathet", "Kata Kerja", "Tolong catat jawabanmu.", "Tulung cathet wangsulanmu.", "Sumangga cathet wangsulan panjenengan."],
            ["Catatan", "Cathetan", "Cathetan", "Sekolah", "Saya membaca catatan.", "Aku maca cathetan.", "Kula maos cathetan."],
            ["Cedera", "Cilaka", "Cilaka", "Kesehatan", "Pemain mengalami cedera.", "Pemain cilaka.", "Pemain cilaka."],
            ["Cegah", "Cegah", "Cegah", "Kata Kerja", "Kita mencegah penyakit.", "Kita nyegah lara.", "Kula nyegah gerah."],
            ["Cek", "Cek", "Cek", "Teknologi", "Guru mengecek tugas.", "Guru ngecek tugas.", "Guru mriksa tugas."],
            ["Celana", "Kathok", "Selana", "Pakaian", "Ayah memakai celana panjang.", "Bapak nganggo kathok dawa.", "Rama ngagem selana dawa."],
            ["Celengan", "Celengan", "Celengan", "Peralatan Rumah", "Adik menabung di celengan.", "Adhik nabung ing celengan.", "Adhi nabung wonten celengan."],
            ["Cemas", "Kuwatir", "Waswas", "Perasaan", "Ibu cemas menunggu ayah.", "Ibu kuwatir ngenteni bapak.", "Ibu waswas ngentosi rama."],
            ["Cempaka", "Cempaka", "Cempaka", "Bunga", "Bunga cempaka harum.", "Kembang cempaka wangi.", "Sekar cempaka wangi."],
            ["Cendana", "Cendana", "Cendana", "Pohon", "Pohon cendana tumbuh subur.", "Wit cendana thukul subur.", "Uwit cendana tuwuh subur."],
            ["Cendekia", "Pinter", "Sujana", "Kata Sifat", "Guru adalah orang cendekia.", "Guru kuwi wong pinter.", "Guru punika sujana."],
            ["Cendol", "Dawet", "Dawet", "Minuman", "Saya minum cendol.", "Aku ngombe dawet.", "Kula ngunjuk dawet."],
            ["Cengkih", "Cengkeh", "Cengkeh", "Tumbuhan", "Cengkih dipanen petani.", "Cengkeh dipanen petani.", "Cengkeh dipunpanen petani."],
            ["Cepat", "Cepet", "Rikat", "Kata Sifat", "Adik berlari cepat.", "Adhik mlayu cepet.", "Adhi mlayu rikat."],
            ["Cerah", "Cerah", "Cerah", "Cuaca", "Langit tampak cerah.", "Langit katon cerah.", "Langit katingal cerah."],
            ["Cerdas", "Pinter", "Sujana", "Kata Sifat", "Anak itu sangat cerdas.", "Bocah kuwi pinter.", "Putra punika sujana."],
            ["Cerita", "Crita", "Cariyos", "Kata Benda", "Nenek bercerita sebelum tidur.", "Mbah nyrita sadurunge turu.", "Eyang nyarios sadèrèngipun tilem."],
            ["Cermin", "Kaca", "Kaca", "Peralatan Rumah", "Cermin itu sangat bersih.", "Kaca kuwi resik.", "Kaca punika resik."],
            ["Cerobong", "Cerobong", "Cerobong", "Rumah", "Asap keluar dari cerobong.", "Kumelun metu saka cerobong.", "Kumelun medal saking cerobong."],
            ["Cetak", "Cithak", "Cithak", "Kata Kerja", "Guru mencetak soal.", "Guru nyithak soal.", "Guru nyithak soal."],
            ["Cicak", "Cecak", "Cecak", "Hewan", "Cicak memakan nyamuk.", "Cecak mangan lemut.", "Cecak dhahar lemut."],
            ["Cincin", "Cincin", "Sesupek", "Aksesori", "Ibu memakai cincin emas.", "Ibu nganggo cincin emas.", "Ibu ngagem sesupek emas."],
            ["Cinta", "Tresna", "Tresna", "Perasaan", "Ibu memberi cinta kepada anak.", "Ibu menehi tresna marang anak.", "Ibu maringi tresna dhateng putra."],
            ["Cium", "Ambung", "Ambung", "Kata Kerja", "Adik mencium tangan ibu.", "Adhik ambung tangan ibu.", "Adhi ambung asta ibu."],
            ["Coba", "Nyoba", "Nyobi", "Kata Kerja", "Saya mencoba menjawab.", "Aku nyoba mangsuli.", "Kula nyobi mangsuli."],
            ["Cokelat", "Coklat", "Coklat", "Makanan", "Adik makan cokelat.", "Adhik mangan coklat.", "Adhi dhahar coklat."],
            ["Cuci", "Ngumbah", "Ngumbah", "Kata Kerja", "Ibu mencuci pakaian.", "Ibu ngumbah klambi.", "Ibu ngumbah busana."],
            ["Cuci tangan", "Ngumbah tangan", "Ngumbah asta", "Kesehatan", "Kita harus cuci tangan.", "Kita kudu ngumbah tangan.", "Kita kedah ngumbah asta."],
            ["Cukur", "Cukur", "Cukur", "Kata Kerja", "Ayah mencukur rambut.", "Bapak cukur rambut.", "Rama cukur rikma."],
            ["Curah hujan", "Udan", "Udan", "Cuaca", "Curah hujan tinggi hari ini.", "Udan deres dina iki.", "Udan deres dinten punika."],
            ["Curiga", "Sujan", "Sujan", "Perasaan", "Jangan mudah curiga.", "Aja gampang sujan.", "Sampun gampil sujan."],
            ["Cuti", "Cuti", "Cuti", "Pekerjaan", "Guru mengambil cuti.", "Guru njupuk cuti.", "Guru mundhut cuti."],
            ["Cyber", null, null, "Teknologi", "Keamanan cyber sangat penting.", "Keamanan cyber penting.", "Keamanan cyber penting."],
            ["Cuci muka", "Ngumbah rai", "Ngumbah pasuryan", "Kesehatan", "Saya cuci muka setiap pagi.", "Aku ngumbah rai saben esuk.", "Kula ngumbah pasuryan saben enjing."],
            ["Cuka", "Cuka", "Cuka", "Makanan", "Ibu menambahkan cuka sedikit.", "Ibu nambahi cuka sethithik.", "Ibu nambahi cuka sekedhik."],
            ["Cumi-cumi", "Cumi-cumi", "Cumi-cumi", "Hewan", "Ayah membeli cumi-cumi.", "Bapak tuku cumi-cumi.", "Rama mundhut cumi-cumi."],
            ["Cupang", "Cupang", "Cupang", "Hewan", "Ikan cupang itu indah.", "Iwak cupang kuwi apik.", "Iwak cupang punika sae."],
            ["Curah", "Deres", "Deres", "Cuaca", "Hujan turun sangat curah.", "Udan deres banget.", "Udan deres sanget."],
            ["Curam", "Jurang", "Curam", "Alam", "Jalan itu sangat curam.", "Dalan kuwi curam.", "Margi punika curam."],
            ["Curhat", "Crita", "Nyarios", "Perasaan", "Adik curhat kepada ibu.", "Adhik crita marang ibu.", "Adhi nyarios dhateng ibu."],
            ["Curut", "Curut", "Curut", "Hewan", "Curut mencari makanan.", "Curut golek pangan.", "Curut pados pangan."],
            ["Custom", null, null, "Teknologi", "Aplikasi memiliki tema custom.", "Aplikasi duwe tema custom.", "Aplikasi gadhah tema custom."],
            ["Cuti bersama", "Cuti sesarengan", "Cuti sesarengan", "Pekerjaan", "Sekolah libur cuti bersama.", "Sekolah prei cuti sesarengan.", "Sekolah prei cuti sesarengan."],
            ["Dada", "Dhadha", "Dhadha", "Anggota Tubuh", "Dada ayah terasa sesak.", "Dhadha bapak krasa sesek.", "Dhadha rama kraos sesek."],
            ["Daerah", "Dhaerah", "Dhaerah", "Tempat Umum", "Daerah itu sangat ramai.", "Dhaerah kuwi rame.", "Dhaerah punika rame."],
            ["Daftar", "Dhaptar", "Dhaptar", "Sekolah", "Saya mengisi daftar hadir.", "Aku ngisi dhaptar rawuh.", "Kula ngisi dhaptar rawuh."],
            ["Dagang", "Dagang", "Dagang", "Profesi", "Ayah berdagang di pasar.", "Bapak dagang ing pasar.", "Rama dagang wonten pasar."],
            ["Daging", "Daging", "Daging", "Makanan", "Ibu memasak daging sapi.", "Ibu masak daging sapi.", "Ibu masak daging sapi."],
            ["Dahaga", "Haus", "Sekeca", "Perasaan", "Saya merasa dahaga.", "Aku krasa haus.", "Kula kraos sekeca."],
            ["Dahan", "Pang", "Pang", "Alam", "Burung hinggap di dahan.", "Manuk manggon ing pang.", "Manuk pinarak wonten pang."],
            ["Dahulu", "Mbiyen", "Rumiyin", "Waktu", "Dahulu desa ini sepi.", "Mbiyen desa iki sepi.", "Rumiyin desa punika sepi."],
            ["Daun", "Godhong", "Godhong", "Tumbuhan", "Daun itu berwarna hijau.", "Godhong kuwi ijo.", "Godhong punika ijem."],
            ["Dawai", "Dawai", "Dawai", "Benda", "Senar gitar terbuat dari dawai.", "Senar gitar digawe saka dawai.", "Senar gitar kadamel saking dawai."],
            ["Daya", "Daya", "Daya", "Pendidikan", "Lampu membutuhkan daya listrik.", "Lampu butuh daya listrik.", "Lampu mbutuhake daya listrik."],
            ["Dekat", "Cedhak", "Celak", "Ruang", "Rumah kami dekat sekolah.", "Omahku cedhak sekolah.", "Griya kula celak sekolah."],
            ["Dekorasi", "Hiasan", "Hiasan", "Rumah", "Ruang kelas memiliki dekorasi.", "Kelas nduweni hiasan.", "Kelas gadhah hiasan."],
            ["Delima", "Delima", "Delima", "Buah", "Delima itu manis.", "Delima kuwi legi.", "Delima punika manis."],
            ["Demam", "Panas", "Gerah", "Kesehatan", "Adik mengalami demam.", "Adhik panas.", "Adhi gerah."],
            ["Dendam", "Dendam", "Dendam", "Perasaan", "Jangan menyimpan dendam.", "Aja nyimpen dendam.", "Sampun nyimpen dendam."],
            ["Dengar", "Krungu", "Mireng", "Indera", "Saya mendengar suara burung.", "Aku krungu swara manuk.", "Kula mireng swanten manuk."],
            ["Denah", "Denah", "Denah", "Bangunan", "Guru menunjukkan denah sekolah.", "Guru nuduhake denah sekolah.", "Guru nedahaken denah sekolah."],
            ["Denda", "Denda", "Denda", "Pendidikan", "Saya membayar denda perpustakaan.", "Aku mbayar denda perpustakaan.", "Kula mbayar denda perpustakaan."],
            ["Dengan", "Karo", "Kaliyan", "Tata Bahasa", "Saya pergi dengan ayah.", "Aku lunga karo bapak.", "Kula tindak kaliyan rama."],
            ["Dengkur", "Ngorok", "Sare ngorok", "Kesehatan", "Kakek dengkur saat tidur.", "Mbah ngorok nalika turu.", "Eyang sare ngorok nalika tilem."],
            ["Denyut", "Denyut", "Denyut", "Kesehatan", "Denyut nadi normal.", "Denyut nadi normal.", "Denyut nadi normal."],
            ["Deras", "Deres", "Deres", "Cuaca", "Air sungai mengalir deras.", "Banyu kali mili deres.", "Toya kali mili deres."],
            ["Deret", "Dheret", "Dheret", "Kata Benda", "Anak berdiri dalam deret.", "Bocah ngadeg ing dheret.", "Putra jumeneng wonten dheret."],
            ["Desa", "Desa", "Desa", "Tempat", "Kakek tinggal di desa.", "Mbah manggon ing desa.", "Eyang dedalem wonten desa."],
            ["Desember", "Desember", "Desember", "Waktu", "Sekolah libur bulan Desember.", "Sekolah prei wulan Desember.", "Sekolah prei wulan Desember."],
            ["Desis", "Sesis", "Sesis", "Suara", "Ular mengeluarkan suara desis.", "Ula muni sesis.", "Ula ngedalaken swanten sesis."],
            ["Detail", "Rinci", "Rinci", "Teknologi", "Guru menjelaskan secara detail.", "Guru nerangake rinci.", "Guru nerangaken kanthi rinci."],
            ["Detik", "Detik", "Detik", "Waktu", "Satu menit enam puluh detik.", "Sakmenit sewidak detik.", "Setunggal menit suwidak detik."],
            ["Diagonal", "Diagonal", "Diagonal", "Matematika", "Guru menggambar garis diagonal.", "Guru nggambar garis diagonal.", "Guru nggambar garis diagonal."],
            ["Diagram", "Diagram", "Diagram", "Matematika", "Siswa membuat diagram.", "Murid nggawe diagram.", "Siswa damel diagram."],
            ["Dialog", "Pacelathon", "Pacelathon", "Bahasa", "Mereka melakukan dialog.", "Dheweke pacelathon.", "Piyambakipun pacelathon."],
            ["Diam", "Meneng", "Meneng", "Perilaku", "Anak itu diam.", "Bocah kuwi meneng.", "Putra punika meneng."],
            ["Diam-diam", "Meneng-meneng", "Meneng-meneng", "Perilaku", "Dia pergi diam-diam.", "Dheweke lunga meneng-meneng.", "Piyambakipun tindak meneng-meneng."],
            ["Diamond", "Inten", "Inten", "Benda", "Cincin itu memiliki diamond.", "Cincin kuwi ana intene.", "Sesupek punika gadhah inten."]
        ];

        foreach ($dataset as $row) {
            $indo = trim($row[0]);
            $ngoko = trim($row[1]);
            $krama = !empty($row[2]) && $row[2] !== 'NULL' ? trim($row[2]) : null;
            $cat = !empty($row[3]) && $row[3] !== 'NULL' ? trim($row[3]) : null;
            $exIndo = !empty($row[4]) && $row[4] !== 'NULL' ? trim($row[4]) : null;
            $exNgoko = !empty($row[5]) && $row[5] !== 'NULL' ? trim($row[5]) : null;
            $exKrama = !empty($row[6]) && $row[6] !== 'NULL' ? trim($row[6]) : null;

            $vocab = Vocabulary::updateOrCreate(
                ['indonesian_word' => $indo],
                [
                    'javanese_ngoko' => $ngoko,
                    'javanese_krama' => $krama,
                    'category'       => $cat
                ]
            );

            if ($exIndo) {
                VocabularyExample::updateOrCreate(
                    ['vocabulary_id' => $vocab->id],
                    [
                        'indonesian_sentence' => $exIndo,
                        'ngoko_sentence'      => $exNgoko,
                        'krama_sentence'      => $exKrama,
                        'javanese_sentence'   => $exNgoko
                    ]
                );
            }
        }
    }
}
