<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WayangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Insert wayang_categories
        DB::table('wayang_categories')->upsert([
            [
                'id'          => 1,
                'name'        => 'Pandawa',
                'description' => 'Lima bersaudara putra Prabu Pandu yang menjadi lambang kebajikan, keadilan, dan ksatria utama dalam epos Mahabharata.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 2,
                'name'        => 'Kurawa',
                'description' => 'Seratus bersaudara putra Prabu Drestarastra yang berkuasa di Kerajaan Astina dan mewakili sifat angkara murka.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 3,
                'name'        => 'Punakawan',
                'description' => 'Empat tokoh abdi pamong jenaka dan bijaksana yang selalu setia mendampingi serta memberi nasihat kepada para ksatria berbudi luhur.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 4,
                'name'        => 'Kesatria dan Sekutu',
                'description' => 'Para kesatria agung dan pahlawan sakti yang menjadi kekuatan penting serta sekutu setia dalam menegakkan kebenaran.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 5,
                'name'        => 'Tokoh Wanita',
                'description' => 'Para ratu, dewi, dan srikandi pewayangan yang anggun, tangguh, berwibawa, dan memiliki peran krusial dalam sejarah keluarga besar Bharatayuda.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 6,
                'name'        => 'Tokoh Kerajaan',
                'description' => 'Para raja, penguasa agung, dan tetua berwibawa yang memegang kendali pemerintahan kerajaan-kerajaan besar dalam dunia wayang.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 7,
                'name'        => 'Resi dan Guru',
                'description' => 'Para begawan, penasihat spiritual, dan mahaguru olah senjata yang membimbing serta membentuk keprajuritan para pangeran.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'id'          => 8,
                'name'        => 'Tokoh Lainnya',
                'description' => 'Tokoh-tokoh penting dengan takdir dan peran khas tersendiri dalam jalinan peristiwa agung Bharatayuda.',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ], ['id'], ['name', 'description', 'updated_at']);

        // 2. Insert 45 wayang_characters
        $characters = [
            // KATEGORI 1: PANDAWA (1 - 5)
            [
                'id'               => 1,
                'category_id'      => 1,
                'name'             => 'Yudhistira',
                'other_names'      => 'Puntadewa, Darmakusuma, Dwijakangka',
                'gender'           => 'Laki-laki',
                'role'             => 'Pemimpin Pandawa dan raja Kerajaan Amarta yang dikenal suci dan bijaksana',
                'character_traits' => 'Jujur, sabar, bijaksana, adil, tenang, ikhlas',
                'weapon'           => 'Jamus Kalimasada',
                'family'           => 'Putra Prabu Pandu dan Dewi Kunti; kakak tertua Bima, Arjuna, Nakula, dan Sadewa; suami Dewi Drupadi',
                'allegiance'       => 'Pandawa',
                'description'      => 'Yudhistira merupakan anak tertua Pandawa yang dikenal memiliki sifat sangat jujur, sabar, dan tidak pernah berbohong. Ia menjadi raja Amarta yang dicintai rakyatnya karena menjunjung tinggi kebenaran dan keadilan.',
                'story'            => 'Yudhistira tumbuh bersama saudara-saudaranya dan memimpin Pandawa menghadapi berbagai ujian hidup akibat kelicikan Kurawa. Kendati sempat terjebak dalam permainan dadu yang menyebabkan pengasingan selama tiga belas tahun, ia tetap tabah dan memegang teguh dharma. Dalam Perang Baratayuda, Yudhistira memimpin pasukan Pandawa hingga meraih kemenangan. Setelah perang berakhir, ia naik tahta sebagai raja Astina sebelum akhirnya melakukan perjalanan suci menuju puncak Himalaya.',
                'image_path'       => 'wayang/yudhistira.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 2,
                'category_id'      => 1,
                'name'             => 'Bima',
                'other_names'      => 'Werkudara, Bratasena, Bayusuta, Jagal Abilawa',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria gagah perkasa Pandawa dan pelindung utama saudara-saudaranya',
                'character_traits' => 'Kuat, berani, tegas, jujur, setia, pantang menyerah',
                'weapon'           => 'Kuku Pancanaka dan Gada Rujakpala',
                'family'           => 'Putra kedua Prabu Pandu dan Dewi Kunti; saudara Yudhistira, Arjuna, Nakula, dan Sadewa; ayah Gatotkaca, Antareja, dan Antasena',
                'allegiance'       => 'Pandawa',
                'description'      => 'Bima merupakan ksatria Pandawa kedua yang memiliki tubuh kekar, kekuatan fisik tiada tanding, dan hati yang tulus. Ia dikenal menggunakan bahasa Jawa ngoko kepada siapa saja sebagai lambang kejujuran dan kesetaraan jiwa.',
                'story'            => 'Sejak masa muda, Bima selalu menjadi benteng pertahanan bagi adik dan kakaknya dari ancaman Kurawa. Dalam lakon Dewa Ruci, Bima menunjukkan ketaatan mutlak kepada guru hingga berhasil mencapai kesempurnaan ilmu sejati. Pada Perang Baratayuda di Kurusetra, Bima menuntaskan sumpahnya dengan mengalahkan Dursasana dan menumbangkan Duryudana dalam pertarungan gada yang sengit. Kekuatan serta keteguhan moral Bima menjadikannya pahlawan sejati yang disegani kawan maupun lawan.',
                'image_path'       => 'wayang/bima.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 3,
                'category_id'      => 1,
                'name'             => 'Arjuna',
                'other_names'      => 'Janaka, Dananjaya, Permadi, Parta, Palguna',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria tampan Pandawa dan mahaguru pemanah terbaik dunia',
                'character_traits' => 'Cerdas, terampil, tenang, sopan, rendah hati, berwibawa',
                'weapon'           => 'Gandewa dan Panah Pasopati',
                'family'           => 'Putra ketiga Prabu Pandu dan Dewi Kunti; saudara Yudhistira, Bima, Nakula, dan Sadewa; suami Subadra dan Srikandi; ayah Abimanyu',
                'allegiance'       => 'Pandawa',
                'description'      => 'Arjuna merupakan ksatria penengah Pandawa yang termasyhur akan ketampanan, kehalusan budi, dan kemahirannya dalam olah senjata panah. Ia menjadi tumpuan utama kemenangan Pandawa dalam menegakkan kebenaran.',
                'story'            => 'Arjuna gemar bertapa dan menuntut ilmu ke berbagai pertapaan suci hingga memperoleh anugerah senjata pusaka sakti dari para dewa. Sebelum pertempuran besar dimulai, Arjuna sempat dirundung keraguan moral melihat sanak saudaranya di medan perang, hingga menerima wejangan suci Bhagawad Gita dari Sri Kresna. Di padang Kurusetra, dengan ketenangan dan ketepatan bidikan panahnya, Arjuna berhasil mengalahkan ksatria-ksatria besar Kurawa termasuk Karna dan Resi Bisma demi menegakkan keadilan.',
                'image_path'       => 'wayang/arjuna.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 4,
                'category_id'      => 1,
                'name'             => 'Nakula',
                'other_names'      => 'Pinten, Madrimputra',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria kembar Pandawa yang mahir merawat kuda dan ilmu pedang',
                'character_traits' => 'Setia, tangkas, jujur, patuh, penyayang, teliti',
                'weapon'           => 'Pedang dan panah',
                'family'           => 'Putra Prabu Pandu dan Dewi Madrim; saudara kembar Sadewa; adik asuh Dewi Kunti bersama Yudhistira, Bima, dan Arjuna',
                'allegiance'       => 'Pandawa',
                'description'      => 'Nakula adalah ksatria kembar Pandawa tertua yang berparas elok dan memiliki keahlian luar biasa dalam merawat serta mengendalikan kuda perang. Ia merupakan sosok ksatria yang sangat patuh dan berbakti kepada para kakaknya.',
                'story'            => 'Setelah wafatnya Prabu Pandu dan Dewi Madrim, Nakula diasuh dengan penuh kasih sayang oleh Dewi Kunti bersama saudara kembarnya. Selama masa penyamaran di Kerajaan Wiratha, Nakula mengabdi sebagai pengurus istal kuda kerajaan dengan nama samaran Grantika. Keahliannya dalam ilmu persenjataan pedang dan strategi mobilitas pasukan berkuda memberikan andil besar bagi kemenangan pertahanan barisan Pandawa dalam perang Bharatayuda.',
                'image_path'       => 'wayang/nakula.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 5,
                'category_id'      => 1,
                'name'             => 'Sadewa',
                'other_names'      => 'Tansen, Sahadewa',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria kembar Pandawa termuda yang ahli ilmu perbintangan dan strategi',
                'character_traits' => 'Bijaksana, cerdas, waspada, jujur, tenang, berwawasan luas',
                'weapon'           => 'Pedang dan panah',
                'family'           => 'Putra bungsu Prabu Pandu dan Dewi Madrim; saudara kembar Nakula; adik asuh Dewi Kunti',
                'allegiance'       => 'Pandawa',
                'description'      => 'Sadewa adalah ksatria kembar Pandawa termuda yang dianugerahi kecerdasan istimewa serta ilmu firasat masa depan dan perbintangan. Kebijaksanaan dan ketenangannya kerap menjadi rujukan penting dalam menentukan keputusan strategis keluarga Pandawa.',
                'story'            => 'Sadewa tumbuh menjadi ksatria yang pendiam namun berwawasan sangat luas tentang rahasia alam dan tata negara. Dalam masa penyamaran di negeri Wiratha, ia bertugas mengelola peternakan sapi istana dengan nama samaran Tantripala. Pada pertempuran Bharatayuda, Sadewa membuktikan ketangguhannya di medan laga dan berhasil menuntaskan dendam kejahatan masa lalu dengan menewaskan Prabu Salya dan Patih Sengkuni yang menjadi dalang segala perselisihan.',
                'image_path'       => 'wayang/sadewa.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 2: KURAWA (6 - 14)
            [
                'id'               => 6,
                'category_id'      => 2,
                'name'             => 'Duryudana',
                'other_names'      => 'Kurupati, Suyudana, Jaka Pitana',
                'gender'           => 'Laki-laki',
                'role'             => 'Pemimpin utama seratus Kurawa dan raja Kerajaan Astina',
                'character_traits' => 'Ambisius, keras kepala, iri hati, sombong, teguh pendirian',
                'weapon'           => 'Gada',
                'family'           => 'Putra sulung Prabu Drestarastra dan Dewi Gandari; kakak tertua para Kurawa; suami Dewi Banowati',
                'allegiance'       => 'Kurawa',
                'description'      => 'Duryudana adalah putra mahkota sekaligus raja Astina yang memimpin kaum Kurawa dalam memperebutkan tahta kerajaan. Ambisinya yang tak terbendung untuk menguasai seluruh takhta menjadikannya musuh utama Pandawa.',
                'story'            => 'Sejak masa kanak-kanak, Duryudana selalu merasa cemburu terhadap keunggulan dan kemuliaan saudara-saudara Pandawa. Di bawah pengaruh bisikan Patih Sengkuni, ia menyusun berbagai siasat licik mulai dari pembakaran Bale Sigala-gala hingga permainan dadu curang. Duryudana menolak mengembalikan hak wilayah Pandawa meski telah diperingatkan oleh Sri Kresna. Di akhir perang Baratayuda, ia gugur dalam duel gada satu lawan satu melawan Bima di tepi telaga Dwaipayana.',
                'image_path'       => 'wayang/duryudana.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 7,
                'category_id'      => 2,
                'name'             => 'Dursasana',
                'other_names'      => 'Duhsasana',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria Kurawa kedua dan tangan kanan utama Duryudana',
                'character_traits' => 'Kasar, bengis, ceroboh, setia buta kepada kakaknya, tak kenal takut',
                'weapon'           => 'Pedang dan gada',
                'family'           => 'Putra kedua Prabu Drestarastra dan Dewi Gandari; adik kandung Duryudana',
                'allegiance'       => 'Kurawa',
                'description'      => 'Dursasana merupakan adik kandung Duryudana yang paling setia dan selalu menjadi pelaksana perintah kekerasan kaum Kurawa. Wataknya yang kasar dan sombong menjadikannya sosok yang amat dibenci oleh pihak Pandawa.',
                'story'            => 'Dursasana dikenal sebagai pelaku tindakan memalukan yang berusaha menelanjangi Dewi Drupadi di balairung istana Astina setelah kekalahan permainan dadu. Perbuatan keji tersebut melahirkan sumpah dari Bima dan Drupadi yang menuntut pembalasan di kemudian hari. Pada perang Baratayuda, Dursasana bertempur dengan penuh kebuasan sebelum akhirnya ditangkap dan ditumpas oleh Bima di padang Kurusetra sebagai penegakan keadilan atas sumpahnya.',
                'image_path'       => 'wayang/dursasana.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 8,
                'category_id'      => 2,
                'name'             => 'Sengkuni',
                'other_names'      => 'Sang Kuni, Sakuni, Harya Suman',
                'gender'           => 'Laki-laki',
                'role'             => 'Patih Kerajaan Astina dan penasihat licik di balik pergerakan Kurawa',
                'character_traits' => 'Licik, pandai berbicara, penuh tipu muslihat, manipulatif, pendendam',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putra Prabu Suwala dari Kerajaan Gandara; saudara kandung Dewi Gandari; paman para Kurawa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Patih Sengkuni adalah tokoh antagonis utama yang menjabat sebagai mahapatih di Kerajaan Astina. Keahliannya dalam bersilat lidah dan menyusun intrik politik menjadikannya dalang di balik permusuhan abadi antara Pandawa dan Kurawa.',
                'story'            => 'Sengkuni menyimpan dendam mendalam terhadap takhta Astina dan bersumpah akan menghancurkan keturunan dinasti Kuru dari dalam. Ia memanfaatkan kepolosan Yudhistira dalam permainan dadu dengan menggunakan dadu sihir miliknya untuk merebut kerajaan Amarta. Sepanjang hidupnya, ia terus mengompori Duryudana agar tidak pernah berdamai dengan Pandawa. Di penghujung perang Bharatayuda, Sengkuni akhirnya tewas di tangan Sadewa dan Bima.',
                'image_path'       => 'wayang/sengkuni.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 9,
                'category_id'      => 2,
                'name'             => 'Dursilawati',
                'other_names'      => 'Duhsala',
                'gender'           => 'Perempuan',
                'role'             => 'Putri tunggal dalam keluarga besar seratus Kurawa',
                'character_traits' => 'Penyayang, manja, setia kepada keluarga, anggun',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri tunggal Prabu Drestarastra dan Dewi Gandari; adik perempuan para Kurawa; istri Prabu Jayadrata',
                'allegiance'       => 'Kurawa',
                'description'      => 'Dursilawati adalah satu-satunya anak perempuan di antara seratus Kurawa yang sangat disayangi oleh orang tua dan saudara-saudaranya. Ia menikah dengan Prabu Jayadrata dari Kerajaan Sindu.',
                'story'            => 'Dursilawati hidup dalam kemewahan istana Astina dan selalu berusaha menjaga keharmonisan di antara kakak-kakaknya. Pernikahannya dengan Jayadrata memperkuat persekutuan politik militer pihak Kurawa. Tatkala perang Baratayuda meletus dan merenggut nyawa suami serta seluruh saudara kandungnya, Dursilawati harus menanggung duka mendalam sebagai saksi kehancuran dinasti Kurawa yang binasa akibat angkara murka.',
                'image_path'       => 'wayang/dursilawati.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 10,
                'category_id'      => 2,
                'name'             => 'Burisrawa',
                'other_names'      => 'Arya Burisrawa',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria perkasa dari Mandaraka dan panglima sekutu Kurawa',
                'character_traits' => 'Tangguh, pemberani, emosional, keras hati, mahir bergulat',
                'weapon'           => 'Keris dan gada',
                'family'           => 'Putra Prabu Salya dari Kerajaan Mandaraka; ipar Prabu Duryudana',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Burisrawa merupakan ksatria tangguh keturunan Mandaraka yang memilih bersekutu dengan pihak Kurawa karena ikatan persaudaraan dan kekeluargaan. Ia terkenal dengan keberaniannya yang luar biasa saat bertarung di baris depan.',
                'story'            => 'Burisrawa memiliki perseteruan pribadi yang panjang dengan Setyaki dari pihak Pandawa dalam memperebutkan kehormatan ksatria. Pada perang Bharatayuda, Burisrawa bertarung gagah berani dan berhasil merobohkan banyak prajurit lawan. Dalam duel puncaknya melawan Setyaki, Burisrawa hampir meraih kemenangan sebelum tangannya terputus oleh panah Arjuna, dan kemudian gugur dengan penuh kehormatan di medan laga.',
                'image_path'       => 'wayang/burisrawa.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 11,
                'category_id'      => 2,
                'name'             => 'Citraksa',
                'other_names'      => 'Citraksha',
                'gender'           => 'Laki-laki',
                'role'             => 'Salah satu anggota seratus Kurawa yang kerap menjadi pengawal garis depan',
                'character_traits' => 'Cepat marah, suka memprovokasi, berani, setia, mudah terhasut',
                'weapon'           => 'Pedang dan tombak',
                'family'           => 'Putra Prabu Drestarastra dan Dewi Gandari; adik Duryudana; saudara kembar Citraksi',
                'allegiance'       => 'Kurawa',
                'description'      => 'Citraksa adalah salah satu pangeran Kurawa yang selalu tampil bersama saudara kembarnya, Citraksi, dalam berbagai tugas kerajaan. Sikapnya yang gegabah dan suka menantang sering memicu keributan di paseban istana.',
                'story'            => 'Citraksa selalu mendukung keputusan Duryudana dan setia menjalankan siasat-siasat yang dirancang oleh Patih Sengkuni. Di medan pertempuran Bharatayuda, Citraksa turut memimpin barisan infanteri Kurawa menghadapi gempuran laskar Pandawa. Ia berjuang membela panji Astina hingga titik darah penghabisan sebelum akhirnya gugur diterjang serangan gada perkasa Bima.',
                'image_path'       => 'wayang/citraksa.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 12,
                'category_id'      => 2,
                'name'             => 'Citraksi',
                'other_names'      => 'Citraksyi',
                'gender'           => 'Laki-laki',
                'role'             => 'Anggota seratus Kurawa yang berwatak ceroboh dan suka berbicara gagap',
                'character_traits' => 'Gegabah, suka menantang, cerewet, setia, mudah panik',
                'weapon'           => 'Pedang dan tombak',
                'family'           => 'Putra Prabu Drestarastra dan Dewi Gandari; adik Duryudana; saudara kembar Citraksa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Citraksi adalah saudara kembar Citraksa dalam deretan seratus pangeran Kurawa yang memiliki ciri khas gaya bicara gagap dan tingkah laku kocak namun licik. Kehadirannya selalu menjadi pendukung aksi para pembesar Kurawa.',
                'story'            => 'Bersama saudara kembarnya, Citraksi aktif terlibat dalam berbagai perselisihan dengan Pandawa sejak masa remaja di padepokan Sokalima. Ketika genderang perang Bharatayuda ditabuh, Citraksi maju ke garis depan Kurusetra dengan membawa tombak pusakanya. Ketidakmampuannya mengimbangi kedahsyatan kekuatan kesatria Pandawa membuatnya tewas bersama saudara-saudaranya di medan tempur.',
                'image_path'       => 'wayang/citraksi.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 13,
                'category_id'      => 2,
                'name'             => 'Kartamarma',
                'other_names'      => 'Kritawarma Kurawa',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria Kurawa yang menjabat sebagai raja di Kadipaten Banyutinalang',
                'character_traits' => 'Waspada, patuh, pemberani, setia kepada Kurawa, licin',
                'weapon'           => 'Keris dan panah',
                'family'           => 'Putra Prabu Drestarastra dan Dewi Gandari; saudara kandung para Kurawa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Kartamarma adalah salah satu ksatria Kurawa terpandang yang diberi kekuasaan memimpin wilayah Banyutinalang. Berbeda dengan saudaranya yang lain, Kartamarma memiliki perhitungan yang lebih taktis di medan peperangan.',
                'story'            => 'Kartamarma berperan aktif dalam menyediakan logistik dan memperkuat pertahanan sayap tentara Kurawa sepanjang kampanye militer Bharatayuda. Pada malam runtuhnya pertahanan Astina setelah kematian Duryudana, Kartamarma mendampingi Aswatama melancarkan serangan senyap ke perkemahan Pandawa. Ia tercatat sebagai salah satu dari sedikit pangeran Kurawa yang berhasil lolos hidup dari kehancuran perang.',
                'image_path'       => 'wayang/kartamarma.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 14,
                'category_id'      => 2,
                'name'             => 'Durmagati',
                'other_names'      => 'Darmagati',
                'gender'           => 'Laki-laki',
                'role'             => 'Pangeran Kurawa yang bertubuh pendek bulat dan berlidah tajam',
                'character_traits' => 'Kritis, suka membantah, berisik, setia, humoris',
                'weapon'           => 'Gada pendek dan pedang',
                'family'           => 'Putra Prabu Drestarastra dan Dewi Gandari; saudara para Kurawa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Durmagati adalah pangeran Kurawa bertubuh gempal yang dikenal sering melontarkan kritik dan celetukan blak-blakan dalam rapat kerajaan Astina. Kendati sering berbeda pendapat, kesetiaannya kepada saudara-saudaranya tidak pernah luntur.',
                'story'            => 'Durmagati kerap mempertanyakan rencana-rencana licik Sengkuni karena menganggapnya berbahaya bagi masa depan kerajaan, namun tetap patuh menjalankan titah Duryudana. Di padang Kurusetra, Durmagati membuktikan loyalitasnya dengan terjun langsung menghadang laju barisan Pandawa. Ia gugur di medan perang setelah bertarung sengit melawan Bima demi mempertahankan kehormatan bangsanya.',
                'image_path'       => 'wayang/durmagati.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 3: PUNAKAWAN (15 - 18)
            [
                'id'               => 15,
                'category_id'      => 3,
                'name'             => 'Semar',
                'other_names'      => 'Kyai Semar, Ismaya, Badranaya, Bojana Gati',
                'gender'           => 'Laki-laki',
                'role'             => 'Tokoh Punakawan agung, pamong utama para ksatria, dan titisan dewa',
                'character_traits' => 'Bijaksana, rendah hati, penyayang, sederhana, pengayom, sabar',
                'weapon'           => 'Kesaktian batin dan Kentut Semar',
                'family'           => 'Jatidiri Batara Ismaya yang turun ke marcapada; ayah angkat Gareng, Petruk, dan Bagong',
                'allegiance'       => 'Punakawan / Pandawa',
                'description'      => 'Semar adalah sosok pamong utama berwujud sederhana dan jenaka yang sejatinya merupakan pengejawantahan dewa agung Batara Ismaya. Ia menjadi penuntun moral, pembimbing spiritual, dan pelindung para ksatria berbudi luhur di bumi.',
                'story'            => 'Semar setia mendampingi para ksatria Pandawa dalam suka maupun duka selama masa pengasingan dan perjuangan hidup. Wejangan yang diberikannya sarat dengan filosofi kebajikan hidup, kerendahan hati, dan keikhlasan. Di saat para dewa berselisih atau marcapada terancam ketidakadilan, kesaktian sejati Semar mampu menundukkan kekacauan kosmis. Semar menjadi perlambang suara rakyat jelata sekaligus penjaga keseimbangan jagat raya.',
                'image_path'       => 'wayang/semar.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 16,
                'category_id'      => 3,
                'name'             => 'Gareng',
                'other_names'      => 'Nala Gareng, Cakruk',
                'gender'           => 'Laki-laki',
                'role'             => 'Anak tertua Semar yang melambangkan kehati-hatian dalam bertindak',
                'character_traits' => 'Sederhana, hati-hati, lucu, suka mengingatkan, jujur, cermat',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Anak angkat sulung Kyai Semar; kakak tertua Petruk dan Bagong',
                'allegiance'       => 'Punakawan / Pandawa',
                'description'      => 'Gareng adalah putra angkat pertama Semar yang memiliki ciri fisik khas bertangan patah, berkaki pincang, dan bermata juling. Ciri fisik tersebut mengandung filosofi mendalam agar manusia selalu berhati-hati dalam melangkah dan berbuat.',
                'story'            => 'Sebelum menjadi punakawan, Gareng merupakan seorang ksatria sakti bernama Bambang Sukodadi yang tersadar setelah dikalahkan oleh Semar. Bersama adik-adiknya, Gareng selalu mencairkan suasana tegang para ksatria dengan lelucon cerdas dan tembang sindiran. Dalam pengabdiannya kepada Pandawa, Gareng selalu mengingatkan agar setiap keputusan dipikirkan matang-matang demi menghindari marabahaya.',
                'image_path'       => 'wayang/gareng.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 17,
                'category_id'      => 3,
                'name'             => 'Petruk',
                'other_names'      => 'Kanthong Bolong, Dawala, Doblang',
                'gender'           => 'Laki-laki',
                'role'             => 'Anak kedua Semar yang cerdik, berbadan tinggi semampai, dan humoris',
                'character_traits' => 'Cerdik, humoris, kritis, menghibur, tangkas, dermawan',
                'weapon'           => 'Senjata cundrik dan tombak',
                'family'           => 'Anak angkat kedua Kyai Semar; adik Gareng; kakak Bagong',
                'allegiance'       => 'Punakawan / Pandawa',
                'description'      => 'Petruk adalah anak kedua Semar yang bertubuh jangkung dengan hidung panjang menyerupai pipa tembakau. Ia dikenal sangat lincah, pandai berdiplomasi, dan memiliki kantong bolong sebagai lambang kedermawanan tanpa pamrih.',
                'story'            => 'Petruk merupakan sosok punakawan yang paling tangkas dan gemar melontarkan kritik sosial yang mengena terhadap penguasa yang lalai. Dalam lakon Petruk Dadi Ratu, ia pernah naik tahta menjadi raja sakti bergelar Prabu Belgeduwelbeh untuk mengingatkan para pembesar kerajaan tentang hakikat kepemimpinan yang adil. Kesetiaannya kepada Pandawa terbukti saat ia menjaga para pangeran dari marabahaya tipu daya musuh.',
                'image_path'       => 'wayang/petruk.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 18,
                'category_id'      => 3,
                'name'             => 'Bagong',
                'other_names'      => 'Bawor, Ki Lurah Bagong',
                'gender'           => 'Laki-laki',
                'role'             => 'Anak bungsu Semar yang berwajah mirip ayahnya dan berwatak polos',
                'character_traits' => 'Polos, jujur, spontan, lucu, berani membantah, apa adanya',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Anak angkat bungsu Kyai Semar yang tercipta dari bayangan Semar; adik Gareng dan Petruk',
                'allegiance'       => 'Punakawan / Pandawa',
                'description'      => 'Bagong adalah anak bungsu Semar yang tercipta dari bayangan Semar sendiri atas sabda Sanghyang Tunggal sehingga memiliki kemiripan fisik dengan ayahnya. Karakternya yang polos, lugu, dan vokal kerap mengundang tawa sekaligus membuka kebenaran.',
                'story'            => 'Bagong memiliki gaya bicara yang ceplas-ceplos tanpa rasa takut meski berhadapan dengan raja atau dewa sekalipun. Kejujuran dan kepolosannya sering kali menjadi jalan keluar tak terduga saat para ksatria menemui jalan buntu dalam memecahkan masalah pelik. Kehadiran Bagong di tengah barisan Pandawa senantiasa menghadirkan kegembiraan dan kehangatan sejati di tengah kerasnya perjuangan hidup.',
                'image_path'       => 'wayang/bagong.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 4: KESATRIA DAN SEKUTU (19 - 24)
            [
                'id'               => 19,
                'category_id'      => 4,
                'name'             => 'Gatotkaca',
                'other_names'      => 'Raden Gatotkaca, Tetuka, Arimbi Putra, Kaca Negara',
                'gender'           => 'Laki-laki',
                'role'             => 'Ksatria perkasa Pringgandani yang berotot kawat bertulang besi dan mampu terbang',
                'character_traits' => 'Gagah berani, setia, rela berkorban, tangguh, berbakti, patriotik',
                'weapon'           => 'Kotang Antakusuma, Caping Basunanda, dan Aji Brajamusti',
                'family'           => 'Putra Raden Bima dan Dewi Arimbi; keponakan Pandawa; suami Dewi Pergiwa',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Gatotkaca adalah ksatria agung Kerajaan Pringgandani yang dijuluki ksatria otot kawat tulang besi karena kedahsyatan kekuatan fisiknya. Ia memiliki kemampuan terbang di angkasa tanpa sayap untuk menjaga kedaulatan tanah air.',
                'story'            => 'Sejak bayi, Gatotkaca telah ditempa di kawah Candradimuka oleh para dewa hingga menjadi kesatria pilih tanding pembasmi angkara murka. Pada perang Bharatayuda, ia diangkat sebagai senopati perang malam yang berhasil mengacaukan barisan tentara Kurawa. Gatotkaca gugur secara mulia setelah tertembus senjata sakti Kuntawijayadanu milik Adipati Karna, di mana tubuh raksasanya jatuh menimpa dan membinasakan ribuan prajurit musuh.',
                'image_path'       => 'wayang/gatotkaca.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 20,
                'category_id'      => 4,
                'name'             => 'Setyaki',
                'other_names'      => 'Wresniwira, Singamulangjaya, Yuyudana',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria tangguh Kerajaan Lesanpura dan benteng pertahanan setia Pandawa',
                'character_traits' => 'Pemberani, setia, teguh pendirian, keras, tanpa kompromi, loyal',
                'weapon'           => 'Gada Kyai Alugora dan panah',
                'family'           => 'Putra Prabu Setyajit; keponakan Prabu Kresna; ipar dan murid Raden Arjuna',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Setyaki adalah ksatria bangsa Wresni yang berjuluk Singamulangjaya karena keberanian dan kekuatannya yang tak pernah mundur selangkah pun. Ia menjadi pelindung setia Sri Kresna dan pilar kekuatan militer bagi Pandawa.',
                'story'            => 'Setyaki menimba ilmu keprajuritan langsung dari Arjuna sehingga mahir dalam memanah dan pertarungan jarak dekat menggunakan gada. Di medan Kurusetra, Setyaki bertindak sebagai salah satu senopati utama yang menghancurkan barisan pertahanan para pangeran Kurawa. Loyalitas dan kesetiaan mutlaknya kepada kebenaran menjadikannya salah satu pahlawan perang yang paling dihormati dalam epos Baratayuda.',
                'image_path'       => 'wayang/setyaki.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 21,
                'category_id'      => 4,
                'name'             => 'Srikandi',
                'other_names'      => 'Dewi Wara Srikandi',
                'gender'           => 'Perempuan',
                'role'             => 'Prajurit wanita tangguh Pancala dan senopati agung perang Bharatayuda',
                'character_traits' => 'Pemberani, tangkas, tegas, mandiri, berjiwa pejuang, pantang menyerah',
                'weapon'           => 'Busur dan panah',
                'family'           => 'Putri Prabu Drupada dari Kerajaan Pancala; adik Dewi Drupadi; istri Raden Arjuna',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Dewi Srikandi adalah ksatria wanita teladan yang terkenal dengan ketangkasan memanah, keberanian memimpin prajurit, dan ketegasan sikapnya. Ia mendobrak tradisi lama dengan membuktikan bahwa wanita mampu menjadi senopati perang di garis depan.',
                'story'            => 'Srikandi mempelajari seni memanah dari Arjuna yang kemudian menjadi suaminya. Dalam perang Bharatayuda, Srikandi mengemban tugas suci sebagai senopati perang agung Pandawa untuk menghadapi Resi Bisma. Dengan keberanian luar biasa dan bidikan panah pusakanya, Srikandi berhasil melumpuhkan sang begawan agung Astina guna memenuhi janji takdir karma Dewi Amba.',
                'image_path'       => 'wayang/srikandi.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 22,
                'category_id'      => 4,
                'name'             => 'Abimanyu',
                'other_names'      => 'Angkawijaya, Jayamurcita, Wanodya Putra',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria muda putra Arjuna yang berjiwa ksatria luhur dan gugur sebagai pahlawan',
                'character_traits' => 'Berani, tampan, halus, berjiwa ksatria, berbakti, rela berkorban',
                'weapon'           => 'Keris Pulanggeni dan panah',
                'family'           => 'Putra Raden Arjuna dan Dewi Subadra; suami Dewi Utari dan Dewi Siti Sundari; ayah Prabu Parikesit',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Abimanyu adalah kesatria muda idola yang mewarisi ketampanan, kehalusan budi, dan keahlian memanah dari ayahnya, Arjuna. Keturunannyalah yang kelak ditakdirkan menjadi penerus tahta agung dinasti Kuru di Kerajaan Astina.',
                'story'            => 'Pada perang Baratayuda, Abimanyu menunjukkan kepahlawanan luar biasa dengan menembus formasi tempur mematikan Cakrabyuha seorang diri guna menyelamatkan barisan Pandawa. Meskipun dikepung oleh para senopati kawakan Kurawa dan dihujani panah pusaka, Abimanyu terus bertarung pantang menyerah hingga hembusan nafas terakhir. Pengorbanan sucinya dikenang abadi sebagai lambang keberanian ksatria sejati.',
                'image_path'       => 'wayang/abimanyu.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 23,
                'category_id'      => 4,
                'name'             => 'Antareja',
                'other_names'      => 'Anantareja, Nagaputra',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria sakti Jangkarbumi putra Bima yang menguasai racun bumi dan liang tanah',
                'character_traits' => 'Rela berkorban, patuh, berani, setia, pendiam, berbudi luhur',
                'weapon'           => 'Lidah bisa beracun dan Cincin Mustikabumi',
                'family'           => 'Putra Raden Bima dan Dewi Nagagini; cucu Batara Anantaboga; saudara tiri Gatotkaca dan Antasena',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Antareja adalah kesatria sakti keturunan bangsa naga yang memiliki kemampuan menembus lapisan bumi dan bisa mematikan hanya dengan menjilat telapak kaki musuh. Sifatnya sangat patuh, tenang, dan ikhlas berkorban demi tegaknya keadilan.',
                'story'            => 'Antareja mengabdi dengan setia membantu perjuangan Pandawa dan membela kaum yang tertindas. Menjelang pecahnya perang Bharatayuda, Sri Kresna menyadari bahwa kesaktian Antareja yang luar biasa dapat menghabisi seluruh pasukan dalam sekejap tanpa pertempuran ksatria. Demi menjaga takdir perang suci, Antareja dengan ikhlas menjilat bekas jejak kakinya sendiri sebagai bentuk tawur pengorbanan suci bagi kemenangan Pandawa.',
                'image_path'       => 'wayang/antareja.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 24,
                'category_id'      => 4,
                'name'             => 'Antasena',
                'other_names'      => 'Anantasena',
                'gender'           => 'Laki-laki',
                'role'             => 'Kesatria sakti mandraguna putra Bima yang menguasai samudra dan kebal segala senjata',
                'character_traits' => 'Polos, jujur, sakti mandraguna, rela berkorban, pemberani, bersahaja',
                'weapon'           => 'Kesaktian kulit bersisik kupang dan bisa racun air',
                'family'           => 'Putra Raden Bima dan Dewi Urangayu; cucu Sanghyang Baruna; saudara tiri Gatotkaca dan Antareja',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Antasena adalah ksatria muda putra Bima yang hidup di dasar samudra dan memiliki kesaktian luar biasa kebal dari segala macam senjata pusaka. Ia berwatak sangat bersahaja, lugu, dan tidak pernah menggunakan bahasa krama kepada siapapun.',
                'story'            => 'Antasena berkali-kali menyelamatkan keluarga Pandawa dari berbagai muslihat berbahaya yang ditebarkan oleh pihak Kurawa. Serupa dengan kakaknya Antareja, Antasena memilih jalan pengorbanan luhur moksa sebelum Bharatayuda meletus demi menaati wejangan Sri Kresna agar roda takdir keadilan dapat berjalan sebagaimana mestinya tanpa dominasi kesaktian mutlak.',
                'image_path'       => 'wayang/antasena.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 5: TOKOH WANITA (25 - 30)
            [
                'id'               => 25,
                'category_id'      => 5,
                'name'             => 'Kunti',
                'other_names'      => 'Dewi Kunti, Kuntinalibrata, Prita',
                'gender'           => 'Perempuan',
                'role'             => 'Ibu agung Pandawa yang penuh ketabahan, welas asih, dan berjiwa mulia',
                'character_traits' => 'Sabar, tabah, penuh kasih sayang, bijaksana, teguh, setia',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri Prabu Kuntiboja; istri pertama Prabu Pandu; ibu kandung Yudhistira, Bima, Arjuna, dan Karna',
                'allegiance'       => 'Pandawa',
                'description'      => 'Dewi Kunti adalah sosok ibu agung yang mengasuh kelima pangeran Pandawa dengan penuh limpahan kasih sayang dan nilai-nilai dharma. Ketabahan hatinya teruji saat harus mendampingi anak-anaknya terlunta-lunta di hutan belantara.',
                'story'            => 'Kunti menyimpan rahasia masa muda bahwa Adipati Karna adalah putra sulungnya yang lahir dari anugerah Batara Surya. Sepanjang hidupnya, ia berusaha mendidik Pandawa agar selalu hidup rukun, adil, dan membela kebenaran. Pasca kemenangan perang Bharatayuda, Kunti memilih undur diri dari gemerlap istana untuk menjalani laku tapa brata di hutan hingga akhir hayatnya.',
                'image_path'       => 'wayang/kunti.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 26,
                'category_id'      => 5,
                'name'             => 'Gandari',
                'other_names'      => 'Dewi Gandari, Gendhari',
                'gender'           => 'Perempuan',
                'role'             => 'Ratu Astina yang setia menutup matanya demi mendampingi suaminya yang buta',
                'character_traits' => 'Setia pada suami, keras hati, penuh duka, penyayang keluarga, tabah',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri Kerajaan Gandara; saudara perempuan Patih Sengkuni; istri Prabu Drestarastra; ibu seratus Kurawa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Dewi Gandari adalah permaisuri Kerajaan Astina yang memilih menutup kedua matanya dengan kain selamanya sebagai wujud kesetiaan mutlak kepada suaminya, Drestarastra, yang terlahir buta. Ia melahirkan seratus pangeran Kurawa.',
                'story'            => 'Gandari kerap mengingatkan anak-anaknya agar menghentikan permusuhan dengan Pandawa, namun nasihat keibuannya selalu diabaikan oleh Duryudana. Ketika seluruh putranya binasa di padang Kurusetra, duka nestapa Gandari mengguncang jagat raya. Kesetiaan dan keteguhannya menjalani takdir duka menjadikannya salah satu tokoh wanita paling tragis dalam pewayangan.',
                'image_path'       => 'wayang/gandari.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 27,
                'category_id'      => 5,
                'name'             => 'Dewi Madrim',
                'other_names'      => 'Madrim, Ratu Madrim',
                'gender'           => 'Perempuan',
                'role'             => 'Istri kedua Prabu Pandu dan ibu kandung kesatria kembar Nakula dan Sadewa',
                'character_traits' => 'Setia, lembut, penuh pengorbanan, penyayang, berbakti',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri Kerajaan Mandaraka; adik kandung Prabu Salya; istri kedua Prabu Pandu; ibu Nakula dan Sadewa',
                'allegiance'       => 'Pandawa',
                'description'      => 'Dewi Madrim adalah putri cantik dari Kerajaan Mandaraka yang dipersunting oleh Prabu Pandu sebagai istri kedua. Dari pernikahannya, ia melahirkan kesatria kembar Nakula dan Sadewa melalui doa pemanggilan dewa kembar Aswin.',
                'story'            => 'Dewi Madrim dikenal sebagai sosok istri yang penuh kepatuhan dan kelembutan budi pekerti. Ketika Prabu Pandu wafat di hutan akibat kutukan Resi Kindama, Dewi Madrim memilih melakukan bela pati membakar diri demi menemani suaminya ke alam keabadian, seraya menitipkan pengasuhan anak kembarnya kepada Dewi Kunti.',
                'image_path'       => 'wayang/dewi_madrim.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 28,
                'category_id'      => 5,
                'name'             => 'Dewi Arimbi',
                'other_names'      => 'Hidimbi, Ratu Arimbi',
                'gender'           => 'Perempuan',
                'role'             => 'Ratu Kerajaan Pringgandani yang setia dan ibu kandung Gatotkaca',
                'character_traits' => 'Setia, penuh kasih sayang, berbakti, penyabar, berhati mulia',
                'weapon'           => 'Kemampuan sihir dan kesaktian raksasa',
                'family'           => 'Berasal dari bangsa raseksa Pringgandani; istri Raden Bima; ibu kandung Raden Gatotkaca',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Dewi Arimbi adalah putri berdarah raksasa dari Pringgandani yang berubah menjadi putri berparas jelita berkat ketulusan cintanya kepada Raden Bima. Ia merupakan ratu yang arif memimpin rakyatnya.',
                'story'            => 'Arimbi mendidik putranya, Gatotkaca, dengan nilai-nilai kepahlawanan luhur hingga menjadi kesatria pelindung utama Pandawa. Ia selalu mendukung perjuangan keluarga suaminya dengan mengerahkan segenap prajurit Pringgandani. Ketika Gatotkaca gugur di perang Bharatayuda, Arimbi merelakan kepergian putranya sebagai ksatria sejati pembela kebenaran.',
                'image_path'       => 'wayang/dewi_arimbi.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 29,
                'category_id'      => 5,
                'name'             => 'Subadra',
                'other_names'      => 'Dewi Wara Subadra, Rumbini, Sumbadra',
                'gender'           => 'Perempuan',
                'role'             => 'Putri agung Mandura, istri utama Arjuna, dan ibu kandung Abimanyu',
                'character_traits' => 'Lembut, anggun, setia, penyabar, berbudi pekerti luhur, penyejuk',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri Prabu Basudewa dari Mandura; adik kandung Sri Kresna dan Prabu Baladewa; istri Raden Arjuna; ibu Abimanyu',
                'allegiance'       => 'Pandawa',
                'description'      => 'Dewi Subadra adalah perwujudan wanita Jawa ideal yang anggun, bertutur kata lemah lembut, sabar, dan memiliki keteguhan batin luar biasa. Ia menjadi permaisuri utama Arjuna di kesatrian Madukara.',
                'story'            => 'Subadra mendampingi Arjuna dalam melewati berbagai rintangan kehidupan dengan kesetiaan yang tak pernah goyah. Kasih sayangnya terpancar nyata dalam membesarkan Abimanyu menjadi kesatria yang berbudi pekerti mulia. Garis keturunan dari rahim Subadra inilah yang melanjutkan kelangsungan dinasti Hastinapura melalui cucunya, Prabu Parikesit.',
                'image_path'       => 'wayang/subadra.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 30,
                'category_id'      => 5,
                'name'             => 'Dewi Drupadi',
                'other_names'      => 'Kresnaa, Panchali, Drupada Putri',
                'gender'           => 'Perempuan',
                'role'             => 'Permaisuri agung Kerajaan Amarta yang menjunjung tinggi harga diri dan kesetiaan',
                'character_traits' => 'Teguh, setia, berprinsip kuat, anggun, tabah, pantang menyerah',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putri Prabu Drupada dari Kerajaan Pancala; saudara Srikandi dan Drestadyumna; istri Prabu Yudhistira',
                'allegiance'       => 'Pandawa',
                'description'      => 'Dewi Drupadi adalah putri kelahiran api suci Kerajaan Pancala yang menjadi permaisuri agung Prabu Yudhistira. Ia merupakan lambang kehormatan, keteguhan hati, dan ketaatan dalam membela martabat keluarga Pandawa.',
                'story'            => 'Drupadi mengalami penghinaan berat di balairung istana Astina saat Kurawa berusaha melucuti busananya, hingga ia bersumpah tidak akan menyanggul rambutnya sebelum dikeramasi darah Dursasana. Sumpah tersebut menjadi pemicu moral penting dalam penegakan keadilan di padang Kurusetra. Setelah perang usai dan sumpahnya terbayar, Drupadi setia mendampingi suaminya memimpin rakyat dengan penuh kebijaksanaan.',
                'image_path'       => 'wayang/dewi_drupadi.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 6: TOKOH KERAJAAN (31 - 36)
            [
                'id'               => 31,
                'category_id'      => 6,
                'name'             => 'Pandu',
                'other_names'      => 'Prabu Pandu Dewanata',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja agung Kerajaan Astina dan ayah kandung kelima ksatria Pandawa',
                'character_traits' => 'Adil, berani, bijaksana, disegani, berwibawa, berjiwa ksatria',
                'weapon'           => 'Panah dan keris pusaka',
                'family'           => 'Putra Begawan Abyasa; adik Drestarastra; suami Dewi Kunti dan Dewi Madrim; ayah para Pandawa',
                'allegiance'       => 'Pandawa',
                'description'      => 'Prabu Pandu Dewanata adalah raja termasyhur Kerajaan Astina yang memerintah dengan adil, bijaksana, dan disegani oleh segenap penguasa marcapada. Kemahiran memanahnya menjadikan wilayah Astina aman tenteram.',
                'story'            => 'Prabu Pandu berhasil memperluas kejayaan kerajaan dan membimbing prajurit Astina menjadi kekuatan tak tertandingi. Namun akibat ketidaksengajaan memanah kijang titisan pertapa, ia menerima kutukan suci yang memaksanya turun tahta dan menyepi ke lereng gunung bersama kedua istrinya. Pandu wafat di usia muda dan mewariskan nilai-nilai keluhuran budi kepada kelima putranya.',
                'image_path'       => 'wayang/pandu.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 32,
                'category_id'      => 6,
                'name'             => 'Drestarastra',
                'other_names'      => 'Prabu Drestarastra, Destarata',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja Astina yang buta penglihatan dan ayah kandung kaum Kurawa',
                'character_traits' => 'Penyayang anak, peragu, bimbang, pasrah, mudah dipengaruhi',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putra sulung Begawan Abyasa; kakak Prabu Pandu; suami Dewi Gandari; ayah seratus Kurawa',
                'allegiance'       => 'Kurawa',
                'description'      => 'Prabu Drestarastra adalah penguasa Astina yang memiliki keterbatasan fisik tunanetra sejak lahir. Rasa cintanya yang berlebihan dan buta kepada anak-anaknya membuatnya tidak berdaya menghentikan kedurhakaan Kurawa.',
                'story'            => 'Drestarastra memegang tampuk pemerintahan Astina setelah Pandu mangkat dengan status wali hingga anak-anak mereka dewasa. Kelemahannya dalam bersikap tegas terhadap intrik Sengkuni dan ambisi Duryudana menyebabkan perselisihan takhta berujung pada malapetaka perang saudara. Di masa senjanya setelah Bharatayuda berakhir, Drestarastra meratapi kehancuran seluruh keturunannya dan menyucikan diri di hutan belantara.',
                'image_path'       => 'wayang/drestarastra.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 33,
                'category_id'      => 6,
                'name'             => 'Kresna',
                'other_names'      => 'Sri Kresna, Narayana, Kesawa, Padmanaba',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja agung Kerajaan Dwarawati, penasihat utama Pandawa, dan titisan Batara Wisnu',
                'character_traits' => 'Cerdas, bijaksana, visioner, ahli strategi, adil, berwibawa',
                'weapon'           => 'Senjata Cakra Baswara dan Kembang Wijayakusuma',
                'family'           => 'Putra Prabu Basudewa; saudara Baladewa dan Subadra; sepupu sekaligus penasihat agung Pandawa',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Sri Kresna adalah raja Dwarawati berdarah titisan Batara Wisnu yang bertugas memelihara keteraturan jagat raya dan membasmi kezaliman di bumi. Ia menjadi arsitek utama strategi kemenangan Pandawa dalam menegakkan keadilan.',
                'story'            => 'Kresna menjadi juru runding agung yang selalu berupaya mencegah pertumpahan darah dengan menawarkan jalan damai kepada Kurawa. Dalam perang Bharatayuda, Kresna memilih peran tanpa senjata sebagai sais kereta perang Arjuna, sekaligus memberikan wejangan suci penuntun jiwa. Kebijaksanaan taktik dan pandangan visionernya berhasil membimbing Pandawa mengatasi rintangan-rintangan paling mustahil di medan laga.',
                'image_path'       => 'wayang/kresna.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 34,
                'category_id'      => 6,
                'name'             => 'Baladewa',
                'other_names'      => 'Prabu Baladewa, Kakrasana, Balarama',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja agung Mandura yang berwatak jujur, bertubuh putih perkasa, dan berjiwa ksatria',
                'character_traits' => 'Keras, jujur, adil, tegas, berwibawa, lekas marah namun berhati mulia',
                'weapon'           => 'Senjata Nanggala dan Alugora',
                'family'           => 'Putra sulung Prabu Basudewa; kakak kandung Sri Kresna dan Subadra; mertua Duryudana; guru gada Bima',
                'allegiance'       => 'Kerajaan / Netral',
                'description'      => 'Prabu Baladewa adalah raja perkasa Kerajaan Mandura berkulit putih bersih yang memiliki kesaktian luar biasa dan watak yang sangat jujur serta lugas. Ia tidak menyukai kepalsuan dan selalu menjunjung tinggi sportivitas ksatria.',
                'story'            => 'Baladewa adalah guru olah senjata gada bagi Bima maupun Duryudana sehingga ia memilih bersikap netral dalam perselisihan keluarga Bharatayuda. Sebelum perang meletus, atas siasat cerdik Kresna, Baladewa diminta bertapa di Grojogan Sewu demi menjaga agar senjata pemusnah massal Nanggala miliknya tidak menghancurkan dunia. Baladewa menjadi saksi akhir perang dan tetap dihormati oleh kedua belah pihak.',
                'image_path'       => 'wayang/baladewa.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 35,
                'category_id'      => 6,
                'name'             => 'Salya',
                'other_names'      => 'Prabu Salya, Narasoma, Somadatta',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja perkasa Mandaraka yang terjebak janji membela pihak Kurawa',
                'character_traits' => 'Pemberani, ahli memanah, bimbang, setia pada janji, berwibawa',
                'weapon'           => 'Ajian Candrabirawa dan panah',
                'family'           => 'Raja Kerajaan Mandaraka; kakak Dewi Madrim; paman Nakula dan Sadewa; mertua Prabu Duryudana',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Prabu Salya adalah penguasa Mandaraka yang masyhur dengan ketampanan, ketangkasan memanah, dan kepemilikan aji kesaktian Candrabirawa. Hatinya sesungguhnya condong kepada keponakannya, Pandawa, namun terikat sumpah membela Kurawa.',
                'story'            => 'Salya terjebak oleh jamuan licik Duryudana dalam perjalanan menuju medan perang sehingga terpaksa bersumpah menjadi senopati pihak Kurawa. Di medan laga, ia sempat menjadi sais kereta perang Karna sebelum akhirnya diangkat sebagai panglima tertinggi terakhir Kurawa. Salya gugur secara terhormat di tangan Prabu Yudhistira yang berdarah putih suci, mampu meredam keganasan aji raksasa Candrabirawa.',
                'image_path'       => 'wayang/salya.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 36,
                'category_id'      => 6,
                'name'             => 'Drupada',
                'other_names'      => 'Prabu Drupada, Sucitra, Yajnasena',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja Kerajaan Pancala dan sekutu setia pertahanan Pandawa',
                'character_traits' => 'Berwibawa, teguh pendirian, berjiwa ksatria, setia kawan, pemberani',
                'weapon'           => 'Panah dan tombak pusaka',
                'family'           => 'Raja agung Pancala; sahabat masa muda Resi Drona; ayah Srikandi, Dewi Drupadi, dan Drestadyumna',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Prabu Drupada adalah raja berwibawa dari Kerajaan Pancala yang menjadi pilar persekutuan militer terpenting bagi keluarga Pandawa. Hubungan kekerabatannya yang erat dengan Pandawa terjalin melalui pernikahan putri-putrinya.',
                'story'            => 'Drupada memiliki sejarah rivalitas panjang dengan Resi Drona sejak masa muda mereka di padepokan. Dalam perang Bharatayuda, Drupada memimpin langsung korps pasukan Pancala dan bertempur gagah berani di garis terdepan Kurusetra. Prabu Drupada gugur dalam duel sengit melawan Drona, namun perjuangannya diteruskan oleh anak-anaknya hingga mengantarkan kemenangan bagi pihak kebenaran.',
                'image_path'       => 'wayang/drupada.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 7: RESI DAN GURU (37 - 41)
            [
                'id'               => 37,
                'category_id'      => 7,
                'name'             => 'Drona',
                'other_names'      => 'Resi Drona, Begawan Drona, Kumbayana, Dronacharya',
                'gender'           => 'Laki-laki',
                'role'             => 'Mahaguru militer agung yang melatih keprajuritan Pandawa dan Kurawa',
                'character_traits' => 'Sangat ahli ilmu perang, cerdas, keras, terikat sumpah setia, berwibawa',
                'weapon'           => 'Senjata Cundamanik dan panah sakti',
                'family'           => 'Berasal dari padepokan Sokalima; suami Dewi Krepi; ayah kandung Aswatama; guru Pandawa dan Kurawa',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Resi Drona adalah mahaguru olah senjata terhebat di tanah Bharata yang mendidik pangeran-pangeran Astina menguasai berbagai seni bela diri dan strategi militer tingkat tinggi. Rasa baktinya kepada takhta Astina mengikatnya di pihak Kurawa.',
                'story'            => 'Drona sangat menyayangi murid-muridnya, terutama Arjuna yang dianggapnya sebagai pemanah terbaik tiada tanding. Ketika perang Bharatayuda berkecamuk, Drona diangkat menjadi panglima tertinggi Kurawa yang nyaris tak terkalahkan. Drona akhirnya meletakkan senjata dan bermeditasi pasrah setelah mendengar kabar gugurnya gajah bernama Hestitama, sebelum kemudian gugur di tangan Drestadyumna.',
                'image_path'       => 'wayang/drona.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 38,
                'category_id'      => 7,
                'name'             => 'Bisma',
                'other_names'      => 'Resi Bisma, Dewabrata, Ganggaputra, Bisma Pitamaha',
                'gender'           => 'Laki-laki',
                'role'             => 'Kakek agung Astina yang rela bersumpah wadat demi keutuhan tanah air',
                'character_traits' => 'Bijaksana, setia pada sumpah, ksatria sejati, sakti, teguh, rela berkorban',
                'weapon'           => 'Panah dan busur pusaka',
                'family'           => 'Putra Prabu Santanu dan Dewi Gangga; kakek buyut para Pandawa dan Kurawa',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Resi Bisma adalah tokoh ksatria paling dihormati dalam dunia pewayangan yang dianugerahi kesaktian luar biasa dapat menentukan waktu kematiannya sendiri. Ia hidup membujang seumur hidup demi menghindari perebutan takhta kerajaan.',
                'story'            => 'Bisma terpaksa memimpin tentara Kurawa demi memegang teguh sumpah prajurit untuk selalu membela tanah air Astina dari ancaman apapun. Di medan Kurusetra, Bisma bertempur tanpa pamrih hingga akhirnya rela gugur di atas hamparan panah setelah berhadapan dengan Dewi Srikandi. Sebelum menghembuskan nafas terakhir, Bisma sempat memberikan wejangan kepemimpinan luhur kepada cucu-cucunya Pandawa.',
                'image_path'       => 'wayang/bisma.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 39,
                'category_id'      => 7,
                'name'             => 'Krepa',
                'other_names'      => 'Resi Krepa, Kripacharya, Bhagawan Krepa',
                'gender'           => 'Laki-laki',
                'role'             => 'Pendeta istana Astina dan guru dasar ilmu tata susila para pangeran',
                'character_traits' => 'Adil, sabar, patuh pada aturan hukum, bijaksana, tenang',
                'weapon'           => 'Panah dan pedang',
                'family'           => 'Saudara kembar Dewi Krepi; saudara ipar Resi Drona; paman Aswatama; penasihat hukum kerajaan Astina',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Resi Krepa adalah pendeta suci dan guru pertama para pangeran Astina sebelum mereka berguru kepada Resi Drona. Ia terkenal dengan integritas moralnya yang tinggi dalam menjunjung keadilan hukum kerajaan.',
                'story'            => 'Krepa kerap menentang tindakan-tindakan curang Kurawa di paseban istana dan menyarankan pembagian takhta secara damai kepada Pandawa. Namun sebagai pejabat istana yang digaji negara, ia tetap menjalankan kewajiban bertempur di Kurusetra. Berkat keluhuran budi dan ketaatannya pada etika kesatria, Resi Krepa selamat dari perang dan kelak dipercaya menjadi guru pembimbing bagi Prabu Parikesit.',
                'image_path'       => 'wayang/krepa.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 40,
                'category_id'      => 7,
                'name'             => 'Widura',
                'other_names'      => 'Arya Widura, Yamawidura, Patih Widura',
                'gender'           => 'Laki-laki',
                'role'             => 'Penasihat agung Kerajaan Astina yang selalu setia pada kebenaran dan dharma',
                'character_traits' => 'Sangat bijaksana, jujur, adil, tenang, berbudi luhur, berwawasan luas',
                'weapon'           => 'Tidak memiliki senjata khusus',
                'family'           => 'Putra Begawan Abyasa dari dayang istana; adik tiri Drestarastra dan Pandu; paman Pandawa dan Kurawa',
                'allegiance'       => 'Kerajaan / Netral',
                'description'      => 'Arya Widura adalah negarawan agung di Kerajaan Astina yang menjadi simbol kebijaksanaan sejati dan penegak hukum yang tak kenal kompromi. Tutur katanya senantiasa menjadi pedoman bagi siapapun yang mencari kebenaran.',
                'story'            => 'Widura berkali-kali menyelamatkan Pandawa dari jebakan maut Kurawa, salah satunya dengan memberi petunjuk jalan bawah tanah saat peristiwa pembakaran rumah damar di Waranawata. Karena kecintaannya pada kedamaian, Widura menolak terlibat dalam perang fisik dan memilih mendoakan keselamatan umat manusia. Pemikirannya tentang tata kelola negara yang adil tetap abadi sepanjang masa.',
                'image_path'       => 'wayang/widura.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 41,
                'category_id'      => 7,
                'name'             => 'Aswatama',
                'other_names'      => 'Bambang Aswatama, Ksatria Sokalima',
                'gender'           => 'Laki-laki',
                'role'             => 'Putra tunggal Resi Drona yang sakti namun dibutakan oleh dendam asmara dan amarah',
                'character_traits' => 'Pemberani, keras kepala, pendendam, setia pada ayah, tangguh',
                'weapon'           => 'Panah dan keris pusaka',
                'family'           => 'Putra tunggal Resi Drona dan Dewi Krepi; keponakan Resi Krepa; perwira setia Kurawa',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Aswatama adalah ksatria sakti putra Resi Drona yang memiliki mustika permata di dahinya sejak lahir. Ia mahir dalam berbagai cabang ilmu perang peninggalan ayahnya namun memiliki perangai yang lekas tersulut emosi.',
                'story'            => 'Aswatama bertarung mendampingi ayahnya di barisan tentara Kurawa sepanjang pertempuran Bharatayuda. Terbakar dendam membara atas kematian ayahnya yang dianggap tidak adil, Aswatama melancarkan serangan gelap pada malam hari ke perkemahan Pandawa setelah perang usai. Tindakan kejinya tersebut mengakhiri riwayatnya dalam kutukan kesengsaraan panjang mengembara di dunia.',
                'image_path'       => 'wayang/aswatama.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // KATEGORI 8: TOKOH LAINNYA (42 - 45)
            [
                'id'               => 42,
                'category_id'      => 8,
                'name'             => 'Karna',
                'other_names'      => 'Adipati Karna, Suryaputra, Basusena, Karna Radheya',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja Kerajaan Awangga, ahli pemanah ulung, dan ksatria pembela janji persahabatan',
                'character_traits' => 'Dermawan, ksatria sejati, setia pada sumpah, bangga, pemberani, pantang ingkar',
                'weapon'           => 'Senjata Kuntawijayadanu dan Panah Wijayandanu',
                'family'           => 'Putra sulung Dewi Kunti dan Batara Surya; kakak kandung tertua seibu Pandawa; sahabat sejati Duryudana',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Adipati Karna adalah ksatria perkasa berjiwa ksatria agung yang terkenal dengan kedermawanannya yang tiada tara kepada siapa saja yang meminta. Meskipun mengetahui Pandawa adalah adik kandungnya, ia memilih gugur membela Duryudana demi membalas budi persahabatan.',
                'story'            => 'Karna berjuang keras membuktikan martabat ksatria sejatinya di tengah cemoohan asal-usul kelahirannya. Dalam perang Bharatayuda, Karna diangkat sebagai senopati agung Kurawa yang menggetarkan Kurusetra dengan bidikan panah saktinya. Pertarungan legendaris antara Karna dan Arjuna di atas kereta perang menjadi puncak drama kepahlawanan paling mengharukan dalam epos pewayangan.',
                'image_path'       => 'wayang/karna.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 43,
                'category_id'      => 8,
                'name'             => 'Jayadrata',
                'other_names'      => 'Prabu Jayadrata, Sinduraja, Tirtanata',
                'gender'           => 'Laki-laki',
                'role'             => 'Raja Kerajaan Sindu, ipar Kurawa, dan penyebab utama gugurnya Abimanyu',
                'character_traits' => 'Congkak, pendendam, licik, keras hati, penakut saat terdesak',
                'weapon'           => 'Tombak dan gada',
                'family'           => 'Putra Begawan Sapwani; suami Dewi Dursilawati; saudara ipar Prabu Duryudana',
                'allegiance'       => 'Sekutu Kurawa',
                'description'      => 'Prabu Jayadrata adalah penguasa Kerajaan Sindu yang bersekutu kuat dengan pihak Kurawa karena ikatan perkawinannya dengan Dewi Dursilawati. Ia memiliki kekebalan gaib berkat anugerah tapa pemujaan dewa.',
                'story'            => 'Jayadrata memegang peranan kunci saat menghalangi barisan Pandawa masuk ke dalam formasi Cakrabyuha sehingga menyebabkan Abimanyu gugur dikeroyok. Kematian Abimanyu memicu sumpah Arjuna untuk memenggal kepala Jayadrata sebelum matahari terbenam. Di bawah bantuan muslihat gerhana buatan Kresna, Arjuna berhasil menuntaskan sumpahnya dengan melepaskan panah Pasopati yang melesat memenggal leher Jayadrata.',
                'image_path'       => 'wayang/jayadrata.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 44,
                'category_id'      => 8,
                'name'             => 'Drestadyumna',
                'other_names'      => 'Trusthajumena, Drestajumena',
                'gender'           => 'Laki-laki',
                'role'             => 'Panglima tertinggi balatentara Pandawa dalam pertempuran Bharatayuda',
                'character_traits' => 'Pemberani, tangkas, berjiwa ksatria, tegas, setia kawan',
                'weapon'           => 'Pedang dan panah',
                'family'           => 'Putra Prabu Drupada dari Kerajaan Pancala; saudara kandung Srikandi dan Dewi Drupadi',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Drestadyumna adalah putra mahkota Kerajaan Pancala yang lahir dari api kurban suci dengan takdir khusus untuk menjadi panglima perang dan mengalahkan Resi Drona. Ia berwatak ksatria yang sangat disegani dan ahli strategi militer.',
                'story'            => 'Drestadyumna diangkat secara mufakat oleh Pandawa dan Sri Kresna sebagai senopati agung pemimpin seluruh laskar gabungan Pandawa. Kepemimpinannya yang taktis berhasil mengimbangi kedahsyatan kekuatan balatentara Kurawa. Pada hari kelima belas perang, Drestadyumna menunaikan takdir hidupnya dengan menumbangkan Resi Drona sebelum akhirnya gugur syahid dalam serangan malam Aswatama.',
                'image_path'       => 'wayang/drestadyumna.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'id'               => 45,
                'category_id'      => 8,
                'name'             => 'Yuyutsu',
                'other_names'      => 'Arya Yuyutsu',
                'gender'           => 'Laki-laki',
                'role'             => 'Satu-satunya putra Drestarastra yang berpihak kepada kebenaran bersama Pandawa',
                'character_traits' => 'Jujur, adil, berani memegang kebenaran, teguh prinsip, cinta damai',
                'weapon'           => 'Pedang dan panah',
                'family'           => 'Putra Prabu Drestarastra dari dayang Gandawati; saudara tiri para Kurawa',
                'allegiance'       => 'Sekutu Pandawa',
                'description'      => 'Arya Yuyutsu adalah putra Prabu Drestarastra yang memiliki keluhuran nurani dan berani menentang kezaliman saudara-saudara tirinya kaum Kurawa. Sebelum perang dimulai, ia dengan tegas memilih menyeberang ke pihak Pandawa demi membela dharma.',
                'story'            => 'Keputusan Yuyutsu mencerminkan keberanian moral sejati seorang ksatria yang lebih mengutamakan keadilan di atas ikatan darah yang salah. Selama perang berlangsung, ia mengelola perbekalan dan barisan pertahanan dengan penuh integritas. Pasca runtuhnya Kurawa, Yuyutsu diangkat oleh Prabu Yudhistira sebagai patih sekaligus penasihat agung kerajaan Astina.',
                'image_path'       => 'wayang/yuyutsu.png',
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ];

        DB::table('wayang_characters')->upsert($characters, ['id'], [
            'category_id', 'name', 'other_names', 'gender', 'role',
            'character_traits', 'weapon', 'family', 'allegiance',
            'description', 'story', 'image_path', 'updated_at',
        ]);
    }
}
